Flow-IPC: ipc::transport::sync_io::Native_socket_stream Class Reference
ipc::transport::sync_io::Native_socket_stream Class Reference
Implements both sync_io::Native_handle_sender and sync_io::Native_handle_receiver concepts by using a stream-oriented Unix domain socket, allowing high-performance but non-zero-copy transmission of discrete messages, each containing a native handle, a binary blob, or both.
#include <native_socket_stream.hpp>
Classes
class Impl
Internal, non-movable pImpl implementation of sync_io::Native_socket_stream class.
Public Types
using Async_io_obj = transport::Native_socket_stream
Useful for generic programming, the async-I/O-pattern counterpart to *this type.
using Sync_io_obj = Null_peer
You may disregard.
Public Member Functions
Native_socket_stream ()
Default ctor (object is in NULL state).
Native_socket_stream (flow::log::Logger *logger_ptr, util::String_view nickname_str)
Creates a Native_socket_stream in NULL (not connected) state.
Native_socket_stream (flow::log::Logger *logger_ptr, util::String_view nickname_str, Native_handle &&native_peer_socket_moved)
Constructs the socket-and-meta-blob stream by taking over an already-connected native Unix domain socket handle.
Native_socket_stream (Native_socket_stream &&src)
Move-constructs from src; src becomes as-if default-cted (therefore in NULL state).
Native_socket_stream (const Native_socket_stream &)=delete
Copy construction is disallowed.
~Native_socket_stream ()
Implements Native_handle_sender and Native_handle_receiver APIs at the same time, per their concept contracts.
Native_socket_stream & operator= (Native_socket_stream &&src)
Move-assigns from src; *this acts as if destructed; src becomes as-if default-cted (therefore in NULL state).
Native_socket_stream & operator= (const Native_socket_stream &)=delete
Copy assignment is disallowed.
const std::string & nickname () const
Returns nickname, a brief string suitable for logging.
flow::log::Logger * get_logger () const
Returns logger (possibly null).
template<typename Create_ev_wait_hndl_func >
bool replace_event_wait_handles (const Create_ev_wait_hndl_func &create_ev_wait_hndl_func)
Implements Native_handle_sender and Native_handle_receiver APIs at the same time, per their concept contracts.
bool sync_connect (const Shared_name &absolute_name, Error_code *err_code=0)
Identical to Async_io_obj counterpart.
size_t send_meta_blob_max_size () const
Implements Native_handle_sender API per contract.
size_t send_blob_max_size () const
Implements Blob_sender API per contract.
template<typename Event_wait_func_t >
bool start_send_native_handle_ops (Event_wait_func_t &&ev_wait_func)
Implements Native_handle_sender API per contract.
template<typename Event_wait_func_t >
bool start_send_blob_ops (Event_wait_func_t &&ev_wait_func)
Implements Blob_sender API per contract.
bool send_native_handle (Native_handle hndl_or_null, const util::Blob_const &meta_blob, Error_code *err_code=0)
Implements Native_handle_sender API per contract.
bool send_blob (const util::Blob_const &blob, Error_code *err_code=0)
Implements Blob_sender API per contract.
template<typename Task_err >
bool async_end_sending (Error_code *sync_err_code, Task_err &&on_done_func)
Implements Native_handle_sender, Blob_sender API per contract.
bool end_sending ()
Implements Native_handle_sender, Blob_sender API per contract.
bool auto_ping (util::Fine_duration period=boost::chrono::seconds(2))
Implements Native_handle_sender, Blob_sender API per contract.
size_t receive_meta_blob_max_size () const
Implements Native_handle_receiver API per contract.
size_t receive_blob_max_size () const
Implements Blob_receiver API per contract.
template<typename Event_wait_func_t >
bool start_receive_native_handle_ops (Event_wait_func_t &&ev_wait_func)
Implements Native_handle_receiver API per contract.
template<typename Event_wait_func_t >
bool start_receive_blob_ops (Event_wait_func_t &&ev_wait_func)
Implements Blob_receiver API per contract.
template<typename Task_err_sz >
bool async_receive_native_handle (Native_handle *target_hndl, const util::Blob_mutable &target_meta_blob, Error_code *sync_err_code, size_t *sync_sz, Task_err_sz &&on_done_func)
Implements Native_handle_receiver API per contract.
template<typename Task_err_sz >
bool async_receive_blob (const util::Blob_mutable &target_blob, Error_code *sync_err_code, size_t *sync_sz, Task_err_sz &&on_done_func)
Implements Blob_receiver API per contract.
bool idle_timer_run (util::Fine_duration timeout=boost::chrono::seconds(5))
Implements Native_handle_receiver, Blob_receiver API per contract.
util::Process_credentials remote_peer_process_credentials (Error_code *err_code=0) const
OS-reported process credential (PID, etc.) info about the other connected peer's process, at the time that the OS first established (via local-socket-connect or local-socket-connected-pair-generate call) that opposing peer socket.
Static Public Attributes
static const Shared_name S_RESOURCE_TYPE_ID = Shared_name::ct("lclSock")
Implements concept API.
static constexpr bool S_META_BLOB_UNDERFLOW_ALLOWED = true
Implements concept API; namely it is true.
static constexpr bool S_BLOB_UNDERFLOW_ALLOWED = true
Implements concept API; namely it is true.
static constexpr bool S_TRANSMIT_NATIVE_HANDLES = true
Useful for generic programming: true to indicate a *this has a send_native_handle() and an async_receive_native_handle().
static const size_t & S_MAX_META_BLOB_LENGTH = Impl::S_MAX_META_BLOB_LENGTH
The maximum length of a blob that can be sent by this protocol.
Private Types
using Impl_ptr = std::experimental::propagate_const< boost::movelib::unique_ptr< Impl > >
Short-hand for const-respecting wrapper around Native_socket_stream::Impl for the pImpl idiom.
Private Member Functions
Impl_ptr & impl () const
Helper that simply returns m_impl while guaranteeing that m_impl is non-null upon return.
bool replace_event_wait_handles_fwd (const Function< util::sync_io::Asio_waitable_native_handle()> &create_ev_wait_hndl_func)
Template-free version of replace_event_wait_handles() as required by pImpl idiom.
bool start_send_native_handle_ops_fwd (util::sync_io::Event_wait_func &&ev_wait_func)
Template-free version of start_send_native_handle_ops() as required by pImpl idiom.
bool start_send_blob_ops_fwd (util::sync_io::Event_wait_func &&ev_wait_func)
Template-free version of start_send_blob_ops() as required by pImpl idiom.
bool async_end_sending_fwd (Error_code *sync_err_code, flow::async::Task_asio_err &&on_done_func)
Template-free version of async_end_sending() as required by pImpl idiom.
bool start_receive_native_handle_ops_fwd (util::sync_io::Event_wait_func &&ev_wait_func)
Template-free version of start_receive_native_handle_ops() as required by pImpl idiom.
bool start_receive_blob_ops_fwd (util::sync_io::Event_wait_func &&ev_wait_func)
Template-free version of start_receive_blob_ops() as required by pImpl idiom.
bool async_receive_native_handle_fwd (Native_handle *target_hndl, const util::Blob_mutable &target_meta_blob, Error_code *sync_err_code, size_t *sync_sz, flow::async::Task_asio_err_sz &&on_done_func)
Template-free version of async_receive_native_handle() as required by pImpl idiom.
bool async_receive_blob_fwd (const util::Blob_mutable &target_blob, Error_code *sync_err_code, size_t *sync_sz, flow::async::Task_asio_err_sz &&on_done_func)
Template-free version of async_receive_blob() as required by pImpl idiom.
Private Attributes
Impl_ptr m_impl
The true implementation of this class.
Friends
std::ostream & operator<< (std::ostream &os, const Native_socket_stream &val)
Friend of Native_socket_stream.
std::ostream & operator<< (std::ostream &os, const Impl &val)
Friend of Native_socket_stream.
Related Functions
(Note that these are not member functions.)
std::ostream & operator<< (std::ostream &os, const Native_socket_stream &val)
Prints string representation of the given Native_socket_stream to the given ostream.
Detailed Description
Implements both sync_io::Native_handle_sender and sync_io::Native_handle_receiver concepts by using a stream-oriented Unix domain socket, allowing high-performance but non-zero-copy transmission of discrete messages, each containing a native handle, a binary blob, or both.
This is the sync_io-pattern counterpart to transport::Native_socket_stream – and in fact the latter use an instance of the present class as its core.
See also
transport::Native_socket_stream and util::sync_io doc headers. The latter describes the general pattern which we implement here; it also contrasts it with the async-I/O pattern, which the former implements. In general we recommend you use a transport::Native_socket_stream rather than a *this – but you may have particular needs (summarized in util::sync_io doc header) that would make you decide otherwise.
Quick note on naming
Notes for transport::Native_socket_stream apply.
sync_io::Blob_sender and sync_io::Blob_receiver concept compatibility
Notes for transport::Native_socket_stream apply analogously.
Informal comparison to other core transport mechanisms
Notes for transport::Native_socket_stream apply.
Cleanup
Notes for transport::Native_socket_stream apply.
How to use
Notes for transport::Native_socket_stream apply. The differences (some of which are quite important) are as follows.
As described by the concepts being implemented – one must use start_send_*_ops() before the send API (send_*(), *end_sending(), auto_ping()) and/or start_receive_*_ops() before the receive API (async_receive_*(), idle_timer_run()).
Before start_*_ops(), it may be required to call replace_event_wait_handles() (depending on your use case).
Regarding ctors: Naturally the transport::Native_socket_stream sync_io-core-adopting ctor does not exist here, as we are a sync_io core. (Or I suppose it's just the move ctor.)
Thread safety
Boring stuff out of the way first: It is safe to concurrently act on 2 separate objects of this type. nickname() and ostream<< are always safe to call, and they always yield the same value (modulo across move-assignment).
Now as to invoking operation X concurrently with operation Y on the same *this, where at least X is non-const:
Firstly let us define operation: Unlike with most APIs in the library, operations don't merely comprise methods (or related free functions). Rather, in addition, invoking util::sync_io::Event_wait_func (*on_active_ev_func)() – to inform *this of an active event due to an earlier async-wait requested by *this – is formally an operation on *this. It can be thought of as a member of its (non-const) API. For the below discussion we shall pretend these methods actually exist, to simplify discussion of these operations:
send_on_active_ev() (on_active_ev_func originating from start_send_*_ops()).
Recall this may synchronously trigger async_end_sending()-passed completion handler.
receive_on_active_ev() (on_active_ev_func originating from start_receive_*_ops()).
Recall this may synchronously trigger async_receive_*()-passed completion handler.
Objects of most types simply declare it to be unsafe to invoke (on one *this) non-const operation X concurrently with operation Y (whether X or Y are the same op or differ). Native_socket_stream, however, works as follows: By default that is indeed the rule... with the exception of the following specific exceptions, wherein it is intentionally safe.
In PEER state
Firstly, let's assume *this is in PEER state, which is achieved either by using the PEER-state ctor form (where a pre-connected Native_handle is subsumed), or else by successfully completing *_connect(). Cool? Cool. We are in PEER state. Then:
Boring ones first: sync_connect() simply returns false and is always safe to call (it is meant for NULL state). *_max_size() always return the same respective constant values and are always safe to call.
Much more significantly, we now list two specific categories of operations:
Send-ops:
send_*(), end_sending(), async_end_sending(), auto_ping(); and send_on_active_ev() (reminder: not a real method but a real op/see definition above).
Receive-ops:
async_receive_*(), idle_timer_run(); and receive_on_active_ev() (reminder: not a real method but a real op/see definition above).
Now then: It is safe to invoke (even on the same *this) any 1 operation from the "send-ops" list concurrently with any 1 operation from the "receive-ops" list.
Formally that's simply the case.
Informally: it may be highly significant to performance of the user code that this is the case. It means that the two mutually-opposing pipes can operate concurrently, despite the fact they're operating on the same socket. E.g., an upload and download being highly active simultaneously will proceed in parallel on separate processor cores if possible. If your event loop is single-threaded in any case, then this does not matter; but if 2+ threads are involved, then it may well matter quite a bit. (For example: non-sync_io transport::Native_socket_stream is internally built on a sync_io::Native_socket_stream. It starts a thread (internally dubbed thread W) in which to perform significant incoming-direction work, while most – but not all – outgoing-direction work is done synchronously from its user's calling thread (dubbed thread U). Therefore it can keep 2 separate mutexes (one for each direction) and lock only 1 when doing in-work (in either thread U/W); and lock the other when doing out-work, in either thread U/W. So if a send can complete synchronously in thread U, while a receive does stuff in the background in thread W, the two may execute concurrently as opposed to serially. Running concurrently would decrease latency latency in sending and/or receipt.)
In NULL state
Nothing interesting here.
Implementation design/rationale
Notes for transport::Native_socket_stream apply: the pImpl stuff; and the fact that:
The rest of the implementation is inside sync_io::Native_socket_stream::Impl and is discussed in that class's doc header.
See also
sync_io::Native_socket_stream::Impl doc header.
See also
sync_io::Native_handle_sender: implemented concept.
sync_io::Native_handle_receiver: implemented concept.
sync_io::Blob_sender: alternatively implemented concept.
sync_io::Blob_receiver: alternatively implemented concept.
Definition at line 150 of file native_socket_stream.hpp.
Member Typedef Documentation
Async_io_obj
using ipc::transport::sync_io::Native_socket_stream::Async_io_obj = transport::Native_socket_stream
Useful for generic programming, the async-I/O-pattern counterpart to *this type.
Definition at line 156 of file native_socket_stream.hpp.
Impl_ptr
using ipc::transport::sync_io::Native_socket_stream::Impl_ptr = std::experimental::propagate_const<boost::movelib::unique_ptr<Impl> > private
Short-hand for const-respecting wrapper around Native_socket_stream::Impl for the pImpl idiom.
Definition at line 613 of file native_socket_stream.hpp.
Sync_io_obj
using ipc::transport::sync_io::Native_socket_stream::Sync_io_obj = Null_peer
You may disregard.
Definition at line 158 of file native_socket_stream.hpp.
Constructor & Destructor Documentation
Native_socket_stream() [1/4]
ipc::transport::sync_io::Native_socket_stream::Native_socket_stream ()
Default ctor (object is in NULL state).
Notes for transport::Native_socket_stream apply.
See also
Native_handle_sender::Native_handle_sender(): implemented concept.
Native_handle_receiver::Native_handle_receiver(): implemented concept.
Blob_sender::Blob_sender(): implemented concept.
Blob_receiver::Blob_receiver(): implemented concept.
Definition at line 55 of file native_socket_stream.cpp.
Native_socket_stream() [2/4]
ipc::transport::sync_io::Native_socket_stream::Native_socket_stream (flow::log::Logger * logger_ptr, util::String_view nickname_str) explicit
Creates a Native_socket_stream in NULL (not connected) state.
Notes for transport::Native_socket_stream apply.
Parameters
logger_ptr See above.
nickname_str See above.
Definition at line 63 of file native_socket_stream.cpp.
Native_socket_stream() [3/4]
ipc::transport::sync_io::Native_socket_stream::Native_socket_stream (flow::log::Logger * logger_ptr, util::String_view nickname_str, Native_handle && native_peer_socket_moved) explicit
Constructs the socket-and-meta-blob stream by taking over an already-connected native Unix domain socket handle.
Notes for transport::Native_socket_stream apply.
Parameters
logger_ptr See above.
native_peer_socket_moved See above.
nickname_str See above.
Definition at line 69 of file native_socket_stream.cpp.
Native_socket_stream() [4/4]
ipc::transport::sync_io::Native_socket_stream::Native_socket_stream (Native_socket_stream && src) default
Move-constructs from src; src becomes as-if default-cted (therefore in NULL state).
Notes for transport::Native_socket_stream apply.
Parameters
src See above.
See also
Native_handle_sender::Native_handle_sender(): implemented concept.
Native_handle_receiver::Native_handle_receiver(): implemented concept.
Blob_sender::Blob_sender(): implemented concept.
Blob_receiver::Blob_receiver(): implemented concept.
~Native_socket_stream()
ipc::transport::sync_io::Native_socket_stream::~Native_socket_stream () default
Implements Native_handle_sender and Native_handle_receiver APIs at the same time, per their concept contracts.
(Also implements Blob_sender and Blob_receiver APIs; they are identical.)
See also
Native_handle_sender::~Native_handle_sender(): implemented concept.
Native_handle_receiver::~Native_handle_receiver(): implemented concept.
Blob_sender::~Blob_sender(): alternatively implemented concept.
Blob_receiver::~Blob_receiver(): alternatively implemented concept.
Member Function Documentation
async_end_sending()
template<typename Task_err > bool ipc::transport::sync_io::Native_socket_stream::async_end_sending (Error_code * sync_err_code, Task_err && on_done_func)
Implements Native_handle_sender, Blob_sender API per contract.
Reminder: Please peruse "Thread safety" in class doc header.
Error_code generated and passed to on_done_func() or emitted synchronously: See Async_io_obj counterpart doc header.
Reminder: In rare circumstances, an error emitted there may represent something detected during handling of a preceding send_native_handle() or send_blob() call but after it returned.
Template Parameters
Task_err See above.
Parameters
sync_err_code See above. Do realize error::Code::S_SYNC_IO_WOULD_BLOCK is still an error, so if this pointer is null, then would-block will make this throw.
on_done_func See above.
Returns
See above. Reminder: If and only if it returns false, we're in NULL state, or *end_sending() has already been called; and on_done_func() will never be called, nor will an error be emitted.
See also
Native_handle_sender::async_end_sending(): implemented concept.
Blob_sender::async_end_sending(): alternatively implemented concept.
Definition at line 795 of file native_socket_stream.hpp.
References async_end_sending_fwd().
async_end_sending_fwd()
bool ipc::transport::sync_io::Native_socket_stream::async_end_sending_fwd (Error_code * sync_err_code, flow::async::Task_asio_err && on_done_func) private
Template-free version of async_end_sending() as required by pImpl idiom.
Parameters
sync_err_code See above. Do realize error::Code::S_SYNC_IO_WOULD_BLOCK is still an error, so if this pointer is null, then would-block will make this throw.
on_done_func See above.
Returns
See above.
Definition at line 178 of file native_socket_stream.cpp.
References impl().
Referenced by async_end_sending().
async_receive_blob()
template<typename Task_err_sz > bool ipc::transport::sync_io::Native_socket_stream::async_receive_blob (const util::Blob_mutable & target_blob, Error_code * sync_err_code, size_t * sync_sz, Task_err_sz && on_done_func)
Implements Blob_receiver API per contract.
Reminder: Please peruse "Thread safety" in class doc header.
Error_code generated and passed to on_done_func() or emitted synchronously: See Async_io_obj::async_receive_blob() doc header (but not S_OBJECT_SHUTDOWN_ABORTED_COMPLETION_HANDLER).
Template Parameters
Task_err_sz See above.
Parameters
target_blob See above.
sync_err_code See above. Do realize error::Code::S_SYNC_IO_WOULD_BLOCK is still an error, so if this pointer is null, then would-block will make this throw.
sync_sz See above.
on_done_func See above.
Returns
See above.
See also
Blob_receiver::async_receive_blob(): implemented concept.
Definition at line 835 of file native_socket_stream.hpp.
References async_receive_blob_fwd().
async_receive_blob_fwd()
bool ipc::transport::sync_io::Native_socket_stream::async_receive_blob_fwd (const util::Blob_mutable & target_blob, Error_code * sync_err_code, size_t * sync_sz, flow::async::Task_asio_err_sz && on_done_func) private
Template-free version of async_receive_blob() as required by pImpl idiom.
Parameters
target_blob See above.
sync_err_code See above. Do realize error::Code::S_SYNC_IO_WOULD_BLOCK is still an error, so if this pointer is null, then would-block will make this throw.
sync_sz See above.
on_done_func See above.
Returns
See above.
Definition at line 202 of file native_socket_stream.cpp.
References impl().
Referenced by async_receive_blob().
async_receive_native_handle()
template<typename Task_err_sz > bool ipc::transport::sync_io::Native_socket_stream::async_receive_native_handle (Native_handle * target_hndl, const util::Blob_mutable & target_meta_blob, Error_code * sync_err_code, size_t * sync_sz, Task_err_sz && on_done_func)
Implements Native_handle_receiver API per contract.
Reminder: Please peruse "Thread safety" in class doc header.
Error_code generated and passed to on_done_func() or emitted synchronously: See Async_io_obj::async_receive_native_handle() doc header (but not S_OBJECT_SHUTDOWN_ABORTED_COMPLETION_HANDLER).
Template Parameters
Task_err_sz See above.
Parameters
target_hndl See above.
target_meta_blob See above.
sync_err_code See above. Do realize error::Code::S_SYNC_IO_WOULD_BLOCK is still an error, so if this pointer is null, then would-block will make this throw.
sync_sz See above.
on_done_func See above.
Returns
See above.
See also
Native_handle_receiver::async_receive_native_handle(): implemented concept.
Definition at line 823 of file native_socket_stream.hpp.
References async_receive_native_handle_fwd().
async_receive_native_handle_fwd()
bool ipc::transport::sync_io::Native_socket_stream::async_receive_native_handle_fwd (Native_handle * target_hndl, const util::Blob_mutable & target_meta_blob, Error_code * sync_err_code, size_t * sync_sz, flow::async::Task_asio_err_sz && on_done_func) private
Template-free version of async_receive_native_handle() as required by pImpl idiom.
Parameters
target_hndl See above.
target_meta_blob See above.
sync_err_code See above. Do realize error::Code::S_SYNC_IO_WOULD_BLOCK is still an error, so if this pointer is null, then would-block will make this throw.
sync_sz See above.
on_done_func See above.
Returns
See above.
Definition at line 193 of file native_socket_stream.cpp.
References impl().
Referenced by async_receive_native_handle().
auto_ping()
bool ipc::transport::sync_io::Native_socket_stream::auto_ping (util::Fine_duration period = boost::chrono::seconds(2))
Implements Native_handle_sender, Blob_sender API per contract.
Parameters
period See above.
Returns
See above.
See also
Native_handle_sender::auto_ping(): implemented concept.
Blob_sender::auto_ping(): alternatively implemented concept.
Definition at line 128 of file native_socket_stream.cpp.
References impl().
end_sending()
bool ipc::transport::sync_io::Native_socket_stream::end_sending ()
Implements Native_handle_sender, Blob_sender API per contract.
Returns
See above.
See also
Native_handle_sender::end_sending(): implemented concept.
Blob_sender::end_sending(): alternatively implemented concept.
Definition at line 123 of file native_socket_stream.cpp.
References impl().
get_logger()
flow::log::Logger * ipc::transport::sync_io::Native_socket_stream::get_logger () const
Returns logger (possibly null).
Returns
See above.
Definition at line 148 of file native_socket_stream.cpp.
References impl().
Referenced by ipc::transport::sync_io::Native_socket_stream::Impl::async_connect(), ipc::transport::sync_io::Native_socket_stream::Impl::Impl(), ipc::transport::sync_io::Native_socket_stream::Impl::rcv_nb_read_low_lvl_payload(), ipc::transport::sync_io::Native_socket_stream::Impl::snd_nb_write_low_lvl_payload(), and ipc::transport::sync_io::Native_socket_stream::Impl::snd_sync_write_or_q_payload().
idle_timer_run()
bool ipc::transport::sync_io::Native_socket_stream::idle_timer_run (util::Fine_duration timeout = boost::chrono::seconds(5))
Implements Native_handle_receiver, Blob_receiver API per contract.
Reminder: Please peruse "Thread safety" in class doc header.
Parameters
timeout See above.
Returns
See above.
See also
Blob_receiver::idle_timer_run(): implemented concept.
Native_handle_receiver::idle_timer_run(): alternatively implemented concept.
Definition at line 143 of file native_socket_stream.cpp.
References impl().
impl()
Native_socket_stream::Impl_ptr & ipc::transport::sync_io::Native_socket_stream::impl () const private
Helper that simply returns m_impl while guaranteeing that m_impl is non-null upon return.
All forwarding-to-m_impl methods (including const ones) shall access m_impl through this impl() method only.
Design/rationale
Notes from transport::Native_socket_stream apply.
Returns
Reference to m_impl.
Definition at line 41 of file native_socket_stream.cpp.
References m_impl.
Referenced by async_end_sending_fwd(), async_receive_blob_fwd(), async_receive_native_handle_fwd(), auto_ping(), end_sending(), get_logger(), idle_timer_run(), nickname(), receive_blob_max_size(), receive_meta_blob_max_size(), remote_peer_process_credentials(), replace_event_wait_handles_fwd(), send_blob(), send_blob_max_size(), send_meta_blob_max_size(), send_native_handle(), start_receive_blob_ops_fwd(), start_receive_native_handle_ops_fwd(), start_send_blob_ops_fwd(), start_send_native_handle_ops_fwd(), and sync_connect().
nickname()
const std::string & ipc::transport::sync_io::Native_socket_stream::nickname () const
Returns nickname, a brief string suitable for logging.
Notes for transport::Native_socket_stream apply.
Returns
See above.
Definition at line 78 of file native_socket_stream.cpp.
References impl().
operator=()
Native_socket_stream & ipc::transport::sync_io::Native_socket_stream::operator= (Native_socket_stream && src) default
Move-assigns from src; *this acts as if destructed; src becomes as-if default-cted (therefore in NULL state).
No-op if &src == this.
Notes for transport::Native_socket_stream apply.
Parameters
src See above.
Returns
*this.
See also
Native_handle_sender move assignment: implemented concept.
Native_handle_receiver move assignment: implemented concept.
Blob_sender move assignment: implemented concept.
Blob_receiver move assignment: implemented concept.
receive_blob_max_size()
size_t ipc::transport::sync_io::Native_socket_stream::receive_blob_max_size () const
Implements Blob_receiver API per contract.
Notes for transport::Blob_receiver apply.
Returns
See above.
See also
Blob_receiver::receive_blob_max_size(): implemented concept.
Definition at line 138 of file native_socket_stream.cpp.
References impl().
receive_meta_blob_max_size()
size_t ipc::transport::sync_io::Native_socket_stream::receive_meta_blob_max_size () const
Implements Native_handle_receiver API per contract.
Notes for transport::Native_handle_receiver apply.
Returns
See above.
See also
Native_handle_receiver::receive_meta_blob_max_size(): implemented concept.
Definition at line 133 of file native_socket_stream.cpp.
References impl().
Referenced by ipc::transport::sync_io::Native_socket_stream::Impl::receive_blob_max_size().
remote_peer_process_credentials()
util::Process_credentials ipc::transport::sync_io::Native_socket_stream::remote_peer_process_credentials (Error_code * err_code = 0) const
OS-reported process credential (PID, etc.) info about the other connected peer's process, at the time that the OS first established (via local-socket-connect or local-socket-connected-pair-generate call) that opposing peer socket.
The value returned, assuming a non-error-emitting execution, shall always be the same for a given *this.
Informally: To avoid (though, formally, not guarantee) error::Code::S_LOW_LVL_TRANSPORT_HOSED, it is best to call this immediately upon entry of *this to PEER state and/or before invoking any other APIs.
If invoked outside of PEER state returns Process_credentials() immediately and otherwise does nothing.
Returns
See above; or Peer_credentials() if invoked outside of PEER state or in case of error. The 2 eventualities can be distinguished by checking *err_code truthiness. Better yet only call remote_peer_process_credentials() in PEER state, as it is otherwise conceptually meaningless.
Parameters
err_code See flow::Error_code docs for error reporting semantics. Error_code generated: See Async_io_obj counterpart doc header.
Definition at line 97 of file native_socket_stream.cpp.
References impl().
replace_event_wait_handles()
template<typename Create_ev_wait_hndl_func > bool ipc::transport::sync_io::Native_socket_stream::replace_event_wait_handles (const Create_ev_wait_hndl_func & create_ev_wait_hndl_func)
Implements Native_handle_sender and Native_handle_receiver APIs at the same time, per their concept contracts.
(Also implements Blob_sender and Blob_receiver APIs; they are identical.)
Parameters
create_ev_wait_hndl_func See above.
Returns
See above.
See also
Native_handle_sender::replace_event_wait_handles(): implemented concept.
Native_handle_receiver::replace_event_wait_handles(): implemented concept.
Blob_sender::replace_event_wait_handles(): alternatively implemented concept.
Blob_receiver::replace_event_wait_handles(): alternatively implemented concept.
Definition at line 771 of file native_socket_stream.hpp.
References replace_event_wait_handles_fwd().
Referenced by ipc::transport::Native_socket_stream::Impl::Impl().
replace_event_wait_handles_fwd()
bool ipc::transport::sync_io::Native_socket_stream::replace_event_wait_handles_fwd (const Function< util::sync_io::Asio_waitable_native_handle()> & create_ev_wait_hndl_func) private
Template-free version of replace_event_wait_handles() as required by pImpl idiom.
Parameters
create_ev_wait_hndl_func See replace_event_wait_handles().
Returns
See replace_event_wait_handles().
Definition at line 162 of file native_socket_stream.cpp.
References impl().
Referenced by replace_event_wait_handles().
send_blob()
bool ipc::transport::sync_io::Native_socket_stream::send_blob (const util::Blob_const & blob, Error_code * err_code = 0)
Implements Blob_sender API per contract.
Reminder: Please peruse "Thread safety" in class doc header.
Parameters
blob See above.
err_code See above. Reminder: In rare circumstances, an error emitted here may represent something detected during handling of a preceding send_native_handle() call but after it returned. Error_code generated: See Async_io_obj counterpart doc header.
Returns
See above.
See also
Blob_sender::send_blob(): implemented concept.
Definition at line 118 of file native_socket_stream.cpp.
References impl().
send_blob_max_size()
size_t ipc::transport::sync_io::Native_socket_stream::send_blob_max_size () const
Implements Blob_sender API per contract.
Notes for transport::Blob_sender apply.
Returns
See above.
See also
Blob_sender::send_blob_max_size(): implemented concept.
Definition at line 107 of file native_socket_stream.cpp.
References impl().
send_meta_blob_max_size()
size_t ipc::transport::sync_io::Native_socket_stream::send_meta_blob_max_size () const
Implements Native_handle_sender API per contract.
Notes for transport::Native_handle_sender apply.
Returns
See above.
See also
Native_handle_sender::send_meta_blob_max_size(): implemented concept.
Definition at line 102 of file native_socket_stream.cpp.
References impl().
Referenced by ipc::transport::sync_io::Native_socket_stream::Impl::send_blob_max_size().
send_native_handle()
bool ipc::transport::sync_io::Native_socket_stream::send_native_handle (Native_handle hndl_or_null, const util::Blob_const & meta_blob, Error_code * err_code = 0)
Implements Native_handle_sender API per contract.
Reminder: Please peruse "Thread safety" in class doc header.
Parameters
hndl_or_null See above.
meta_blob See above.
err_code See above. Reminder: In rare circumstances, an error emitted here may represent something detected during handling of a preceding send_native_handle() call but after it returned. Error_code generated: See Async_io_obj counterpart doc header.
Returns
See above.
See also
Native_handle_sender::send_native_handle(): implemented concept.
Definition at line 112 of file native_socket_stream.cpp.
References impl().
Referenced by ipc::transport::sync_io::Native_socket_stream::Impl::send_blob().
start_receive_blob_ops()
template<typename Event_wait_func_t > bool ipc::transport::sync_io::Native_socket_stream::start_receive_blob_ops (Event_wait_func_t && ev_wait_func)
Implements Blob_receiver API per contract.
In this implementation start_receive_native_handle_ops() and start_receive_blob_ops() are interchangeable: calling either one gets the job done, and calling the other subsequently is harmless but would return false and no-op/log WARNING.
Template Parameters
Event_wait_func_t See above.
Parameters
ev_wait_func See above.
Returns
See above. In addition return false/WARNING/no-op, if start_receive_native_handle_ops() earlier succeeded.
See also
Native_handle_receiver::start_receive_blob_ops(): implemented concept.
Definition at line 815 of file native_socket_stream.hpp.
References start_receive_blob_ops_fwd().
start_receive_blob_ops_fwd()
bool ipc::transport::sync_io::Native_socket_stream::start_receive_blob_ops_fwd (util::sync_io::Event_wait_func && ev_wait_func) private
Template-free version of start_receive_blob_ops() as required by pImpl idiom.
Parameters
ev_wait_func See above.
Returns
See above.
Definition at line 188 of file native_socket_stream.cpp.
References impl().
Referenced by start_receive_blob_ops().
start_receive_native_handle_ops()
template<typename Event_wait_func_t > bool ipc::transport::sync_io::Native_socket_stream::start_receive_native_handle_ops (Event_wait_func_t && ev_wait_func)
Implements Native_handle_receiver API per contract.
See also start_receive_blob_ops().
Template Parameters
Event_wait_func_t See above.
Parameters
ev_wait_func See above.
Returns
See above. In addition return false/WARNING/no-op, if start_receive_blob_ops() earlier succeeded.
See also
Native_handle_receiver::receive_blob_max_size(): implemented concept.
Definition at line 807 of file native_socket_stream.hpp.
References start_receive_native_handle_ops_fwd().
Referenced by ipc::transport::sync_io::Native_socket_stream::Impl::start_receive_blob_ops().
start_receive_native_handle_ops_fwd()
bool ipc::transport::sync_io::Native_socket_stream::start_receive_native_handle_ops_fwd (util::sync_io::Event_wait_func && ev_wait_func) private
Template-free version of start_receive_native_handle_ops() as required by pImpl idiom.
Parameters
ev_wait_func See above.
Returns
See above.
Definition at line 183 of file native_socket_stream.cpp.
References impl().
Referenced by start_receive_native_handle_ops().
start_send_blob_ops()
template<typename Event_wait_func_t > bool ipc::transport::sync_io::Native_socket_stream::start_send_blob_ops (Event_wait_func_t && ev_wait_func)
Implements Blob_sender API per contract.
In this implementation start_send_native_handle_ops() and start_send_blob_ops() are interchangeable: calling either one gets the job done, and calling the other subsequently is harmless but would return false and no-op/log WARNING.
Template Parameters
Event_wait_func_t See above.
Parameters
ev_wait_func See above.
Returns
See above. In addition return false/WARNING/no-op, if start_send_native_handle_ops() earlier succeeded.
See also
Blob_sender::start_send_blob_ops(): implemented concept.
Definition at line 787 of file native_socket_stream.hpp.
References start_send_blob_ops_fwd().
start_send_blob_ops_fwd()
bool ipc::transport::sync_io::Native_socket_stream::start_send_blob_ops_fwd (util::sync_io::Event_wait_func && ev_wait_func) private
Template-free version of start_send_blob_ops() as required by pImpl idiom.
Parameters
ev_wait_func See above.
Returns
See above.
Definition at line 173 of file native_socket_stream.cpp.
References impl().
Referenced by start_send_blob_ops().
start_send_native_handle_ops()
template<typename Event_wait_func_t > bool ipc::transport::sync_io::Native_socket_stream::start_send_native_handle_ops (Event_wait_func_t && ev_wait_func)
Implements Native_handle_sender API per contract.
See also start_send_blob_ops().
Template Parameters
Event_wait_func_t See above.
Parameters
ev_wait_func See above.
Returns
See above. In addition return false/WARNING/no-op, if start_send_blob_ops() earlier succeeded.
See also
Native_handle_sender::start_send_native_handle_ops(): implemented concept.
Definition at line 779 of file native_socket_stream.hpp.
References start_send_native_handle_ops_fwd().
Referenced by ipc::transport::sync_io::Native_socket_stream::Impl::start_send_blob_ops().
start_send_native_handle_ops_fwd()
bool ipc::transport::sync_io::Native_socket_stream::start_send_native_handle_ops_fwd (util::sync_io::Event_wait_func && ev_wait_func) private
Template-free version of start_send_native_handle_ops() as required by pImpl idiom.
Parameters
ev_wait_func See above.
Returns
See above.
Definition at line 168 of file native_socket_stream.cpp.
References impl().
Referenced by start_send_native_handle_ops().
sync_connect()
bool ipc::transport::sync_io::Native_socket_stream::sync_connect (const Shared_name & absolute_name, Error_code * err_code = 0)
Identical to Async_io_obj counterpart.
Parameters
absolute_name See above.
err_code See above.
Returns
See above.
Definition at line 83 of file native_socket_stream.cpp.
References impl().
Referenced by ipc::session::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, S_SHM_TYPE_OR_NONE, S_GRACEFUL_FINISH_REQUIRED_V >::async_connect().
Friends And Related Function Documentation
operator<< [1/3]
std::ostream & operator<< (std::ostream & os, const Impl & val) friend
Friend of Native_socket_stream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 519 of file native_socket_stream_impl.cpp.
operator<< [2/3]
std::ostream & operator<< (std::ostream & os, const Native_socket_stream & val) friend
Friend of Native_socket_stream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 155 of file native_socket_stream.cpp.
operator<<() [3/3]
std::ostream & operator<< (std::ostream & os, const Native_socket_stream & val) related
Prints string representation of the given Native_socket_stream to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 155 of file native_socket_stream.cpp.
Member Data Documentation
m_impl
Impl_ptr ipc::transport::sync_io::Native_socket_stream::m_impl mutable private
The true implementation of this class.
See also our class doc header; and impl() (in particular explaining why this is mutable).
Do not access directly but only via impl().
Definition at line 763 of file native_socket_stream.hpp.
Referenced by impl().
S_BLOB_UNDERFLOW_ALLOWED
constexpr bool ipc::transport::sync_io::Native_socket_stream::S_BLOB_UNDERFLOW_ALLOWED = true static constexpr
Implements concept API; namely it is true.
Notes for transport::Native_socket_stream apply.
See also
Native_handle_receiver::S_BLOB_UNDERFLOW_ALLOWED: implemented concept. Accordingly also see "Blob underflow semantics" in transport::Native_handle_receiver doc header.
Definition at line 179 of file native_socket_stream.hpp.
Referenced by ipc::transport::sync_io::Native_socket_stream::Impl::async_receive_native_handle_impl().
S_MAX_META_BLOB_LENGTH
const size_t & ipc::transport::sync_io::Native_socket_stream::S_MAX_META_BLOB_LENGTH = Impl::S_MAX_META_BLOB_LENGTH static
The maximum length of a blob that can be sent by this protocol.
send_native_handle() shall synchronously emit a particular error, if meta_blob.size() exceeds this. send_blob() shall do similarly for blob arg. The same is accurate of their async-I/O-pattern transport::Native_socket_stream counterparts.
Why is it a reference? Answer: To provide for strict pImpl adherence without exploding due to indeterminate order of static initializations across translation units (.cpp files).
Definition at line 197 of file native_socket_stream.hpp.
Referenced by ipc::session::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, S_SHM_TYPE_OR_NONE, S_GRACEFUL_FINISH_REQUIRED_V >::mdt_builder(), ipc::transport::sync_io::Native_socket_stream::Impl::receive_meta_blob_max_size(), ipc::transport::sync_io::Native_socket_stream::Impl::send_meta_blob_max_size(), and ipc::transport::sync_io::Native_socket_stream::Impl::send_native_handle().
S_META_BLOB_UNDERFLOW_ALLOWED
constexpr bool ipc::transport::sync_io::Native_socket_stream::S_META_BLOB_UNDERFLOW_ALLOWED = true static constexpr
Implements concept API; namely it is true.
Notes for transport::Native_socket_stream apply.
See also
Native_handle_receiver::S_META_BLOB_UNDERFLOW_ALLOWED: implemented concept. Accordingly also see "Blob underflow semantics" in transport::Native_handle_receiver doc header.
Definition at line 171 of file native_socket_stream.hpp.
S_RESOURCE_TYPE_ID
const Shared_name ipc::transport::sync_io::Native_socket_stream::S_RESOURCE_TYPE_ID = Shared_name::ct("lclSock") static
Implements concept API.
Definition at line 163 of file native_socket_stream.hpp.
S_TRANSMIT_NATIVE_HANDLES
constexpr bool ipc::transport::sync_io::Native_socket_stream::S_TRANSMIT_NATIVE_HANDLES = true static constexpr
Useful for generic programming: true to indicate a *this has a send_native_handle() and an async_receive_native_handle().
Definition at line 185 of file native_socket_stream.hpp.
The documentation for this class was generated from the following files:
transport/sync_io/native_socket_stream.hpp
transport/sync_io/native_socket_stream.cpp
transport/transport_fwd.hpp