Flow-IPC: ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle > Class Template Reference
ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle > Class Template Reference
Internal, non-movable pImpl-lite implementation of Blob_stream_mq_sender class template.
#include <blob_stream_mq_snd_impl.hpp>
Public Types
using Base = Blob_stream_mq_base_impl< Persistent_mq_handle >
Short-hand for our base with static goodies at least.
using Mq = typename Base::Mq
Short-hand for template arg for underlying MQ handle type.
Public Types inherited from ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle >
using Mq = Persistent_mq_handle
Short-hand for template arg for underlying MQ handle type.
using Auto_closing_mq = boost::movelib::unique_ptr< Mq, Function< void(Mq *)> >
Persistent_mq_handle holder that takes a deleter lambda on construction, intended here to perform additional deinit steps in addition to closing the Mq by deleting it.
Public Member Functions
Blob_stream_mq_sender_impl (flow::log::Logger *logger_ptr, util::String_view nickname_str, Mq &&mq_moved, Error_code *err_code)
See Blob_stream_mq_sender counterpart.
Blob_stream_mq_sender_impl (sync_io::Blob_stream_mq_sender< Mq > &&sync_io_core_in_peer_state_moved)
See Blob_stream_mq_sender counterpart.
~Blob_stream_mq_sender_impl ()
See Blob_stream_mq_sender counterpart.
size_t send_blob_max_size () const
See Blob_stream_mq_sender counterpart, but assuming PEER state.
void send_blob (const util::Blob_const &blob, Error_code *err_code)
See Blob_stream_mq_sender counterpart, but assuming PEER state.
template<typename Task_err >
bool async_end_sending (Task_err &&on_done_func)
See Blob_stream_mq_sender counterpart, but assuming PEER state.
bool end_sending ()
See Blob_stream_mq_sender counterpart, but assuming PEER state.
bool auto_ping (util::Fine_duration period)
See Blob_stream_mq_sender counterpart, but assuming PEER state.
const std::string & nickname () const
See Blob_stream_mq_sender counterpart, but assuming PEER state.
const Shared_name & absolute_name () const
See Blob_stream_mq_sender counterpart, but assuming PEER state.
Private Attributes
flow::async::Single_thread_task_loop m_worker
Single-thread worker pool for all internal async work.
sync_io::Blob_stream_mq_sender< Mq > m_sync_io
The core Blob_stream_mq_sender engine, implementing the sync_io pattern (see util::sync_io doc header).
std::optional< sync_io::Async_adapter_sender< decltype(m_sync_io)> > m_sync_io_adapter
This handles ~all logic in that state.
Related Functions
(Note that these are not member functions.)
template<typename Persistent_mq_handle >
std::ostream & operator<< (std::ostream &os, const Blob_stream_mq_sender_impl< Persistent_mq_handle > &val)
Prints string representation of the given Blob_stream_mq_sender to the given ostream.
Additional Inherited Members
Static Public Member Functions inherited from ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle >
static void remove_persistent (flow::log::Logger *logger_ptr, const Shared_name &name, Error_code *err_code)
See Blob_stream_mq_base counterpart.
template<typename Handle_name_func >
static void for_each_persistent (const Handle_name_func &handle_name_func)
See Blob_stream_mq_base counterpart.
static Auto_closing_mq ensure_unique_peer (flow::log::Logger *logger_ptr, Mq &&mq, bool snd_else_rcv, Error_code *err_code)
Internal helper for Blob_stream_mq_sender and Blob_stream_mq_receiver that operates both the start and end of the anti-dupe-endpoint machinery used by those 2 classes to prevent more than 1 _sender and more than 1 _receiver for a given underlying MQ.
Protected Types inherited from ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle >
enum class Control_cmd : int64_t { S_END_SENDING , S_PING , S_END_SENTINEL }
If Blob_stream_mq_sender_impl sends an empty message, in NORMAL state Blob_stream_mq_receiver enters CONTROL state and expects one of these values in the next message, to react as documented per enum value (upon re-entering NORMAL state).
Detailed Description
template<typename Persistent_mq_handle>
class ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >
Internal, non-movable pImpl-lite implementation of Blob_stream_mq_sender class template.
In and of itself it would have been directly and publicly usable; however Blob_stream_mq_sender adds move semantics which are essential to cooperation with the rest of the API, Channel in particular.
See also
All discussion of the public API is in Blob_stream_mq_sender doc header; that class template forwards to this one. All discussion of pImpl-lite-related notions is also there. See that doc header first please. Then come back here.
Impl design
The actual logic in this class is very simple, because (1) it's either in PEER state or NULL state, and there is no CONNECTING to speak of – the only way to go between them is move-assignment; and (2) while in PEER state it is only a matter of adapting a sync_io::Blob_sender – namely sync_io::Blob_stream_mq_sender – core into the requirements of async-I/O-pattern Blob_sender concept. PEER state has 100% of the logic; and 99% of that logic is adapting which is accomplished by class template sync_io::Async_adapter_sender.
Therefore:
See also
sync_io::Blob_stream_mq_sender for the core logic having to do with managing MQs.
sync_io::Async_adapter_sender for the transport-agnostic adapting of the latter (as a sync_io::Blob_sender) into a *this. We just forward to it.
Template Parameters
Persistent_mq_handle See Persistent_mq_handle concept doc header.
Definition at line 59 of file blob_stream_mq_snd_impl.hpp.
Member Typedef Documentation
Base
template<typename Persistent_mq_handle > using ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Base = Blob_stream_mq_base_impl<Persistent_mq_handle>
Short-hand for our base with static goodies at least.
Definition at line 68 of file blob_stream_mq_snd_impl.hpp.
Mq
template<typename Persistent_mq_handle > using ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Mq = typename Base::Mq
Short-hand for template arg for underlying MQ handle type.
Definition at line 71 of file blob_stream_mq_snd_impl.hpp.
Constructor & Destructor Documentation
Blob_stream_mq_sender_impl() [1/2]
template<typename Persistent_mq_handle > ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Blob_stream_mq_sender_impl (flow::log::Logger * logger_ptr, util::String_view nickname_str, Mq && mq_moved, Error_code * err_code) explicit
See Blob_stream_mq_sender counterpart.
Parameters
logger_ptr See Blob_stream_mq_sender counterpart.
mq_moved See Blob_stream_mq_sender counterpart.
nickname_str See Blob_stream_mq_sender counterpart.
err_code See Blob_stream_mq_sender counterpart.
Definition at line 220 of file blob_stream_mq_snd_impl.hpp.
Blob_stream_mq_sender_impl() [2/2]
template<typename Persistent_mq_handle > ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Blob_stream_mq_sender_impl (sync_io::Blob_stream_mq_sender< Mq > && sync_io_core_in_peer_state_moved) explicit
See Blob_stream_mq_sender counterpart.
Parameters
sync_io_core_in_peer_state_moved See Blob_stream_mq_sender counterpart.
Definition at line 233 of file blob_stream_mq_snd_impl.hpp.
References ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_sync_io, ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_sync_io_adapter, ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_worker, and ipc::transport::sync_io::Blob_stream_mq_sender< Persistent_mq_handle >::replace_event_wait_handles().
~Blob_stream_mq_sender_impl()
template<typename Persistent_mq_handle > ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::~Blob_stream_mq_sender_impl
See Blob_stream_mq_sender counterpart.
Impl note: The unspecified thread, as of this writing, is not thread W. There is rationale discussion and detail in the body, but it seemed prudent to point it out here.
Definition at line 262 of file blob_stream_mq_snd_impl.hpp.
Member Function Documentation
absolute_name()
template<typename Persistent_mq_handle > const Shared_name & ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::absolute_name
See Blob_stream_mq_sender counterpart, but assuming PEER state.
Returns
See Blob_stream_mq_sender counterpart.
Definition at line 346 of file blob_stream_mq_snd_impl.hpp.
Referenced by ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::operator<<().
async_end_sending()
template<typename Persistent_mq_handle > template<typename Task_err > bool ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::async_end_sending (Task_err && on_done_func)
See Blob_stream_mq_sender counterpart, but assuming PEER state.
Parameters
on_done_func See Blob_stream_mq_sender counterpart.
Returns
See Blob_stream_mq_sender counterpart.
Definition at line 326 of file blob_stream_mq_snd_impl.hpp.
auto_ping()
template<typename Persistent_mq_handle > bool ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::auto_ping (util::Fine_duration period)
See Blob_stream_mq_sender counterpart, but assuming PEER state.
Parameters
period See Blob_stream_mq_sender counterpart.
Returns
See Blob_stream_mq_sender counterpart.
Definition at line 332 of file blob_stream_mq_snd_impl.hpp.
end_sending()
template<typename Persistent_mq_handle > bool ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::end_sending
See Blob_stream_mq_sender counterpart, but assuming PEER state.
Returns
See Blob_stream_mq_sender counterpart.
Definition at line 317 of file blob_stream_mq_snd_impl.hpp.
nickname()
template<typename Persistent_mq_handle > const std::string & ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::nickname
See Blob_stream_mq_sender counterpart, but assuming PEER state.
Returns
See Blob_stream_mq_sender counterpart.
Definition at line 352 of file blob_stream_mq_snd_impl.hpp.
Referenced by ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::operator<<().
send_blob()
template<typename Persistent_mq_handle > void ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::send_blob (const util::Blob_const & blob, Error_code * err_code)
See Blob_stream_mq_sender counterpart, but assuming PEER state.
Parameters
blob See Blob_stream_mq_sender counterpart.
err_code See Blob_stream_mq_sender counterpart.
Definition at line 311 of file blob_stream_mq_snd_impl.hpp.
send_blob_max_size()
template<typename Persistent_mq_handle > size_t ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::send_blob_max_size
See Blob_stream_mq_sender counterpart, but assuming PEER state.
Returns
See Blob_stream_mq_sender counterpart.
Definition at line 338 of file blob_stream_mq_snd_impl.hpp.
Friends And Related Function Documentation
operator<<()
template<typename Persistent_mq_handle > std::ostream & operator<< (std::ostream & os, const Blob_stream_mq_sender_impl< Persistent_mq_handle > & val) related
Prints string representation of the given Blob_stream_mq_sender to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 358 of file blob_stream_mq_snd_impl.hpp.
References ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::absolute_name(), and ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::nickname().
Member Data Documentation
m_sync_io
template<typename Persistent_mq_handle > sync_io::Blob_stream_mq_sender<Mq> ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_sync_io private
The core Blob_stream_mq_sender engine, implementing the sync_io pattern (see util::sync_io doc header).
See our class doc header for overview of how we use it (the aforementioned sync_io doc header talks about the sync_io pattern generally).
Thus, m_sync_io is the synchronous engine that we use to perform our work in our asynchronous boost.asio loop running in thread W (m_worker) while collaborating with user thread(s) a/k/a thread U. (Recall that the user may choose to set up their own event loop/thread(s) – boost.asio-based or otherwise – and use their own equivalent of an m_sync_io instead.)
Order subtlety versus m_worker
When constructing m_sync_io, we need the Task_engine from m_worker. On the other hand tasks operating in m_worker access m_sync_io. So in destructor it is important to m_worker.stop() explicitly, so that the latter is no longer a factor. Then when automatic destruction occurs in the opposite order of creation, the fact that m_sync_io is destroyed before m_worker has no bad effect.
Definition at line 192 of file blob_stream_mq_snd_impl.hpp.
Referenced by ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Blob_stream_mq_sender_impl().
m_sync_io_adapter
template<typename Persistent_mq_handle > std::optional<sync_io::Async_adapter_sender<decltype(m_sync_io)> > ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_sync_io_adapter private
This handles ~all logic in that state.
sync_io::Async_adapter_sender adapts any sync_io::Blob_sender and makes available ~all necessary async-I/O Blob_sender APIs. So we forward ~everything to this guy.
Creation
By its contract, this guy's ctor will handle what it needs to, as long as m_worker (to which it stores a pointer) has been .start()ed by that time, and m_sync_io (to which it stores... ditto) has been .replace_event_wait_handles()ed as required.
Destruction
By its contract, this guy's dtor will handle what it needs to, as long as m_worker (to which it stores a pointer) has been .stop()ed by that time, and any queued-up (ready to execute) handlers on it have been Task_enginer::poll()ed-through by that time as well.
Why optional?
The only reason is we have to invoke a certain method on m_sync_io before we can construct this guy.
Definition at line 212 of file blob_stream_mq_snd_impl.hpp.
Referenced by ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Blob_stream_mq_sender_impl().
m_worker
template<typename Persistent_mq_handle > flow::async::Single_thread_task_loop ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_worker private
Single-thread worker pool for all internal async work.
Referred to as thread W in comments.
Ordering: Must be either declared after mutex(es), or .stop()ed explicitly in dtor: Thread must be joined, before mutex possibly-locked-in-it destructs.
Definition at line 174 of file blob_stream_mq_snd_impl.hpp.
Referenced by ipc::transport::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Blob_stream_mq_sender_impl().
The documentation for this class was generated from the following files:
transport/detail/blob_stream_mq_snd_impl.hpp
transport/detail/transport_fwd.hpp