Flow-IPC: ipc::session::shm::classic::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > Class Template Reference
ipc::session::shm::classic::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > Class Template Reference
Core internally-used implementation of shm::classic::Server_session: it is to the latter what its public super-class Server_session_impl is to Server_session.
#include <server_session_impl.hpp>
Public Types
using Base = Session_impl< session::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, schema::ShmType::CLASSIC, transport::struc::shm::Builder_base::S_MAX_SERIALIZATION_SEGMENT_SZ > >
Short-hand for our non-virtual base.
Public Types inherited from ipc::session::shm::classic::Session_impl< session::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, schema::ShmType::CLASSIC, transport::struc::shm::Builder_base::S_MAX_SERIALIZATION_SEGMENT_SZ > >
using Base = session::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, schema::ShmType::CLASSIC, transport::struc::shm::Builder_base::S_MAX_SERIALIZATION_SEGMENT_SZ >
Short-hand for base class.
using Session_base_obj = typename Base::Session_base_obj
Short-hand for Session_base super-class.
using Arena = ipc::shm::classic::Pool_arena
See shm::classic::Session_mv counterpart for public description.
using Structured_msg_builder_config = typename transport::struc::shm::classic::Builder::Config
See shm::classic::Session_mv counterpart for public description.
using Structured_msg_reader_config = typename transport::struc::shm::classic::Reader::Config
See shm::classic::Session_mv counterpart for public description.
using Structured_channel = transport::struc::shm::classic::Channel< typename Base::Channel_obj, Message_body >
See shm::classic::Session_mv counterpart for public description.
using Blob = Arena::Blob
Alias for a light-weight blob used in borrow_object() and lend_object().
Public Types inherited from ipc::session::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, schema::ShmType::CLASSIC, transport::struc::shm::Builder_base::S_MAX_SERIALIZATION_SEGMENT_SZ >
using Base = Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
Short-hand for base type.
using Session_base_obj = Base
Short-hand for Session_base super-class.
using Channel_obj = typename Base::Channel_obj
See Server_session_mv counterpart.
using Channels = typename Base::Channels
See Session_mv counterpart.
using Mdt_payload_obj = typename Base::Mdt_payload_obj
See Server_session_mv counterpart.
using Mdt_reader_ptr = typename Base::Mdt_reader_ptr
See Server_session_mv counterpart.
using Mdt_builder = typename Base::Mdt_builder
See Server_session_mv counterpart.
using Mdt_builder_ptr = typename Base::Mdt_builder_ptr
See Server_session_mv counterpart.
using Structured_msg_builder_config = typename Base::Structured_msg_builder_config
See Session_mv counterpart.
using Structured_msg_reader_config = typename Base::Structured_msg_reader_config
See Session_mv counterpart.
Public Types inherited from ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
using Persistent_mq_handle_from_cfg = std::conditional_t<!S_MQS_ENABLED, transport::Null_peer, std::conditional_t< S_MQ_TYPE_OR_NONE==schema::MqType::POSIX, transport::Posix_mq_handle, transport::Bipc_mq_handle > >
Relevant only if S_MQS_ENABLED, this is the Persistent_mq_handle-concept impl type specified by the user via S_MQ_TYPE_OR_NONE.
using Channel_obj = std::conditional_t< S_MQS_ENABLED, std::conditional_t< S_TRANSMIT_NATIVE_HANDLES, transport::Mqs_socket_stream_channel< true, Persistent_mq_handle_from_cfg >, transport::Mqs_channel< true, Persistent_mq_handle_from_cfg > >, std::conditional_t< S_TRANSMIT_NATIVE_HANDLES, transport::Socket_stream_channel< true >, transport::Socket_stream_channel_of_blobs< true > > >
See Session_mv (or Session concept).
using Channels = std::vector< Channel_obj >
See Session_mv. Note: If changed from vector please update those doc headers too.
using Mdt_payload_obj = Mdt_payload
See Session_mv (or Session concept).
using Mdt_reader_ptr = boost::shared_ptr< typename transport::struc::schema::Metadata< Mdt_payload_obj >::Reader >
See Session_mv (or Session concept).
using Mdt_builder = typename transport::struc::schema::Metadata< Mdt_payload_obj >::Builder
See Session_mv (or Session concept).
using Mdt_builder_ptr = boost::shared_ptr< Mdt_builder >
See Session_mv (or Session concept).
using Structured_msg_builder_config = transport::struc::Heap_fixed_builder::Config
See Session_mv (or Session concept).
using Structured_msg_reader_config = transport::struc::Heap_reader::Config
See Session_mv (or Session concept).
Public Member Functions
~Server_session_impl ()
See Session concept counterpart; but read on for notes on per-session SHM-pool cleanup.
template<typename Session_server_impl_t , typename Task_err , typename Cli_app_lookup_func , typename Cli_namespace_func , typename Pre_rsp_setup_func , typename N_init_channels_by_srv_req_func , typename Mdt_load_func >
void async_accept_log_in (Session_server_impl_t *srv, typename Base::Base::Channels *init_channels_by_srv_req, typename Base::Base::Mdt_reader_ptr *mdt_from_cli_or_null, typename Base::Base::Channels *init_channels_by_cli_req, Cli_app_lookup_func &&cli_app_lookup_func, Cli_namespace_func &&cli_namespace_func, Pre_rsp_setup_func &&pre_rsp_setup_func, N_init_channels_by_srv_req_func &&n_init_channels_by_srv_req_func, Mdt_load_func &&mdt_load_func, Task_err &&on_done_func)
For use by internal user Session_server: See Server_session_mv counterpart.
Public Member Functions inherited from ipc::session::shm::classic::Session_impl< session::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, schema::ShmType::CLASSIC, transport::struc::shm::Builder_base::S_MAX_SERIALIZATION_SEGMENT_SZ > >
Arena * session_shm ()
See shm::classic::Session_mv counterpart.
Arena * app_shm ()
See shm::classic::Session_mv counterpart.
Blob lend_object (const typename Arena::template Handle< T > &handle)
See shm::classic::Session_mv counterpart.
Arena::template Handle< T > borrow_object (const Blob &serialization)
See shm::classic::Session_mv counterpart.
Structured_msg_builder_config session_shm_builder_config ()
See shm::classic::Session_mv counterpart.
Structured_msg_builder_config::Builder::Session session_shm_lender_session ()
See shm::classic::Session_mv counterpart.
Structured_msg_reader_config session_shm_reader_config ()
See shm::classic::Session_mv counterpart.
Structured_msg_builder_config app_shm_builder_config ()
See shm::classic::Session_mv counterpart.
Structured_msg_builder_config::Builder::Session app_shm_lender_session ()
See shm::classic::Session_mv counterpart.
Structured_msg_reader_config app_shm_reader_config ()
See shm::classic::Session_mv counterpart.
Public Member Functions inherited from ipc::session::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, schema::ShmType::CLASSIC, transport::struc::shm::Builder_base::S_MAX_SERIALIZATION_SEGMENT_SZ >
Server_session_impl (flow::log::Logger *logger_ptr, const Server_app &srv_app_ref, transport::sync_io::Native_socket_stream &&master_channel_sock_stm)
For use by internal user Session_server: See Server_session_mv counterpart.
~Server_session_impl ()
See Server_session_mv counterpart.
void async_accept_log_in (Session_server_impl_t *srv, Channels *init_channels_by_srv_req, Mdt_reader_ptr *mdt_from_cli_or_null, Channels *init_channels_by_cli_req, Cli_app_lookup_func &&cli_app_lookup_func, Cli_namespace_func &&cli_namespace_func, Pre_rsp_setup_func &&pre_rsp_setup_func, N_init_channels_by_srv_req_func &&n_init_channels_by_srv_req_func, Mdt_load_func &&mdt_load_func, Task_err &&on_done_func)
For use by internal user Session_server: See Server_session_mv counterpart.
const Client_app * client_app () const
See Server_session_mv counterpart.
bool init_handlers (Task_err &&on_err_func_arg, On_passive_open_channel_handler &&on_passive_open_channel_func_arg)
See Server_session_mv counterpart.
bool init_handlers (Task_err &&on_err_func_arg)
See Server_session_mv counterpart.
Mdt_builder_ptr mdt_builder ()
See Server_session_mv counterpart.
bool open_channel (Channel_obj *target_channel, const Mdt_builder_ptr &mdt, Error_code *err_code=0)
See Server_session_mv counterpart.
bool open_channel (Channel_obj *target_channel, Error_code *err_code=0)
See Server_session_mv counterpart.
const Session_token & session_token () const
See Server_session_mv counterpart.
const Base & base () const
See Server_session_mv counterpart.
Public Member Functions inherited from ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
const Shared_name & srv_namespace () const
See Server_session_impl, Client_session_impl.
const Shared_name & cli_namespace () const
See Server_session_impl, Client_session_impl.
const Client_app * cli_app_ptr () const
See Server_session_impl, Client_session_impl.
Shared_name cur_ns_store_mutex_absolute_name () const
Computes the name of the interprocess named-mutex used to control reading/writing to the file storing (written by server, read by client) the value for srv_namespace().
fs::path cur_ns_store_absolute_path () const
Computes the absolute path to file storing (written by server, read by client) the value for srv_namespace().
Shared_name session_master_socket_stream_acceptor_absolute_name () const
Computes the absolute name at which the server shall set up a transport::Native_socket_stream_acceptor to which client shall transport::Native_socket_stream::async_connect() in order to establish a PEER-state session.
Related Functions
(Note that these are not member functions.)
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload >
std::ostream & operator<< (std::ostream &os, const Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > &val)
Prints string representation of the given Server_session_impl to the given ostream.
Related Functions inherited from ipc::session::shm::classic::Session_impl< session::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, schema::ShmType::CLASSIC, transport::struc::shm::Builder_base::S_MAX_SERIALIZATION_SEGMENT_SZ > >
std::ostream & operator<< (std::ostream &os, const Session_impl< session::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, schema::ShmType::CLASSIC, transport::struc::shm::Builder_base::S_MAX_SERIALIZATION_SEGMENT_SZ > > &val)
Prints string representation of the given Session_impl to the given ostream.
Related Functions inherited from ipc::session::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, schema::ShmType::CLASSIC, transport::struc::shm::Builder_base::S_MAX_SERIALIZATION_SEGMENT_SZ >
std::ostream & operator<< (std::ostream &os, const Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, S_SHM_TYPE_OR_NONE, S_SHM_MAX_HNDL_SZ > &val)
Prints string representation of the given Server_session_impl to the given ostream.
Additional Inherited Members
Static Public Member Functions inherited from ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
static Structured_msg_builder_config heap_fixed_builder_config (flow::log::Logger *logger_ptr)
See Session_mv::heap_fixed_builder_config() (1-arg).
static Structured_msg_reader_config heap_reader_config (flow::log::Logger *logger_ptr)
See Session_mv::heap_reader_config() (1-arg).
Public Attributes inherited from ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
const Server_app & m_srv_app_ref
Reference to Server_app (referring to local process in Server_session, opposing process in Client_session).
Static Public Attributes inherited from ipc::session::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, schema::ShmType::CLASSIC, transport::struc::shm::Builder_base::S_MAX_SERIALIZATION_SEGMENT_SZ >
static constexpr schema::ShmType S_SHM_TYPE
See Session_mv counterpart.
static constexpr bool S_SHM_ENABLED
See Session_mv counterpart.
static constexpr bool S_MQS_ENABLED
See Server_session_mv counterpart.
static constexpr bool S_SOCKET_STREAM_ENABLED
See Server_session_mv counterpart.
Static Public Attributes inherited from ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
static constexpr bool S_MQS_ENABLED = S_MQ_TYPE_OR_NONE != schema::MqType::NONE
See Session_mv.
static constexpr bool S_SOCKET_STREAM_ENABLED = (!S_MQS_ENABLED) || S_TRANSMIT_NATIVE_HANDLES
See Session_mv.
Protected Types inherited from ipc::session::shm::classic::Session_impl< session::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, schema::ShmType::CLASSIC, transport::struc::shm::Builder_base::S_MAX_SERIALIZATION_SEGMENT_SZ > >
using Arena_ptr = boost::movelib::unique_ptr< Arena >
Short-hand for, basically, Arena that may not have been opened yet (and is therefore null).
Protected Types inherited from ipc::session::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, schema::ShmType::CLASSIC, transport::struc::shm::Builder_base::S_MAX_SERIALIZATION_SEGMENT_SZ >
using Master_structured_channel = typename Base::Master_structured_channel
See Session_base.
Protected Types inherited from ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
using Master_structured_channel = transport::struc::Channel_via_heap< transport::Socket_stream_channel< true >, schema::detail::SessionMasterChannelMessageBody< Mdt_payload_obj > >
The (internally used) session master channel is a transport::struc::Channel of this concrete type.
using Master_structured_channel_ptr = boost::shared_ptr< Master_structured_channel >
Handle to Master_structured_channel.
using Master_structured_channel_observer = boost::weak_ptr< Master_structured_channel >
Observer of Master_structured_channel_ptr. See its doc header.
using On_passive_open_channel_func = Function< void(Channel_obj &&new_channel, Mdt_reader_ptr &&new_channel_mdt)>
Concrete function type for the on-passive-open handler (if any), used for storage.
Protected Member Functions inherited from ipc::session::shm::classic::Session_impl< session::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, schema::ShmType::CLASSIC, transport::struc::shm::Builder_base::S_MAX_SERIALIZATION_SEGMENT_SZ > >
void init_shm_arenas (Arena_ptr &&session_shm_not_null, Arena *app_shm_not_null)
To be invoked at most once, sets the values returned by session_shm() and app_shm() to non-null values replacing null values.
void reset_shm_arenas ()
Undoes init_shm_arenas().
Protected Member Functions inherited from ipc::session::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, schema::ShmType::CLASSIC, transport::struc::shm::Builder_base::S_MAX_SERIALIZATION_SEGMENT_SZ >
void sub_class_set_deinit_func (Task &&task)
Utility for sub-classes: ensures that task() is invoked near the end of *this dtor's execution, from thread U, after thread W is joined, and any async_accept_log_in() on-done handler has fired with operation-aborted code.
flow::async::Single_thread_task_loop * async_worker ()
Utility for sub-classes: provides ability to schedule or post tasks onto thread W.
Master_structured_channel * master_channel ()
Utility for sub-classes: provides ability to do work on the session master channel after our async_accept_log_in() succeeds, but before the sub-classed wrapper of its on-done handler succeeds.
const Master_structured_channel & master_channel_const () const
Analogous to Client_session_impl::master_channel_const().
void dtor_async_worker_stop ()
Analogous to Client_session_impl::dtor_async_worker_stop(). See that doc header.
Protected Member Functions inherited from ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
Session_base (const Client_app &cli_app_ref, const Server_app &srv_app_ref, flow::async::Task_asio_err &&on_err_func, On_passive_open_channel_func &&on_passive_open_channel_func_or_empty_arg)
Constructs: Client_session form (the user is the one constructing the object, though in NULL state).
Session_base (const Server_app &srv_app_ref)
Constructs: Server_session form (Session_server is the one constructing the object, though in NULL state, before log-in has completed, but after the socket-stream connection has been established).
void set_srv_namespace (Shared_name &&srv_namespace_new)
Sets srv_namespace() (do not call if already set).
void set_cli_namespace (Shared_name &&cli_namespace_new)
Sets cli_namespace() (do not call if already set).
void set_cli_app_ptr (const Client_app *cli_app_ptr_new)
Sets cli_app_ptr() (do not call if already set).
void set_on_passive_open_channel_func (On_passive_open_channel_func &&on_passive_open_channel_func)
Sets on_passive_open_channel_func_or_empty() (do not call if already set; do not call if user intends for passive-opens to be disabled on this side).
void set_on_err_func (flow::async::Task_asio_err &&on_err_func_arg)
Sets on_err_func() (do not call if already set).
bool on_err_func_set () const
Returns true if and only if set_on_err_func() has been called, or .
const On_passive_open_channel_func & on_passive_open_channel_func_or_empty () const
The on-passive-open handler (may be empty even in final state, meaning user wants passive-opens disabled on this side).
void hose (const Error_code &err_code)
Marks this session as hosed for (truthy) reason err_code; and synchronously invokes on-error handler; only invoke if not already hosed().
bool hosed () const
Returns true if and only if hose() has been called.
Static Protected Attributes inherited from ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
static constexpr util::Fine_duration S_OPEN_CHANNEL_TIMEOUT = boost::chrono::seconds(60)
Internal timeout for open_channel().
static constexpr size_t S_MQS_MAX_MSG_SZ = 8 * 1024
The max sendable MQ message size as decided by Server_session_impl::make_channel_mqs() (and imposed on both sides, both directions), if S_MQS_ENABLED and Server_session_impl::S_SHM_ENABLED is false, when a channel is opened (regardless of which side did the active-open or requested pre-opening at session start).
Detailed Description
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload>
class ipc::session::shm::classic::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
Core internally-used implementation of shm::classic::Server_session: it is to the latter what its public super-class Server_session_impl is to Server_session.
See also
shm::classic::Server_session doc header which covers both its public behavior/API and a detailed sketch of the entire implementation.
Impl notes
The use of app_shm() and session_shm(), and various public APIs around them, is totally symmetrical with shm::classic::Client_session_impl; so that all is in super-class Session_impl. We do what's asymmetrical: assigning session_shm() and app_shm() values; and provide the server-specific APIs (notably async_accept_log_in()).
To implement app_shm() assignment we share a member map (from Client_app to Arena) in the "parent" (emitting) shm::classic::Session_server – after all it did have to create such a handle, in create-only mode, possibly even during pre_rsp_setup_func() (if the opposing Client_app is encountered the first time by that server). So we just access it through shm::classic::Session_server::app_shm(), passing-in the relevant Client_app; and save that pointer to be returned by app_shm().
(Why jump through such hoops? Couldn't we simply OPEN_OR_CREATE it ourselves; after all the OS would then essentially implement the map for us in the kernel, and we needn't all the boiler-plate? Answer: That's fantastic and superior; except the shm::classic::Pool_arena thus created could not live past *this; which would break the contract of shm::classic::Session::app_shm() as listed in its doc header.)
session_shm(), however, is simple. We just CREATE_ONLY it, as its lifetime by definition equals the session's (*this).
Template Parameters
S_MQ_TYPE_OR_NONE See shm::classic::Server_session counterpart.
S_TRANSMIT_NATIVE_HANDLES See shm::classic::Server_session counterpart.
Mdt_payload See shm::classic::Server_session counterpart.
Definition at line 66 of file server_session_impl.hpp.
Member Typedef Documentation
Base
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::classic::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Base = Session_impl <session::Server_session_impl<S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, schema::ShmType::CLASSIC, transport::struc::shm::Builder_base::S_MAX_SERIALIZATION_SEGMENT_SZ> >
Short-hand for our non-virtual base.
Definition at line 76 of file server_session_impl.hpp.
Constructor & Destructor Documentation
~Server_session_impl()
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > ipc::session::shm::classic::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::~Server_session_impl () default
See Session concept counterpart; but read on for notes on per-session SHM-pool cleanup.
In particular this dtor shall perform (if *this is opened OK) shm::classic::Pool_arena::remove_persistent() on the pool returned by Session_impl::session_shm() (the per-session pool). Reminder: like all kernel-persistent remove_persistent() methods this will not necessarily free the RAM held on behalf of the pool; any currently opened Pool_arenas – presumably one still (possibly) held by the counterpart shm::classic::Client_session_impl – will continue to function fine.
Rationale for aforementioned remove_persistent() op
Why do it? Answer: Naturally this should be freed sometime; otherwise the RAM will leak, even though the session pertaining to the per-session pool is gone.
Why not do it earlier? Answer: It would be nice to do it super-early... like, say, just after creating the pool during the async portion of async_accept_log_in(). The only reason not to do it is if the client handle (Pool_arena) to the pool has not yet had a chance to get opened by the name deleted via remove_persistent(). The opening occurs in the counterpart shm::classic::Client_session_impl during the log-in procedure, initiated on this side by async_accept_log_in(). However, as of this writing, the async portion of async_accept_log_in() (at least when there are no init-channels) completes just after creating the SHM-pool – upon sending the log-in response message; it does not wait for any ack from the client. While in practice the client side will indeed open the pool quite soon after we send the log-in response, we don't know exactly when that is. Hence we postpone it until this dtor, at which point the session is definitely done-for. (We could do it earlier, perhaps by adding the ack from client, but this way is solid if less zealous.)
Why not do it later? Answer: Session is done-for, if we are being invoked; the counterpart Client_session could not possibly hope to open the pool now, even if it somehow wanted to do so. So why wait?
What if this dtor never runs?
In any program that exits without aborting abruptly, it will run. Furthermore the proper behavior (see Session::~Session() doc header) is to either invoke the Session dtor proactively (graceful exit triggered locally) or in response to an error (triggered by client counterpart ending session and our detecting this). If the user follows this recommended behavior, then this dtor will run just as soon as it should. If not, then it will at least run when the program is exiting gracefully.
It however may not run due to abrupt termination (a crash). In that case the session_shm() pool will indeed leak, in that this dtor won't execute, so the remove_persistent() will not occur in that fashion. The shm::classic::Session_server has a contingency for this, which we don't describe here, wherein it has cleanup points at which it cleans up anything thus leaked during previous invocations of the same Server_app.
What about the per-app pool?
The above talks only of the Session_impl::session_shm() pool; what about Session_impl::app_shm()? Shouldn't we clean it up here? Answer: No. By definition that pool is cross-session; more sessions may be opened within for the same Server_app and will expect the pool to persist. Hence any graceful cleanup is under the purview of Session_server dtor (in loosely similar fashion to the present dtor).
Member Function Documentation
async_accept_log_in()
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > template<typename Session_server_impl_t , typename Task_err , typename Cli_app_lookup_func , typename Cli_namespace_func , typename Pre_rsp_setup_func , typename N_init_channels_by_srv_req_func , typename Mdt_load_func > void ipc::session::shm::classic::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::async_accept_log_in (Session_server_impl_t * srv, typename Base::Base::Channels * init_channels_by_srv_req, typename Base::Base::Mdt_reader_ptr * mdt_from_cli_or_null, typename Base::Base::Channels * init_channels_by_cli_req, Cli_app_lookup_func && cli_app_lookup_func, Cli_namespace_func && cli_namespace_func, Pre_rsp_setup_func && pre_rsp_setup_func, N_init_channels_by_srv_req_func && n_init_channels_by_srv_req_func, Mdt_load_func && mdt_load_func, Task_err && on_done_func)
For use by internal user Session_server: See Server_session_mv counterpart.
While the formal contract here is unchanged from vanilla Server_session_impl, internally: this one, before on_done_func() can be invoked successfully – and moreover before the opposing shm::classic::Client_session is informed the session may proceed – also creates a per-session-scope SHM arena which is accessible in PEER state via session_shm(). The opposing session peer hence also makes it available via shm::classic::Client_session::session_shm().
Parameters
srv See Server_session_mv counterpart.
init_channels_by_srv_req See Server_session_mv counterpart.
mdt_from_cli_or_null See Server_session_mv counterpart.
init_channels_by_cli_req See Server_session_mv counterpart.
cli_app_lookup_func See Server_session_mv counterpart.
cli_namespace_func See Server_session_mv counterpart.
pre_rsp_setup_func See Server_session_mv counterpart.
n_init_channels_by_srv_req_func See Server_session_mv counterpart.
mdt_load_func See Server_session_mv counterpart.
on_done_func See Server_session_mv counterpart.
Definition at line 205 of file server_session_impl.hpp.
References ipc::session::build_conventional_shared_name(), ipc::util::CREATE_ONLY, ipc::util::Shared_name::ct(), ipc::util::Shared_name::S_1ST_OR_ONLY, ipc::session::error::S_OBJECT_SHUTDOWN_ABORTED_COMPLETION_HANDLER, ipc::util::Shared_name::S_RESOURCE_TYPE_ID_SHM, ipc::util::shared_resource_permissions(), and ipc::session::shm::classic::SHM_SUBTYPE_PREFIX.
Friends And Related Function Documentation
operator<<()
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > std::ostream & operator<< (std::ostream & os, const Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > & val) related
Prints string representation of the given Server_session_impl to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 368 of file server_session_impl.hpp.
The documentation for this class was generated from the following files:
session/detail/shm/classic/classic_fwd.hpp
session/detail/shm/classic/server_session_impl.hpp