Flow-IPC: ipc::transport::sync_io::Native_socket_stream_acceptor Class Reference
ipc::transport::sync_io::Native_socket_stream_acceptor Class Reference
sync_io-pattern counterpart to async-I/O-pattern transport::Native_socket_stream_acceptor.
#include <native_socket_stream_acceptor.hpp>
Public Types
using Peer = transport::Native_socket_stream::Sync_io_obj
Short-hand for type of target peer-socket objects targeted by async_accept().
using Sync_io_obj = Null_peer
You may disregard.
using Async_io_obj = transport::Native_socket_stream_acceptor
Useful for generic programming, the async-I/O-pattern counterpart to *this type.
Public Member Functions
Native_socket_stream_acceptor (flow::log::Logger *logger_ptr, const Shared_name &absolute_name, Error_code *err_code=0)
All notes from Async_io_obj API counterpart API apply.
~Native_socket_stream_acceptor ()
All notes from Async_io_obj API counterpart API apply, except that no completion handler(s) are fired, even if an async-accept is currently outstanding.
const Shared_name & absolute_name () const
All notes from Async_io_obj API counterpart API apply.
template<typename Event_wait_func_t >
bool start_accept_ops (Event_wait_func_t &&ev_wait_func)
Sets up the sync_io-pattern interaction between *this and the user's event loop; required before async_accept() will work (as opposed to no-op/return false).
template<typename Create_ev_wait_hndl_func >
bool replace_event_wait_handles (const Create_ev_wait_hndl_func &create_ev_wait_hndl_func)
Analogous to transport::sync_io::Native_handle_sender::replace_event_wait_handles().
template<typename Task_err >
bool async_accept (Peer *target_peer, Task_err &&on_done_func)
Starts background attempt at a peer connection being established, contingent on the user reporting (via sync_io pattern) the necessary native handle event(s); completion handler on_done_func() shall execute synchronously during such a future report.
Static Public Attributes
static const Shared_name S_RESOURCE_TYPE_ID = Shared_name::ct("sockStmAcc")
Shared_name relative-folder fragment (no separators) identifying this resource type.
Private Types
using On_peer_accepted_func = flow::async::Task_asio_err
Short-hand for callback called on new peer-to-peer connection; or on unrecoverable error.
Private Attributes
flow::util::Task_engine m_nb_task_engine
The Task_engine for m_ready_*.
flow::util::Task_engine m_ev_hndl_task_engine_unused
The Task_engine for m_ev_wait_hndl, unless it is replaced via replace_event_wait_handles().
util::Pipe_reader m_ready_reader
Read-end of IPC-pipe used by *this user do detect that an acceptability-wait has completed.
util::Pipe_writer m_ready_writer
Write-end of IPC-pipe together with m_ready_reader.
util::sync_io::Asio_waitable_native_handle m_ev_wait_hndl
Descriptor waitable by outside event loop async-waits – storing the same Native_handle as (and thus being used to wait on events from) m_ready_reader.
util::sync_io::Event_wait_func m_ev_wait_func
Function (set forever in start_accept_ops()) through which we invoke the outside event loop's async-wait facility for descriptors/events relevant to our ops.
On_peer_accepted_func m_on_done_func_or_empty
on_done_func from async_accept() if one is pending; otherwise .empty().
Error_code m_target_err_code
Result of last m_async_io.async_accept().
Async_io_obj m_async_io
This guy does all the work. We merely report async_accept() completion via m_ready_reader and m_ready_writer.
Related Functions
(Note that these are not member functions.)
std::ostream & operator<< (std::ostream &os, const Native_socket_stream_acceptor &val)
Prints string representation of the given Native_socket_stream_acceptor to the given ostream.
Detailed Description
sync_io-pattern counterpart to async-I/O-pattern transport::Native_socket_stream_acceptor.
See also
util::sync_io doc header – describes the general sync_io pattern we are following.
transport::Native_socket_stream_acceptor – generally all notes, other than the mechanism of how async_accept() reports readiness, in that doc header apply here.
As is generally the case when choosing sync_io::X versus X, we recommend using X due to it being easier. In this particular case (see below) there is no perf benefit to using sync_io::X, either, so the only reason to use sync_io::X in this case would be because you've got an old-school reactor event loop with a poll() or epoll_wait(), in which case the sync_io API may be easier to integrate.
Internal implementation
Normally this would not be in the public docs for this public-use class, but indulge us.
In perf-critical situations, such as the various transport::Blob_sender / transport::Blob_receiver / etc. impls, typically sync_io::X contains the core implementation, then X adapts a sync_io::X core to provide background-thread-driven work and signaling of completion. We do not consider the present X = Native_socket_stream_acceptor to be perf-critical; as such as of this writing transport::Native_socket_stream_acceptor has the logic, while sync_io::Native_socket_stream_acceptor adapts it into the sync_io pattern. Internally this is accomplished using an unnamed IPC-pipe, where an internal background thread W tickles said IPC-pipe which is waited-on by the user of sync_io::Native_socket_stream_acceptor.
Definition at line 58 of file native_socket_stream_acceptor.hpp.
Member Typedef Documentation
Async_io_obj
using ipc::transport::sync_io::Native_socket_stream_acceptor::Async_io_obj = transport::Native_socket_stream_acceptor
Useful for generic programming, the async-I/O-pattern counterpart to *this type.
Definition at line 71 of file native_socket_stream_acceptor.hpp.
On_peer_accepted_func
using ipc::transport::sync_io::Native_socket_stream_acceptor::On_peer_accepted_func = flow::async::Task_asio_err private
Short-hand for callback called on new peer-to-peer connection; or on unrecoverable error.
Definition at line 180 of file native_socket_stream_acceptor.hpp.
Peer
using ipc::transport::sync_io::Native_socket_stream_acceptor::Peer = transport::Native_socket_stream::Sync_io_obj
Short-hand for type of target peer-socket objects targeted by async_accept().
Definition at line 66 of file native_socket_stream_acceptor.hpp.
Sync_io_obj
using ipc::transport::sync_io::Native_socket_stream_acceptor::Sync_io_obj = Null_peer
You may disregard.
Definition at line 69 of file native_socket_stream_acceptor.hpp.
Constructor & Destructor Documentation
Native_socket_stream_acceptor()
ipc::transport::sync_io::Native_socket_stream_acceptor::Native_socket_stream_acceptor (flow::log::Logger * logger_ptr, const Shared_name & absolute_name, Error_code * err_code = 0) explicit
All notes from Async_io_obj API counterpart API apply.
However, additionally, per sync_io pattern, you'll need to invoke start_accept_ops() (possibly preceded by replace_event_wait_handles()) before further real work.
If err_code is not null, and this emits truthy *err_code, then any use of *this other than destruction => undefined behavior.
Parameters
logger_ptr See Async_io_obj API.
absolute_name See Async_io_obj API.
err_code See Async_io_obj API.
Definition at line 31 of file native_socket_stream_acceptor.cpp.
References ipc::util::sync_io::Asio_waitable_native_handle::assign(), m_ev_wait_hndl, m_ready_reader, and m_ready_writer.
Member Function Documentation
absolute_name()
const Shared_name & ipc::transport::sync_io::Native_socket_stream_acceptor::absolute_name () const
All notes from Async_io_obj API counterpart API apply.
Returns
See above.
Definition at line 76 of file native_socket_stream_acceptor.cpp.
References ipc::transport::Native_socket_stream_acceptor::absolute_name(), and m_async_io.
Referenced by operator<<().
async_accept()
template<typename Task_err > bool ipc::transport::sync_io::Native_socket_stream_acceptor::async_accept (Peer * target_peer, Task_err && on_done_func)
Starts background attempt at a peer connection being established, contingent on the user reporting (via sync_io pattern) the necessary native handle event(s); completion handler on_done_func() shall execute synchronously during such a future report.
Or perhaps in plainer English:
Call this.
It will synchronously invoke util::sync_io::Event_wait_func from start_accept_ops(), causing you to synchronously begin an async-wait for some status of some native handle (FD).
Once that async-wait completes, call (*on_active_ev_func)() to report that fact to *this.
It will synchronously invoke on_done_func() saved from the present call, indicating via the Error_code arg success or failure. The semantics of this are equivalent to those of Async_io_obj async_accept().
Note
There is no mode of async_accept() wherein *target_peer is synchronously (immediately) available. Completion shall always be reported via on_done_func() after a mandatory async-wait. This is in contrast to perf-critical operations such as, say, Native_socket_stream::async_receive_blob(). (Native_socket_stream::async_connect() also behaves in that dual manner, for consistency with the other APIs of that type, even though async-connect is not usually thought of as perf-critical.)
Template Parameters
Task_err See Async_io_obj API.
Parameters
target_peer See Async_io_obj API.
on_done_func See Async_io_obj API.
Returns
true if op started; false if one is already in progress, and therefore this one is ignored (no-op).
Definition at line 249 of file native_socket_stream_acceptor.hpp.
References ipc::transport::Native_socket_stream_acceptor::async_accept(), m_async_io, m_ev_wait_func, m_ev_wait_hndl, m_on_done_func_or_empty, m_ready_reader, m_ready_writer, m_target_err_code, ipc::util::pipe_consume(), ipc::util::pipe_produce(), and ipc::transport::error::S_OBJECT_SHUTDOWN_ABORTED_COMPLETION_HANDLER.
replace_event_wait_handles()
template<typename Create_ev_wait_hndl_func > bool ipc::transport::sync_io::Native_socket_stream_acceptor::replace_event_wait_handles (const Create_ev_wait_hndl_func & create_ev_wait_hndl_func)
Analogous to transport::sync_io::Native_handle_sender::replace_event_wait_handles().
Template Parameters
Create_ev_wait_hndl_func See above.
Parameters
create_ev_wait_hndl_func See above.
Returns
See above.
Definition at line 312 of file native_socket_stream_acceptor.hpp.
References ipc::util::sync_io::Asio_waitable_native_handle::assign(), m_ev_wait_func, and m_ev_wait_hndl.
start_accept_ops()
template<typename Event_wait_func_t > bool ipc::transport::sync_io::Native_socket_stream_acceptor::start_accept_ops (Event_wait_func_t && ev_wait_func)
Sets up the sync_io-pattern interaction between *this and the user's event loop; required before async_accept() will work (as opposed to no-op/return false).
ev_wait_func() – with signature matching util::sync_io::Event_wait_func – is a key function memorized by *this. It shall be invoked by *this operations when some op cannot complete synchronously and requires a certain event (readable/writable) to be active on a certain native-handle.
See also
util::sync_io::Event_wait_func doc header for useful and complete instructions on how to write an ev_wait_func() properly. Doing so correctly is the crux of using the sync_io pattern.
This is a standard sync_io-pattern API per util::sync_io doc header.
Template Parameters
Event_wait_func_t Function type matching util::sync_io::Event_wait_func.
Parameters
ev_wait_func See above.
Returns
false if this has already been invoked; no-op logging aside. true otherwise.
Definition at line 296 of file native_socket_stream_acceptor.hpp.
References m_ev_wait_func.
Friends And Related Function Documentation
operator<<()
std::ostream & operator<< (std::ostream & os, const Native_socket_stream_acceptor & val) related
Prints string representation of the given Native_socket_stream_acceptor to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 81 of file native_socket_stream_acceptor.cpp.
References absolute_name().
Member Data Documentation
m_async_io
Async_io_obj ipc::transport::sync_io::Native_socket_stream_acceptor::m_async_io private
This guy does all the work. We merely report async_accept() completion via m_ready_reader and m_ready_writer.
Definition at line 241 of file native_socket_stream_acceptor.hpp.
Referenced by absolute_name(), and async_accept().
m_ev_hndl_task_engine_unused
flow::util::Task_engine ipc::transport::sync_io::Native_socket_stream_acceptor::m_ev_hndl_task_engine_unused private
The Task_engine for m_ev_wait_hndl, unless it is replaced via replace_event_wait_handles().
This is to fulfill the sync_io pattern.
Definition at line 200 of file native_socket_stream_acceptor.hpp.
m_ev_wait_func
util::sync_io::Event_wait_func ipc::transport::sync_io::Native_socket_stream_acceptor::m_ev_wait_func private
Function (set forever in start_accept_ops()) through which we invoke the outside event loop's async-wait facility for descriptors/events relevant to our ops.
See util::sync_io::Event_wait_func doc header for a refresher on this mechanic.
Definition at line 228 of file native_socket_stream_acceptor.hpp.
Referenced by async_accept(), replace_event_wait_handles(), and start_accept_ops().
m_ev_wait_hndl
util::sync_io::Asio_waitable_native_handle ipc::transport::sync_io::Native_socket_stream_acceptor::m_ev_wait_hndl private
Descriptor waitable by outside event loop async-waits – storing the same Native_handle as (and thus being used to wait on events from) m_ready_reader.
Definition at line 221 of file native_socket_stream_acceptor.hpp.
Referenced by async_accept(), Native_socket_stream_acceptor(), and replace_event_wait_handles().
m_nb_task_engine
flow::util::Task_engine ipc::transport::sync_io::Native_socket_stream_acceptor::m_nb_task_engine private
The Task_engine for m_ready_*.
It is necessary to construct those pipe-end objects, but we never use that guy's ->async_*() APIs – only non-blocking operations, essentially leveraging boost.asio's portable transmission APIs but not its actual, um, async-I/O abilities in this case. Accordingly we never load any tasks onto m_nb_task_engine and certainly never .run() (or .poll() or ...) it.
In the sync_io pattern the user's outside event loop is responsible for awaiting readability/writability of a guy like m_ready_reader via our exporting of its .native_handle().
Definition at line 193 of file native_socket_stream_acceptor.hpp.
m_on_done_func_or_empty
On_peer_accepted_func ipc::transport::sync_io::Native_socket_stream_acceptor::m_on_done_func_or_empty private
on_done_func from async_accept() if one is pending; otherwise .empty().
We maybe could have kept it as a lambda capture only, but this way it can double as a guard against allowing 2+ async-accepts (which goes against the spirit of what sync_io-pattern objects provide).
Definition at line 235 of file native_socket_stream_acceptor.hpp.
Referenced by async_accept().
m_ready_reader
util::Pipe_reader ipc::transport::sync_io::Native_socket_stream_acceptor::m_ready_reader private
Read-end of IPC-pipe used by *this user do detect that an acceptability-wait has completed.
The signal byte is read out of m_ready_reader, making it empty again (the steady-state before the next time acceptability-wait begins, and a byte is written to it making it non-empty).
See also
m_ready_writer.
Definition at line 209 of file native_socket_stream_acceptor.hpp.
Referenced by async_accept(), and Native_socket_stream_acceptor().
m_ready_writer
util::Pipe_writer ipc::transport::sync_io::Native_socket_stream_acceptor::m_ready_writer private
Write-end of IPC-pipe together with m_ready_reader.
See also
m_ready_reader.
Definition at line 215 of file native_socket_stream_acceptor.hpp.
Referenced by async_accept(), and Native_socket_stream_acceptor().
m_target_err_code
Error_code ipc::transport::sync_io::Native_socket_stream_acceptor::m_target_err_code private
Result of last m_async_io.async_accept().
Definition at line 238 of file native_socket_stream_acceptor.hpp.
Referenced by async_accept().
S_RESOURCE_TYPE_ID
const Shared_name ipc::transport::sync_io::Native_socket_stream_acceptor::S_RESOURCE_TYPE_ID = Shared_name::ct("sockStmAcc") static
Shared_name relative-folder fragment (no separators) identifying this resource type.
Definition at line 76 of file native_socket_stream_acceptor.hpp.
The documentation for this class was generated from the following files:
transport/sync_io/native_socket_stream_acceptor.hpp
transport/sync_io/native_socket_stream_acceptor.cpp
transport/transport_fwd.hpp