Flow-IPC: ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Graceful_finisher Class Reference
ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Graceful_finisher Class Reference
Optional to use by subclasses, this operates a simple state machine that carries out a graceful-session-end handshake procedure.
#include <session_base.hpp>
Public Member Functions
Graceful_finisher (flow::log::Logger *logger_ptr, Session_base *this_session, flow::async::Single_thread_task_loop *async_worker, Master_structured_channel *master_channel)
You must invoke this ctor (instantiate us) if and only if synchronized dtor execution is indeed required; and *this_session has just reached PEER state.
void on_master_channel_hosed ()
Must be invoked if the *_session_impl detects that the master channel has emitted channel-hosing error.
void on_dtor_start ()
The reason Graceful_finisher exists, this method must be called at the start of *_session_impl dtor; and will block until it is appropriate to let that dtor proceed to shut down the *_session_impl.
Private Attributes
Session_base *const m_this_session
The containing Session_base. It shall exist until *this is gone.
flow::async::Single_thread_task_loop * m_async_worker
The containing Session thread W loop. It shall exist until *this is gone.
Master_structured_channel * m_master_channel
The containing Session master channel. It shall exist until *this is gone.
boost::promise< void > m_opposing_session_done
A promise whose fulfillment is a necessary and sufficient condition for on_dtor_start() returning (letting Session dtor complete).
Detailed Description
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload>
class ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Graceful_finisher
Optional to use by subclasses, this operates a simple state machine that carries out a graceful-session-end handshake procedure.
A particular Client_session_impl and symmetrically its opposing Server_session_impl shall instantiate a *this internally and invoke its methods on certain events, as described in their contracts.
Now we explain what we're solving (Rationale); then how we solve it (Design). The latter is much simpler, we think, to understand then the former. Hence apologies in advance for the length of "Rationale" section.
Rationale
Consider a particular Client_session_impl + Server_session_impl class/object pair, A and B. In this case – which is somewhat unusual (relative to most internal Session algorithms) but in a good, simplifying way – it does not matter which is A and which is B. So let's say A is us and B is the opposing guy.
Also, for now, assume these are just the vanilla ones: session::Client_session_impl and session::Server_session_impl; not SHM-enabled – no SHM arenas in play.
Consider what happens when A dtor is invoked, in PEER state. The session ends, and the session-end trigger is us. Without Graceful_finisher what happens is as follows. The Master_structured_channel in *this is closed; and then *this goes away altogether right away/synchronously. Soon B's Master_structured_channel throws the graceful-close error; B itself correctly interprets this as a session-end trigger; and B throws an error via the Session error handler. Now, the user is told by docs they informally should destroy the B (invoke its dtor) ASAP, but nothing is formally forcing them to; it can sit around. It will never accept channel passive-opens; open_channel() will no-op / return null; etc. It is useless, but it can stay around. Eventually B dtor will be invoked by user; it'll basically clean up data structures, and that's that.
There is no problem there: A dtor and B dtor can run at quite different times, or more precisely B dtor can run much later than A dtor which triggered session-end. Nothing bad happens.
Now we'll discuss this in specific terms around actual Client/Server_session_impl variants that do exist at this time. We could try to be formal and general, but it's easier to just be specific for exposition purposes.
Take, now, the shm::classic::Client_session_impl shm::classic::Server_session_impl variants. The above generally holds, but there are now SHM arenas in play. We can forget about the app-scope arenas right off the bat: That guy stays around as long as the Session_server does, and that guy is formally required to be around until all child Sessions have been destroyed. So only session-scope arenas – the ones inside A and B – are relevant. In fact, for SHM-classic there really is only one arena: A holds a handle to it (a.session_shm() points to it), and B does so symmetrically.
Now reconsider the scenario above: A dtor runs. (Insert vanilla *_session_impl text from above here.) Also, though, A dtor will remove the underlying SHM-pool by its name. (This is possibly a lie. This is technically so, only if A is a Server_session_impl; we've assigned the task to the server side as of this writing. But this technicality is irrelevant: unlinking the SHM-pool doesn't blow up the other side's access to the arena; it remains in RAM until that guy closes. So just bear with us here.) Then indeed B dtor can run sometime later. Is there a problem? For SHM-classic, which is what we're discussing, no: The arena – 1 shared SHM-pool in this case – stays alive, until B's handle gets closed by B dtor. What about allocations/deallocations? No problem there either: By contract, the A user must drop all cross-process shared_ptr handles to objects that it owns, before invoking A dtor; so A is fine, and the internal cross-process ref-counts for each A-held object get decremented by 1, due to the shared_ptr handles being nullified by the user by contract. (For context: The guided manual session_app_org page describes to the reader how to structure their program, so that this is guaranteed. In short, declare the object handle data members in their code after the Session data member, so they get deinitialized in the reverse order, in the user's hypothetical recommended App_session class.) Isn't there a problem in B, though? No: the B user shall drop its shared_ptr handles, before invoking B dtor; this will drop their internal cross-process ref-counts to 0; at which point shm::Pool_arena logic will deallocate those objects. Deallocation is entirely distributed between A and B; in this scenario B's handles just happen to live longer and therefore happen to be the ones triggering the deallocations – by the B process itself, synchronously. A is not "in charge" of deallocations of anything in any special way; it doesn't matter which process originally allocated a given object either. That's the beauty/simplicity of SHM-classic. (There are of course trade-offs in play; this is worse for segregation/safety... see Manual and such.)
Now we come to the point. Consider session::shm::arena_lend::jemalloc::Client_session_impl and Server_session_impl. There is a problem. Interestingly this time it really does not matter whether A is server or client-side. In SHM-jemalloc the session-scope arenas are not 1 but 2: A has an arena, from which process A can allocate, and in which process A shall deallocate. B has an arena, from which process B can allocate, and in which process B shall deallocate. If B borrows object X from A, and is later done with it – the shared_ptr local ref-count reached 0 – SHM-jemalloc-arranged shared_ptr deleter will send an internal message over a special channel to A. A will deallocate X once that has occurred, and any A-held shared_ptr group for X has also reached ref-count 0 (which may have happened before, or it may happen later). Exactly the same is true of A borrowing from B, conversely/symmetrically.
The problem is this: Suppose B holds a borrowed handle X (to an A-allocated object). Now A dtor runs; its .session_shm() arena – its constitutent SHM-pools! – is destroyed. That in itself shouldn't be a problem; again B presumably holds a SHM-pool handle, so it won't just disappear from RAM under it. I (ygoldfel) am somewhat fuzzy on what exactly happens (not being the direct author of SHM-jemalloc), but basically as I understand it, in destroying the arena, a bunch of jemalloc deinit steps execute; perhaps heap-marker data structures are modified all over the place... it's chaos. The bottom line is: A arena gets mangled, so the B-held borrowed handle X has a high chance of pointing, now, to garbage: Not unmapped garbage; not into a SHM-pool that's magically gone – it's still there – so there's not necessarily a SEGV as a result; just garbage in the ~sense of accessing free()d (not un-mmap()ped) memory.
(Update: I've spoken to the SHM-jemalloc author echan, and the above is basically right with a couple clarifications. It's not so much that the arena object being destroyed is the issue; in fact that in itself would be handled gracefully by SHM-jemalloc innards; they will keep the arena around, even if the outer object goes away (or more precisely as of this writing the arena-handle – a shared_ptr – does), while it knows things are pointing into it, even borrowed things in another process. Really it's the fact that we kill the channel it uses to communicate with the borrower process: the arena is told there's nothing out there pointing into it: locally the user has to have dropped all constructed-object handles; and the borrower process it no longer has a way of contacting it; so it assumes tgat guy's done/gone, as are all the borrowed handles in it. That clarification doesn't change the situation though: Whether it's the SHM-jemalloc-session, or the SHM-jemalloc-session-used-channel, or the SHM-jemalloc-arena going away that makes borrowed objects unusable – they are unusable, is the bottom line.)
All that is to say: A dtor runs; and user handle to object X in B instantly becomes unusable. For example, I (ygoldfel) have observed a simple thing: A SHM-jemalloc-backed transport::struc::Msg_in received from A, in B, was absolutely fine. Then it was running a long tight-loop verification of its contents – verifying hashes of millions of X-pointed objects in SHM, preventing B dtor from running. Meanwhile, A in a test program had nothing more to do and ran A dtor (closed session). Suddenly, the hash-verifier code in the tight loop was hitting hash mismatches, throwing capnp exceptions in trying to traverse the message, and so on.
What this means, ultimately, is straightforward: A dtor must not destroy its SHM-jemalloc arena (as accessible normally through .session_shm()), until not just A user has dropped all its object shared_ptr handles; but B user – that's in the other process, B – has as well! How can we enforce this, though? One approach is to just put it on the user: Tell them that they must design their protocol in such a way as to arrange some kind of handshake, as appropriate, beyond which each side knows for a fact that the session objects, and therefore arenas, are safe to destroy.
We don't want to do that for obvious reasons. What we already tell them should be sufficient: If you get a session-hosing error handler execution in your Session, then don't use that Session, and you should destroy it ASAP, for it is useless, and the other side's Session is not long for this life. If they listen to this, then A dtor will soon be followed by B dtor anyway. It might be delayed by some long tight-loop operation such as the test-program hash-verifying scenario above, but generally users avoid such things; and when they don't they can expect other things to get blocked, possibly in the opposing process. Subjectively, weird blocking – caused by the other side acting pathologically – is a lot more acceptable at session-start or session-end than something like that occuring mid-session.
So what's the exact proposal? It's this: If A dtor begins executing, it must first block until it knows B dtor has begun executing; but once it does know that, it knows that all B-held object handles have been dropped – which is what we want. (It would be possible for B user to indicate it some other way – another API call, short of destruction – but that seems unnecessarily complex/precious. If the session is finished, then there's no reason to keep the Session object around = the overall policy we've pursued so far, so why make exceptions for this?)
To be clear, this means certain behavior by B user can cause A dtor to block. We can explain this in the docs, of course, but perhaps much more effective is to make it clear in the logs: say the wait begins here and what it'll take for it to end; and say when it has ended and why.
Also to be clear, Graceful_finisher should be used only in *_session_impl pairs that actually have this problem; so of the 3 pairs we've discussed above – only SHM-jemalloc's ones. The others can completely forego all this.
Todo:
Consider how to avoid having SHM-jemalloc ipc::session mechanism require one side's Session dtor await (and possibly block) the start of the opposing side's Session dtor, before it can proceed. The reason it does this today is above this to-do in the code. The blocking is not too bad – if the user's applications are properly written, it will not occur, and the existing logging should make clear why it happens, if it happens; but it's still not ideal. There are a couple known mitigating approaches, and at least 1 ticket covering them is likely filed. (Either way the Graceful_finisher mechanism could then be removed probably.) To summarize them: 1, there can be a mechanism deep inside SHM-jemalloc code that gives (arbitrarily long, configurable) grace period for known borrowed objects whose session channels have closed before those objects were returned; this was echan's idea on this topic. Once the grace period is reached, it would act as-if they got returned then (so in the above scenario the arena could get jemalloc-deinitialized and all). If program needs to exit, it could either block until the end of the grace period or... who knows? 2, something similar could be done about the SHM-internal-use channel: do not close it but add it to some list of such channels; they would be finally closed upon detection of the other side's Session dtor being reached, in some background thread somewhere. (On 2nd thought this sounds a lot like Graceful_finisher – but for this particular internal-use channel only. The code here would only get more complex, thought maybe not too much more. However, it would resolve the observed Session-dtor-blocking user-visible issue, at least until the delayed-channel-death process had to exit entirely.) Beyond these basic ideas (which could even perhaps be combined) this requires some thinking; it is an interesting problem. In the meantime the dtor-cross-process-barrier-of-sorts existing solution is pretty decent.
Design / how to use
How to use: Subclass shall create a *this if and only if the feature is required; it shall call its methods and ctor on certain events, as prescribed in their doc headers.
Design: All this assumes PEER state. Now:
Again let's say we're A, and they're B – and just like we are. Our goal is to ensure A dtor, at its start, blocks until B dtor has started executing; and to give their side the information necessary to do the same. That's on_dtor_start(): the method that'll do the blocking; when it returns the dtor of subclass can proceed. So what's needed for on_dtor_start() to return? One, A dtor has to have started – but that's true by the contract of when the method is called; two, B dtor has to have started. How do we get informed of the latter? Answer: B sends a special message along the Master_structured_channel, from its own on_dtor_start(). Naturally, we do the same – in full-duplex fashion in a sense – so that they can use the same logic. So then the steps in on_dtor_start() are:
Send GracefulSessionEnd message to B, if possible (Master_structured_channel is up, and the send op doesn't return failure).
Perform m_opposing_session_done.get_future().wait(), where m_opposing_session_done is a promise<void> that shall be fulfilled on these events (and only if it hasn't already been fulfilled before):
The Master_structured_channel has received GracefulSessionEnd from B.
The Master_structured_channel has emitted a channel-hosing error.
Notes:
The mainstream case is receiving GracefulSessionEnd: In normal operation, with no acts of god, we will no longer destroy the session-master-channel, until returning from on_dtor_start().
This could happen after the .wait() starts – meaning A dtor indeed ran before B dtor (our side is the one triggering session-end).
It could just as easily happen before the .wait() starts – meaning the reverse. Then .wait() will return immediately.
Of course who knows what's going on – the Master_structured_channel could still go down without the GracefulSessionEnd. Is it really right to treat this the same, and let on_dtor_start() return? Answer: Yes. Firstly, there's hardly any other choice: the channel's dead; there's no other way of knowing what to wait for; and we can't just sit there cluelessly. But more to the point, this means it's a not-graceful scenario: Graceful_finisher can't hope to deal with it and can only proceed heuristically. This is not networking; so we should have a pretty good level of predictability at any rate.
Last but not least consider that by delaying the destruction of the Master_structured_channel until after the dtor has started (assuming no channel-hosing acts of god), we've changed something: The error handler shall no longer inform the user of a session-end trigger from the other side! Left alone this way, we've broken the whole system by introducing a chicken-egg paradox: We don't let our user be informed of the session-end trigger when would normally, so they won't call our dtor; but because they won't call our dtor, we'll never reach the point where the channel would get hosed and we'd know the inform the user. How to fix this? The answer is pretty obvious: Receiving the GracefulSessionEnd shall now trigger a special graceful-session-end error. Naturally this would only be usefully emitted if we're not in the dtor yet. So the latter situation should kick-off the user invoking our dtor sometime soon, hopefully; we'll send our GracefulSessionEnd to them; and so on.
Definition at line 575 of file session_base.hpp.
Constructor & Destructor Documentation
Graceful_finisher()
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Graceful_finisher::Graceful_finisher (flow::log::Logger * logger_ptr, Session_base * this_session, flow::async::Single_thread_task_loop * async_worker, Master_structured_channel * master_channel) explicit
You must invoke this ctor (instantiate us) if and only if synchronized dtor execution is indeed required; and *this_session has just reached PEER state.
Invoke from thread W only.
How master_channel shall be touched by *this
We're being very explicit about this, since there's some inter-class private-state sharing going on... generally not the most stable or stylistically-amazing situation....
This ctor will .expect_msg(GRACEFUL_SESSION_END), so we can detect its arrival and mark it down as needed and possibly invoke this_session->hose() to report it to the user. Hence there's no method you'll need to call nor any setup like this needed on your part.
on_dtor_start() will attempt to send GracefulSessionEnd to the opposing Graceful_finisher.
Parameters
logger_ptr Logger to use for logging subsequently. (Maybe Session_base should just subclass Log_context for all os us? Add to-do?)
this_session The containing Session_base.
async_worker The thread W of the containing *_session_impl. GracefulSessionEnd handler is at least partially invoked there (hose(...)); and on_dtor_start() posts onto it.
master_channel The containing Session master channel. The pointee must exist until *this Graceful_finisher is gone.
Definition at line 1070 of file session_base.hpp.
References ipc::transport::struc::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::expect_msg(), ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::hose(), ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::hosed(), ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Graceful_finisher::m_async_worker, ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Graceful_finisher::m_master_channel, ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Graceful_finisher::m_opposing_session_done, ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Graceful_finisher::m_this_session, and ipc::session::error::S_SESSION_FINISHED.
Member Function Documentation
on_dtor_start()
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > void ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Graceful_finisher::on_dtor_start
The reason Graceful_finisher exists, this method must be called at the start of *_session_impl dtor; and will block until it is appropriate to let that dtor proceed to shut down the *_session_impl.
Invoke from thread U, not thread W.
Definition at line 1126 of file session_base.hpp.
Referenced by ipc::session::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, S_SHM_TYPE_OR_NONE, S_GRACEFUL_FINISH_REQUIRED_V >::dtor_async_worker_stop(), and ipc::session::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, S_SHM_TYPE_OR_NONE, S_SHM_MAX_HNDL_SZ, S_GRACEFUL_FINISH_REQUIRED_V >::dtor_async_worker_stop().
on_master_channel_hosed()
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > void ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Graceful_finisher::on_master_channel_hosed
Must be invoked if the *_session_impl detects that the master channel has emitted channel-hosing error.
Invoke from thread W.
Definition at line 1110 of file session_base.hpp.
Member Data Documentation
m_async_worker
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > flow::async::Single_thread_task_loop* ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Graceful_finisher::m_async_worker private
The containing Session thread W loop. It shall exist until *this is gone.
Definition at line 634 of file session_base.hpp.
Referenced by ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Graceful_finisher::Graceful_finisher().
m_master_channel
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > Master_structured_channel* ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Graceful_finisher::m_master_channel private
The containing Session master channel. It shall exist until *this is gone.
Definition at line 637 of file session_base.hpp.
Referenced by ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Graceful_finisher::Graceful_finisher().
m_opposing_session_done
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > boost::promise<void> ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Graceful_finisher::m_opposing_session_done private
A promise whose fulfillment is a necessary and sufficient condition for on_dtor_start() returning (letting Session dtor complete).
It is fulfilled once the Master_structured_channel receives GracefulSessionEnd from opposing side (indicating the opposing on_dtor_start() has started) or got hosed (indicating we'll now never know this and must act as-if opposing on_dtor_start() has started). See "Design" in our doc header.
Definition at line 647 of file session_base.hpp.
Referenced by ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Graceful_finisher::Graceful_finisher().
m_this_session
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > Session_base* const ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Graceful_finisher::m_this_session private
The containing Session_base. It shall exist until *this is gone.
Definition at line 631 of file session_base.hpp.
Referenced by ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Graceful_finisher::Graceful_finisher().
The documentation for this class was generated from the following file:
session/detail/session_base.hpp