Flow-IPC: ipc::transport::Socket_stream_channel< SIO > Class Template Reference
ipc::transport::Socket_stream_channel< SIO > Class Template Reference
A Channel with a handles pipe only (no blobs pipe) that uses a Unix domain socket connection as the underlying transport for that pipe.
#include <channel.hpp>
Public Types
using Base = Channel< Null_peer, Null_peer, std::conditional_t< SIO, sync_io::Native_socket_stream, Native_socket_stream >, std::conditional_t< SIO, sync_io::Native_socket_stream, Native_socket_stream > >
Short-hand for our base class.
Public Types inherited from ipc::transport::Channel< Null_peer, Null_peer, std::conditional_t< SIO, sync_io::Native_socket_stream, Native_socket_stream >, std::conditional_t< SIO, sync_io::Native_socket_stream, Native_socket_stream > >
using Blob_sender_obj = Null_peer
Alias for Blob_sender template parameter.
using Blob_receiver_obj = Null_peer
Alias for Blob_receiver template parameter.
using Native_handle_sender_obj = std::conditional_t< SIO, sync_io::Native_socket_stream, Native_socket_stream >
Alias for Native_handle_sender template parameter.
using Native_handle_receiver_obj = std::conditional_t< SIO, sync_io::Native_socket_stream, Native_socket_stream >
Alias for Native_handle_receiver template parameter.
using Async_io_obj = Channel< typename Blob_sender_obj::Async_io_obj, typename Blob_receiver_obj::Async_io_obj, typename Native_handle_sender_obj::Async_io_obj, typename Native_handle_receiver_obj::Async_io_obj >
Assuming S_IS_SYNC_IO_OBJ yields async-I/O counterpart; else yields Channel<Null_peer, Null_peer, Null_peer, Null_peer>.
using Sync_io_obj = Channel< typename Blob_sender_obj::Sync_io_obj, typename Blob_receiver_obj::Sync_io_obj, typename Native_handle_sender_obj::Sync_io_obj, typename Native_handle_receiver_obj::Sync_io_obj >
Assuming S_IS_ASYNC_IO_OBJ yields sync_io counterpart; else yields Channel<Null_peer, Null_peer, Null_peer, Null_peer>.
Public Member Functions
Socket_stream_channel (flow::log::Logger *logger_ptr, util::String_view nickname_str, typename Base::Native_handle_sender_obj &&sock_stm)
Constructs the Channel in PEER state.
Socket_stream_channel ()
Identical to Channel default ctor.
util::Process_credentials remote_peer_process_credentials (Error_code *err_code=0) const
Identical to Native_socket_stream::remote_peer_process_credentials(): OS-reported process credential (PID, etc.) info about the other connected peer's process.
Public Member Functions inherited from ipc::transport::Channel< Null_peer, Null_peer, std::conditional_t< SIO, sync_io::Native_socket_stream, Native_socket_stream >, std::conditional_t< SIO, sync_io::Native_socket_stream, Native_socket_stream > >
Channel ()
Default ctor (Channel is in ??? state; intended to be move-assigned).
Channel (flow::log::Logger *logger_ptr, util::String_view nickname_str)
Constructs Channel in ??? state with the intention to continue initialization via init_blob_pipe() and/or init_native_handle_pipe() call(s).
Channel (Channel &&src)
Move-constructs from src; src becomes as-if default-cted (therefore in ??? state).
Channel (const Channel &)=delete
Copy construction is disallowed.
~Channel ()
Destructor: synchronously invokes the destructors for each peer object moved-into *this via init_blob_pipe() and/or init_native_handle_pipe().
bool initialized (bool suppress_log=false) const
Returns true if and only if the required init_blob_pipe() and init_native_handle_pipe() calls have been made, loading exactly the expected peer objects as the template params Blob_sender_obj, Blob_receiver_obj, Native_handle_sender_obj, Native_handle_receiver_obj specify.
Channel & operator= (Channel &&src)
Move-assigns from src; *this acts as if destructed; src becomes as-if default-cted (therefore in ??? state).
Channel & operator= (const Channel &)=delete
Copy assignment is disallowed.
Async_io_obj async_io_obj ()
Converts a sync_io-peer-bearing *this to a returned async-I/O-peer-bearing new Channel, while *this becomes as-if default-cted.
const Blob_sender_obj * blob_snd () const
Pointer to the immutable owned Blob_sender_obj; null if yet initialized.
Blob_sender_obj * blob_snd ()
Pointer to the mutable owned Blob_sender_obj; null if yet initialized.
const Blob_receiver_obj * blob_rcv () const
Pointer to the immutable owned Blob_receiver_obj; null if not yet initialized.
Blob_receiver_obj * blob_rcv ()
Pointer to the mutable owned Blob_receiver_obj; null if not yet initialized.
const Native_handle_sender_obj * hndl_snd () const
Pointer to the immutable owned Native_handle_sender_obj; null if not yet initialized.
Native_handle_sender_obj * hndl_snd ()
Pointer to the mutable owned Native_handle_sender_obj; null if not yet initialized.
const Native_handle_receiver_obj * hndl_rcv () const
Pointer to the immutable owned Native_handle_receiver_obj; null if not yet initialized.
Native_handle_receiver_obj * hndl_rcv ()
Pointer to the mutable owned Native_handle_receiver_obj; null if not yet initialized.
bool init_blob_pipe (Blob_sender_obj &&snd_and_rcv)
Completes initialization of the blobs pipe by taking ownership (via move semantics) of an object that is simultaneously the Blob_sender_obj and Blob_receiver_obj for our end of the blobs pipe.
bool init_blob_pipe (Blob_sender_obj &&snd, Blob_receiver_obj &&rcv)
Completes initialization of the blobs pipe by taking ownership (via move semantics) of separate Blob_sender_obj and Blob_receiver_obj objects for our end of the blobs pipe.
bool init_native_handle_pipe (Native_handle_sender_obj &&snd_and_rcv)
Analogous to 1-arg init_blob_pipe() but as applied to the handles pipe.
bool init_native_handle_pipe (Native_handle_sender_obj &&snd, Native_handle_receiver_obj &&rcv)
Analogous to 2-arg init_blob_pipe() but as applied to the handles pipe.
size_t send_blob_max_size () const
Yields blob_snd()-> same method.
size_t send_meta_blob_max_size () const
Yields hndl_snd()-> same method.
size_t receive_blob_max_size () const
Yields blob_rcv()-> same method.
size_t receive_meta_blob_max_size () const
Yields hndl_rcv()-> same method.
bool send_blob (const util::Blob_const &blob, Error_code *err_code)
Yields blob_snd()-> same method.
bool send_native_handle (Native_handle hndl_or_null, const util::Blob_const &meta_blob, Error_code *err_code)
Yields hndl_snd()-> same method.
bool async_end_sending (Task_err &&on_done_func)
Performs hndl_snd()-> and/or blob_snd()-> same method, synthesizing completion handlers into one if applicable.
bool async_end_sending (Error_code *sync_err_code, Task_err &&on_done_func)
Performs hndl_snd()-> and/or blob_snd()-> same method, synthesizing completions into one if applicable.
bool end_sending ()
Performs hndl_snd()-> and/or blob_snd()-> same method, returning true if all (1-2) invoked methods returned true; false conversely.
bool auto_ping (util::Fine_duration period=boost::chrono::seconds(2))
Performs hndl_snd()-> and/or blob_snd()-> same method, returning true if all (1-2) invoked methods returned true; false conversely.
bool async_receive_blob (Args &&... args)
Yields blob_rcv()-> same method.
bool async_receive_native_handle (Args &&... args)
Yields hndl_rcv()-> same method.
bool idle_timer_run (util::Fine_duration timeout=boost::chrono::seconds(5))
Performs hndl_rcv()-> and/or blob_rcv()-> same method, returning true if all (1-2) invoked methods returned true; false conversely.
bool replace_event_wait_handles (const Create_ev_wait_hndl_func &create_ev_wait_hndl_func)
Executes same method on all unique stored peer objects; returns true if and only if they all did.
bool start_send_blob_ops (Event_wait_func_t &&ev_wait_func)
Yields blob_snd()-> same method.
bool start_send_native_handle_ops (Event_wait_func_t &&ev_wait_func)
Yields hndl_snd()-> same method.
bool start_receive_blob_ops (Event_wait_func_t &&ev_wait_func)
Yields blob_rcv()-> same method.
bool start_receive_native_handle_ops (Event_wait_func_t &&ev_wait_func)
Yields hndl_rcv()-> same method.
const std::string & nickname () const
Returns nickname, a brief string suitable for logging.
Additional Inherited Members
Static Public Attributes inherited from ipc::transport::Channel< Null_peer, Null_peer, std::conditional_t< SIO, sync_io::Native_socket_stream, Native_socket_stream >, std::conditional_t< SIO, sync_io::Native_socket_stream, Native_socket_stream > >
static constexpr bool S_HAS_2_PIPES
Useful for generic programming: true if and only if types imply both blobs and handles pipes are enabled.
static constexpr bool S_HAS_BLOB_PIPE_ONLY
Useful for generic programming: true if and only if types imply only the blobs pipe is enabled.
static constexpr bool S_HAS_NATIVE_HANDLE_PIPE_ONLY
Useful for generic programming: true if and only if types imply only the handles pipe is enabled.
static constexpr bool S_HAS_BLOB_PIPE
Useful for generic programming: true if and only if types imply at least the blobs pipe is enabled.
static constexpr bool S_HAS_NATIVE_HANDLE_PIPE
Useful for generic programming: true if and only if types imply at least the handles pipe is enabled.
static constexpr bool S_IS_SYNC_IO_OBJ
Useful for generic programming: true <=> each non-Null_peer peer type (Blob_sender_obj, Blob_receiver_obj, Native_handle_sender_obj, Native_handle_receiver_obj) implements the sync_io pattern (by convention living in namespace ipc::transport::sync_io).
static constexpr bool S_IS_ASYNC_IO_OBJ
It equals the reverse of S_IS_SYNC_IO_OBJ.
Related Functions inherited from ipc::transport::Channel< Null_peer, Null_peer, std::conditional_t< SIO, sync_io::Native_socket_stream, Native_socket_stream >, std::conditional_t< SIO, sync_io::Native_socket_stream, Native_socket_stream > >
std::ostream & operator<< (std::ostream &os, const Channel< Null_peer, Null_peer, std::conditional_t< SIO, sync_io::Native_socket_stream, Native_socket_stream >, std::conditional_t< SIO, sync_io::Native_socket_stream, Native_socket_stream > > &val)
Prints string representation of the given Channel to the given ostream.
Detailed Description
template<bool SIO>
class ipc::transport::Socket_stream_channel< SIO >
A Channel with a handles pipe only (no blobs pipe) that uses a Unix domain socket connection as the underlying transport for that pipe.
Note this is a glorified alias; it stores no additional data on top of the super-class. It is easier to use than the super-class, as the ctor takes care of the necessary init_native_handle_pipe() call to complete initialization directly during construction. You may freely static_cast pointers/references between the 2 types.
send_native_handle(), async_receive_native_handle() will work (over Unix domain socket stream transport).
send_blob(), async_receive_blob() will not compile.
Template Parameters
SIO Selects between transport::sync_io:: and transport:: version of held type(s); hence between Channel::S_IS_SYNC_IO_OBJ and Channel::S_IS_ASYNC_IO_OBJ.
Definition at line 1025 of file channel.hpp.
Member Typedef Documentation
Base
template<bool SIO> using ipc::transport::Socket_stream_channel< SIO >::Base = Channel<Null_peer, Null_peer, std::conditional_t<SIO, sync_io::Native_socket_stream, Native_socket_stream>, std::conditional_t<SIO, sync_io::Native_socket_stream, Native_socket_stream> >
Short-hand for our base class.
Definition at line 1034 of file channel.hpp.
Constructor & Destructor Documentation
Socket_stream_channel()
template<bool SIO> ipc::transport::Socket_stream_channel< SIO >::Socket_stream_channel (flow::log::Logger * logger_ptr, util::String_view nickname_str, typename Base::Native_handle_sender_obj && sock_stm) explicit
Constructs the Channel in PEER state.
sock_stm must be in PEER state; else behavior is undefined.
Parameters
logger_ptr Logger to use for logging subsequently.
nickname_str See nickname().
sock_stm The peer object that becomes owned by *this via move. sock_stm becomes as-if default-cted (NULL state).
Definition at line 2199 of file channel.hpp.
References ipc::transport::Channel< Null_peer, Null_peer, std::conditional_t< SIO, sync_io::Native_socket_stream, Native_socket_stream >, std::conditional_t< SIO, sync_io::Native_socket_stream, Native_socket_stream > >::init_native_handle_pipe(), and ipc::transport::Channel< Null_peer, Null_peer, std::conditional_t< SIO, sync_io::Native_socket_stream, Native_socket_stream >, std::conditional_t< SIO, sync_io::Native_socket_stream, Native_socket_stream > >::initialized().
Member Function Documentation
remote_peer_process_credentials()
template<bool SIO> util::Process_credentials ipc::transport::Socket_stream_channel< SIO >::remote_peer_process_credentials (Error_code * err_code = 0) const
Identical to Native_socket_stream::remote_peer_process_credentials(): OS-reported process credential (PID, etc.) info about the other connected peer's process.
See its doc header.
Parameters
err_code See above.
Returns
See above.
Definition at line 2211 of file channel.hpp.
Referenced by ipc::session::Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, S_SHM_TYPE_OR_NONE, S_SHM_MAX_HNDL_SZ >::async_accept_log_in(), and ipc::session::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, S_SHM_TYPE_OR_NONE >::conn_on_async_connect_or_error().
The documentation for this class was generated from the following file:
transport/channel.hpp