Flow-IPC: ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > Class Template Reference
ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > Class Template Reference
This is to vanilla Session_server what shm::classic::Server_session is to vanilla Server_session: it is the session-server type that starts SHM-enabled sessions with SHM-classic provider (ipc::shm::classic::Pool_arena).
#include <session_server.hpp>
Public Types
using Server_session_obj = shm::classic::Server_session< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
Short-hand for the concrete Server_session-like type emitted by async_accept().
using Mdt_reader_ptr = typename Impl::Mdt_reader_ptr
Short-hand for Session_mv::Mdt_reader_ptr.
using Mdt_builder = typename Server_session_obj::Mdt_builder
Metadata builder type passed to mdt_load_func() in advanced async_accept() overload.
using Channels = typename Impl::Channels
Short-hand for Session_mv::Channels.
using Arena = typename Server_session_obj::Base::Arena
Short-hand for shm::classic::Session_mv::Arena. See app_shm() in particular.
using Structured_msg_builder_config = typename Server_session_obj::Base::Structured_msg_builder_config
Short-hand for shm::classic::Session_mv::Structured_msg_builder_config.
using Structured_msg_reader_config = typename Server_session_obj::Base::Structured_msg_reader_config
Short-hand for shm::classic::Session_mv::Structured_msg_reader_config.
Public Member Functions
Session_server (flow::log::Logger *logger_ptr, const Server_app &srv_app_ref, const Client_app::Master_set &cli_app_master_set_ref, Error_code *err_code=0)
Constructor: identical to session::Session_server ctor.
~Session_server ()
Destructor: contract is identical to session::Session_server dtor.
size_t pool_size_limit_mi () const
The pool-size value, in mebibytes, which will be used to size the pool in subsequent async_accept()s.
void pool_size_limit_mi (size_t limit_mi)
Sets the value as returned by pool_size_limit_mi() accessor.
template<typename Task_err >
void async_accept (Server_session_obj *target_session, Task_err &&on_done_func)
Contract identical to simpler session::Session_server::async_accept() overload; but internally ensures that the appropriate SHM-classic arenas are available for use in the emitted Server_session_obj.
template<typename Task_err , typename N_init_channels_by_srv_req_func , typename Mdt_load_func >
void async_accept (Server_session_obj *target_session, Channels *init_channels_by_srv_req, Mdt_reader_ptr *mdt_from_cli_or_null, Channels *init_channels_by_cli_req, N_init_channels_by_srv_req_func &&n_init_channels_by_srv_req_func, Mdt_load_func &&mdt_load_func, Task_err &&on_done_func)
Contract identical to advanced session::Session_server::async_accept() overload; but internally ensures that the appropriate SHM-classic arenas are available for use in the emitted Server_session_obj.
Arena * app_shm (const Client_app &app)
Returns pointer to the per-app SHM-arena, whose lifetime extends until *this is destroyed; or null if the given Client_app has not yet opened at least 1 shm::classic::Server_session via async_accept().
Structured_msg_builder_config app_shm_builder_config (const Client_app &app)
Returns builder config suitable for capnp-serializing out-messages in SHM arena app_shm() for the same Client_app app.
Structured_msg_builder_config::Builder::Session app_shm_lender_session (const Client_app &app)
In short, what app_shm_builder_config() is to shm::classic::Session_mv::app_shm_builder_config(), this is to shm::classic::Session_mv::app_shm_lender_session().
Structured_msg_reader_config app_shm_reader_config (const Client_app &app)
Returns reader config counterpart to app_shm_builder_config() for a given Client_app app.
void to_ostream (std::ostream *os) const
Prints string representation to the given ostream.
Private Types
using Impl = Session_server_impl< Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >, Server_session< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > >
Short-hand for our base/core impl.
using Mutex = flow::util::Mutex_non_recursive
Short-hand for m_app_shm_mutex type.
using Lock_guard = flow::util::Lock_guard< Mutex >
Short-hand for Mutex lock.
Private Types inherited from ipc::session::Session_server_impl< Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >, Server_session< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > >
using Session_server_obj = Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
See this_session_srv().
using Server_session_obj = Server_session< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
Useful short-hand for the concrete Server_session type emitted by async_accept().
using Mdt_reader_ptr = typename Server_session_obj::Mdt_reader_ptr
Short-hand for Session_mv::Mdt_reader_ptr.
using Channels = typename Server_session_obj::Channels
Short-hand for Session_mv::Channels.
Private Member Functions
Error_code init_app_shm_as_needed (const Client_app &app)
Implementation of our per_app_setup_func() customization point used in the ctor impl: invoked from an unspecified thread, asynchronously, by async_accept() during log-in, it synchronously makes it so that this->app_shm(app) returns non-null from now on.
Private Member Functions inherited from ipc::session::Session_server_impl< Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >, Server_session< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > >
Session_server_impl (flow::log::Logger *logger_ptr, Session_server_obj *this_session_srv_arg, const Server_app &srv_app_ref, const Client_app::Master_set &cli_app_master_set_ref, Error_code *err_code, Per_app_setup_func &&per_app_setup_func)
See Session_server ctor; it does that.
~Session_server_impl ()
See Session_server dtor.
void async_accept (Server_session_obj *target_session, Channels *init_channels_by_srv_req, Mdt_reader_ptr *mdt_from_cli_or_null, Channels *init_channels_by_cli_req, N_init_channels_by_srv_req_func &&n_init_channels_by_srv_req_func, Mdt_load_func &&mdt_load_func, Task_err &&on_done_func)
See Session_server method.
void to_ostream (std::ostream *os) const
See Server_session method.
Session_server_obj * this_session_srv ()
Returns pointer to the object that is privately sub-classing us.
void sub_class_set_deinit_func (Task &&task)
Utility for sub-classes: ensures that task() is invoked near the end of *this dtor's execution, after all other (mutable) state has been destroyed, including stopping/joining any threads performing async async_accept() ops.
Private Attributes
size_t m_pool_size_limit_mi
See pool_size_limit_mi().
const Server_app & m_srv_app_ref
Identical to Session_server::m_srv_app_ref. Used in init_app_shm_as_needed() name calc.
const Shared_name m_srv_namespace
Identical Session_base::m_srv_namespace. Used in init_app_shm_as_needed() name calc.
Mutex m_app_shm_mutex
Protects m_app_shm_by_name and m_shm_pool_names.
boost::unordered_map< std::string, boost::movelib::unique_ptr< Arena > > m_app_shm_by_name
The per-app-scope SHM arenas by App::m_name.
boost::shared_ptr< std::vector< Shared_name > > m_shm_pool_names
Set of names of every SHM-pool created w/r/t m_app_shm_by_name.
Private Attributes inherited from ipc::session::Session_server_impl< Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >, Server_session< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > >
const Server_app & m_srv_app_ref
See Session_server public data member.
Related Functions
(Note that these are not member functions.)
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload >
std::ostream & operator<< (std::ostream &os, const Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > &val)
Prints string representation of the given Session_server to the given ostream.
Related Functions inherited from ipc::session::Session_server_impl< Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >, Server_session< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > >
std::ostream & operator<< (std::ostream &os, const Session_server_impl< Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >, Server_session< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > > &val)
Prints string representation of the given Session_server_impl to the given ostream.
Detailed Description
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload>
class ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
This is to vanilla Session_server what shm::classic::Server_session is to vanilla Server_session: it is the session-server type that starts SHM-enabled sessions with SHM-classic provider (ipc::shm::classic::Pool_arena).
Its API is identical to that of Session_server, except that it emits Server_session_obj that are shm::classic::Server_session and not vanilla Server_session. In addition:
Max pool size configuration API (optional)
If using this, as opposed to (at least) SHM-jemalloc provider (session::shm::arena_lend::jemalloc::Session_server), you could potentially encounter "No space left on device" (ENOSPC in at least Linux) in async_accept(). This has nothing to do with drive space, or even physical RAM in fact. It has to do with certain kernel parameters governing virtual SHM-mapped space. If this becomes a problem then please look into Session_server::pool_size_limit_mi() API. See the doc header for the accessor for discussion.
In most cases it should not come up.
Implementation
See similar section of session::Session_server. It explains why we sub-class Session_server_impl and even how how that's used for this SHM-classic scenario. To reiterate:
We use 2 of 2 available customization points of private super-class Session_server_impl. We:
pass-up a per_app_setup_func() that, given the new session's desired Client_app, creates-if-needed the per-app SHM-arena and keeps handle open as well as available via this->app_shm(Client_app::m_name); and
parameterize Session_server_impl on shm::classic::Server_session which, during log-in, creates the per-session SHM-arena and keeps handle open; and saves this->app_shm(Client_app::m_name).
shm::classic::Server_session doc header delves deeply into the entire impl strategy for setting up these arenas. If you read/grok that, then the present class's impl should be straightforward to follow.
Template Parameters
S_MQ_TYPE_OR_NONE See vanilla Session_server.
S_TRANSMIT_NATIVE_HANDLES See vanilla Session_server.
Mdt_payload See vanilla Session_server.
Definition at line 70 of file session_server.hpp.
Member Typedef Documentation
Arena
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Arena = typename Server_session_obj::Base::Arena
Short-hand for shm::classic::Session_mv::Arena. See app_shm() in particular.
Definition at line 99 of file session_server.hpp.
Channels
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Channels = typename Impl::Channels
Short-hand for Session_mv::Channels.
Definition at line 96 of file session_server.hpp.
Impl
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Impl = Session_server_impl <Session_server<S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload>, Server_session<S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload> > private
Short-hand for our base/core impl.
Definition at line 79 of file session_server.hpp.
Lock_guard
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Lock_guard = flow::util::Lock_guard<Mutex> private
Short-hand for Mutex lock.
Definition at line 381 of file session_server.hpp.
Mdt_builder
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Mdt_builder = typename Server_session_obj::Mdt_builder
Metadata builder type passed to mdt_load_func() in advanced async_accept() overload.
Definition at line 93 of file session_server.hpp.
Mdt_reader_ptr
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Mdt_reader_ptr = typename Impl::Mdt_reader_ptr
Short-hand for Session_mv::Mdt_reader_ptr.
Definition at line 90 of file session_server.hpp.
Mutex
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Mutex = flow::util::Mutex_non_recursive private
Short-hand for m_app_shm_mutex type.
Definition at line 378 of file session_server.hpp.
Server_session_obj
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Server_session_obj = shm::classic::Server_session<S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload>
Short-hand for the concrete Server_session-like type emitted by async_accept().
Definition at line 87 of file session_server.hpp.
Structured_msg_builder_config
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Structured_msg_builder_config = typename Server_session_obj::Base::Structured_msg_builder_config
Short-hand for shm::classic::Session_mv::Structured_msg_builder_config.
Definition at line 102 of file session_server.hpp.
Structured_msg_reader_config
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Structured_msg_reader_config = typename Server_session_obj::Base::Structured_msg_reader_config
Short-hand for shm::classic::Session_mv::Structured_msg_reader_config.
Definition at line 105 of file session_server.hpp.
Constructor & Destructor Documentation
Session_server()
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Session_server (flow::log::Logger * logger_ptr, const Server_app & srv_app_ref, const Client_app::Master_set & cli_app_master_set_ref, Error_code * err_code = 0) explicit
Constructor: identical to session::Session_server ctor.
See its doc header. Consider also pool_size_limit_mi() mutator (though if there are no problems in practice, then you can leave it alone).
Parameters
logger_ptr See above.
srv_app_ref See above.
cli_app_master_set_ref See above.
err_code See above.
Definition at line 455 of file session_server.hpp.
References ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::init_app_shm_as_needed().
~Session_server()
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::~Session_server () default
Destructor: contract is identical to session::Session_server dtor.
In particular this dtor shall perform shm::classic::Pool_arena::remove_persistent() on each pool returnable by app_shm() (the per-Client_app pools). Reminder: like all kernel-persistent remove_persistent() methods this will not necessarily free the RAM held on behalf of a given pool; any currently opened Pool_arenas – presumably ones still (possibly) held by counterpart shm::classic::Client_session_impls – will continue to function fine.
Rationale for aforementioned remove_persistent() op
Why do it? Answer: Naturally this should be freed sometime; otherwise the RAM will leak, even though the session pertaining to the per-session pool is gone.
Why not do it earlier? Answer: It would be nice to do it super-early... like, say, just after creating the pool during the async portion of async_accept(), namely in init_app_shm_as_needed(). The only reason not to do it is if a client handle (Pool_arena) to the pool has not yet had a chance to get opened by the name deleted via remove_persistent(). But this can occur an indefinite number of times after init_app_shm_as_needed() creates the pool: the whole idea is the pool is shared between different sessions with the same (by value equality) Client_app, across different client processes in fact.
Hence we postpone it until this dtor, at which point all the sessions are definitely done-for.
Why not do it later? Answer: Session-server is done-for, if we are being invoked; the counterpart Client_sessions could not possibly hope to open the pool now, even if they somehow wanted to do so. So why wait?
What if this dtor never runs?
In any program that exits without aborting abruptly, it will run – either proactively during user program de-init code or implicity when it exits.
It however may not run due to abrupt termination (a crash). In that case the app_shm() pools will indeed leak, in that this dtor won't execute, so the remove_persistent()s will not occur in that fashion. The shm::classic::Session_server has a contingency for this, which we don't describe here, wherein it has cleanup points at which it cleans up anything thus leaked during previous invocations of the same Server_app.
What about the per-session pools?
The above talks only of the app_shm()-returned pools; what about shm::classic::Session_impl::session_shm()? Shouldn't we clean it up here? Answer: Well, we could, but since it's a per-session thing, each shm::classic::Session_server_impl takes care of its own session_shm().
Member Function Documentation
app_shm()
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Arena * ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::app_shm (const Client_app & app)
Returns pointer to the per-app SHM-arena, whose lifetime extends until *this is destroyed; or null if the given Client_app has not yet opened at least 1 shm::classic::Server_session via async_accept().
Alternatively you may use shm::classic::Session_mv::app_shm() off any session object filled-out by *this async_accept(), as long as its Server_session_mv::client_app() equals app (by App::m_name equality).
If non-null is returned, then the same pointer value shall be returned for all subsequent calls with the same (by App::m_name equality) app. The non-null pointers returned for any 2 calls, where app is different (by App::m_name equality) among them, shall always differ.
See shm::classic::Session_mv::Arena doc header for useful instructions on working with Arena, lend_object(), and borrow_object().
Perf
Given the choice between Server_session_mv::app_shm() and the present method, the latter is somewhat slower; internally it involves a mutex-protected map lookup, while the former simply returns a cached pointer as of this writing.
Generally it is also quite fast for the user to save any non-null value returned by either app_shm(); the pointer returned shall always be the same after all.
Thread safety
For internal use, namely by shm::classic::Server_session_impl::async_accept_log_in() at least, it is guaranteed the app_shm() may be called on the same *this concurrently to itself and init_app_shm_as_needed(). Formally speaking this isn't publicly documented, as I (ygoldfel) didn't want to get users into any bad habit, but internally it does have this property – as it is required.
Parameters
app Client_app whose segregated SHM-arena to return, if a session for a client of the app has been opened prior to this call.
Returns
Pointer to *this-held per-app SHM-arena, if it has been created; null otherwise. See above.
Definition at line 618 of file session_server.hpp.
References ipc::session::App::m_name.
app_shm_builder_config()
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Structured_msg_builder_config ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::app_shm_builder_config (const Client_app & app)
Returns builder config suitable for capnp-serializing out-messages in SHM arena app_shm() for the same Client_app app.
Alternatively you may use shm::classic::Session_mv::app_shm_builder_config() off any session object filled-out by *this async_accept(), as long as its Server_session_mv::client_app() equals app (by App::m_name equality).
Unlike app_shm() this method does not allow the case where app_shm(app) would have returned null. In that case the present method yields undefined behavior (assertion may trip).
Perf
Given the choice between Server_session_mv::app_shm_builder_config() and the present method, the latter is somewhat slower (reason: same as listed in app_shm() doc header).
Generally it is also quite fast for the user to save any value returned by either app_shm_builder_config(), as an equal-by-value Config object shall be returned for the same (by App::m_name equality) app.
Parameters
app See app_shm().
Returns
See above.
Definition at line 634 of file session_server.hpp.
app_shm_lender_session()
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Structured_msg_builder_config::Builder::Session ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::app_shm_lender_session (const Client_app & app)
In short, what app_shm_builder_config() is to shm::classic::Session_mv::app_shm_builder_config(), this is to shm::classic::Session_mv::app_shm_lender_session().
Notes in app_shm_builder_config() doc header apply here.
Parameters
app See app_shm().
Returns
See above.
Definition at line 644 of file session_server.hpp.
app_shm_reader_config()
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Structured_msg_reader_config ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::app_shm_reader_config (const Client_app & app)
Returns reader config counterpart to app_shm_builder_config() for a given Client_app app.
Parameters
app See app_shm().
Returns
See above.
Definition at line 654 of file session_server.hpp.
async_accept() [1/2]
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > template<typename Task_err , typename N_init_channels_by_srv_req_func , typename Mdt_load_func > void ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::async_accept (Server_session_obj * target_session, Channels * init_channels_by_srv_req, Mdt_reader_ptr * mdt_from_cli_or_null, Channels * init_channels_by_cli_req, N_init_channels_by_srv_req_func && n_init_channels_by_srv_req_func, Mdt_load_func && mdt_load_func, Task_err && on_done_func)
Contract identical to advanced session::Session_server::async_accept() overload; but internally ensures that the appropriate SHM-classic arenas are available for use in the emitted Server_session_obj.
See doc header for session::Session_server::async_accept() advanced overload.
Additional (to those documented for session::Session_server::async_accept()) Error_code generated and passed to on_done_func(): See shm::classic::Pool_arena ctor doc header. The most likely reason for failure of that code in this context is a permissions issue creating the SHM pool or ENOSPC (Linux at least) a/k/a "No space left on device" if a kernel level for sum of pool sizes has been reached. In this case consider pool_size_limit_mi() mutator and/or tweaking the kernel parameter.
Template Parameters
Task_err See above.
N_init_channels_by_srv_req_func See above.
Mdt_load_func See above.
Parameters
target_session See other async_accept() overload.
init_channels_by_srv_req See above.
mdt_from_cli_or_null See above.
init_channels_by_cli_req See above.
n_init_channels_by_srv_req_func See above.
mdt_load_func See above.
on_done_func See above.
Definition at line 681 of file session_server.hpp.
async_accept() [2/2]
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > template<typename Task_err > void ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::async_accept (Server_session_obj * target_session, Task_err && on_done_func)
Contract identical to simpler session::Session_server::async_accept() overload; but internally ensures that the appropriate SHM-classic arenas are available for use in the emitted Server_session_obj.
See doc header for session::Session_server::async_accept() simple overload.
Additional (to those documented for Session_server::async_accept()) Error_code generated and passed to on_done_func(): See shm::classic::Pool_arena ctor doc header. The most likely reason for failure of that code in this context is a permissions issue creating the SHM pool, or ENOSPC (Linux at least) a/k/a "No space left on device" if a kernel level for sum of pool sizes has been reached. In this case consider pool_size_limit_mi() mutator and/or tweaking the kernel parameter.
Template Parameters
Task_err See above.
Parameters
target_session See above. Reminder (though this is enforced at compile-time): the type of *target_session for Session_server::async_accept() is Server_session; whereas here it is shm::classic::Server_session.
on_done_func See above.
Definition at line 664 of file session_server.hpp.
init_app_shm_as_needed()
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > Error_code ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::init_app_shm_as_needed (const Client_app & app) private
Implementation of our per_app_setup_func() customization point used in the ctor impl: invoked from an unspecified thread, asynchronously, by async_accept() during log-in, it synchronously makes it so that this->app_shm(app) returns non-null from now on.
What it returns is a pointer (always the same one) to the segregated SHM-arena pertaining to all sessions (current and future) pertaining to app in *this server. On success returns falsy Error_code. Success means either app_shm(app) was already going to return non-null, or it wasn't, but we successfuly made it so it will.
On failure to set this up:
Truthy Error_code reason for failure is returned.
app_shm(app) shall continue to return null.
*this is not hosed.
This method is thread-safe to invoke on the same *this w/r/t concurrent calls to itself and app_shm().
Parameters
app The Client_app for which to set up, if needed, the per-app SHM-arena.
Returns
See above; falsy if and only if app_shm(app) shall return non-null from now on.
Definition at line 531 of file session_server.hpp.
References ipc::session::build_conventional_shared_name(), ipc::util::CREATE_ONLY, ipc::util::Shared_name::ct(), ipc::session::App::m_name, ipc::util::Shared_name::S_1ST_OR_ONLY, ipc::util::Shared_name::S_RESOURCE_TYPE_ID_SHM, ipc::util::shared_resource_permissions(), and ipc::session::shm::classic::SHM_SUBTYPE_PREFIX.
Referenced by ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Session_server().
pool_size_limit_mi() [1/2]
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > size_t ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::pool_size_limit_mi
The pool-size value, in mebibytes, which will be used to size the pool in subsequent async_accept()s.
One can change this via the mutator overload.
A large default value is used if one does not invoke that mutator.
How it works
Each time async_accept() succeeds, a SHM pool sized according to this value is created for the session; and potentially another SHM pool sized similarly is created for the Client_app (if and only if a session against the same Client_app has not yet been opened by *this). The key point: only a tiny amount of RAM is actually taken at that time for each pool; the pool size only counts against vaddr space which is essentially unlimited. Physical RAM is reserved only upon actual allocation for objects subsequently, with kernel-page-sized quantization. Therefore a huge value can be used here with no RAM-use penalty; on the other hand if this value is too small, and an allocation makes a pool run out of vaddr space, then a bad_alloc exception will be thrown, and you're pretty much kaput. So you should use a huge value! And indeed the default is quite large.
Unfortunately, at least in Linux, there is nevertheless a system-wide limit against the sum of these SHM-pool virtual sizes. This is a kernel parameter and is usually admin-configurable; it might default to half your physical RAM for example. Therefore unfortunately if too much virtual space is used by active SHM-pools across the system, a Linux (at least) ENOSPC (No space left on device) error might result (in our case be passed to async_accept() completion handler). In that case, you can either tweak the relevant kernel parameter(s); or use pool_size_limit_mi() mutator to reduce your pool sizes – assuming of course it'll be sufficient for your allocation needs.
For most use cases none of this will be a problem. If it becomes a problem, either use a solution above; or consider ipc::session::shm::arena_lend::jemalloc::Session_server (SHM-jemalloc) which is a multi-pool system that adjusts dynamically without your having to worry about it at all.
Returns
See above.
Definition at line 525 of file session_server.hpp.
pool_size_limit_mi() [2/2]
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > void ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::pool_size_limit_mi (size_t limit_mi)
Sets the value as returned by pool_size_limit_mi() accessor.
See its doc header. Behavior is undefined if this is called concurrently with async_accept() itself, or while an async_accept() is outstanding.
A large default value is used if one does not call this.
Parameters
limit_mi The new value. It must be positive.
Definition at line 518 of file session_server.hpp.
to_ostream()
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > void ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::to_ostream (std::ostream * os) const
Prints string representation to the given ostream.
Parameters
os Stream to which to write.
Definition at line 694 of file session_server.hpp.
Friends And Related Function Documentation
operator<<()
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > std::ostream & operator<< (std::ostream & os, const Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > & val) related
Prints string representation of the given Session_server to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 700 of file session_server.hpp.
Member Data Documentation
m_app_shm_by_name
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > boost::unordered_map<std::string, boost::movelib::unique_ptr<Arena> > ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::m_app_shm_by_name private
The per-app-scope SHM arenas by App::m_name.
If it's not in the map, it has not been needed yet. If it is but is null, it has but error caused it to not be set-up successfully.
Definition at line 426 of file session_server.hpp.
m_app_shm_mutex
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > Mutex ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::m_app_shm_mutex mutable private
Protects m_app_shm_by_name and m_shm_pool_names.
Definition at line 420 of file session_server.hpp.
m_pool_size_limit_mi
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > size_t ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::m_pool_size_limit_mi private
See pool_size_limit_mi().
Definition at line 411 of file session_server.hpp.
m_shm_pool_names
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > boost::shared_ptr<std::vector<Shared_name> > ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::m_shm_pool_names private
Set of names of every SHM-pool created w/r/t m_app_shm_by_name.
Each time an Arena is added to m_app_shm_by_name, its pool name is added to m_shm_pool_names. A certain cleanup function, run from Session_server_impl dtor due to our use of Session_server_impl::sub_class_set_deinit_func(), removes (unlinks) each pool listed in *m_shm_pool_names.
Rationale
Why a shared_ptr? Answer: By the time the aforementioned cleanup task runs, *static_cast<shm::classic::Session_server*>(this) is destroyed – so it cannot access that this or specifically this->m_shm_pool_names. Hence it captures a shared_ptr from this shared-pointer group instead; and the vector lives as long as it needs to to be scanned by the cleanup task.
Definition at line 440 of file session_server.hpp.
m_srv_app_ref
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > const Server_app& ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::m_srv_app_ref private
Identical to Session_server::m_srv_app_ref. Used in init_app_shm_as_needed() name calc.
Definition at line 414 of file session_server.hpp.
m_srv_namespace
template<schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > const Shared_name ipc::session::shm::classic::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::m_srv_namespace private
Identical Session_base::m_srv_namespace. Used in init_app_shm_as_needed() name calc.
Definition at line 417 of file session_server.hpp.
The documentation for this class was generated from the following files:
session/shm/classic/classic_fwd.hpp
session/shm/classic/session_server.hpp