Flow-IPC: ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t > Class Template Reference
ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t > Class Template Reference
Common data and logic for shm::arena_lend::jemalloc::Server_session_impl and shm::arena_lend::jemalloc::Client_session_impl.
#include <session_impl.hpp>
Public Types
using Base = Session_impl_t
Short-hand for base class.
using Session_base_obj = typename Base::Session_base_obj
Short-hand for Session_base super-class.
using Arena = ipc::shm::arena_lend::jemalloc::Ipc_arena
See shm::arena_lend::jemalloc::Session_mv counterpart for public description.
using Shm_session = jemalloc::Shm_session
See shm::arena_lend::jemalloc::Session_mv counterpart for public description.
template<typename Message_body >
using Structured_channel = transport::struc::shm::arena_lend::jemalloc::Channel< typename Base::Channel_obj, Message_body >
See shm::arena_lend::jemalloc::Session_mv counterpart for public description.
using Structured_msg_builder_config = typename transport::struc::shm::arena_lend::jemalloc::Builder::Config
See shm::arena_lend::jemalloc::Session_mv counterpart for public description.
using Structured_msg_reader_config = typename transport::struc::shm::arena_lend::jemalloc::Reader::Config
See shm::arena_lend::jemalloc::Session_mv counterpart for public description.
using Blob = Shm_session::Blob
Alias for a light-weight blob used in borrow_object() and lend_object().
Public Member Functions
Arena * session_shm ()
See shm::arena_lend::jemalloc::Session_mv counterpart.
std::shared_ptr< Arena > session_shm_ptr ()
See shm::arena_lend::jemalloc::Session_mv counterpart.
template<typename T >
Blob lend_object (const typename Arena::template Handle< T > &handle)
See shm::arena_lend::jemalloc::Session_mv counterpart.
template<typename T >
Arena::template Handle< T > borrow_object (const Blob &serialization)
See shm::arena_lend::jemalloc::Session_mv counterpart.
Structured_msg_builder_config session_shm_builder_config ()
See shm::arena_lend::jemalloc::Session_mv counterpart.
Structured_msg_builder_config::Builder::Session session_shm_lender_session ()
See shm::arena_lend::jemalloc::Session_mv counterpart.
Structured_msg_reader_config session_shm_reader_config ()
See shm::arena_lend::jemalloc::Session_mv counterpart.
Structured_msg_reader_config app_shm_reader_config ()
See shm::arena_lend::jemalloc::Session_mv counterpart.
Shm_session * shm_session ()
See shm::arena_lend::jemalloc::Session_mv counterpart.
Structured_msg_reader_config shm_reader_config ()
See shm::arena_lend::jemalloc::Session_mv counterpart.
Protected Types
using Shm_session_ptr = std::shared_ptr< Shm_session >
How the SHM-provider refers to a Shm_session.
Protected Member Functions
Error_code init_shm (util::Native_handle &&local_hndl, const Shared_name &pool_name_fragment_or_empty, const std::shared_ptr< Arena > &app_shm_or_null={})
To be invoked at most once, synchronously sets up nearly-all aspects of this arena-lending-SHM-capable Session; the prerequisite from sub-class _impl being that the possibly-asynchronous steps leading up to this have been completed successfully.
void reset_shm ()
Undoes init_shm_arenas(), namely destroying shm_session() pointee and session_shm() pointee.
Private Attributes
std::shared_ptr< Arena > m_session_shm
See session_shm(). This becomes non-null in init_shm().
std::optional< typename Shm_session::Shm_channel > m_shm_channel
Internal-use transport::struc::Channel for m_shm_session. null <=> m_shm_session is null.
Shm_session_ptr m_shm_session
See shm_session(). This becomes non-null in init_shm().
Related Functions
(Note that these are not member functions.)
template<typename Session_impl_t >
std::ostream & operator<< (std::ostream &os, const Session_impl< Session_impl_t > &val)
Prints string representation of the given Session_impl to the given ostream.
Detailed Description
template<typename Session_impl_t>
class ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >
Common data and logic for shm::arena_lend::jemalloc::Server_session_impl and shm::arena_lend::jemalloc::Client_session_impl.
Arena-lending SHM-providers are almost exactly the same, once everything is open; the only difference is session-server provides an extra Arena shared among all sessions with the same opposing Client_app (created the first time such a session-client establishes a session); jemalloc::Session_server tracks these Arenas and coordinates with jemalloc::Server_session. So all the in-common stuff is here in this internally-used super-class of the 2 *_impl. The setup procedure is asymmetrical, and the two sides of that asymmetry are in those 2 *_impls – including the differing APIs (e.g., Client_session_impl::sync_connect()).
Template Parameters
Session_impl_t Our base that our sub-class wants to build on-top-of. E.g., Server_session_impl<...>.
Definition at line 59 of file session_impl.hpp.
Member Typedef Documentation
Arena
template<typename Session_impl_t > using ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::Arena = ipc::shm::arena_lend::jemalloc::Ipc_arena
See shm::arena_lend::jemalloc::Session_mv counterpart for public description.
Internally: An arena-lending SHM-provider's arena is simply this. The key is each side (including ours) maintains 1+ (2 on server, 1 on client) such arenas and then all allocations in this process are from there, never from an opposing process. This is in contrast to, in particular, non-arena-lending session::shm::classic::Session_impl::Arena which is symmetrically shared (allocated-in, etc.) by both sides.
Definition at line 79 of file session_impl.hpp.
Base
template<typename Session_impl_t > using ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::Base = Session_impl_t
Short-hand for base class.
Definition at line 65 of file session_impl.hpp.
Blob
template<typename Session_impl_t > using ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::Blob = Shm_session::Blob
Alias for a light-weight blob used in borrow_object() and lend_object().
Definition at line 96 of file session_impl.hpp.
Session_base_obj
template<typename Session_impl_t > using ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::Session_base_obj = typename Base::Session_base_obj
Short-hand for Session_base super-class.
Definition at line 68 of file session_impl.hpp.
Shm_session
template<typename Session_impl_t > using ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::Shm_session = jemalloc::Shm_session
See shm::arena_lend::jemalloc::Session_mv counterpart for public description.
Definition at line 82 of file session_impl.hpp.
Shm_session_ptr
template<typename Session_impl_t > using ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::Shm_session_ptr = std::shared_ptr<Shm_session> protected
How the SHM-provider refers to a Shm_session.
As of this writing publicly they are exclusively available via these handles (I (ygoldfel) believe there might be plans to eliminate this requirement). At any rate, until then, an Shm_session_ptr null state is useful as "not-an-arena-yet" semantic; if indeed the mandatory-ref-counted-handle semantic goes away, this should probably become unique_ptr<Shm_session>.
Definition at line 193 of file session_impl.hpp.
Structured_channel
template<typename Session_impl_t > template<typename Message_body > using ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::Structured_channel = transport::struc::shm::arena_lend::jemalloc::Channel<typename Base::Channel_obj, Message_body>
See shm::arena_lend::jemalloc::Session_mv counterpart for public description.
Definition at line 86 of file session_impl.hpp.
Structured_msg_builder_config
template<typename Session_impl_t > using ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::Structured_msg_builder_config = typename transport::struc::shm::arena_lend::jemalloc::Builder::Config
See shm::arena_lend::jemalloc::Session_mv counterpart for public description.
Definition at line 90 of file session_impl.hpp.
Structured_msg_reader_config
template<typename Session_impl_t > using ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::Structured_msg_reader_config = typename transport::struc::shm::arena_lend::jemalloc::Reader::Config
See shm::arena_lend::jemalloc::Session_mv counterpart for public description.
Definition at line 93 of file session_impl.hpp.
Member Function Documentation
app_shm_reader_config()
template<typename Session_impl_t > Session_impl< Session_impl_t >::Structured_msg_reader_config ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::app_shm_reader_config
See shm::arena_lend::jemalloc::Session_mv counterpart.
Note
app_shm_builder_config() is only in our sub-class Server_session_impl, not Client_session_impl. Yet this app_shm_reader_config() exists in both. Again see the public counterpart for discussion as to why/the exact meaning of app_shm_reader_config() for arena-lending SHM-providers.
Returns
See shm::arena_lend::jemalloc::Session_mv counterpart.
Definition at line 606 of file session_impl.hpp.
borrow_object()
template<typename Session_impl_t > template<typename T > Session_impl< Session_impl_t >::Arena::template Handle< T > ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::borrow_object (const Blob & serialization)
See shm::arena_lend::jemalloc::Session_mv counterpart.
Parameters
serialization See shm::arena_lend::jemalloc::Session_mv counterpart.
Returns
See shm::arena_lend::jemalloc::Session_mv counterpart.
Definition at line 571 of file session_impl.hpp.
init_shm()
template<typename Session_impl_t > Error_code ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::init_shm (util::Native_handle && local_hndl, const Shared_name & pool_name_fragment_or_empty, const std::shared_ptr< Arena > & app_shm_or_null = {}) protected
To be invoked at most once, synchronously sets up nearly-all aspects of this arena-lending-SHM-capable Session; the prerequisite from sub-class _impl being that the possibly-asynchronous steps leading up to this have been completed successfully.
Namely the arg local_hndl is the local half of the connected socket-pair created by the server as needed to create the internal-use IPC channel for the SHM-provider; and
Client_session_impl: it has async-received this item, after opposing Server_session_impl generated it;
Server_session_impl: it has generated it and successfully sent the other (of 2) handle to opposing Client_session_impl.
That says "nearly-all aspects." That is because Server_session_impl must do one extra thing; namely also create the .app_shm()-returned Arena and pass that to us as app_shm_or_null.
Parameters
local_hndl See above. Must not be .null(); else behavior undefined (assertion may trip). local_hndl becomes .null() at exit. Regardless of init_shm() success or failure, it shall ensure return of the contained native handle to the OS at the proper time (the caller can rest easy).
pool_name_fragment_or_empty Function that shall help compute SHM-pool names as needed by the SHM-provider. In particular the final absolute pool name, for each pool, shall be /P/X/R, where P and R will be determined by *this internally; while X – which shall exclude the leading and trailing util::Shared_name::S_SEPARATOR (represented as forward-slash in this explanation) – is supplied in pool_name_fragment_or_empty. If the arg is .empty(), then the /X/ part shall be omitted. Rationale: for cleanup purposes Client_session_impl needs to encode certain info (spoiler alert: session-client process ID) that can be later parsed-out upon performing a for_each_persistent() (spoiler alert: directory-listing of /dev/shm in Linux at least). More generally perhaps other info could be encoded there so as to be acquired from an existing pool-name later. So this here provides the opportunity for our sub-classes to do that.
app_shm_or_null See above. It'll be registered with shm_session() unless null.
Returns
Whether it was successful (creation of, at least, the Arena may fail); falsy if so, the reason describing failure if not. In the former case, post-conditions: session_shm() and shm_session() are not null.
Definition at line 269 of file session_impl.hpp.
References ipc::session::build_conventional_shared_name(), ipc::util::Shared_name::ct(), ipc::util::Shared_name::empty(), ipc::transport::asio_local_stream_socket::release_native_peer_socket(), ipc::util::Shared_name::S_RESOURCE_TYPE_ID_SHM, ipc::transport::struc::Channel_base::S_SERIALIZE_VIA_HEAP, ipc::session::shm::arena_lend::jemalloc::error::S_SHM_ARENA_CREATION_FAILED, ipc::session::shm::arena_lend::jemalloc::error::S_SHM_ARENA_LEND_FAILED, ipc::util::shared_resource_permissions(), ipc::session::shm::arena_lend::jemalloc::SHM_SUBTYPE_PREFIX, and ipc::util::Shared_name::str().
lend_object()
template<typename Session_impl_t > template<typename T > Session_impl< Session_impl_t >::Blob ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::lend_object (const typename Arena::template Handle< T > & handle)
See shm::arena_lend::jemalloc::Session_mv counterpart.
Parameters
handle See shm::arena_lend::jemalloc::Session_mv counterpart.
Returns
See shm::arena_lend::jemalloc::Session_mv counterpart.
Definition at line 563 of file session_impl.hpp.
reset_shm()
template<typename Session_impl_t > void ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::reset_shm protected
Undoes init_shm_arenas(), namely destroying shm_session() pointee and session_shm() pointee.
Note that any other arena (perhaps Server_session_impl::app_shm() pointee?) registered with shm_session() continues to exist; just objects from it cannot be lend_object()ed through that shm_session() anymore (but may well be lendable through other sessions – to other processes).
Intended as of this writing as a one-time resource clean in case of subsequent failure.
Definition at line 535 of file session_impl.hpp.
session_shm()
template<typename Session_impl_t > Session_impl< Session_impl_t >::Arena * ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::session_shm
See shm::arena_lend::jemalloc::Session_mv counterpart.
Note
app_shm() is only in our sub-class Server_session_impl, not Client_session_impl.
Returns
See shm::arena_lend::jemalloc::Session_mv counterpart.
Definition at line 543 of file session_impl.hpp.
session_shm_builder_config()
template<typename Session_impl_t > Session_impl< Session_impl_t >::Structured_msg_builder_config ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::session_shm_builder_config
See shm::arena_lend::jemalloc::Session_mv counterpart.
Returns
See shm::arena_lend::jemalloc::Session_mv counterpart.
Definition at line 578 of file session_impl.hpp.
session_shm_lender_session()
template<typename Session_impl_t > Session_impl< Session_impl_t >::Structured_msg_builder_config::Builder::Session ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::session_shm_lender_session
See shm::arena_lend::jemalloc::Session_mv counterpart.
Returns
See shm::arena_lend::jemalloc::Session_mv counterpart.
Definition at line 585 of file session_impl.hpp.
session_shm_ptr()
template<typename Session_impl_t > std::shared_ptr< typename Session_impl< Session_impl_t >::Arena > ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::session_shm_ptr
See shm::arena_lend::jemalloc::Session_mv counterpart.
Returns
See shm::arena_lend::jemalloc::Session_mv counterpart.
Definition at line 549 of file session_impl.hpp.
session_shm_reader_config()
template<typename Session_impl_t > Session_impl< Session_impl_t >::Structured_msg_reader_config ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::session_shm_reader_config
See shm::arena_lend::jemalloc::Session_mv counterpart.
Returns
See shm::arena_lend::jemalloc::Session_mv counterpart.
Definition at line 599 of file session_impl.hpp.
shm_reader_config()
template<typename Session_impl_t > Session_impl< Session_impl_t >::Structured_msg_reader_config ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::shm_reader_config
See shm::arena_lend::jemalloc::Session_mv counterpart.
Returns
See shm::arena_lend::jemalloc::Session_mv counterpart.
Definition at line 592 of file session_impl.hpp.
shm_session()
template<typename Session_impl_t > Session_impl< Session_impl_t >::Shm_session * ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::shm_session
See shm::arena_lend::jemalloc::Session_mv counterpart.
Returns
See shm::arena_lend::jemalloc::Session_mv counterpart.
Definition at line 555 of file session_impl.hpp.
Friends And Related Function Documentation
operator<<()
template<typename Session_impl_t > std::ostream & operator<< (std::ostream & os, const Session_impl< Session_impl_t > & val) related
Prints string representation of the given Session_impl to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 612 of file session_impl.hpp.
Member Data Documentation
m_session_shm
template<typename Session_impl_t > std::shared_ptr<Arena> ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::m_session_shm private
See session_shm(). This becomes non-null in init_shm().
Definition at line 248 of file session_impl.hpp.
m_shm_channel
template<typename Session_impl_t > std::optional<typename Shm_session::Shm_channel> ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::m_shm_channel private
Internal-use transport::struc::Channel for m_shm_session. null <=> m_shm_session is null.
Definition at line 251 of file session_impl.hpp.
m_shm_session
template<typename Session_impl_t > Shm_session_ptr ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::m_shm_session private
See shm_session(). This becomes non-null in init_shm().
Definition at line 254 of file session_impl.hpp.
The documentation for this class was generated from the following files:
session/detail/shm/arena_lend/jemalloc/jemalloc_fwd.hpp
session/detail/shm/arena_lend/jemalloc/session_impl.hpp