Flow-IPC: ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle > Class Template Reference
ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle > Class Template Reference
Internal, non-movable pImpl-lite implementation of sync_io::Blob_stream_mq_receiver class template.
#include <blob_stream_mq_rcv_impl.hpp>
Classes
struct User_request
Identical to sync_io::Async_adapter_receiver::User_request, except we only keep at most 1 of these and thus don't need a Ptr alias inside; and we need not worry about transmitting Native_handles.
Public Types
using Base = Blob_stream_mq_base_impl< Persistent_mq_handle >
Short-hand for our base with static goodies at least.
using Mq = typename Base::Mq
Short-hand for template arg for underlying MQ handle type.
Public Types inherited from ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle >
using Mq = Persistent_mq_handle
Short-hand for template arg for underlying MQ handle type.
using Auto_closing_mq = boost::movelib::unique_ptr< Mq, Function< void(Mq *)> >
Persistent_mq_handle holder that takes a deleter lambda on construction, intended here to perform additional deinit steps in addition to closing the Mq by deleting it.
Public Member Functions
Blob_stream_mq_receiver_impl (flow::log::Logger *logger_ptr, util::String_view nickname_str, Mq &&mq_moved, Error_code *err_code)
See Blob_stream_mq_receiver counterpart.
~Blob_stream_mq_receiver_impl ()
See Blob_stream_mq_receiver counterpart.
template<typename Create_ev_wait_hndl_func >
bool replace_event_wait_handles (const Create_ev_wait_hndl_func &create_ev_wait_hndl_func)
See Blob_stream_mq_receiver counterpart.
size_t receive_blob_max_size () const
See Blob_stream_mq_receiver counterpart, but assuming PEER state.
bool start_receive_blob_ops (util::sync_io::Event_wait_func &&ev_wait_func)
See Blob_stream_mq_receiver counterpart.
template<typename Task_err_sz >
bool async_receive_blob (const util::Blob_mutable &target_blob, Error_code *sync_err_code, size_t *sync_sz, Task_err_sz &&on_done_func)
See Blob_stream_mq_receiver counterpart, but assuming PEER state.
bool idle_timer_run (util::Fine_duration timeout)
See Blob_stream_mq_receiver counterpart, but assuming PEER state.
const std::string & nickname () const
See Blob_stream_mq_receiver counterpart, but assuming PEER state.
const Shared_name & absolute_name () const
See Blob_stream_mq_receiver counterpart, but assuming PEER state.
Private Types
using Control_cmd = typename Base::Control_cmd
Short-hand for Blob_stream_mq_base_impl::Control_cmd.
Private Member Functions
void on_ev_idle_timer_fired ()
Handler for the async-wait, via util::sync_io::Timer_event_emitter, of the idle timer firing; if still relevant it records the idle-timeout error in m_pending_err_code; and if an async_receive_blob() is in progress (awaiting data via async-wait), it completes that operation with the appropriate idle-timeout error (completion handler in m_user_request runs synchronously).
void not_idle ()
No-ops if idle_timer_run() is not engaged; otherwise reacts to non-idleness of the in-pipe by rescheduling idle timer to occur in m_idle_timeout again.
void read_msg (Error_code *sync_err_code, size_t *sync_sz)
Begins read chain (completing it as synchronously as possible, async-completing the rest) for the next in-message.
bool op_started (util::String_view context) const
Helper that returns true silently if start_*_ops() has been called; else logs WARNING and returns false.
Private Attributes
const std::string m_nickname
See nickname().
Protocol_negotiator m_protocol_negotiator
Handles the protocol negotiation at the start of the pipe and subsequently stores the result of that negotiation.
const Shared_name m_absolute_name
See absolute_name().
std::optional< flow::util::Task_engine > m_nb_task_engine
The Task_engine for m_mq_ready_*.
flow::util::Task_engine m_ev_hndl_task_engine_unused
The Task_engine for m_ev_wait_hndl_*, unless it is replaced via replace_event_wait_handles().
Base::Auto_closing_mq m_mq
The MQ handle adopted by the ctor, through which nb-receives and blocking-waits are executed.
const size_t m_mq_max_msg_sz
Equals m_mq.max_msg_size().
std::optional< util::Pipe_reader > m_mq_ready_reader
Read-end of IPC-pipe used by thread U to detect that a thread-W transmissibility-wait has completed, meaning would-block has cleared, and therefore thread U can attempt to nb-transmit again.
std::optional< util::Pipe_writer > m_mq_ready_writer
Write-end of IPC-pipe used by thread W to inform thread U that a thread-W transmissibility-wait has completed, meaning would-block has cleared, and therefore thread U can attempt to nb-transmit again.
util::sync_io::Asio_waitable_native_handle m_ev_wait_hndl_mq
Descriptor waitable by outside event loop async-waits – storing the same Native_handle as (and thus being used to wait on events from) m_mq_ready_reader; or if m_mq can be watched directly (known at compile-time) then as m_mq itself.
util::sync_io::Timer_event_emitter m_timer_worker
As typical in timer-needing sync_io-pattern-implementing objects, maintains a thread exclusively for Timer wait completion handlers which ferry timer-fired events to internal IPC-mechanisms waitable by the sync_io-pattern-using outside event loop.
std::optional< User_request > m_user_request
Null if no async_receive_blob()` is currently pending; else describes the arguments to that pending async_receive_blob().
bool m_control_state
At steady-state false, becomes true if a low-level "escape" payload (empty message) was last received meaning the next message will be the encoding of a Control_cmd enumeration value, receiving which shall reset this to false.
flow::util::Blob m_target_control_blob
Used only when m_control_state is true, this is where payload 2 (the Control_cmd) is placed.
Error_code m_pending_err_code
The first and only MQ-hosing error condition detected when attempting to low-level-read on m_mq; or falsy if no such error has yet been detected.
util::Fine_duration m_idle_timeout
timeout from idle_timer_run() args; or zero() if not yet called.
flow::util::Timer m_idle_timer
Timer that fires on_ev_idle_timer_fired() (which hoses the pipe with idle timeour error) and is (re)scheduled to fire in m_idle_timeout each time *this receives a complete message on m_mq.
util::sync_io::Timer_event_emitter::Timer_fired_read_end * m_idle_timer_fired_peer
Read-end of IPC-mechanism used by m_timer_worker to ferry timer-fired events from m_idle_timer to sync_io outside async-wait to our actual on-timer-fired handler logic.
util::sync_io::Asio_waitable_native_handle m_ev_wait_hndl_idle_timer_fired_peer
Descriptor waitable by outside event loop async-waits – storing the same Native_handle as (and thus being used to wait on events from) m_idle_timer_fired_peer.
util::sync_io::Event_wait_func m_ev_wait_func
Function (set forever in start_receive_blob_ops()) through which we invoke the outside event loop's async-wait facility for descriptors/events relevant to our ops.
std::optional< flow::async::Single_thread_task_loop > m_blocking_worker
Worker thread W always in one of 2 states: idle; or (when m_mq is in would-block condition) executing an indefinite, interrupting blocking wait for transmissibility of m_mq.
Related Functions
(Note that these are not member functions.)
template<typename Persistent_mq_handle >
std::ostream & operator<< (std::ostream &os, const Blob_stream_mq_receiver_impl< Persistent_mq_handle > &val)
Prints string representation of the given Blob_stream_mq_receiver_impl to the given ostream.
Additional Inherited Members
Static Public Member Functions inherited from ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle >
static void remove_persistent (flow::log::Logger *logger_ptr, const Shared_name &name, Error_code *err_code)
See Blob_stream_mq_base counterpart.
template<typename Handle_name_func >
static void for_each_persistent (const Handle_name_func &handle_name_func)
See Blob_stream_mq_base counterpart.
static Auto_closing_mq ensure_unique_peer (flow::log::Logger *logger_ptr, Mq &&mq, bool snd_else_rcv, Error_code *err_code)
Internal helper for Blob_stream_mq_sender and Blob_stream_mq_receiver that operates both the start and end of the anti-dupe-endpoint machinery used by those 2 classes to prevent more than 1 _sender and more than 1 _receiver for a given underlying MQ.
Protected Types inherited from ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle >
enum class Control_cmd : int64_t { S_END_SENDING , S_PING , S_END_SENTINEL }
If Blob_stream_mq_sender_impl sends an empty message, in NORMAL state Blob_stream_mq_receiver enters CONTROL state and expects one of these values in the next message, to react as documented per enum value (upon re-entering NORMAL state).
Detailed Description
template<typename Persistent_mq_handle>
class ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >
Internal, non-movable pImpl-lite implementation of sync_io::Blob_stream_mq_receiver class template.
In and of itself it would have been directly and publicly usable; however Blob_stream_mq_receiver adds move semantics which are essential to cooperation with the rest of the API, Channel in particular.
See also
All discussion of the public API is in Blob_stream_mq_receiver doc header; that class template forwards to this one. All discussion of pImpl-lite-related notions is also there. See that doc header first please. Then come back here.
Impl design
See sync_io::Blob_stream_mq_sender_impl. The same notes apply. That isn't to say our algorithm is the same at all: we are receiving; they are sending. However, obviously, they speak the same protocol. And beyond that it is again about (1) understanding the sync_io pattern (util::sync_io doc header) and (2) jumping into the code.
Again, for that last part, we recommend starting with the data member doc headers.
Protocol negotiation
Do see the same-named section in sync_io::Blob_stream_mq_sender_impl doc header. Naturally again we're mirroring the same protocol; but we're receiving; they're sending. Due to the latter difference, though, a couple additional notes:
We are the guy receiving the preceding-all-messages message containing the opposing side's preferred (highest) protocol version. As of this writing we only speak v1, but they might speak a range – including or excluding it. However our Protocol_negotiator takes care of all that; and we only need to add logic to emit fatal error, if Protocol_negotiator reports that we're incompatible with opposing side.
Having gotten past that without error, we simply then speak the only version we know how (v1).
Since only protocol v1 exists as of this writing, there's no need yet for an API to signal a partner MQ-sender object of the negotiated protocol version, once we have it. As noted in sync_io::Blob_stream_mq_sender_impl doc header, that may change in the future.
Note
We suggest that if version 2, etc., is/are added, then the above notes be kept more or less intact; then add updates to show changes. This will provide a good overview of how the protocol evolved; and our backwards-compatibility story (even if we decide to have no backwards-compatibility).
Template Parameters
Persistent_mq_handle See Persistent_mq_handle concept doc header.
Definition at line 71 of file blob_stream_mq_rcv_impl.hpp.
Member Typedef Documentation
Base
template<typename Persistent_mq_handle > using ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::Base = Blob_stream_mq_base_impl<Persistent_mq_handle>
Short-hand for our base with static goodies at least.
Definition at line 80 of file blob_stream_mq_rcv_impl.hpp.
Control_cmd
template<typename Persistent_mq_handle > using ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::Control_cmd = typename Base::Control_cmd private
Short-hand for Blob_stream_mq_base_impl::Control_cmd.
Definition at line 194 of file blob_stream_mq_rcv_impl.hpp.
Mq
template<typename Persistent_mq_handle > using ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::Mq = typename Base::Mq
Short-hand for template arg for underlying MQ handle type.
Definition at line 83 of file blob_stream_mq_rcv_impl.hpp.
Constructor & Destructor Documentation
Blob_stream_mq_receiver_impl()
template<typename Persistent_mq_handle > ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::Blob_stream_mq_receiver_impl (flow::log::Logger * logger_ptr, util::String_view nickname_str, Mq && mq_moved, Error_code * err_code) explicit
See Blob_stream_mq_receiver counterpart.
Parameters
logger_ptr See Blob_stream_mq_receiver counterpart.
mq_moved See Blob_stream_mq_receiver counterpart.
nickname_str See Blob_stream_mq_receiver counterpart.
err_code See Blob_stream_mq_receiver counterpart.
Definition at line 476 of file blob_stream_mq_rcv_impl.hpp.
References ipc::util::sync_io::Asio_waitable_native_handle::assign(), ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle >::ensure_unique_peer(), ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_blocking_worker, ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_ev_wait_hndl_mq, ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_mq, ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_mq_ready_reader, ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_mq_ready_writer, ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_nb_task_engine, ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_pending_err_code, and ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::nickname().
~Blob_stream_mq_receiver_impl()
template<typename Persistent_mq_handle > ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::~Blob_stream_mq_receiver_impl
See Blob_stream_mq_receiver counterpart.
Definition at line 575 of file blob_stream_mq_rcv_impl.hpp.
Member Function Documentation
absolute_name()
template<typename Persistent_mq_handle > const Shared_name & ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::absolute_name
See Blob_stream_mq_receiver counterpart, but assuming PEER state.
Returns
See Blob_stream_mq_receiver counterpart.
Definition at line 1242 of file blob_stream_mq_rcv_impl.hpp.
Referenced by ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::operator<<().
async_receive_blob()
template<typename Persistent_mq_handle > template<typename Task_err_sz > bool ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::async_receive_blob (const util::Blob_mutable & target_blob, Error_code * sync_err_code, size_t * sync_sz, Task_err_sz && on_done_func)
See Blob_stream_mq_receiver counterpart, but assuming PEER state.
Parameters
target_blob See Blob_stream_mq_receiver counterpart.
sync_err_code See Blob_stream_mq_receiver counterpart.
sync_sz See Blob_stream_mq_receiver counterpart.
on_done_func See Blob_stream_mq_receiver counterpart.
Returns
See Blob_stream_mq_receiver counterpart.
Definition at line 667 of file blob_stream_mq_rcv_impl.hpp.
References ipc::transport::error::S_INVALID_ARGUMENT, and ipc::transport::error::S_SYNC_IO_WOULD_BLOCK.
idle_timer_run()
template<typename Persistent_mq_handle > bool ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::idle_timer_run (util::Fine_duration timeout)
See Blob_stream_mq_receiver counterpart, but assuming PEER state.
Parameters
timeout See Blob_stream_mq_receiver counterpart.
Returns
See Blob_stream_mq_receiver counterpart.
Definition at line 777 of file blob_stream_mq_rcv_impl.hpp.
nickname()
template<typename Persistent_mq_handle > const std::string & ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::nickname
See Blob_stream_mq_receiver counterpart, but assuming PEER state.
Returns
See Blob_stream_mq_receiver counterpart.
Definition at line 1248 of file blob_stream_mq_rcv_impl.hpp.
Referenced by ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::Blob_stream_mq_receiver_impl(), and ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::operator<<().
not_idle()
template<typename Persistent_mq_handle > void ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::not_idle private
No-ops if idle_timer_run() is not engaged; otherwise reacts to non-idleness of the in-pipe by rescheduling idle timer to occur in m_idle_timeout again.
(Other code calls this, as of this writing, on receipt of a complete message.)
Note that this can only occur while an async_receive_blob() is in progress; as otherwise we will not be reading the low-level pipe at all. This is a requirement for using idle_timer_run(), so it's not our fault, if they don't do it and get timed-out.
Definition at line 869 of file blob_stream_mq_rcv_impl.hpp.
on_ev_idle_timer_fired()
template<typename Persistent_mq_handle > void ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::on_ev_idle_timer_fired private
Handler for the async-wait, via util::sync_io::Timer_event_emitter, of the idle timer firing; if still relevant it records the idle-timeout error in m_pending_err_code; and if an async_receive_blob() is in progress (awaiting data via async-wait), it completes that operation with the appropriate idle-timeout error (completion handler in m_user_request runs synchronously).
If not still relevant – m_pending_err_code already is truthy – then no-ops.
Definition at line 834 of file blob_stream_mq_rcv_impl.hpp.
References ipc::transport::error::S_RECEIVER_IDLE_TIMEOUT.
op_started()
template<typename Persistent_mq_handle > bool ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::op_started (util::String_view context) const private
Helper that returns true silently if start_*_ops() has been called; else logs WARNING and returns false.
Parameters
context For logging: the algorithmic context (function name or whatever).
Returns
See above.
Definition at line 652 of file blob_stream_mq_rcv_impl.hpp.
read_msg()
template<typename Persistent_mq_handle > void ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::read_msg (Error_code * sync_err_code, size_t * sync_sz) private
Begins read chain (completing it as synchronously as possible, async-completing the rest) for the next in-message.
Given the pre-condition that (1) async_receive_blob() is oustanding (m_user_request not null), (2) in the pipe we expect payload 1 (of 1 or 2) of the next in-message next, (3) there is no known pipe error already detected, and (4) there is no known would-block condition on the in-pipe: this reads (asynchronously if would-block is encountered at some point in there) the next message.
Parameters
sync_err_code Outcome out-arg: error::Code::S_SYNC_IO_WOULD_BLOCK if async-wait triggered, as message could not be fully read synchronously; falsy if message fully read synchronously; non-would-block truthy value, if pipe-hosing condition encountered.
sync_sz Outcome out-arg: If *sync_err_code truthy then zero; else size of completed in-message.
Definition at line 905 of file blob_stream_mq_rcv_impl.hpp.
References ipc::util::pipe_consume(), ipc::util::pipe_produce(), ipc::transport::error::S_BLOB_STREAM_MQ_RECEIVER_BAD_CTL_CMD, ipc::transport::error::S_INTERRUPTED, ipc::transport::error::S_RECEIVES_FINISHED_CANNOT_RECEIVE, ipc::transport::error::S_SYNC_IO_WOULD_BLOCK, and ipc::transport::Protocol_negotiator::S_VER_UNKNOWN.
receive_blob_max_size()
template<typename Persistent_mq_handle > size_t ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::receive_blob_max_size
See Blob_stream_mq_receiver counterpart, but assuming PEER state.
Returns
See Blob_stream_mq_receiver counterpart.
Definition at line 1236 of file blob_stream_mq_rcv_impl.hpp.
replace_event_wait_handles()
template<typename Persistent_mq_handle > template<typename Create_ev_wait_hndl_func > bool ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::replace_event_wait_handles (const Create_ev_wait_hndl_func & create_ev_wait_hndl_func)
See Blob_stream_mq_receiver counterpart.
Template Parameters
Create_ev_wait_hndl_func See Blob_stream_mq_receiver counterpart.
Parameters
create_ev_wait_hndl_func See Blob_stream_mq_receiver counterpart.
Returns
See Blob_stream_mq_receiver counterpart.
Definition at line 594 of file blob_stream_mq_rcv_impl.hpp.
References ipc::util::Native_handle::m_native_handle.
start_receive_blob_ops()
template<typename Persistent_mq_handle > bool ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::start_receive_blob_ops (util::sync_io::Event_wait_func && ev_wait_func)
See Blob_stream_mq_receiver counterpart.
Parameters
ev_wait_func See Blob_stream_mq_receiver counterpart.
Returns
See Blob_stream_mq_receiver counterpart.
Definition at line 634 of file blob_stream_mq_rcv_impl.hpp.
Friends And Related Function Documentation
operator<<()
template<typename Persistent_mq_handle > std::ostream & operator<< (std::ostream & os, const Blob_stream_mq_receiver_impl< Persistent_mq_handle > & val) related
Prints string representation of the given Blob_stream_mq_receiver_impl to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 1254 of file blob_stream_mq_rcv_impl.hpp.
References ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::absolute_name(), and ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::nickname().
Member Data Documentation
m_absolute_name
template<typename Persistent_mq_handle > const Shared_name ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_absolute_name private
See absolute_name().
Definition at line 261 of file blob_stream_mq_rcv_impl.hpp.
m_blocking_worker
template<typename Persistent_mq_handle > std::optional<flow::async::Single_thread_task_loop> ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_blocking_worker private
Worker thread W always in one of 2 states: idle; or (when m_mq is in would-block condition) executing an indefinite, interrupting blocking wait for transmissibility of m_mq.
When thread U wants to receive a payload but gets would-block, it issues the wait on this thread W and a sync_io-pattern async-wait for m_ev_wait_hndl_mq; once that wait completes in thread W, it writes a byte to an internal IPC-pipe. m_ev_wait_hndl_mq becomes readable, the outside event loop lets *this know, which completes the async-wait.
In dtor we stop thread W, including using Persistent_mq_handle::interrupt_receives() to abort the indefinite wait in thread W, as it will no longer be used once *this is destroyed.
Ordering: If we want to let things get auto-destroyed without explicit m_blocking_worker->stop() or nullifying wrappers in an explicit order, then this must be declared after m_mq. Otherwise code may still be finishing up in thread W when m_mq is destroyed already. Anyway – as long as this is destroyed or .stop()ed before m_mq is gone, you're cool.
Never touched if Persistent_mq_handle::S_HAS_NATIVE_HANDLE.
Definition at line 468 of file blob_stream_mq_rcv_impl.hpp.
Referenced by ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::Blob_stream_mq_receiver_impl().
m_control_state
template<typename Persistent_mq_handle > bool ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_control_state private
At steady-state false, becomes true if a low-level "escape" payload (empty message) was last received meaning the next message will be the encoding of a Control_cmd enumeration value, receiving which shall reset this to false.
Definition at line 385 of file blob_stream_mq_rcv_impl.hpp.
m_ev_hndl_task_engine_unused
template<typename Persistent_mq_handle > flow::util::Task_engine ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_ev_hndl_task_engine_unused private
The Task_engine for m_ev_wait_hndl_*, unless it is replaced via replace_event_wait_handles().
There are 2 possibilities:
They leave this guy associated with m_ev_wait_hndl_*. Then no one shall be doing .async_wait() on them, and instead the user aims to perhaps use raw [e]poll*() on their .native_handle()s. We still need some Task_engine to construct them though, so we use this.
They use replace_event_wait_handles(), and therefore this becomes dissociated with m_ev_wait_hndl_* and becomes completely unused in any fashion, period. Then they shall probably be doing their own .async_wait() – associated with their own Task_engine – on m_ev_wait_hndl_*.
This is all to fulfill the sync_io pattern.
Definition at line 292 of file blob_stream_mq_rcv_impl.hpp.
m_ev_wait_func
template<typename Persistent_mq_handle > util::sync_io::Event_wait_func ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_ev_wait_func private
Function (set forever in start_receive_blob_ops()) through which we invoke the outside event loop's async-wait facility for descriptors/events relevant to our ops.
See util::sync_io::Event_wait_func doc header for a refresher on this mechanic.
Definition at line 449 of file blob_stream_mq_rcv_impl.hpp.
m_ev_wait_hndl_idle_timer_fired_peer
template<typename Persistent_mq_handle > util::sync_io::Asio_waitable_native_handle ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_ev_wait_hndl_idle_timer_fired_peer private
Descriptor waitable by outside event loop async-waits – storing the same Native_handle as (and thus being used to wait on events from) m_idle_timer_fired_peer.
See also
m_timer_worker for more info.
Definition at line 442 of file blob_stream_mq_rcv_impl.hpp.
m_ev_wait_hndl_mq
template<typename Persistent_mq_handle > util::sync_io::Asio_waitable_native_handle ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_ev_wait_hndl_mq private
Descriptor waitable by outside event loop async-waits – storing the same Native_handle as (and thus being used to wait on events from) m_mq_ready_reader; or if m_mq can be watched directly (known at compile-time) then as m_mq itself.
Its name suggests it's watching m_mq (for transmissibility), and that's true: In the latter case one directly watches it for transmissibility in the proper direction; in the former case Persistent_mq_handle lacks a Native_handle to watch directly – but we use the m_mq_ready_* pipe and a background thread to simulate it having one. Thus in that case m_mq_ready_reader FD = this FD, and it being transmissible = MQ being transmissible.
Definition at line 353 of file blob_stream_mq_rcv_impl.hpp.
Referenced by ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::Blob_stream_mq_receiver_impl().
m_idle_timeout
template<typename Persistent_mq_handle > util::Fine_duration ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_idle_timeout private
timeout from idle_timer_run() args; or zero() if not yet called.
m_idle_timer stays inactive until this becomes not-zero().
Definition at line 414 of file blob_stream_mq_rcv_impl.hpp.
m_idle_timer
template<typename Persistent_mq_handle > flow::util::Timer ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_idle_timer private
Timer that fires on_ev_idle_timer_fired() (which hoses the pipe with idle timeour error) and is (re)scheduled to fire in m_idle_timeout each time *this receives a complete message on m_mq.
If it does fire, without being preempted by some error to have occurred since then, the pipe is hosed with a particular error indicating idle-timeout (so that Error_code is saved to m_pending_err_code).
Since we implement sync_io pattern, the timer is obtained from, and used via, util::sync_io::Timer_event_emitter m_timer_worker. See that member's doc header for more info.
Definition at line 426 of file blob_stream_mq_rcv_impl.hpp.
m_idle_timer_fired_peer
template<typename Persistent_mq_handle > util::sync_io::Timer_event_emitter::Timer_fired_read_end* ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_idle_timer_fired_peer private
Read-end of IPC-mechanism used by m_timer_worker to ferry timer-fired events from m_idle_timer to sync_io outside async-wait to our actual on-timer-fired handler logic.
See also
m_timer_worker for more info.
Definition at line 434 of file blob_stream_mq_rcv_impl.hpp.
m_mq
template<typename Persistent_mq_handle > Base::Auto_closing_mq ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_mq private
The MQ handle adopted by the ctor, through which nb-receives and blocking-waits are executed.
It is not directly protected by any mutex; however it is accessed exclusively as follows:
By thread W, when m_user_request is non-null (would-block state), thus thread U has tasked it with awaiting readability – which it is doing and is not yet done doing.
By thread U, when m_user_request is null (no would-block at the moment); or it is not null, but thread W has signaled it is done awaiting non-would-block, so thread U is trying to nullify it via nb-reads.
Exception: m_mq->interrupt_receives() is done from thread U (dtor), potentially while thread W is inside m_mq->wait_receivable(). However that specific action is allowed by Persistent_mq_handle contract (in fact that is the main utility of Persistent_mq_handle::interrupt_receives()). It makes the Persistent_mq_handle::wait_receivable() immediately return.
If and only if m_pending_err_code is truthy, m_mq is null; hence the handle's system resources (and the handle object's memory itself) are given back at the earliest possible time.
Definition at line 311 of file blob_stream_mq_rcv_impl.hpp.
Referenced by ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::Blob_stream_mq_receiver_impl().
m_mq_max_msg_sz
template<typename Persistent_mq_handle > const size_t ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_mq_max_msg_sz private
Equals m_mq.max_msg_size().
Rationale
It is saved in ctor, instead of invoking m_mq->max_msg_size() when needed, to keep the rules for when m_mq is accessed simple and as described in its doc header. After all this value would never change anyway.
Definition at line 319 of file blob_stream_mq_rcv_impl.hpp.
m_mq_ready_reader
template<typename Persistent_mq_handle > std::optional<util::Pipe_reader> ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_mq_ready_reader private
Read-end of IPC-pipe used by thread U to detect that a thread-W transmissibility-wait has completed, meaning would-block has cleared, and therefore thread U can attempt to nb-transmit again.
The signal byte is read out of m_mq_ready_reader, making it empty again (the steady-state before the next time would-block occurs, and a byte is written to it making it non-empty).
See also
m_mq_ready_writer.
Never touched if Persistent_mq_handle::S_HAS_NATIVE_HANDLE.
Definition at line 331 of file blob_stream_mq_rcv_impl.hpp.
Referenced by ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::Blob_stream_mq_receiver_impl().
m_mq_ready_writer
template<typename Persistent_mq_handle > std::optional<util::Pipe_writer> ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_mq_ready_writer private
Write-end of IPC-pipe used by thread W to inform thread U that a thread-W transmissibility-wait has completed, meaning would-block has cleared, and therefore thread U can attempt to nb-transmit again.
A signal byte is written to m_mq_ready_writer, making it non-empty.
See also
m_mq_ready_reader.
Never touched if Persistent_mq_handle::S_HAS_NATIVE_HANDLE.
Definition at line 342 of file blob_stream_mq_rcv_impl.hpp.
Referenced by ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::Blob_stream_mq_receiver_impl().
m_nb_task_engine
template<typename Persistent_mq_handle > std::optional<flow::util::Task_engine> ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_nb_task_engine private
The Task_engine for m_mq_ready_*.
It is necessary to construct those pipe-end objects, but we never use that guy's ->async_*() APIs – only non-blocking operations, essentially leveraging boost.asio's portable transmission APIs but not its actual, um, async-I/O abilities in this case. Accordingly we never load any tasks onto m_nb_task_engine and certainly never .run() (or .poll() or ...) it.
In the sync_io pattern the user's outside event loop is responsible for awaiting readability/writability of a guy like m_mq_ready_reader via our exporting of its .native_handle().
Never touched if Persistent_mq_handle::S_HAS_NATIVE_HANDLE.
Todo:
Consider using specialization instead of or in addition if constexpr() w/r/t Mq::S_HAS_NATIVE_HANDLE-based compile-time branching: it could save some RAM by eliminating optionals such as the one near this to-do; though code would likely become wordier.
Definition at line 278 of file blob_stream_mq_rcv_impl.hpp.
Referenced by ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::Blob_stream_mq_receiver_impl().
m_nickname
template<typename Persistent_mq_handle > const std::string ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_nickname private
See nickname().
Definition at line 249 of file blob_stream_mq_rcv_impl.hpp.
m_pending_err_code
template<typename Persistent_mq_handle > Error_code ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_pending_err_code private
The first and only MQ-hosing error condition detected when attempting to low-level-read on m_mq; or falsy if no such error has yet been detected.
Among possible other uses, it is emitted to the ongoing-at-the-time async_receive_blob()'s completion handler (if one is indeed outstanding) and immediately to any subsequent async_receive_blob().
Definition at line 408 of file blob_stream_mq_rcv_impl.hpp.
Referenced by ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::Blob_stream_mq_receiver_impl().
m_protocol_negotiator
template<typename Persistent_mq_handle > Protocol_negotiator ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_protocol_negotiator private
Handles the protocol negotiation at the start of the pipe and subsequently stores the result of that negotiation.
See also
Protocol_negotiator doc header for key background on the topic.
Blob_stream_mq_sender_impl::m_protocol_negotiator doc header which contains notes relevant to possible future development of the present class regarding speaking multiple protocol versions.
Definition at line 258 of file blob_stream_mq_rcv_impl.hpp.
m_target_control_blob
template<typename Persistent_mq_handle > flow::util::Blob ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_target_control_blob private
Used only when m_control_state is true, this is where payload 2 (the Control_cmd) is placed.
Though in reality it should only require sizeof(Control_cmd) bytes, m_mq receive will emit an error if it cannot hold m_mq_max_msg_sz bytes (that is just how Persistent_mq_handle works; though we do not care why here the reason is that's how both ipc and POSIX MQ APIs work).
We could also abuse m_user_request m_target_blob; but that seems uncool.
Todo:
Maybe we should indeed use m_user_request->m_target_blob (instead of locally stored m_target_control_blob) to save RAM/a few cycles? Technically at least user should not care if some garbage is temporarily placed there (after PING a real message should arrive and replace it; or else on error or graceful-close who cares?).
Definition at line 400 of file blob_stream_mq_rcv_impl.hpp.
m_timer_worker
template<typename Persistent_mq_handle > util::sync_io::Timer_event_emitter ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_timer_worker private
As typical in timer-needing sync_io-pattern-implementing objects, maintains a thread exclusively for Timer wait completion handlers which ferry timer-fired events to internal IPC-mechanisms waitable by the sync_io-pattern-using outside event loop.
In our case we (optionally) maintain the idle timer.
See also
util::sync_io::Timer_event_emitter doc header for design/rationale discussion.
Definition at line 362 of file blob_stream_mq_rcv_impl.hpp.
m_user_request
template<typename Persistent_mq_handle > std::optional<User_request> ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::m_user_request private
Null if no async_receive_blob()` is currently pending; else describes the arguments to that pending async_receive_blob().
Rationale
It exists for a hopefully obvious reasons: At least a non-immediately-completed async_receive_blob() needs to keep track of the request so as to know where to place results and what completion handler to invoke.
As for it being nullable: this is used to guard against async_receive_*() being invoked while another is already outstanding. We do not queue pending requests per sync_io::Blob_receiver concept. (However the non-sync_io a/k/a async-I/O Blob_receiver transport::Blob_stream_mq_receiver does. Therefore the latter class does internally implement a User_request queue.)
Definition at line 378 of file blob_stream_mq_rcv_impl.hpp.
The documentation for this class was generated from the following files:
transport/detail/transport_fwd.hpp
transport/sync_io/detail/blob_stream_mq_rcv_impl.hpp