Flow-IPC: ipc::transport::Posix_mq_handle Class Reference
ipc::transport::Posix_mq_handle Class Reference
Implements the Persistent_mq_handle concept by wrapping the POSIX message queue API (see man mq_overview).
#include <posix_mq_handle.hpp>
Public Member Functions
Posix_mq_handle ()
Implements Persistent_mq_handle API: Construct null handle.
Posix_mq_handle (flow::log::Logger *logger_ptr, const Shared_name &absolute_name, util::Create_only mode_tag, size_t max_n_msg, size_t max_msg_sz, const util::Permissions &perms=util::Permissions(), Error_code *err_code=0)
Implements Persistent_mq_handle API: Construct handle to non-existing named MQ, creating it first.
Posix_mq_handle (flow::log::Logger *logger_ptr, const Shared_name &absolute_name, util::Open_or_create mode_tag, size_t max_n_msg_on_create, size_t max_msg_sz_on_create, const util::Permissions &perms_on_create=util::Permissions(), Error_code *err_code=0)
Implements Persistent_mq_handle API: Construct handle to existing named MQ, or else if it does not exist creates it first and opens it (atomically).
Posix_mq_handle (flow::log::Logger *logger_ptr, const Shared_name &absolute_name, util::Open_only mode_tag, Error_code *err_code=0)
Implements Persistent_mq_handle API: Construct handle to existing named MQ.
Posix_mq_handle (Posix_mq_handle &&src)
Implements Persistent_mq_handle API: Constructs handle from the source handle while making the latter as-if default-cted.
Posix_mq_handle (const Posix_mq_handle &)=delete
Copying of handles is prohibited, per Persistent_mq_handle concept.
~Posix_mq_handle ()
Implements Persistent_mq_handle API: Destroys this handle (or no-op if no handle was successfully constructed, or if it's a moved-from or default-cted handle).
Posix_mq_handle & operator= (Posix_mq_handle &&src)
Implements Persistent_mq_handle API: Replaces handle with the source handle while making the latter invalid as-if default-cted.
Posix_mq_handle & operator= (const Posix_mq_handle &)=delete
Copying of handles is prohibited, per Persistent_mq_handle concept.
bool try_send (const util::Blob_const &blob, Error_code *err_code=0)
Implements Persistent_mq_handle API: Non-blocking send: pushes copy of message to queue and returns true; if queue is full then no-op and returns false.
void send (const util::Blob_const &blob, Error_code *err_code=0)
Implements Persistent_mq_handle API: Blocking send: pushes copy of message to queue; if queue is full blocks until it is not.
bool timed_send (const util::Blob_const &blob, util::Fine_duration timeout_from_now, Error_code *err_code=0)
Implements Persistent_mq_handle API: Blocking timed send: pushes copy of message to queue; if queue is full blocks until it is not, or the specified time passes, whichever happens first.
bool is_sendable (Error_code *err_code=0)
Implements Persistent_mq_handle API: Like try_send() but without the actual pushing of a message.
void wait_sendable (Error_code *err_code=0)
Implements Persistent_mq_handle API: Like send() but without the actual pushing of a message.
bool timed_wait_sendable (util::Fine_duration timeout_from_now, Error_code *err_code=0)
Implements Persistent_mq_handle API: Like timed_send() but without the actual pushing of a message.
bool try_receive (util::Blob_mutable *blob, Error_code *err_code=0)
Implements Persistent_mq_handle API: Non-blocking receive: pops copy of message from queue into buffer and returns true; if queue is empty then no-op and returns false.
void receive (util::Blob_mutable *blob, Error_code *err_code=0)
Implements Persistent_mq_handle API: Blocking receive: pops copy of message from queue into buffer; if queue is empty blocks until it is not.
bool timed_receive (util::Blob_mutable *blob, util::Fine_duration timeout_from_now, Error_code *err_code=0)
Implements Persistent_mq_handle API: Blocking timed receive: pops copy of message from queue into buffer; if queue is empty blocks until it is not, or the specified time passes, whichever happens first.
bool is_receivable (Error_code *err_code=0)
Implements Persistent_mq_handle API: Like try_receive() but without the actual popping of a message.
void wait_receivable (Error_code *err_code=0)
Implements Persistent_mq_handle API: Like receive() but without the actual popping of a message.
bool timed_wait_receivable (util::Fine_duration timeout_from_now, Error_code *err_code=0)
Implements Persistent_mq_handle API: Like timed_receive() but without the actual popping of a message.
bool interrupt_sends ()
Implements Persistent_mq_handle API: Turn on preemptive/concurrent interruption of blocking-sends and sendable-waits/polls.
bool allow_sends ()
Implements Persistent_mq_handle API: Turn off preemptive/concurrent interruption of blocking-sends and sendable-waits/polls.
bool interrupt_receives ()
Implements Persistent_mq_handle API: Turn on preemptive/concurrent interruption of blocking-receives and receivable-waits/polls.
bool allow_receives ()
Implements Persistent_mq_handle API: Turn off preemptive/concurrent interruption of blocking-receives and receivable-waits/polls.
const Shared_name & absolute_name () const
Implements Persistent_mq_handle API: Returns name equal to absolute_name passed to ctor.
size_t max_msg_size () const
Implements Persistent_mq_handle API: Returns the max message size of the underlying queue.
size_t max_n_msgs () const
Implements Persistent_mq_handle API: Returns the max message count of the underlying queue.
Native_handle native_handle () const
Implements Persistent_mq_handle API: Returns the stored native MQ handle; null if not open.
Static Public Member Functions
static void remove_persistent (flow::log::Logger *logger_ptr, const Shared_name &name, Error_code *err_code=0)
Implements Persistent_mq_handle API: Removes the named persistent MQ.
template<typename Handle_name_func >
static void for_each_persistent (const Handle_name_func &handle_name_func)
Implements Persistent_mq_handle API.
Static Public Attributes
static const Shared_name S_RESOURCE_TYPE_ID = Shared_name::ct("posixQ")
Implements concept API.
static constexpr bool S_HAS_NATIVE_HANDLE = true
Implements concept API. Contrast this value with Bipc_mq_handle::S_HAS_NATIVE_HANDLE.
Private Types
using Pipe_writer = util::Pipe_writer
Short-hand for anonymous pipe write end.
using Pipe_reader = util::Pipe_reader
Short-hand for anonymous pipe read end.
Private Member Functions
template<typename Mode_tag >
Posix_mq_handle (Mode_tag mode_tag, flow::log::Logger *logger_ptr, const Shared_name &absolute_name, size_t max_n_msg_on_create, size_t max_msg_sz_on_create, const util::Permissions &perms_on_create, Error_code *err_code)
Helper ctor delegated by the 2 public ctors that take Open_or_create or Create_only mode.
Error_code pipe_setup ()
Ctor helper that sets up m_interrupt* pipe items.
Error_code epoll_setup ()
Ctor helper that sets up m_epoll_hndl_snd and m_epoll_hndl_rcv.
bool set_non_blocking (bool nb, Error_code *err_code)
Sets m_mq to blocking or non-blocking and returns true on success and clears *err_code; otherwise returns false and sets truthy *err_code.
bool handle_mq_api_result (int result, Error_code *err_code, util::String_view context) const
Helper that handles the result of an mq_*() call by logging WARNING(s) on error; setting *err_code on error; clearing it on success.
template<bool SND_ELSE_RCV>
bool interrupt_impl ()
Impl body for interrupt_*().
template<bool SND_ELSE_RCV>
bool allow_impl ()
Impl body for allow_*().
bool wait_impl (util::Fine_duration timeout_from_now_or_none, bool snd_else_rcv, Error_code *err_code)
Impl body for *_sendable() and *_receivable().
Private Attributes
Native_handle m_mq
Underlying MQ handle.
Shared_name m_absolute_name
See absolute_name().
Native_handle m_epoll_hndl_snd
epoll_*() handle (.null() if and only if m_mq is null) that is level-triggered to be active (with only 1 event registered) if and only if m_mq is currently capable of sending at least 1 message (we could push 1+ messages right now).
Native_handle m_epoll_hndl_rcv
epoll_*() handle (.null() if and only if m_mq is null) that is level-triggered to be active (with only 1 event registered) if and only if m_mq is currently storing at least 1 message (we could pop 1+ messages right now).
bool m_interrupting_snd
Starting at false, this is made true via interrupt_sends(), and back by allow_sends(); acts as a guard against doing it when already in effect.
bool m_interrupting_rcv
Other-direction counterpart to m_interrupting_snd.
flow::util::Task_engine m_nb_task_engine
Never used for .run() or .async() – just so we can construct Pipe_reader, Pipe_writer.
Pipe_writer m_interrupter_snd
A byte is written to this end by interrupt_sends() to make it readable for the poll-wait in wait_impl() indicating that m_interrupting_snd mode is on.
Pipe_reader m_interrupt_detector_snd
A byte is read from this end by allow_sends() to make it not-readable for the poll-wait in wait_impl() indicating that m_interrupting_snd mode is off; and wait_impl() poll-waits on this along with m_mq – if it is readable, then the mode is on.
Pipe_writer m_interrupter_rcv
Other-direction counterpart to m_interrupter_snd.
Pipe_reader m_interrupt_detector_rcv
Other-direction counterpart to m_interrupt_detector_snd.
Friends
void swap (Posix_mq_handle &val1, Posix_mq_handle &val2)
Implements Persistent_mq_handle related concept: Swaps two objects.
Related Functions
(Note that these are not member functions.)
std::ostream & operator<< (std::ostream &os, const Posix_mq_handle &val)
Prints string representation of the given Posix_mq_handle to the given ostream.
void swap (Posix_mq_handle &val1, Posix_mq_handle &val2)
Implements Persistent_mq_handle related concept: Swaps two objects.
Detailed Description
Implements the Persistent_mq_handle concept by wrapping the POSIX message queue API (see man mq_overview).
See also
Persistent_mq_handle: implemented concept.
Reminder: This is available publicly in case it is useful; but it is more likely one would use a Blob_stream_mq_sender or Blob_stream_mq_receiver which provides a far more convenient boost.asio-like async-capable API. It uses class(es) like this one in its impl.
native_handle() returns the underlying MQ descriptor; in Linux (the only OS supported as of this writing) this happens to be an FD; and as an FD it can (according to man mq_overview) participate in epoll/poll/select(). It is simple to wrap this descriptor in a boost.asio posix::descriptor. Having done that, one can async_wait() on it, awaiting writability and readability in async fashion not supported by the Persistent_mq_handle concept. Accordingly Posix_mq_handle::S_HAS_NATIVE_HANDLE is true.
Implementation
I (ygoldfel) wrote this immediately after Bipc_mq_handle. Notably the thing that thinly wraps, bipc::message_queue, appears to be heavily influenced by the POSIX MQ API in terms of its API and functionality. So the implementation here is conceptually similar.
Definition at line 60 of file posix_mq_handle.hpp.
Member Typedef Documentation
Pipe_reader
using ipc::transport::Posix_mq_handle::Pipe_reader = util::Pipe_reader private
Short-hand for anonymous pipe read end.
Definition at line 508 of file posix_mq_handle.hpp.
Pipe_writer
using ipc::transport::Posix_mq_handle::Pipe_writer = util::Pipe_writer private
Short-hand for anonymous pipe write end.
Definition at line 505 of file posix_mq_handle.hpp.
Constructor & Destructor Documentation
Posix_mq_handle() [1/6]
ipc::transport::Posix_mq_handle::Posix_mq_handle ()
Implements Persistent_mq_handle API: Construct null handle.
Definition at line 48 of file posix_mq_handle.cpp.
Posix_mq_handle() [2/6]
ipc::transport::Posix_mq_handle::Posix_mq_handle (flow::log::Logger * logger_ptr, const Shared_name & absolute_name, util::Create_only mode_tag, size_t max_n_msg, size_t max_msg_sz, const util::Permissions & perms = util::Permissions(), Error_code * err_code = 0) explicit
Implements Persistent_mq_handle API: Construct handle to non-existing named MQ, creating it first.
If it already exists, it is an error.
See also
Persistent_mq_handle::Persistent_mq_handle(): implemented concept.
max_n_msg and max_msg_sz are subject to certain OS limits, according to man mq_overview. Watch out for those: we have no control over them here. The man page should give you the necessary information.
Parameters
logger_ptr See above.
absolute_name See above.
mode_tag See above.
perms See above. Reminder: Suggest the use of util::shared_resource_permissions() to translate from one of a small handful of levels of access; these apply almost always in practice.
max_n_msg See above.
max_msg_sz See above.
err_code See above.
Definition at line 284 of file posix_mq_handle.cpp.
Posix_mq_handle() [3/6]
ipc::transport::Posix_mq_handle::Posix_mq_handle (flow::log::Logger * logger_ptr, const Shared_name & absolute_name, util::Open_or_create mode_tag, size_t max_n_msg_on_create, size_t max_msg_sz_on_create, const util::Permissions & perms_on_create = util::Permissions(), Error_code * err_code = 0) explicit
Implements Persistent_mq_handle API: Construct handle to existing named MQ, or else if it does not exist creates it first and opens it (atomically).
See also
Persistent_mq_handle::Persistent_mq_handle(): implemented concept.
Parameters
logger_ptr See above.
absolute_name See above.
mode_tag See above.
perms_on_create See above. Reminder: Suggest the use of util::shared_resource_permissions() to translate from one of a small handful of levels of access; these apply almost always in practice.
max_n_msg_on_create See above.
max_msg_sz_on_create See above.
err_code See above.
Definition at line 292 of file posix_mq_handle.cpp.
Posix_mq_handle() [4/6]
ipc::transport::Posix_mq_handle::Posix_mq_handle (flow::log::Logger * logger_ptr, const Shared_name & absolute_name, util::Open_only mode_tag, Error_code * err_code = 0) explicit
Implements Persistent_mq_handle API: Construct handle to existing named MQ.
If it does not exist, it is an error.
Parameters
logger_ptr See above.
absolute_name See above.
mode_tag See above.
err_code See above.
Definition at line 300 of file posix_mq_handle.cpp.
References absolute_name(), epoll_setup(), m_mq, ipc::util::Native_handle::m_native_handle, ipc::util::Native_handle::null(), pipe_setup(), and set_non_blocking().
Posix_mq_handle() [5/6]
ipc::transport::Posix_mq_handle::Posix_mq_handle (Posix_mq_handle && src)
Implements Persistent_mq_handle API: Constructs handle from the source handle while making the latter as-if default-cted.
Reminder, informally: This is a light-weight op.
See also
Persistent_mq_handle::Persistent_mq_handle(): implemented concept.
Parameters
src See above.
Definition at line 495 of file posix_mq_handle.cpp.
References operator=().
~Posix_mq_handle()
ipc::transport::Posix_mq_handle::~Posix_mq_handle ()
Implements Persistent_mq_handle API: Destroys this handle (or no-op if no handle was successfully constructed, or if it's a moved-from or default-cted handle).
Reminder: The underlying MQ (if any) is not destroyed and can be attached-to by another handle.
See also
Persistent_mq_handle::~Persistent_mq_handle(): implemented concept.
Definition at line 501 of file posix_mq_handle.cpp.
References m_epoll_hndl_rcv, m_epoll_hndl_snd, m_mq, ipc::util::Native_handle::m_native_handle, and ipc::util::Native_handle::null().
Posix_mq_handle() [6/6]
template<typename Mode_tag > ipc::transport::Posix_mq_handle::Posix_mq_handle (Mode_tag mode_tag, flow::log::Logger * logger_ptr, const Shared_name & absolute_name, size_t max_n_msg_on_create, size_t max_msg_sz_on_create, const util::Permissions & perms_on_create, Error_code * err_code) explicit private
Helper ctor delegated by the 2 public ctors that take Open_or_create or Create_only mode.
Template Parameters
Mode_tag Either util::Open_or_create or util::Create_only.
Parameters
logger_ptr See public ctors.
absolute_name See public ctors.
mode_tag See public ctors.
max_n_msg_on_create See public ctors.
max_msg_sz_on_create See public ctors.
perms_on_create See public ctors.
err_code See public ctors.
Definition at line 60 of file posix_mq_handle.cpp.
References absolute_name(), epoll_setup(), m_mq, ipc::util::Native_handle::m_native_handle, ipc::util::Native_handle::null(), pipe_setup(), set_non_blocking(), and ipc::util::set_resource_permissions().
Member Function Documentation
absolute_name()
const Shared_name & ipc::transport::Posix_mq_handle::absolute_name () const
Implements Persistent_mq_handle API: Returns name equal to absolute_name passed to ctor.
Returns
See above.
See also
Persistent_mq_handle::absolute_name(): implemented concept.
Definition at line 1359 of file posix_mq_handle.cpp.
References m_absolute_name.
Referenced by operator<<(), pipe_setup(), Posix_mq_handle(), and remove_persistent().
allow_impl()
template<bool SND_ELSE_RCV> bool ipc::transport::Posix_mq_handle::allow_impl private
Impl body for allow_*().
Template Parameters
SND_ELSE_RCV True for *_sends(), else *_receives().
Returns
See callers.
Definition at line 1120 of file posix_mq_handle.cpp.
References m_interrupt_detector_rcv, m_interrupt_detector_snd, m_interrupting_rcv, m_interrupting_snd, m_mq, ipc::util::Native_handle::null(), and ipc::util::pipe_consume().
allow_receives()
bool ipc::transport::Posix_mq_handle::allow_receives ()
Implements Persistent_mq_handle API: Turn off preemptive/concurrent interruption of blocking-receives and receivable-waits/polls.
See also
Persistent_mq_handle::allow_receives(): implemented concept.
INFO+ logging
WARNING on duplicate use, INFO otherwise.
Returns
See above.
Definition at line 1175 of file posix_mq_handle.cpp.
allow_sends()
bool ipc::transport::Posix_mq_handle::allow_sends ()
Implements Persistent_mq_handle API: Turn off preemptive/concurrent interruption of blocking-sends and sendable-waits/polls.
See also
Persistent_mq_handle::allow_sends(): implemented concept.
INFO+ logging
WARNING on duplicate use, INFO otherwise.
Returns
See above.
Definition at line 1165 of file posix_mq_handle.cpp.
epoll_setup()
Error_code ipc::transport::Posix_mq_handle::epoll_setup () private
Ctor helper that sets up m_epoll_hndl_snd and m_epoll_hndl_rcv.
If it fails it returns truthy code and puts everything back to as-if-ctor-failed state, including m_mq being null.
Returns
See above.
Definition at line 404 of file posix_mq_handle.cpp.
References m_epoll_hndl_rcv, m_epoll_hndl_snd, m_interrupt_detector_rcv, m_interrupt_detector_snd, m_interrupter_rcv, m_interrupter_snd, m_mq, and ipc::util::Native_handle::m_native_handle.
Referenced by Posix_mq_handle().
for_each_persistent()
template<typename Handle_name_func > void ipc::transport::Posix_mq_handle::for_each_persistent (const Handle_name_func & handle_name_func) static
Implements Persistent_mq_handle API.
Impl note for exposition: we use the fact that, e.g., in Linux the POSIX MQ devices are listed in flat fashion in /dev/mqueue.
See also
Persistent_mq_handle::for_each_persistent(): implemented concept.
Template Parameters
Handle_name_func See above.
Parameters
handle_name_func See above.
Definition at line 683 of file posix_mq_handle.hpp.
References ipc::util::for_each_persistent_impl().
handle_mq_api_result()
bool ipc::transport::Posix_mq_handle::handle_mq_api_result (int result, Error_code * err_code, util::String_view context) const private
Helper that handles the result of an mq_*() call by logging WARNING(s) on error; setting *err_code on error; clearing it on success.
errno is presumably set by the native API on error going into this.
Parameters
result What the native API returned.
err_code To set. If null behavior is undefined (assertion may trip).
context See Bipc_mq_handle::op_with_possible_bipc_mq_exception().
Returns
true if *err_code was set to success (falsy); else false (it was set to truthy).
Definition at line 1337 of file posix_mq_handle.cpp.
References ipc::transport::error::S_MQ_MESSAGE_SIZE_OVER_OR_UNDERFLOW.
Referenced by max_msg_size(), max_n_msgs(), receive(), send(), set_non_blocking(), timed_receive(), timed_send(), try_receive(), and try_send().
interrupt_impl()
template<bool SND_ELSE_RCV> bool ipc::transport::Posix_mq_handle::interrupt_impl private
Impl body for interrupt_*().
Template Parameters
SND_ELSE_RCV True for *_sends(), else *_receives().
Returns
See callers.
Definition at line 1081 of file posix_mq_handle.cpp.
References m_interrupter_rcv, m_interrupter_snd, m_interrupting_rcv, m_interrupting_snd, m_mq, ipc::util::Native_handle::null(), and ipc::util::pipe_produce().
interrupt_receives()
bool ipc::transport::Posix_mq_handle::interrupt_receives ()
Implements Persistent_mq_handle API: Turn on preemptive/concurrent interruption of blocking-receives and receivable-waits/polls.
See also
Persistent_mq_handle::interrupt_receives(): implemented concept.
INFO+ logging
WARNING on duplicate use, INFO otherwise.
Returns
See above.
Definition at line 1170 of file posix_mq_handle.cpp.
interrupt_sends()
bool ipc::transport::Posix_mq_handle::interrupt_sends ()
Implements Persistent_mq_handle API: Turn on preemptive/concurrent interruption of blocking-sends and sendable-waits/polls.
See also
Persistent_mq_handle::interrupt_sends(): implemented concept.
INFO+ logging
WARNING on duplicate use, INFO otherwise.
Returns
See above.
Definition at line 1160 of file posix_mq_handle.cpp.
is_receivable()
bool ipc::transport::Posix_mq_handle::is_receivable (Error_code * err_code = 0)
Implements Persistent_mq_handle API: Like try_receive() but without the actual popping of a message.
See also
Persistent_mq_handle::is_receivable(): implemented concept.
INFO+ logging
WARNING on error.
Parameters
err_code See above.
Returns
See above.
Definition at line 1286 of file posix_mq_handle.cpp.
References wait_impl().
is_sendable()
bool ipc::transport::Posix_mq_handle::is_sendable (Error_code * err_code = 0)
Implements Persistent_mq_handle API: Like try_send() but without the actual pushing of a message.
See also
Persistent_mq_handle::is_sendable(): implemented concept.
INFO+ logging
WARNING on error.
Parameters
err_code See above.
Returns
See above.
Definition at line 1271 of file posix_mq_handle.cpp.
References wait_impl().
max_msg_size()
size_t ipc::transport::Posix_mq_handle::max_msg_size () const
Implements Persistent_mq_handle API: Returns the max message size of the underlying queue.
Reminder: This is not required to match was was passed to Create_only or Open_or_create ctor.
Returns
See above.
See also
Persistent_mq_handle::max_msg_size(): implemented concept.
Definition at line 616 of file posix_mq_handle.cpp.
References handle_mq_api_result(), m_mq, ipc::util::Native_handle::m_native_handle, and ipc::util::Native_handle::null().
max_n_msgs()
size_t ipc::transport::Posix_mq_handle::max_n_msgs () const
Implements Persistent_mq_handle API: Returns the max message count of the underlying queue.
Reminder: This is not required to match was was passed to Create_only or Open_or_create ctor.
Returns
See above.
See also
Persistent_mq_handle::max_n_msgs(): implemented concept.
Definition at line 641 of file posix_mq_handle.cpp.
References handle_mq_api_result(), m_mq, ipc::util::Native_handle::m_native_handle, and ipc::util::Native_handle::null().
native_handle()
Native_handle ipc::transport::Posix_mq_handle::native_handle () const
Implements Persistent_mq_handle API: Returns the stored native MQ handle; null if not open.
Returns
See above.
See also
Persistent_mq_handle::native_handle(): implemented concept.
Definition at line 1301 of file posix_mq_handle.cpp.
References m_mq.
Referenced by operator<<().
operator=()
Posix_mq_handle & ipc::transport::Posix_mq_handle::operator= (Posix_mq_handle && src)
Implements Persistent_mq_handle API: Replaces handle with the source handle while making the latter invalid as-if default-cted.
Reminder, informally: this is a light-weight op.
Parameters
src See above.
Returns
*this.
Definition at line 525 of file posix_mq_handle.cpp.
References ipc::util::Shared_name::clear(), m_absolute_name, m_epoll_hndl_rcv, m_epoll_hndl_snd, m_interrupt_detector_rcv, m_interrupt_detector_snd, m_interrupter_rcv, m_interrupter_snd, m_mq, m_nb_task_engine, ipc::transport::swap(), and swap.
Referenced by Posix_mq_handle().
pipe_setup()
Error_code ipc::transport::Posix_mq_handle::pipe_setup () private
Ctor helper that sets up m_interrupt* pipe items.
If it fails it returns truthy code and cleans up what it did. It ignores everything else like m_mq.
Returns
See above.
Definition at line 377 of file posix_mq_handle.cpp.
References absolute_name(), m_interrupt_detector_rcv, m_interrupt_detector_snd, m_interrupter_rcv, and m_interrupter_snd.
Referenced by Posix_mq_handle().
receive()
void ipc::transport::Posix_mq_handle::receive (util::Blob_mutable * blob, Error_code * err_code = 0)
Implements Persistent_mq_handle API: Blocking receive: pops copy of message from queue into buffer; if queue is empty blocks until it is not.
See also
Persistent_mq_handle::receive(): implemented concept.
INFO+ logging
WARNING on error. (You may use the flow::log::Config::this_thread_verbosity_override_auto() to temporarily, in that thread only, disable/reduce logging. This is quite easy and performant.)
Parameters
blob See above.
err_code See above.
Definition at line 927 of file posix_mq_handle.cpp.
References handle_mq_api_result(), m_mq, ipc::util::Native_handle::m_native_handle, ipc::util::Native_handle::null(), receive(), and wait_receivable().
Referenced by receive().
remove_persistent()
void ipc::transport::Posix_mq_handle::remove_persistent (flow::log::Logger * logger_ptr, const Shared_name & name, Error_code * err_code = 0) static
Implements Persistent_mq_handle API: Removes the named persistent MQ.
Reminder: name is removed immediately (if present – otherwise error), but underlying MQ continues to exist until all system-wide handles to it are closed.
See also
Persistent_mq_handle::remove_persistent(): implemented concept.
Reminder: see also util::remove_each_persistent_*().
Parameters
logger_ptr See above.
name See above.
err_code See above.
Definition at line 1306 of file posix_mq_handle.cpp.
References absolute_name(), and remove_persistent().
Referenced by remove_persistent().
send()
void ipc::transport::Posix_mq_handle::send (const util::Blob_const & blob, Error_code * err_code = 0)
Implements Persistent_mq_handle API: Blocking send: pushes copy of message to queue; if queue is full blocks until it is not.
See also
Persistent_mq_handle::send(): implemented concept.
INFO+ logging
WARNING on error. (You may use the flow::log::Config::this_thread_verbosity_override_auto() to temporarily, in that thread only, disable/reduce logging. This is quite easy and performant.)
Parameters
blob See above.
err_code See above.
Definition at line 728 of file posix_mq_handle.cpp.
References ipc::util::blob_data(), handle_mq_api_result(), m_mq, ipc::util::Native_handle::m_native_handle, ipc::util::Native_handle::null(), send(), and wait_sendable().
Referenced by send().
set_non_blocking()
bool ipc::transport::Posix_mq_handle::set_non_blocking (bool nb, Error_code * err_code) private
Sets m_mq to blocking or non-blocking and returns true on success and clears *err_code; otherwise returns false and sets truthy *err_code.
Parameters
err_code To set. If null behavior is undefined (assertion may trip).
nb Non-blocking if true, else blocking.
Returns
true <=> success.
Definition at line 660 of file posix_mq_handle.cpp.
References handle_mq_api_result(), m_mq, and ipc::util::Native_handle::m_native_handle.
Referenced by Posix_mq_handle().
timed_receive()
bool ipc::transport::Posix_mq_handle::timed_receive (util::Blob_mutable * blob, util::Fine_duration timeout_from_now, Error_code * err_code = 0)
Implements Persistent_mq_handle API: Blocking timed receive: pops copy of message from queue into buffer; if queue is empty blocks until it is not, or the specified time passes, whichever happens first.
See also
Persistent_mq_handle::timed_receive(): implemented concept.
INFO+ logging
WARNING on error or timed out. (You may use the flow::log::Config::this_thread_verbosity_override_auto() to temporarily, in that thread only, disable/reduce logging. This is quite easy and performant.)
Parameters
blob See above.
timeout_from_now See above.
err_code See above.
Returns
See above.
Definition at line 995 of file posix_mq_handle.cpp.
References handle_mq_api_result(), m_mq, ipc::util::Native_handle::m_native_handle, ipc::util::Native_handle::null(), timed_receive(), and timed_wait_receivable().
Referenced by timed_receive().
timed_send()
bool ipc::transport::Posix_mq_handle::timed_send (const util::Blob_const & blob, util::Fine_duration timeout_from_now, Error_code * err_code = 0)
Implements Persistent_mq_handle API: Blocking timed send: pushes copy of message to queue; if queue is full blocks until it is not, or the specified time passes, whichever happens first.
See also
Persistent_mq_handle::timed_send(): implemented concept.
INFO+ logging
WARNING on error or timed out. (You may use the flow::log::Config::this_thread_verbosity_override_auto() to temporarily, in that thread only, disable/reduce logging. This is quite easy and performant.)
Parameters
blob See above.
timeout_from_now See above.
err_code See above.
Returns
See above.
Definition at line 796 of file posix_mq_handle.cpp.
References ipc::util::blob_data(), handle_mq_api_result(), m_mq, ipc::util::Native_handle::m_native_handle, ipc::util::Native_handle::null(), timed_send(), and timed_wait_sendable().
Referenced by timed_send().
timed_wait_receivable()
bool ipc::transport::Posix_mq_handle::timed_wait_receivable (util::Fine_duration timeout_from_now, Error_code * err_code = 0)
Implements Persistent_mq_handle API: Like timed_receive() but without the actual popping of a message.
See also
Persistent_mq_handle::timed_wait_receivable(): implemented concept.
INFO+ logging
WARNING on error.
Parameters
err_code See above.
timeout_from_now See above.
Returns
See above.
Definition at line 1296 of file posix_mq_handle.cpp.
References wait_impl().
Referenced by timed_receive().
timed_wait_sendable()
bool ipc::transport::Posix_mq_handle::timed_wait_sendable (util::Fine_duration timeout_from_now, Error_code * err_code = 0)
Implements Persistent_mq_handle API: Like timed_send() but without the actual pushing of a message.
See also
Persistent_mq_handle::timed_wait_sendable(): implemented concept.
INFO+ logging
WARNING on error.
Parameters
err_code See above.
timeout_from_now See above.
Returns
See above.
Definition at line 1281 of file posix_mq_handle.cpp.
References wait_impl().
Referenced by timed_send().
try_receive()
bool ipc::transport::Posix_mq_handle::try_receive (util::Blob_mutable * blob, Error_code * err_code = 0)
Implements Persistent_mq_handle API: Non-blocking receive: pops copy of message from queue into buffer and returns true; if queue is empty then no-op and returns false.
See also
Persistent_mq_handle::try_receive(): implemented concept.
INFO+ logging
WARNING on error. (You may use the flow::log::Config::this_thread_verbosity_override_auto() to temporarily, in that thread only, disable/reduce logging. This is quite easy and performant.)
Parameters
blob See above.
err_code See above.
Returns
See above.
Definition at line 881 of file posix_mq_handle.cpp.
References handle_mq_api_result(), m_mq, ipc::util::Native_handle::m_native_handle, ipc::util::Native_handle::null(), and try_receive().
Referenced by try_receive().
try_send()
bool ipc::transport::Posix_mq_handle::try_send (const util::Blob_const & blob, Error_code * err_code = 0)
Implements Persistent_mq_handle API: Non-blocking send: pushes copy of message to queue and returns true; if queue is full then no-op and returns false.
See also
Persistent_mq_handle::try_send(): implemented concept.
INFO+ logging
WARNING on error. (You may use the flow::log::Config::this_thread_verbosity_override_auto() to temporarily, in that thread only, disable/reduce logging. This is quite easy and performant.)
Parameters
blob See above.
err_code See above.
Returns
See above.
Definition at line 678 of file posix_mq_handle.cpp.
References ipc::util::blob_data(), handle_mq_api_result(), m_mq, ipc::util::Native_handle::m_native_handle, ipc::util::Native_handle::null(), and try_send().
Referenced by try_send().
wait_impl()
bool ipc::transport::Posix_mq_handle::wait_impl (util::Fine_duration timeout_from_now_or_none, bool snd_else_rcv, Error_code * err_code) private
Impl body for *_sendable() and *_receivable().
Parameters
timeout_from_now_or_none timeout_from_now; or 0 for is_*(), or Fine_duration::max() for non-timed-blocking variant.
snd_else_rcv True for *_sendable(), else *_receivable().
err_code See callers.
Returns
See callers.
Definition at line 1180 of file posix_mq_handle.cpp.
References m_epoll_hndl_rcv, m_epoll_hndl_snd, m_mq, ipc::util::Native_handle::m_native_handle, ipc::util::Native_handle::null(), ipc::transport::error::S_INTERRUPTED, and wait_impl().
Referenced by is_receivable(), is_sendable(), timed_wait_receivable(), timed_wait_sendable(), wait_impl(), wait_receivable(), and wait_sendable().
wait_receivable()
void ipc::transport::Posix_mq_handle::wait_receivable (Error_code * err_code = 0)
Implements Persistent_mq_handle API: Like receive() but without the actual popping of a message.
See also
Persistent_mq_handle::wait_receivable(): implemented concept.
INFO+ logging
WARNING on error.
Parameters
err_code See above.
Definition at line 1291 of file posix_mq_handle.cpp.
References wait_impl().
Referenced by receive().
wait_sendable()
void ipc::transport::Posix_mq_handle::wait_sendable (Error_code * err_code = 0)
Implements Persistent_mq_handle API: Like send() but without the actual pushing of a message.
See also
Persistent_mq_handle::wait_sendable(): implemented concept.
INFO+ logging
WARNING on error.
Parameters
err_code See above.
Definition at line 1276 of file posix_mq_handle.cpp.
References wait_impl().
Referenced by send().
Friends And Related Function Documentation
operator<<()
std::ostream & operator<< (std::ostream & os, const Posix_mq_handle & val) related
Prints string representation of the given Posix_mq_handle to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 1364 of file posix_mq_handle.cpp.
References absolute_name(), and native_handle().
swap [1/2]
void swap (Posix_mq_handle & val1, Posix_mq_handle & val2) friend
Implements Persistent_mq_handle related concept: Swaps two objects.
Parameters
val1 Object.
val2 Object.
Definition at line 545 of file posix_mq_handle.cpp.
Referenced by operator=().
swap() [2/2]
void swap (Posix_mq_handle & val1, Posix_mq_handle & val2) related
Implements Persistent_mq_handle related concept: Swaps two objects.
Parameters
val1 Object.
val2 Object.
Definition at line 545 of file posix_mq_handle.cpp.
Member Data Documentation
m_absolute_name
Shared_name ipc::transport::Posix_mq_handle::m_absolute_name private
See absolute_name().
Definition at line 629 of file posix_mq_handle.hpp.
Referenced by absolute_name(), and operator=().
m_epoll_hndl_rcv
Native_handle ipc::transport::Posix_mq_handle::m_epoll_hndl_rcv private
epoll_*() handle (.null() if and only if m_mq is null) that is level-triggered to be active (with only 1 event registered) if and only if m_mq is currently storing at least 1 message (we could pop 1+ messages right now).
Used by wait_impl() and its various public *_receivable() forms.
Definition at line 643 of file posix_mq_handle.hpp.
Referenced by epoll_setup(), operator=(), wait_impl(), and ~Posix_mq_handle().
m_epoll_hndl_snd
Native_handle ipc::transport::Posix_mq_handle::m_epoll_hndl_snd private
epoll_*() handle (.null() if and only if m_mq is null) that is level-triggered to be active (with only 1 event registered) if and only if m_mq is currently capable of sending at least 1 message (we could push 1+ messages right now).
Used by wait_impl() and its various public *_sendable() forms.
Definition at line 636 of file posix_mq_handle.hpp.
Referenced by epoll_setup(), operator=(), wait_impl(), and ~Posix_mq_handle().
m_interrupt_detector_rcv
Pipe_reader ipc::transport::Posix_mq_handle::m_interrupt_detector_rcv private
Other-direction counterpart to m_interrupt_detector_snd.
Definition at line 675 of file posix_mq_handle.hpp.
Referenced by allow_impl(), epoll_setup(), operator=(), and pipe_setup().
m_interrupt_detector_snd
Pipe_reader ipc::transport::Posix_mq_handle::m_interrupt_detector_snd private
A byte is read from this end by allow_sends() to make it not-readable for the poll-wait in wait_impl() indicating that m_interrupting_snd mode is off; and wait_impl() poll-waits on this along with m_mq – if it is readable, then the mode is on.
Definition at line 669 of file posix_mq_handle.hpp.
Referenced by allow_impl(), epoll_setup(), operator=(), and pipe_setup().
m_interrupter_rcv
Pipe_writer ipc::transport::Posix_mq_handle::m_interrupter_rcv private
Other-direction counterpart to m_interrupter_snd.
Definition at line 672 of file posix_mq_handle.hpp.
Referenced by epoll_setup(), interrupt_impl(), operator=(), and pipe_setup().
m_interrupter_snd
Pipe_writer ipc::transport::Posix_mq_handle::m_interrupter_snd private
A byte is written to this end by interrupt_sends() to make it readable for the poll-wait in wait_impl() indicating that m_interrupting_snd mode is on.
Definition at line 662 of file posix_mq_handle.hpp.
Referenced by epoll_setup(), interrupt_impl(), operator=(), and pipe_setup().
m_interrupting_rcv
bool ipc::transport::Posix_mq_handle::m_interrupting_rcv private
Other-direction counterpart to m_interrupting_snd.
Definition at line 653 of file posix_mq_handle.hpp.
Referenced by allow_impl(), and interrupt_impl().
m_interrupting_snd
bool ipc::transport::Posix_mq_handle::m_interrupting_snd private
Starting at false, this is made true via interrupt_sends(), and back by allow_sends(); acts as a guard against doing it when already in effect.
Note that that is its only purpose; as wait_impl() never checks it; instead it relies on epoll_wait() detecting a readable m_interrupt_detector_rcv.
Definition at line 650 of file posix_mq_handle.hpp.
Referenced by allow_impl(), and interrupt_impl().
m_mq
Native_handle ipc::transport::Posix_mq_handle::m_mq private
Underlying MQ handle.
We are a thin wrapper around this really. .null() if creation fails in ctor, or if *this was moved-from. This is very light-weight; probably int.
Definition at line 626 of file posix_mq_handle.hpp.
Referenced by allow_impl(), epoll_setup(), interrupt_impl(), max_msg_size(), max_n_msgs(), native_handle(), operator=(), Posix_mq_handle(), receive(), send(), set_non_blocking(), timed_receive(), timed_send(), try_receive(), try_send(), wait_impl(), and ~Posix_mq_handle().
m_nb_task_engine
flow::util::Task_engine ipc::transport::Posix_mq_handle::m_nb_task_engine private
Never used for .run() or .async() – just so we can construct Pipe_reader, Pipe_writer.
Definition at line 656 of file posix_mq_handle.hpp.
Referenced by operator=().
S_HAS_NATIVE_HANDLE
constexpr bool ipc::transport::Posix_mq_handle::S_HAS_NATIVE_HANDLE = true static constexpr
Implements concept API. Contrast this value with Bipc_mq_handle::S_HAS_NATIVE_HANDLE.
Definition at line 70 of file posix_mq_handle.hpp.
S_RESOURCE_TYPE_ID
const Shared_name ipc::transport::Posix_mq_handle::S_RESOURCE_TYPE_ID = Shared_name::ct("posixQ") static
Implements concept API.
Definition at line 67 of file posix_mq_handle.hpp.
The documentation for this class was generated from the following files:
transport/posix_mq_handle.hpp
transport/posix_mq_handle.cpp
transport/transport_fwd.hpp