Flow-IPC: ipc::util::sync_io::Asio_waitable_native_handle Class Reference
ipc::util::sync_io::Asio_waitable_native_handle Class Reference
Useful if using the sync_io pattern within a user event loop built on boost.asio (optionally with flow.async help), an object of this class wraps a non-null Native_handle and allows one to use .async_wait() to perform event waiting on behalf of any sync_io-implementing ipc::transport or ipc::session object.
#include <asio_waitable_native_hndl.hpp>
Public Types
using Base = boost::asio::posix::descriptor
Short-hand for our base type; can be used for, e.g., Base::wait_write and Base::wait_read.
Public Member Functions
Asio_waitable_native_handle (const Base::executor_type &ex, Native_handle hndl)
Construct boost.asio descriptor object such that one can async_wait() events on the given non-.null() Native_handle.
Asio_waitable_native_handle (const Base::executor_type &ex)
Construct boost.asio descriptor object that stores no handle.
template<typename Execution_context >
Asio_waitable_native_handle (Execution_context &context, Native_handle hndl, typename std::enable_if_t< std::is_convertible_v< Execution_context &, boost::asio::execution_context & > > *ignored=nullptr)
Construct boost.asio descriptor object such that one can async_wait() events on the given non-.null() Native_handle.
template<typename Execution_context >
Asio_waitable_native_handle (Execution_context &context, typename std::enable_if_t< std::is_convertible_v< Execution_context &, boost::asio::execution_context & > > *ignored=nullptr)
Construct boost.asio descriptor object that stores no handle.
Asio_waitable_native_handle (Asio_waitable_native_handle &&src)
Move-construct.
~Asio_waitable_native_handle ()
Destructor that does not OS-close ("::close()") the stored native handle (if any) but rather performs this->release() (eating any potential error in doing so).
Asio_waitable_native_handle & operator= (Asio_waitable_native_handle &&src)
Move-assign.
Native_handle native_handle ()
Returns the same Native_handle as passed to original handle-loading ctor or assign(), whichever happened last; or .null() Native_handle, if neither has been invoked, or release() was invoked more recently than either.
void assign (Native_handle hndl)
Loads value to be returned by native_handle().
Detailed Description
Useful if using the sync_io pattern within a user event loop built on boost.asio (optionally with flow.async help), an object of this class wraps a non-null Native_handle and allows one to use .async_wait() to perform event waiting on behalf of any sync_io-implementing ipc::transport or ipc::session object.
If boost.asio integration is not the goal, it can at least act as a mere container of a Native_handle. sync_io pattern uses Asio_waitable_native_handle in either capacity. If you're familiar with boost.asio POSIX descriptor, then you're familiar with this class.
See also
sync_io::Event_wait_func doc header; and specifically section "Integrating with boost.asio." It provides context and rationale for this guy when used for .async_wait().
It may also be useful in its own right independently.
In any case use is quite straightforward:
Construct from a non-null, opened w/r/t kernel Native_handle – and an executor/execution context (typically a Task_engine or possibly boost.asio strand). (If boost.asio integration is not the goal, then any blank/otherwise-unused Task_engine is fine.)
(Optional) If the wrapped handle is unknown at construction time, use the 1-arg ctor form; then .assign() it when it is known.
Invoke .async_wait() (from Asio_waitable_native_handle::Base a/k/a boost::asio::posix::descriptor) as many times as desired.
And/or invoke accessor .native_handle() to re-obtain the wrapped handle as desired.
Destroy when no more .async_wait()ing or .native_handle() access is necessary.
.release() may be used to essentially nullify a *this. This may be desirable for cleanliness in some situations.
You may not use *this object directly to perform actual I/O; it lacks such methods as async_read_some(). Moreover it is likely against the (informal) aim of Asio_waitable_native_handle to perform actual I/O by obtaining the handle via .native_handle() and then doing reads/writes on that handle.
Construction is likely performed by internal Flow-IPC code only in practice, though you are free to use it for your own purposes.
Warning
This object, like Asio_waitable_native_handle::Base, isn't just a Native_handle wrapper: It also has to be associated with an execution context, usually Task_engine (boost::asio::io_context) or boost.asio strand. If you associate, via ctor or assign(), 2 *thises each wrapping the same-valued Native_handle (storing the same raw handle) with the same Task_engine, behavior is undefined formally; though internally it'll cause a duplicate-descriptor error/exception (in Linux from errno == EEXIST from an internal epoll_ctl()). Even if you don't plan to async_wait(), this will unfortunately still happen; and for async_wait() purposes it will and should happen. So just take care not to create duplicate-handle *thises associated with the same Task_engine.
Note
Move assignment works which can be useful to associate a *this with a different execution context (event loop, Task_engine, etc.).
Rationale for protected rather than public inheritance
public inheritance would have been fine, more or less, but it seemed prudent to close off access to mutators from Asio_waitable_native_handle::Base like close() and non_blocking() which could sow sheer chaos; the point here is to watch for events on this guy, not (e.g.) blow up some internal transport within transport::Native_socket_stream et al.
Definition at line 80 of file asio_waitable_native_hndl.hpp.
Member Typedef Documentation
Base
using ipc::util::sync_io::Asio_waitable_native_handle::Base = boost::asio::posix::descriptor
Short-hand for our base type; can be used for, e.g., Base::wait_write and Base::wait_read.
Definition at line 86 of file asio_waitable_native_hndl.hpp.
Constructor & Destructor Documentation
Asio_waitable_native_handle() [1/5]
ipc::util::sync_io::Asio_waitable_native_handle::Asio_waitable_native_handle (const Base::executor_type & ex, Native_handle hndl) explicit
Construct boost.asio descriptor object such that one can async_wait() events on the given non-.null() Native_handle.
The handle must be a valid (not closed) handle (descriptor, FD).
Consider also the 1-arg ctor variant which stores no handle; followed by assign().
Parameters
ex See boost.asio docs for similar posix::basic_descriptor ctor.
hndl The handle that might be watched subsequently. .null() leads to undefined behavior; assertion may trip. If the associated Task_engine is already associated with another Asio_waitable_native_handle (or other I/O object) that stores the same Native_handle::m_native_handle, it is formally undefined behavior (in reality a boost.asio exception is thrown; but just don't do it).
Definition at line 27 of file asio_waitable_native_hndl.cpp.
References ipc::util::Native_handle::null().
Asio_waitable_native_handle() [2/5]
ipc::util::sync_io::Asio_waitable_native_handle::Asio_waitable_native_handle (const Base::executor_type & ex) explicit
Construct boost.asio descriptor object that stores no handle.
You may call assign() to change this.
Parameters
ex See boost.asio docs for similar posix::basic_descriptor ctor.
Definition at line 36 of file asio_waitable_native_hndl.cpp.
Asio_waitable_native_handle() [3/5]
template<typename Execution_context > ipc::util::sync_io::Asio_waitable_native_handle::Asio_waitable_native_handle (Execution_context & context, Native_handle hndl, typename std::enable_if_t< std::is_convertible_v< Execution_context &, boost::asio::execution_context & > > * ignored = nullptr) explicit
Construct boost.asio descriptor object such that one can async_wait() events on the given non-.null() Native_handle.
The handle must be a valid (not closed) handle (descriptor, FD).
Consider also the 1-arg ctor variant which stores no handle; followed by assign().
Template Parameters
Execution_context See boost.asio docs for similar posix::basic_descriptor ctor.
Parameters
context See boost.asio docs for similar posix::basic_descriptor ctor.
hndl The handle that might be watched subsequently. .null() leads to undefined behavior; assertion may trip. If the associated Task_engine is already associated with another Asio_waitable_native_handle that stores the same Native_handle::m_native_handle, it is formally undefined behavior (in reality a boost.asio exception is thrown; but just don't do it).
ignored Disregard.
Definition at line 216 of file asio_waitable_native_hndl.hpp.
References ipc::util::Native_handle::null().
Asio_waitable_native_handle() [4/5]
template<typename Execution_context > ipc::util::sync_io::Asio_waitable_native_handle::Asio_waitable_native_handle (Execution_context & context, typename std::enable_if_t< std::is_convertible_v< Execution_context &, boost::asio::execution_context & > > * ignored = nullptr) explicit
Construct boost.asio descriptor object that stores no handle.
You may call assign() to change this.
Template Parameters
Execution_context See boost.asio docs for similar posix::basic_descriptor ctor.
Parameters
context See boost.asio docs for similar posix::basic_descriptor ctor.
ignored Disregard.
Definition at line 227 of file asio_waitable_native_hndl.hpp.
Asio_waitable_native_handle() [5/5]
ipc::util::sync_io::Asio_waitable_native_handle::Asio_waitable_native_handle (Asio_waitable_native_handle && src) default
Move-construct.
Parameters
src See boost.asio docs for similar posix::basic_descriptor ctor.
~Asio_waitable_native_handle()
ipc::util::sync_io::Asio_waitable_native_handle::~Asio_waitable_native_handle ()
Destructor that does not OS-close ("::close()") the stored native handle (if any) but rather performs this->release() (eating any potential error in doing so).
Definition at line 46 of file asio_waitable_native_hndl.cpp.
Member Function Documentation
assign()
void ipc::util::sync_io::Asio_waitable_native_handle::assign (Native_handle hndl)
Loads value to be returned by native_handle().
As with the 2+-arg ctor(s) the handle must be valid (not closed). See also .release() and dtor.
If a handle is already loaded (Base::is_open() == true), this method automatically release()s it first.
Parameters
hndl The handle that might be watched subsequently. .null() leads to undefined behavior; assertion may trip. If the associated Task_engine is already associated with another Asio_waitable_native_handle that stores the same Native_handle::m_native_handle, it is formally undefined behavior (in reality a boost.asio exception is thrown; but just don't do it).
Definition at line 65 of file asio_waitable_native_hndl.cpp.
References ipc::util::Native_handle::m_native_handle, and ipc::util::Native_handle::null().
Referenced by ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::Blob_stream_mq_receiver_impl(), ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Blob_stream_mq_sender_impl(), ipc::transport::sync_io::Native_socket_stream::Impl::Impl(), ipc::session::sync_io::Session_adapter< Session >::init_pipe(), ipc::transport::sync_io::Native_socket_stream_acceptor::Native_socket_stream_acceptor(), ipc::transport::sync_io::Native_socket_stream_acceptor::replace_event_wait_handles(), and ipc::session::sync_io::Session_server_adapter< Session_server >::Session_server_adapter().
native_handle()
Native_handle ipc::util::sync_io::Asio_waitable_native_handle::native_handle ()
Returns the same Native_handle as passed to original handle-loading ctor or assign(), whichever happened last; or .null() Native_handle, if neither has been invoked, or release() was invoked more recently than either.
Returns
See above.
Definition at line 60 of file asio_waitable_native_hndl.cpp.
operator=()
Asio_waitable_native_handle & ipc::util::sync_io::Asio_waitable_native_handle::operator= (Asio_waitable_native_handle && src) default
Move-assign.
Parameters
src See boost.asio docs for similar posix::basic_descriptor method.
Returns
See boost.asio docs for similar posix::basic_descriptor method.
The documentation for this class was generated from the following files:
util/sync_io/asio_waitable_native_hndl.hpp
util/sync_io/asio_waitable_native_hndl.cpp