Flow-IPC: ipc::session::shm::arena_lend::jemalloc::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > Class Template Reference
ipc::session::shm::arena_lend::jemalloc::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > Class Template Reference
Core internally-used implementation of shm::arena_lend::jemalloc::Client_session: it is to the latter what its public super-class Client_session_impl is to Client_session.
#include <client_session_impl.hpp>
Public Types
using Base = Session_impl< session::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, session::schema::ShmType::JEMALLOC, true > >
Short-hand for our non-virtual base.
Public Types inherited from ipc::session::shm::arena_lend::jemalloc::Session_impl< session::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, session::schema::ShmType::JEMALLOC, true > >
using Base = session::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, session::schema::ShmType::JEMALLOC, true >
Short-hand for base class.
using Session_base_obj = typename Base::Session_base_obj
Short-hand for Session_base super-class.
using Arena = ipc::shm::arena_lend::jemalloc::Ipc_arena
See shm::arena_lend::jemalloc::Session_mv counterpart for public description.
using Shm_session = jemalloc::Shm_session
See shm::arena_lend::jemalloc::Session_mv counterpart for public description.
using Structured_channel = transport::struc::shm::arena_lend::jemalloc::Channel< typename Base::Channel_obj, Message_body >
See shm::arena_lend::jemalloc::Session_mv counterpart for public description.
using Structured_msg_builder_config = typename transport::struc::shm::arena_lend::jemalloc::Builder::Config
See shm::arena_lend::jemalloc::Session_mv counterpart for public description.
using Structured_msg_reader_config = typename transport::struc::shm::arena_lend::jemalloc::Reader::Config
See shm::arena_lend::jemalloc::Session_mv counterpart for public description.
using Blob = Shm_session::Blob
Alias for a light-weight blob used in borrow_object() and lend_object().
Public Types inherited from ipc::session::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, session::schema::ShmType::JEMALLOC, true >
using Base = Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
Short-hand for base type.
using Session_base_obj = Base
Short-hand for Session_base super-class.
using Channel_obj = typename Base::Channel_obj
See Client_session_mv counterpart.
using Channels = typename Base::Channels
See Session_mv counterpart.
using Mdt_payload_obj = typename Base::Mdt_payload_obj
See Client_session_mv counterpart.
using Mdt_reader_ptr = typename Base::Mdt_reader_ptr
See Client_session_mv counterpart.
using Mdt_builder = typename Base::Mdt_builder
See Client_session_mv counterpart.
using Mdt_builder_ptr = typename Base::Mdt_builder_ptr
See Client_session_mv counterpart.
using Structured_msg_builder_config = typename Base::Structured_msg_builder_config
See Session_mv counterpart.
using Structured_msg_reader_config = typename Base::Structured_msg_reader_config
See Session_mv counterpart.
Public Types inherited from ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
using Persistent_mq_handle_from_cfg = std::conditional_t<!S_MQS_ENABLED, transport::Null_peer, std::conditional_t< S_MQ_TYPE_OR_NONE==schema::MqType::POSIX, transport::Posix_mq_handle, transport::Bipc_mq_handle > >
Relevant only if S_MQS_ENABLED, this is the Persistent_mq_handle-concept impl type specified by the user via S_MQ_TYPE_OR_NONE.
using Channel_obj = std::conditional_t< S_MQS_ENABLED, std::conditional_t< S_TRANSMIT_NATIVE_HANDLES, transport::Mqs_socket_stream_channel< true, Persistent_mq_handle_from_cfg >, transport::Mqs_channel< true, Persistent_mq_handle_from_cfg > >, std::conditional_t< S_TRANSMIT_NATIVE_HANDLES, transport::Socket_stream_channel< true >, transport::Socket_stream_channel_of_blobs< true > > >
See Session_mv (or Session concept).
using Channels = std::vector< Channel_obj >
See Session_mv. Note: If changed from vector please update those doc headers too.
using Mdt_payload_obj = Mdt_payload
See Session_mv (or Session concept).
using Mdt_reader_ptr = boost::shared_ptr< typename transport::struc::schema::Metadata< Mdt_payload_obj >::Reader >
See Session_mv (or Session concept).
using Mdt_builder = typename transport::struc::schema::Metadata< Mdt_payload_obj >::Builder
See Session_mv (or Session concept).
using Mdt_builder_ptr = boost::shared_ptr< Mdt_builder >
See Session_mv (or Session concept).
using Structured_msg_builder_config = transport::struc::Heap_fixed_builder::Config
See Session_mv (or Session concept).
using Structured_msg_reader_config = transport::struc::Heap_reader::Config
See Session_mv (or Session concept).
Public Member Functions
template<typename On_passive_open_channel_handler , typename Task_err >
Client_session_impl (flow::log::Logger *logger_ptr, const Client_app &cli_app_ref, const Server_app &srv_app_ref, Task_err &&on_err_func, On_passive_open_channel_handler &&on_passive_open_channel_func)
See session::Client_session_impl::Client_session_impl() counterpart.
template<typename Task_err >
Client_session_impl (flow::log::Logger *logger_ptr, const Client_app &cli_app_ref, const Server_app &srv_app_ref, Task_err &&on_err_func)
See session::Client_session_impl::Client_session_impl() counterpart.
~Client_session_impl ()
Destructor.
bool sync_connect (Error_code *err_code)
See Client_session_mv counterpart.
bool sync_connect (const typename Base::Base::Base::Mdt_builder_ptr &mdt, typename Base::Base::Base::Channels *init_channels_by_cli_req_pre_sized, typename Base::Base::Base::Mdt_reader_ptr *mdt_from_srv_or_null, typename Base::Base::Base::Channels *init_channels_by_srv_req, Error_code *err_code)
See Client_session_mv counterpart.
Public Member Functions inherited from ipc::session::shm::arena_lend::jemalloc::Session_impl< session::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, session::schema::ShmType::JEMALLOC, true > >
Arena * session_shm ()
See shm::arena_lend::jemalloc::Session_mv counterpart.
std::shared_ptr< Arena > session_shm_ptr ()
See shm::arena_lend::jemalloc::Session_mv counterpart.
Blob lend_object (const typename Arena::template Handle< T > &handle)
See shm::arena_lend::jemalloc::Session_mv counterpart.
Arena::template Handle< T > borrow_object (const Blob &serialization)
See shm::arena_lend::jemalloc::Session_mv counterpart.
Structured_msg_builder_config session_shm_builder_config ()
See shm::arena_lend::jemalloc::Session_mv counterpart.
Structured_msg_builder_config::Builder::Session session_shm_lender_session ()
See shm::arena_lend::jemalloc::Session_mv counterpart.
Structured_msg_reader_config session_shm_reader_config ()
See shm::arena_lend::jemalloc::Session_mv counterpart.
Structured_msg_reader_config app_shm_reader_config ()
See shm::arena_lend::jemalloc::Session_mv counterpart.
Shm_session * shm_session ()
See shm::arena_lend::jemalloc::Session_mv counterpart.
Structured_msg_reader_config shm_reader_config ()
See shm::arena_lend::jemalloc::Session_mv counterpart.
Public Member Functions inherited from ipc::session::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, session::schema::ShmType::JEMALLOC, true >
Client_session_impl (flow::log::Logger *logger_ptr, const Client_app &cli_app_ref, const Server_app &srv_app_ref, Task_err &&on_err_func, On_passive_open_channel_handler &&on_passive_open_channel_func)
See Client_session_mv counterpart.
Client_session_impl (flow::log::Logger *logger_ptr, const Client_app &cli_app_ref, const Server_app &srv_app_ref, Task_err &&on_err_func)
See Client_session_mv counterpart.
~Client_session_impl ()
See Client_session_mv counterpart.
Mdt_builder_ptr mdt_builder () const
See Client_session_mv counterpart.
bool sync_connect (Error_code *err_code)
See Client_session_mv counterpart.
bool sync_connect (const Mdt_builder_ptr &mdt, Channels *init_channels_by_cli_req_pre_sized, Mdt_reader_ptr *mdt_from_srv_or_null, Channels *init_channels_by_srv_req, Error_code *err_code)
See Client_session_mv counterpart.
bool open_channel (Channel_obj *target_channel, const Mdt_builder_ptr &mdt, Error_code *err_code)
See Client_session_mv counterpart.
bool open_channel (Channel_obj *target_channel, Error_code *err_code)
See Client_session_mv counterpart.
const Session_token & session_token () const
See Client_session_mv counterpart.
Public Member Functions inherited from ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
const Shared_name & srv_namespace () const
See Server_session_impl, Client_session_impl.
const Shared_name & cli_namespace () const
See Server_session_impl, Client_session_impl.
const Client_app * cli_app_ptr () const
See Server_session_impl, Client_session_impl.
Shared_name cur_ns_store_mutex_absolute_name () const
Computes the name of the interprocess named-mutex used to control reading/writing to the file storing (written by server, read by client) the value for srv_namespace().
fs::path cur_ns_store_absolute_path () const
Computes the absolute path to file storing (written by server, read by client) the value for srv_namespace().
Shared_name session_master_socket_stream_acceptor_absolute_name () const
Computes the absolute name at which the server shall set up a transport::Native_socket_stream_acceptor to which client shall transport::Native_socket_stream::sync_connect() in order to establish a PEER-state session.
Private Member Functions
template<typename Task_err >
bool async_connect (const typename Base::Base::Base::Mdt_builder_ptr &mdt, typename Base::Base::Base::Channels *init_channels_by_cli_req_pre_sized, typename Base::Base::Base::Mdt_reader_ptr *mdt_from_srv_or_null, typename Base::Base::Base::Channels *init_channels_by_srv_req, Task_err &&on_done_func)
See session::Client_session_impl counterpart.
void cleanup ()
Invoked on m_async_cleanup_worker, performs a round of the SHM-pool cleanup algorithm and schedules same.
Private Attributes
ipc::shm::arena_lend::Owner_shm_pool_listener_for_repository m_shm_arena_pool_listener
This guy needs to be around, with each arena (in our case, out of the box, just session_shm()) registered against it, for shm::stl::Arena_allocator (and thus STL/allocator-compliant data structures, including containers like our own transport::struc::shm::Capnp_message_builder::Segments_in_shm) to work properly with that arena.
flow::async::Single_thread_task_loop m_async_cleanup_worker
Thread used for low-priority periodic low-priority cleanup work.
Related Functions
(Note that these are not member functions.)
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload >
std::ostream & operator<< (std::ostream &os, const Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > &val)
Prints string representation of the given Client_session_impl to the given ostream.
Related Functions inherited from ipc::session::shm::arena_lend::jemalloc::Session_impl< session::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, session::schema::ShmType::JEMALLOC, true > >
std::ostream & operator<< (std::ostream &os, const Session_impl< session::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, session::schema::ShmType::JEMALLOC, true > > &val)
Prints string representation of the given Session_impl to the given ostream.
Related Functions inherited from ipc::session::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, session::schema::ShmType::JEMALLOC, true >
std::ostream & operator<< (std::ostream &os, const Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, S_SHM_TYPE_OR_NONE, S_GRACEFUL_FINISH_REQUIRED_V > &val)
Prints string representation of the given Client_session_impl to the given ostream.
Additional Inherited Members
Static Public Member Functions inherited from ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
static Structured_msg_builder_config heap_fixed_builder_config (flow::log::Logger *logger_ptr)
See Session_mv::heap_fixed_builder_config() (1-arg).
static Structured_msg_reader_config heap_reader_config (flow::log::Logger *logger_ptr)
See Session_mv::heap_reader_config() (1-arg).
Public Attributes inherited from ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
const Server_app & m_srv_app_ref
Reference to Server_app (referring to local process in Server_session_impl, opposing process in Client_session_impl).
Static Public Attributes inherited from ipc::session::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, session::schema::ShmType::JEMALLOC, true >
static constexpr schema::ShmType S_SHM_TYPE
See Session_mv counterpart.
static constexpr bool S_SHM_ENABLED
See Session_mv counterpart.
static constexpr bool S_MQS_ENABLED
See Client_session_mv counterpart.
static constexpr bool S_SOCKET_STREAM_ENABLED
See Client_session_mv counterpart.
static constexpr bool S_GRACEFUL_FINISH_REQUIRED
Short-hand for template parameter knob S_GRACEFUL_FINISH_REQUIRED_V: see class template doc header.
Static Public Attributes inherited from ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
static constexpr bool S_MQS_ENABLED = S_MQ_TYPE_OR_NONE != schema::MqType::NONE
See Session_mv.
static constexpr bool S_SOCKET_STREAM_ENABLED = (!S_MQS_ENABLED) || S_TRANSMIT_NATIVE_HANDLES
See Session_mv.
Protected Types inherited from ipc::session::shm::arena_lend::jemalloc::Session_impl< session::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, session::schema::ShmType::JEMALLOC, true > >
using Shm_session_ptr = std::shared_ptr< Shm_session >
How the SHM-provider refers to a Shm_session.
Protected Types inherited from ipc::session::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, session::schema::ShmType::JEMALLOC, true >
using Master_structured_channel = typename Base::Master_structured_channel
See Session_base.
Protected Types inherited from ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
using Master_structured_channel = transport::struc::Channel_via_heap< transport::Socket_stream_channel< true >, schema::detail::SessionMasterChannelMessageBody< Mdt_payload_obj > >
The (internally used) session master channel is a transport::struc::Channel of this concrete type.
using Master_structured_channel_ptr = boost::shared_ptr< Master_structured_channel >
Handle to Master_structured_channel.
using Master_structured_channel_observer = boost::weak_ptr< Master_structured_channel >
Observer of Master_structured_channel_ptr. See its doc header.
using On_passive_open_channel_func = Function< void(Channel_obj &&new_channel, Mdt_reader_ptr &&new_channel_mdt)>
Concrete function type for the on-passive-open handler (if any), used for storage.
Protected Member Functions inherited from ipc::session::shm::arena_lend::jemalloc::Session_impl< session::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, session::schema::ShmType::JEMALLOC, true > >
Error_code init_shm (util::Native_handle &&local_hndl, const Shared_name &pool_name_fragment_or_empty, const std::shared_ptr< Arena > &app_shm_or_null={})
To be invoked at most once, synchronously sets up nearly-all aspects of this arena-lending-SHM-capable Session; the prerequisite from sub-class _impl being that the possibly-asynchronous steps leading up to this have been completed successfully.
void reset_shm ()
Undoes init_shm_arenas(), namely destroying shm_session() pointee and session_shm() pointee.
Protected Member Functions inherited from ipc::session::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, session::schema::ShmType::JEMALLOC, true >
bool sync_connect_impl (Error_code *err_code, Function< bool(flow::async::Task_asio_err &&)> *async_connect_impl_func)
Utility for *this and sub-classes: Implements sync_connect() given a functor that invokes the calling class's (including Client_session_impl) async_connect() with the args passed to the calling sync_connect().
bool async_connect (const Mdt_builder_ptr &mdt, Channels *init_channels_by_cli_req_pre_sized, Mdt_reader_ptr *mdt_from_srv_or_null, Channels *init_channels_by_srv_req, Task_err &&on_done_func)
Core implementation of sync_connect().
void cancel_peer_state_to_null ()
Utility for sub-classes: executed from async_connect()'s on_done_func(Error_code()) (i.e., directly from handler invoked on success) – hence from thread W – this instead goes back to NULL state, essentially indicating "never mind -- this successful async_connect() actually failed.".
Master_structured_channel * cancel_peer_state_to_connecting (Task_err &&on_done_func)
Utility for sub-classes: executed from async_connect()'s on_done_func(Error_code()) (i.e., directly from handler invoked on success) – hence from thread W – this instead goes back to CONNECTING state, essentially indicating "yes, the vanilla async_connect() succeeded, but the true user-called async_connect() that piggybacked on the vanilla one will now do some more async stuff before reaching PEER state (or NULL on error).
void complete_async_connect_after_canceling_peer_state (const Error_code &err_code_or_success)
Utility for sub-classes: to be invoked, only from thread W and asynchronously at that, after cancel_peer_state_to_connecting(), this indicates the completion of the sub-class's additional async-connect steps, setting state to either NULL or PEER.
flow::async::Single_thread_task_loop * async_worker ()
Utility for sub-classes: provides ability to schedule or post tasks onto thread W.
const Master_structured_channel & master_channel_const () const
Utility for sub-classes: provides ability to immutably query the session master channel, particularly after our async_accept_log_in() succeeds, but before the sub-classed wrapper of its on-done handler succeeds.
void dtor_async_worker_stop ()
Synchronously stops async_worker() loop, the post-condition being that thread W has been joined; no tasks post()ed onto it by *this or subclass shall execute after this returns.
Protected Member Functions inherited from ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
Session_base (const Client_app &cli_app_ref, const Server_app &srv_app_ref, flow::async::Task_asio_err &&on_err_func, On_passive_open_channel_func &&on_passive_open_channel_func_or_empty_arg)
Constructs: Client_session_impl form (the user is the one constructing the object, though in NULL state).
Session_base (const Server_app &srv_app_ref)
Constructs: Server_session_impl form (Session_server is the one constructing the object, though in NULL state, before log-in has completed, but after the socket-stream connection has been established).
void set_srv_namespace (Shared_name &&srv_namespace_new)
Sets srv_namespace() (do not call if already set).
void set_cli_namespace (Shared_name &&cli_namespace_new)
Sets cli_namespace() (do not call if already set).
void set_cli_app_ptr (const Client_app *cli_app_ptr_new)
Sets cli_app_ptr() (do not call if already set).
void set_on_passive_open_channel_func (On_passive_open_channel_func &&on_passive_open_channel_func)
Sets on_passive_open_channel_func_or_empty() (do not call if already set; do not call if user intends for passive-opens to be disabled on this side).
void set_on_err_func (flow::async::Task_asio_err &&on_err_func_arg)
Sets on_err_func() (do not call if already set).
bool on_err_func_set () const
Returns true if and only if set_on_err_func() has been called.
const On_passive_open_channel_func & on_passive_open_channel_func_or_empty () const
The on-passive-open handler (may be empty even in final state, meaning user wants passive-opens disabled on this side).
void hose (const Error_code &err_code)
Marks this session as hosed for (truthy) reason err_code; and synchronously invokes on-error handler; only invoke if not already hosed().
bool hosed () const
Returns true if and only if hose() has been called.
Static Protected Attributes inherited from ipc::session::Session_base< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
static constexpr util::Fine_duration S_OPEN_CHANNEL_TIMEOUT = boost::chrono::seconds(60)
Internal timeout for open_channel().
static constexpr size_t S_MQS_MAX_MSG_SZ = 8 * 1024
The max sendable MQ message size as decided by Server_session_impl::make_channel_mqs() (and imposed on both sides, both directions), if S_MQS_ENABLED and Server_session_impl::S_SHM_ENABLED is false, when a channel is opened (regardless of which side did the active-open or requested pre-opening at session start).
Detailed Description
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload>
class ipc::session::shm::arena_lend::jemalloc::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
Core internally-used implementation of shm::arena_lend::jemalloc::Client_session: it is to the latter what its public super-class Client_session_impl is to Client_session.
See also
shm::arena_lend::jemalloc::Client_session doc header which covers both its public behavior/API and a detailed sketch of the entire implementation.
Template Parameters
S_MQ_TYPE_OR_NONE See shm::arena_lend::jemalloc::Client_session counterpart.
S_TRANSMIT_NATIVE_HANDLES See shm::arena_lend::jemalloc::Client_session counterpart.
Mdt_payload See shm::arena_lend::jemalloc::Client_session counterpart.
Definition at line 54 of file client_session_impl.hpp.
Member Typedef Documentation
Base
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::arena_lend::jemalloc::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Base = Session_impl <session::Client_session_impl<S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload, session::schema::ShmType::JEMALLOC, true> >
Short-hand for our non-virtual base.
Definition at line 64 of file client_session_impl.hpp.
Constructor & Destructor Documentation
Client_session_impl() [1/2]
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > template<typename On_passive_open_channel_handler , typename Task_err > ipc::session::shm::arena_lend::jemalloc::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Client_session_impl (flow::log::Logger * logger_ptr, const Client_app & cli_app_ref, const Server_app & srv_app_ref, Task_err && on_err_func, On_passive_open_channel_handler && on_passive_open_channel_func) explicit
See session::Client_session_impl::Client_session_impl() counterpart.
Internally, in addition, we set up a SHM-pool cleanup algorithm.
Parameters
logger_ptr See above.
cli_app_ref See above.
srv_app_ref See above.
on_err_func See above.
on_passive_open_channel_func See above.
Definition at line 222 of file client_session_impl.hpp.
References ipc::session::shm::arena_lend::jemalloc::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::cleanup(), and ipc::session::shm::arena_lend::jemalloc::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::m_async_cleanup_worker.
Client_session_impl() [2/2]
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > template<typename Task_err > ipc::session::shm::arena_lend::jemalloc::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Client_session_impl (flow::log::Logger * logger_ptr, const Client_app & cli_app_ref, const Server_app & srv_app_ref, Task_err && on_err_func) explicit
See session::Client_session_impl::Client_session_impl() counterpart.
Internally, in addition, we set up a SHM-pool cleanup algorithm.
Parameters
logger_ptr See above.
cli_app_ref See above.
srv_app_ref See above.
on_err_func See above.
Definition at line 236 of file client_session_impl.hpp.
References ipc::session::shm::arena_lend::jemalloc::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::cleanup(), and ipc::session::shm::arena_lend::jemalloc::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::m_async_cleanup_worker.
~Client_session_impl()
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > ipc::session::shm::arena_lend::jemalloc::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::~Client_session_impl
Destructor.
Internally: at least does what it must according to session::Client_session_impl::dtor_async_worker_stop() doc header contract. See inside for comment more resembling English hopefully.
Definition at line 248 of file client_session_impl.hpp.
Member Function Documentation
async_connect()
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > template<typename Task_err > bool ipc::session::shm::arena_lend::jemalloc::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::async_connect (const typename Base::Base::Base::Mdt_builder_ptr & mdt, typename Base::Base::Base::Channels * init_channels_by_cli_req_pre_sized, typename Base::Base::Base::Mdt_reader_ptr * mdt_from_srv_or_null, typename Base::Base::Base::Channels * init_channels_by_srv_req, Task_err && on_done_func) private
See session::Client_session_impl counterpart.
Parameters
mdt See session::Client_session_impl counterpart.
init_channels_by_cli_req_pre_sized See session::Client_session_impl counterpart.
mdt_from_srv_or_null See session::Client_session_impl counterpart.
init_channels_by_srv_req See session::Client_session_impl counterpart.
on_done_func See session::Client_session_impl counterpart.
Returns
See session::Client_session_impl counterpart.
Definition at line 280 of file client_session_impl.hpp.
cleanup()
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > void ipc::session::shm::arena_lend::jemalloc::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::cleanup private
Invoked on m_async_cleanup_worker, performs a round of the SHM-pool cleanup algorithm and schedules same.
Definition at line 471 of file client_session_impl.hpp.
References ipc::session::decompose_conventional_shared_name(), ipc::util::process_running(), ipc::util::Shared_name::S_RESOURCE_TYPE_ID_SHM, ipc::util::Shared_name::S_SEPARATOR, ipc::session::shm::classic::SHM_SUBTYPE_PREFIX, and ipc::util::Shared_name::str().
Referenced by ipc::session::shm::arena_lend::jemalloc::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Client_session_impl().
sync_connect() [1/2]
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > bool ipc::session::shm::arena_lend::jemalloc::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::sync_connect (const typename Base::Base::Base::Mdt_builder_ptr & mdt, typename Base::Base::Base::Channels * init_channels_by_cli_req_pre_sized, typename Base::Base::Base::Mdt_reader_ptr * mdt_from_srv_or_null, typename Base::Base::Base::Channels * init_channels_by_srv_req, Error_code * err_code)
See Client_session_mv counterpart.
Parameters
mdt See Client_session_mv counterpart.
init_channels_by_cli_req_pre_sized See Client_session_mv counterpart.
mdt_from_srv_or_null See Client_session_mv counterpart.
init_channels_by_srv_req See Client_session_mv counterpart.
err_code See Client_session_mv counterpart.
Returns
See Client_session_mv counterpart.
Definition at line 262 of file client_session_impl.hpp.
sync_connect() [2/2]
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > bool ipc::session::shm::arena_lend::jemalloc::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::sync_connect (Error_code * err_code)
See Client_session_mv counterpart.
Parameters
err_code See Client_session_mv counterpart.
Returns
See Client_session_mv counterpart.
Definition at line 256 of file client_session_impl.hpp.
Friends And Related Function Documentation
operator<<()
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > std::ostream & operator<< (std::ostream & os, const Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > & val) related
Prints string representation of the given Client_session_impl to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 585 of file client_session_impl.hpp.
Member Data Documentation
m_async_cleanup_worker
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > flow::async::Single_thread_task_loop ipc::session::shm::arena_lend::jemalloc::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::m_async_cleanup_worker private
Thread used for low-priority periodic low-priority cleanup work.
See cleanup().
Rationale
Why not piggy-back on session::Client_session_impl's thread W? Answer: That guy actually does important stuff sometimes; we would not want some endless scan through /dev/shm (or whatever) to delay a channel opening or some-such. So just parallelize it.
Definition at line 206 of file client_session_impl.hpp.
Referenced by ipc::session::shm::arena_lend::jemalloc::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Client_session_impl().
m_shm_arena_pool_listener
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > ipc::shm::arena_lend::Owner_shm_pool_listener_for_repository ipc::session::shm::arena_lend::jemalloc::Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::m_shm_arena_pool_listener private
This guy needs to be around, with each arena (in our case, out of the box, just session_shm()) registered against it, for shm::stl::Arena_allocator (and thus STL/allocator-compliant data structures, including containers like our own transport::struc::shm::Capnp_message_builder::Segments_in_shm) to work properly with that arena.
Details:
It is recommended there are not tons of these lying around, but in a production application there should be one session::Client_session around at a time at most. So keeping this here makes sense.
It is not a problem if there is more than one per process; so if there are more sessions around in the process, it won't cause any problem. It's not a singleton situation.
There is also one in each Session_server.
Definition at line 196 of file client_session_impl.hpp.
The documentation for this class was generated from the following files:
session/detail/shm/arena_lend/jemalloc/client_session_impl.hpp
session/detail/shm/arena_lend/jemalloc/jemalloc_fwd.hpp