Flow-IPC: ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > Class Template Reference
ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > Class Template Reference
This is to vanilla Session_server what shm::arena_lend::jemalloc::Server_session is to vanilla Server_session: it is the session-server type that starts SHM-enabled sessions with SHM-jemalloc provider (ipc::shm::arena_lend::jemalloc).
#include <session_server.hpp>
Public Types
using Server_session_obj = shm::arena_lend::jemalloc::Server_session< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
Short-hand for the concrete Server_session-like type emitted by async_accept().
using Mdt_reader_ptr = typename Impl::Mdt_reader_ptr
Short-hand for Session_mv::Mdt_reader_ptr.
using Mdt_builder = typename Server_session_obj::Mdt_builder
Metadata builder type passed to mdt_load_func() in advanced async_accept() overload.
using Channels = typename Impl::Channels
Short-hand for Session_mv::Channels.
using Arena = typename Server_session_obj::Base::Arena
Short-hand for shm::arena_lend::jemalloc::Session_mv::Arena. See app_shm() in particular.
using Structured_msg_builder_config = typename Server_session_obj::Base::Structured_msg_builder_config
Short-hand for shm::arena_lend::jemalloc::Session_mv::Structured_msg_builder_config.
using Structured_msg_reader_config = typename Server_session_obj::Base::Structured_msg_reader_config
Short-hand for shm::arena_lend::jemalloc::Session_mv::Structured_msg_reader_config.
Public Member Functions
Session_server (flow::log::Logger *logger_ptr, const Server_app &srv_app_ref, const Client_app::Master_set &cli_app_master_set_ref, Error_code *err_code=0)
Constructor: identical to session::Session_server ctor.
template<typename Task_err >
void async_accept (Server_session_obj *target_session, Task_err &&on_done_func)
Contract identical to simpler session::Session_server::async_accept() overload; but internally ensures that the appropriate SHM-jemalloc arenas are available for use in the emitted Server_session_obj.
template<typename Task_err , typename N_init_channels_by_srv_req_func , typename Mdt_load_func >
void async_accept (Server_session_obj *target_session, Channels *init_channels_by_srv_req, Mdt_reader_ptr *mdt_from_cli_or_null, Channels *init_channels_by_cli_req, N_init_channels_by_srv_req_func &&n_init_channels_by_srv_req_func, Mdt_load_func &&mdt_load_func, Task_err &&on_done_func)
Contract identical to advanced Session_server::async_accept() overload; but internally ensures that the appropriate SHM-jemalloc arenas are available for use in the emitted Server_session_obj.
Arena * app_shm (const Client_app &app)
Returns pointer to the per-app SHM-arena, whose lifetime extends until *this is destroyed; or null if the given Client_app has not yet opened at least 1 shm::arena_lend::jemalloc::Server_session via async_accept().
std::shared_ptr< Arena > app_shm_ptr (const Client_app &app)
Identical to app_shm() but returns that via a shared_ptr-handle as required for work directly within ipc::shm::arena_lend::jemalloc APIs.
Structured_msg_builder_config app_shm_builder_config (const Client_app &app)
Returns builder config suitable for capnp-serializing out-messages in SHM arena app_shm() for the same Client_app app.
Structured_msg_builder_config::Builder::Session app_shm_lender_session (const Client_app &app)
In short, what app_shm_builder_config() is to shm::arena_lend::jemalloc::Session_mv::app_shm_builder_config(), this is to shm::arena_lend::jemalloc::app_shm_lender_session().
Structured_msg_reader_config app_shm_reader_config (const Client_app &app)
Returns reader config counterpart to app_shm_builder_config() for a given Client_app app.
ipc::shm::arena_lend::Owner_shm_pool_listener_for_repository * shm_arena_pool_listener ()
Returns the arena-pool listener maintained throughout *this Session_server's life.
void to_ostream (std::ostream *os) const
Prints string representation to the given ostream.
Private Types
using Impl = Session_server_impl< Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >, Server_session< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > >
Short-hand for our base/core impl.
using Mutex = flow::util::Mutex_non_recursive
Short-hand for m_app_shm_mutex type.
using Lock_guard = flow::util::Lock_guard< Mutex >
Short-hand for Mutex lock.
Private Types inherited from ipc::session::Session_server_impl< Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >, Server_session< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > >
using Session_server_obj = Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
See this_session_srv().
using Server_session_obj = Server_session< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
Useful short-hand for the concrete Server_session type emitted by async_accept().
using Mdt_reader_ptr = typename Server_session_obj::Mdt_reader_ptr
Short-hand for Session_mv::Mdt_reader_ptr.
using Channels = typename Server_session_obj::Channels
Short-hand for Session_mv::Channels.
Private Member Functions
Error_code init_app_shm_as_needed (const Client_app &app)
Analogous to classic::Session_server::init_app_shm_as_needed().
void cleanup ()
Invoked on m_async_cleanup_worker, performs a round of the SHM-pool cleanup algorithm and schedules same.
Private Member Functions inherited from ipc::session::Session_server_impl< Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >, Server_session< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > >
Session_server_impl (flow::log::Logger *logger_ptr, Session_server_obj *this_session_srv_arg, const Server_app &srv_app_ref, const Client_app::Master_set &cli_app_master_set_ref, Error_code *err_code, Per_app_setup_func &&per_app_setup_func)
See Session_server ctor; it does that.
~Session_server_impl ()
See Session_server dtor.
void async_accept (Server_session_obj *target_session, Channels *init_channels_by_srv_req, Mdt_reader_ptr *mdt_from_cli_or_null, Channels *init_channels_by_cli_req, N_init_channels_by_srv_req_func &&n_init_channels_by_srv_req_func, Mdt_load_func &&mdt_load_func, Task_err &&on_done_func)
See Session_server method.
void to_ostream (std::ostream *os) const
See Server_session method.
Session_server_obj * this_session_srv ()
Returns pointer to the object that is privately sub-classing us.
void sub_class_set_deinit_func (Task &&task)
Utility for sub-classes: ensures that task() is invoked near the end of *this dtor's execution, after all other (mutable) state has been destroyed, including stopping/joining any threads performing async async_accept() ops.
Private Attributes
const Server_app & m_srv_app_ref
Identical to Session_server::m_srv_app_ref. Used in init_app_shm_as_needed() name calc.
const Shared_name m_srv_namespace
Identical Session_base::m_srv_namespace. Used in init_app_shm_as_needed() name calc.
Mutex m_app_shm_mutex
Protects m_app_shm_by_name.
ipc::shm::arena_lend::Owner_shm_pool_listener_for_repository m_shm_arena_pool_listener
This guy needs to be around, with each arena (in our case, out of the box, session_shm()s and app_shm()s) registered against it, for shm::stl::Arena_allocator (and thus STL/allocator-compliant data structures, including containers like our own transport::struc::shm::Capnp_message_builder::Segments_in_shm) to work properly with that arena.
boost::unordered_map< std::string, std::shared_ptr< Arena > > m_app_shm_by_name
The per-app-scope SHM arenas by App::m_name.
flow::async::Single_thread_task_loop m_async_cleanup_worker
Thread used for low-priority periodic low-priority cleanup work. See cleanup().
Private Attributes inherited from ipc::session::Session_server_impl< Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >, Server_session< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > >
const Server_app & m_srv_app_ref
See Session_server public data member.
Related Functions
(Note that these are not member functions.)
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload >
std::ostream & operator<< (std::ostream &os, const Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > &val)
Prints string representation of the given Session_server to the given ostream.
Related Functions inherited from ipc::session::Session_server_impl< Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >, Server_session< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > >
std::ostream & operator<< (std::ostream &os, const Session_server_impl< Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >, Server_session< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > > &val)
Prints string representation of the given Session_server_impl to the given ostream.
Detailed Description
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload>
class ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >
This is to vanilla Session_server what shm::arena_lend::jemalloc::Server_session is to vanilla Server_session: it is the session-server type that starts SHM-enabled sessions with SHM-jemalloc provider (ipc::shm::arena_lend::jemalloc).
Its API is identical to that of Session_server, except that it emits Server_session_obj that are shm::arena_lend::jemalloc::Server_session and not vanilla Server_session.
Implementation
See similar section of session::Session_server. It explains why we sub-class Session_server_impl and even how how that's used for this SHM-jemalloc scenario. To reiterate:
We use 2 of 2 available customization points of private super-class Session_server_impl. We:
pass-up a per_app_setup_func() that, given the new session's desired Client_app, creates-if-needed the per-app SHM-arena and keeps it open as well as available via this->app_shm(Client_app::m_name); and
parameterize Session_server_impl on shm::arena_lend::jemalloc::Server_session which, during log-in, creates the per-session SHM-arena and keeps it open; saves this->app_shm(Client_app::m_name); and partners with Client_session_impl to set up the lend/borrowing capability between us.
shm::arena_lend::jemalloc::Server_session doc header delves deeply into the entire impl strategy for setting up these arenas. If you read/grok that, then the present class's impl should be straightforward to follow.
Template Parameters
S_MQ_TYPE_OR_NONE See vanilla Session_server.
S_TRANSMIT_NATIVE_HANDLES See vanilla Session_server.
Mdt_payload See vanilla Session_server.
Definition at line 69 of file session_server.hpp.
Member Typedef Documentation
Arena
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Arena = typename Server_session_obj::Base::Arena
Short-hand for shm::arena_lend::jemalloc::Session_mv::Arena. See app_shm() in particular.
Definition at line 99 of file session_server.hpp.
Channels
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Channels = typename Impl::Channels
Short-hand for Session_mv::Channels.
Definition at line 96 of file session_server.hpp.
Impl
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Impl = Session_server_impl <Session_server<S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload>, Server_session<S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload> > private
Short-hand for our base/core impl.
Definition at line 78 of file session_server.hpp.
Lock_guard
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Lock_guard = flow::util::Lock_guard<Mutex> private
Short-hand for Mutex lock.
Definition at line 305 of file session_server.hpp.
Mdt_builder
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Mdt_builder = typename Server_session_obj::Mdt_builder
Metadata builder type passed to mdt_load_func() in advanced async_accept() overload.
Definition at line 93 of file session_server.hpp.
Mdt_reader_ptr
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Mdt_reader_ptr = typename Impl::Mdt_reader_ptr
Short-hand for Session_mv::Mdt_reader_ptr.
Definition at line 90 of file session_server.hpp.
Mutex
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Mutex = flow::util::Mutex_non_recursive private
Short-hand for m_app_shm_mutex type.
Definition at line 302 of file session_server.hpp.
Server_session_obj
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Server_session_obj = shm::arena_lend::jemalloc::Server_session<S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload>
Short-hand for the concrete Server_session-like type emitted by async_accept().
Definition at line 86 of file session_server.hpp.
Structured_msg_builder_config
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Structured_msg_builder_config = typename Server_session_obj::Base::Structured_msg_builder_config
Short-hand for shm::arena_lend::jemalloc::Session_mv::Structured_msg_builder_config.
Definition at line 102 of file session_server.hpp.
Structured_msg_reader_config
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > using ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Structured_msg_reader_config = typename Server_session_obj::Base::Structured_msg_reader_config
Short-hand for shm::arena_lend::jemalloc::Session_mv::Structured_msg_reader_config.
Definition at line 105 of file session_server.hpp.
Constructor & Destructor Documentation
Session_server()
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Session_server (flow::log::Logger * logger_ptr, const Server_app & srv_app_ref, const Client_app::Master_set & cli_app_master_set_ref, Error_code * err_code = 0) explicit
Constructor: identical to session::Session_server ctor.
See its doc header.
Parameters
logger_ptr See above.
srv_app_ref See above.
cli_app_master_set_ref See above.
err_code See above.
Definition at line 371 of file session_server.hpp.
References ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::init_app_shm_as_needed().
Member Function Documentation
app_shm()
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Arena * ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::app_shm (const Client_app & app)
Returns pointer to the per-app SHM-arena, whose lifetime extends until *this is destroyed; or null if the given Client_app has not yet opened at least 1 shm::arena_lend::jemalloc::Server_session via async_accept().
Alternatively you may use shm::arena_lend::jemalloc::Session_mv::app_shm() off any session object filled-out by *this async_accept(), as long as its Server_session_mv::client_app() equals app (by App::m_name equality).
If non-null is returned, then the same pointer value shall be returned for all subsequent calls with the same (by App::m_name equality) app. The non-null pointers returned for any 2 calls, where app is different (by App::m_name equality) among them, shall always differ.
See shm::arena_lend::jemalloc::Session_mv::Arena doc header for useful instructions on working with Arena, lend_object(), and borrow_object().
Perf
Given the choice between Server_session_mv::app_shm() and the present method, the latter is somewhat slower; internally it involves a mutex-protected map lookup, while the former simply returns a cached pointer as of this writing.
Generally it is also quite fast for the user to save any non-null value returned by either app_shm(); the pointer returned shall always be the same after all.
Thread safety
For internal use, namely by shm::arena_lend::jemalloc::Server_session_impl::async_accept_log_in() at least, it is guaranteed the app_shm() may be called on the same *this concurrently to itself and init_app_shm_as_needed(). Formally speaking this isn't publicly documented, as I (ygoldfel) didn't want to get users into any bad habit, but internally it does have this property – as it is required.
Parameters
app Client_app whose segregated SHM-arena to return, if a session for a client of the app has been opened prior to this call.
Returns
Pointer to *this-held per-app SHM-arena, if it has been created; null otherwise. See above.
Definition at line 479 of file session_server.hpp.
app_shm_builder_config()
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Structured_msg_builder_config ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::app_shm_builder_config (const Client_app & app)
Returns builder config suitable for capnp-serializing out-messages in SHM arena app_shm() for the same Client_app app.
Alternatively you may use shm::arena_lend::jemalloc::Session_mv::app_shm_builder_config() off any session object filled-out by *this async_accept(), as long as its Server_session_mv::client_app() equals app (by App::m_name equality).
Unlike app_shm() this method does not allow the case where app_shm(app) would have returned null. In that case the present method yields undefined behavior (assertion may trip).
Perf
Given the choice between Server_session_mv::app_shm_builder_config() and the present method, the latter is somewhat slower (reason: same as listed in app_shm() doc header).
Generally it is also quite fast for the user to save any value returned by either app_shm_builder_config(), as an equal-by-value Config object shall be returned for the same (by App::m_name equality) app.
Parameters
app See app_shm().
Returns
See above.
Definition at line 503 of file session_server.hpp.
app_shm_lender_session()
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > Structured_msg_builder_config::Builder::Session ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::app_shm_lender_session (const Client_app & app)
In short, what app_shm_builder_config() is to shm::arena_lend::jemalloc::Session_mv::app_shm_builder_config(), this is to shm::arena_lend::jemalloc::app_shm_lender_session().
Notes in app_shm_builder_config() doc header apply here.
Parameters
app See app_shm().
Returns
See above.
app_shm_ptr()
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > std::shared_ptr< typename Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Arena > ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::app_shm_ptr (const Client_app & app)
Identical to app_shm() but returns that via a shared_ptr-handle as required for work directly within ipc::shm::arena_lend::jemalloc APIs.
Note this is a quirk of that particular API and, in particular, has no equivalent in ipc::session::shm::classic Session and Session_server counterparts. It should not be necessary to use except when going beyond ipc::session for your SHM-arena needs.
Parameters
app See above.
Returns
See above.
Definition at line 485 of file session_server.hpp.
References ipc::session::App::m_name.
app_shm_reader_config()
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Structured_msg_reader_config ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::app_shm_reader_config (const Client_app & app)
Returns reader config counterpart to app_shm_builder_config() for a given Client_app app.
Parameters
app See app_shm().
Returns
See above.
Definition at line 513 of file session_server.hpp.
async_accept() [1/2]
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > template<typename Task_err , typename N_init_channels_by_srv_req_func , typename Mdt_load_func > void ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::async_accept (Server_session_obj * target_session, Channels * init_channels_by_srv_req, Mdt_reader_ptr * mdt_from_cli_or_null, Channels * init_channels_by_cli_req, N_init_channels_by_srv_req_func && n_init_channels_by_srv_req_func, Mdt_load_func && mdt_load_func, Task_err && on_done_func)
Contract identical to advanced Session_server::async_accept() overload; but internally ensures that the appropriate SHM-jemalloc arenas are available for use in the emitted Server_session_obj.
See doc header for Session_server::async_accept() advanced overload. However additional Error_codes may be emitted on error.
Template Parameters
Task_err See above.
N_init_channels_by_srv_req_func See above.
Mdt_load_func See above.
Parameters
target_session See other async_accept() overload.
init_channels_by_srv_req See above.
mdt_from_cli_or_null See above.
init_channels_by_cli_req See above.
n_init_channels_by_srv_req_func See above.
mdt_load_func See above.
on_done_func See above.
Definition at line 540 of file session_server.hpp.
async_accept() [2/2]
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > template<typename Task_err > void ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::async_accept (Server_session_obj * target_session, Task_err && on_done_func)
Contract identical to simpler session::Session_server::async_accept() overload; but internally ensures that the appropriate SHM-jemalloc arenas are available for use in the emitted Server_session_obj.
See doc header for session::Session_server::async_accept() simple overload. However additional Error_codes may be emitted on error.
Template Parameters
Task_err See above.
Parameters
target_session See above. Reminder (though this is enforced at compile-time): the type of *target_session for Session_server::async_accept() is Server_session; whereas here it is shm::arena_lend::jemalloc::Server_session.
on_done_func See above.
Definition at line 523 of file session_server.hpp.
cleanup()
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > void ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::cleanup private
Invoked on m_async_cleanup_worker, performs a round of the SHM-pool cleanup algorithm and schedules same.
Definition at line 560 of file session_server.hpp.
References ipc::session::decompose_conventional_shared_name(), ipc::util::process_running(), ipc::util::Shared_name::S_RESOURCE_TYPE_ID_SHM, ipc::util::Shared_name::S_SEPARATOR, ipc::session::shm::arena_lend::jemalloc::SHM_SUBTYPE_PREFIX, ipc::util::Shared_name::size(), and ipc::util::Shared_name::str().
init_app_shm_as_needed()
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > Error_code ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::init_app_shm_as_needed (const Client_app & app) private
Analogous to classic::Session_server::init_app_shm_as_needed().
See that doc header.
Parameters
app See above.
Returns
See above.
Definition at line 396 of file session_server.hpp.
References ipc::session::build_conventional_shared_name(), ipc::util::Shared_name::ct(), ipc::session::App::m_name, ipc::util::Shared_name::S_RESOURCE_TYPE_ID_SHM, ipc::session::shm::arena_lend::jemalloc::error::S_SHM_ARENA_CREATION_FAILED, ipc::util::shared_resource_permissions(), and ipc::session::shm::arena_lend::jemalloc::SHM_SUBTYPE_PREFIX.
Referenced by ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::Session_server().
shm_arena_pool_listener()
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > ipc::shm::arena_lend::Owner_shm_pool_listener_for_repository * ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::shm_arena_pool_listener
Returns the arena-pool listener maintained throughout *this Session_server's life.
One must register it with any arena A, if one wants to do A.construct<T>(), where T is an allocator-compliant data structure type with shm::stl::Stateless_allocator. (Session_server does so automatically for any Arena it maintains out of the box, namely Session_mv::session_shm() and the ones returned by app_shm().) This may be useful if creating your own custom-purpose Arena; instead you can create your own Owner_shm_pool_listener_for_repository, but it is generally encouraged to not do so unnecessarily.
Returns
See above.
Definition at line 554 of file session_server.hpp.
to_ostream()
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > void ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::to_ostream (std::ostream * os) const
Prints string representation to the given ostream.
Parameters
os Stream to which to write.
Definition at line 708 of file session_server.hpp.
Friends And Related Function Documentation
operator<<()
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > std::ostream & operator<< (std::ostream & os, const Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > & val) related
Prints string representation of the given Session_server to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 714 of file session_server.hpp.
Member Data Documentation
m_app_shm_by_name
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > boost::unordered_map<std::string, std::shared_ptr<Arena> > ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::m_app_shm_by_name private
The per-app-scope SHM arenas by App::m_name.
If it's not in the map, it has not been needed yet. If it is but is null, it has but error caused it to not be set-up successfully.
Definition at line 353 of file session_server.hpp.
m_app_shm_mutex
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > Mutex ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::m_app_shm_mutex mutable private
Protects m_app_shm_by_name.
Definition at line 330 of file session_server.hpp.
m_async_cleanup_worker
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > flow::async::Single_thread_task_loop ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::m_async_cleanup_worker private
Thread used for low-priority periodic low-priority cleanup work. See cleanup().
Definition at line 356 of file session_server.hpp.
m_shm_arena_pool_listener
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > ipc::shm::arena_lend::Owner_shm_pool_listener_for_repository ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::m_shm_arena_pool_listener private
This guy needs to be around, with each arena (in our case, out of the box, session_shm()s and app_shm()s) registered against it, for shm::stl::Arena_allocator (and thus STL/allocator-compliant data structures, including containers like our own transport::struc::shm::Capnp_message_builder::Segments_in_shm) to work properly with that arena.
Details:
It is recommended there are not tons of these lying around, but in a production application there should be one session::Session_server around at a time at most. So keeping this here makes sense. Note we didn't, say, put one in each Server_session_impl.
It is not a problem if there is more than one per process; so if there are more sessions around in the process, it won't cause any problem. It's not a singleton situation.
There is also one in each Client_session_impl.
Definition at line 347 of file session_server.hpp.
m_srv_app_ref
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > const Server_app& ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::m_srv_app_ref private
Identical to Session_server::m_srv_app_ref. Used in init_app_shm_as_needed() name calc.
Definition at line 324 of file session_server.hpp.
m_srv_namespace
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > const Shared_name ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::m_srv_namespace private
Identical Session_base::m_srv_namespace. Used in init_app_shm_as_needed() name calc.
Definition at line 327 of file session_server.hpp.
The documentation for this class was generated from the following files:
session/shm/arena_lend/jemalloc/jemalloc_fwd.hpp
session/shm/arena_lend/jemalloc/session_server.hpp