Flow-IPC: ipc::transport::struc::Msg_out< Message_body, Struct_builder_t > Class Template Reference
ipc::transport::struc::Msg_out< Message_body, Struct_builder_t > Class Template Reference
A structured out-message suitable to be sent via struc::Channel::send().
#include <msg.hpp>
Public Types
using Body = Message_body
See struc::Channel::Msg_body.
using Body_builder = typename Body::Builder
Short-hand for capnp-generated mutating Builder nested class of Body. See body_root().
using Builder = Struct_builder_t
Short-hand for user-specified Struct_builder type.
using Builder_config = typename Builder::Config
Short-hand for user-specified Struct_builder::Config.
using Orphanage = ::capnp::Orphanage
Short-hand for capnp orphan factory. See orphanage().
Public Member Functions
Msg_out (const Builder_config &struct_builder_config)
Creates blank Body-bearing out-message message, with no native handle, all of which can be modified via body_root() and the ancillary mutator store_native_handle_or_null().
Msg_out (Builder &&struct_builder)
Advanced technique: Creates message by subsuming the provided already-prepared Capnp_msg_builder_interface-bearing, root-initialized-to-Body Builder object (which is moved-to *this), with no native handle, all of which can be (further) modified via body_root() and the ancillary mutator store_native_handle_or_null().
Msg_out ()
Creates non-message; any operation except move-to or destruction results in undefined behavior subsequently.
Msg_out (Msg_out &&src)
Move ctor: Make *this equal to src, while src becomes as-if default-cted (in that any operation except move-to or destruction results in undefined behavior subsequently).
Msg_out (const Msg_out &)=delete
Disallow copying.
~Msg_out ()
Returns resources, including potentially significant RAM resources and native_handle_or_null(), taken throughout; in the case of SHM-based RAM resources their return may be delayed until counterpart Msg_ins are also destroyed.
Msg_out & operator= (Msg_out &&src)
Move assignment: Destroy *this contents; make *this equal to src, while src becomes as-if default-cted (in that any operation except move-to or destruction results in undefined behavior subsequently).
Msg_out & operator= (const Msg_out &)=delete
Disallow copying.
Body_builder * body_root ()
The Body root capnp-generated mutator object.
const Body_builder * body_root () const
Equivalent to the other body_root() overload but immutable version.
Orphanage orphanage ()
Convenience method that returns a capnp::Orphan factory in the same capnp::MessageBuilder as body_root().
void store_native_handle_or_null (Native_handle &&native_handle_or_null)
Store the Native_handle (potentially .null(), meaning none) in this out-message; no-ops if the same .m_native_handle already stored; otherwise returns the previously stored native handle to the OS (similarly to dtor).
Native_handle native_handle_or_null () const
Returns whatever was the last word according to store_native_handle_or_null().
void to_ostream (std::ostream *os) const
Prints string representation to the given ostream.
Protected Member Functions
void emit_serialization (Segment_ptrs *target_blobs, const typename Builder::Session &session, Error_code *err_code) const
Returns the serialization in the form of a sequence of 1+ Blobs.
size_t n_serialization_segments () const
Returns what target_blobs.size() would return after calling emit_serialization(&target_blobs) (with an empty target_blobs going-in), right now.
Private Attributes
Builder m_builder
The guy serializing a Body. Underlying serialization potentially futher mutated by user via body_root().
Body_builder m_body_root
See body_root().
Native_handle m_hndl_or_null
The Native_handle, if any, embedded inside this message.
Related Functions
(Note that these are not member functions.)
template<typename Message_body , typename Struct_builder_t >
std::ostream & operator<< (std::ostream &os, const Msg_out< Message_body, Struct_builder_t > &val)
Prints string representation of the given Msg_out to the given ostream.
Detailed Description
template<typename Message_body, typename Struct_builder_t>
class ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >
A structured out-message suitable to be sent via struc::Channel::send().
Publicly this can be constructed directly; or via struc::Channel::create_msg(). The latter has the advantage of reusing the serialization engine knobs registered with the channel and hence is simply easier to write. If one uses the direction-construction route, the builder (serialization) engine type – Struct_builder Builder – must match that of the struc::Channel used to send() a *this; otherwise it simply will not compile.
See also
"Lifecycle of an out-message" section of struc::Channel class doc header for useful context.
As explained in that doc section, a Msg_out (struc::Channel::Msg_out) is akin to a container, like vector<uint8_t>; and the Builder template param + ctor arg are akin to the allocator used by such a container. A given *this represents the message payload; it does not represent a particular send()t (past/present/future) instance of that payload. Modifying it is akin to modifying the vector<uint8_t>, albeit in structured-schema fashion – available API controlled by Message_body template param – and with an optionally attached Native_handle.
As explained in that doc section, like any container, once another process has access to it – which is only possible in read-only fashion as of this writing – modifying it must be done with concurrency/synchronization considered. If the compile-time-chosen Builder is SHM-based, then this is a concern. If it is heap-based (notably Heap_fixed_builder), then it is not: the serialization is copied into and out of the transport.
After construction, one mutates the message via body_root() and/or store_native_handle_or_null(). You may also use orphanage() to build the message in bottom-up fashion, eventually grafting pieces in via body_root()->....adopt...(). See orphanage() doc header for more information on this technique. Lastly consider the following section for another, more holistic bottom-up appraoch (or perhaps taking the orphanage technique further).
Advanced technique: Construction from earlier-prepared raw Capnp_msg_builder_interface
To enable the straightforward operation implied above, one uses the 1st/simple ctor form which by definition necessitates specifying the root schema, Body (as to contruct one must know the type). This is typically perfectly natural: a module knows it's building a message of schema Body, so they construct a Msg_out<Body> (which already auto-creates a blank Body via initRoot<Body>()), then fills it out via body_root() (which points to what initRoot() returned). The orphanage technique above is a slight complication, in that things can be built bottom-up, but in any case by then the root schema already had to be specified, even if it's actually mutated only somewhat later, once the component orphan(s) can be plugged in.
When working with capnp outside of ipc, users typically do basically the same thing: start with M.initRoot<Body>(), then set stuff in its tree; or in more complex cases maybe use M.getOrphanage() from the same MessageBuilder M to help build bottom-up.
However consider a complex schema Huge_body built by collaboration between modules A and B. Now module A may be aware the ultimate product is rooted at Huge_body, while module B has no idea, and yet they work together to build parts of the final thing. In that case B does not necessarily think of any particular overall Huge_body tree but only the sub-schema types it cares about; so to it the MessageBuilder M is just a memory pool or heap of sorts; it makes whatever structures it wants (via M.getOrphanage()) from it but does not call or know about initRoot<Huge_body>(). Conceivably, even, module B is first to run its procedures (before module A) and to create M in the first place; and only later module A perhaps finally sets the root (initRoot<HugeBody>()) and attaches whatever orphan values module B produces, hooking them into the HugeBody.
The straightforward use of Msg_out, as described before, does in fact force one (from the start) to specify HugeBody by definition (it's – again – a template argument to the class template), and that may not be desirable in this module A-B scenario. So to support it: use the 2nd/advanced ctor form which takes over (via std::move()) an already-created Builder – not templated on any schema Body. The Builder exposes the direct MessageBuilder, so the tree can be built using whatever features in whatever order one desires... and only then create the Msg_out. The only constraint is that by ctor time, the MessageBuilder (a/k/a Capnp_msg_builder_interface) is initialized to be rooted at Body; but this could be done anytime up to that point; so module B need not do it, while module A might ultimately do it and then construct the Msg_out<Body>. Alternatively, the user can omit performing initRoot<Body>(), and it will be done as needed by the ctor, resulting in a blank message at that point which then can be filled-out via body_root() mutations. (Note: This is just an example. The point is with this technique one can use a MessageBuilder in any fashion desired, and the only constraint is it is in fact rooted at some structure `S, at which point Msg_out<S> can be cted. In that sense it removes any – albeit typically simplifying – ipc::transport constraints on how one builds a message, allowing one to use the full builder API provided by capnp without any stylistic concessions.)
Resource use (RAM)
Creating a *this, and mutating it via body_root(), uses proportionally large RAM resources; e.g., if you successfully store a multi-megabyte blob, *this will allocate RAM accordingly. Conversely, destroying *this returns such resources. However, if Builder is SHM-based, then a process-counting ref-count (conceptually) exists. It is 1 after construction. It is incremented each time it is struc::Channel::send()t. For each such increment, there is a decrement when the receiving process's counterpart Msg_in, which is always passed-around by shared_ptr, is no longer owned by that process (when that shared_ptr group's ref-count drops to zero). Once *this is destroyed, and each send() target process has both yielded the struc::Channel::Msg_in_ptr and let that shared_ptr drop to ref-count-zero, the backing RAM is released.
Resource use: the Native_handle (if any)
It is returned to the OS by our destructor. This does not, necessarily, destroy whatever resource it references: presumably the idea is to send it, via IPC, to the opposing process. The handle (FD) that process receives is really a new one in that process's table; there are at that point two descriptors referencing one resource description, and the latter disappears in the kernel only once both descriptors go away. If you do not wish to let the local handle (FD) be destroyed by *this destructor, consider (in Unix-type OS) passing-in dup(your_hndl) instead of your_hndl itself.
The Native_handle, if any, stored via store_native_handle_or_null() is not a part of the serialization/deserialization/sharing schema described above. It just sits in *this until *this dtor runs (or it is replaced/unloaded via store_native_handle_or_null()). If at send() time there's one in *this, then a copy is transmitted to the recipient process. store_native_handle_or_null() on *this will never have any direct effect on any received copy.
Impl notes
Some important aspects of this class template's API, which must be accessed by the ipc::transport (structured layer) internals only, are protected. struc::Channel then sub-classes this guy and exposes them publicly (to itself). This avoids friend which would would be not quite as clean, since private parts would be exposed too, and so on. In other words this is a class an API – not a mere data-store – but there is an internally used API which is left protected. As of this writing it's essentially emit_serialization() which the user does not access directly (struc::Channel::send() internals do).
The internally-used APIs are reasonably self-explanatory, so just see their doc headers.
Template Parameters
Message_body See struc::Channel.
Struct_builder_t See struc::Channel.
Definition at line 153 of file msg.hpp.
Member Typedef Documentation
Body
template<typename Message_body , typename Struct_builder_t > using ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::Body = Message_body
See struc::Channel::Msg_body.
Definition at line 159 of file msg.hpp.
Body_builder
template<typename Message_body , typename Struct_builder_t > using ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::Body_builder = typename Body::Builder
Short-hand for capnp-generated mutating Builder nested class of Body. See body_root().
Definition at line 162 of file msg.hpp.
Builder
template<typename Message_body , typename Struct_builder_t > using ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::Builder = Struct_builder_t
Short-hand for user-specified Struct_builder type.
An internally stored instance of this contains the user payload.
Definition at line 168 of file msg.hpp.
Builder_config
template<typename Message_body , typename Struct_builder_t > using ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::Builder_config = typename Builder::Config
Short-hand for user-specified Struct_builder::Config.
One can construct a Builder via Builder(const Builder_config&).
Definition at line 174 of file msg.hpp.
Orphanage
template<typename Message_body , typename Struct_builder_t > using ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::Orphanage = ::capnp::Orphanage
Short-hand for capnp orphan factory. See orphanage().
Definition at line 177 of file msg.hpp.
Constructor & Destructor Documentation
Msg_out() [1/4]
template<typename Message_body , typename Struct_builder_t > ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::Msg_out (const Builder_config & struct_builder_config) explicit
Creates blank Body-bearing out-message message, with no native handle, all of which can be modified via body_root() and the ancillary mutator store_native_handle_or_null().
See also the alternate (advanced-technique) ctor form which may be more suitable in more complex scenarios. This is discussed in our class doc header.
Obtaining the Builder_config object
In the first place it is often easier/better to not invoke this ctor directly but rather invoke struc::Channel::create_msg() which will do so for you and supply the proper Builder_config. However it is definitely possible for a Msg_out to be constructed orthogonally to a particular struc::Channel – or even to a particular ipc::Session (if even applicable). How to get the struct_builder_config arg for this ctor then? Informally: if you're constructing the Builder_config directly, you're probably not doing the right thing. The following places are available to obtain one for safety and efficiency (and code maintainability):
From another, compatible, struc::Channel via struc::Channel::struct_builder_config().
Heap-backed:
If you have a target struc::Channel::Owned_channel: via static struc::Channel::heap_fixed_builder_config().
Otherwise: session::Session_mv::heap_fixed_builder_config() (static or non-static).
SHM-backed (e.g., SHM-classic):
session::shm::classic::Session_mv::session_shm_builder_config(), session::shm::classic::Session_mv::app_shm_builder_config(). Requires a Session object.
session::shm::classic::Session_server::app_shm_builder_config() (requires session::Client_app). Server-only; if a Session is not available or applicable.
Parameters
struct_builder_config See above. This is neither memorized nor copied.
Definition at line 874 of file msg.hpp.
Msg_out() [2/4]
template<typename Message_body , typename Struct_builder_t > ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::Msg_out (Builder && struct_builder) explicit
Advanced technique: Creates message by subsuming the provided already-prepared Capnp_msg_builder_interface-bearing, root-initialized-to-Body Builder object (which is moved-to *this), with no native handle, all of which can be (further) modified via body_root() and the ancillary mutator store_native_handle_or_null().
The advanced technique revolving around the use of this ctor form is discussed in our class doc header. That said:
*struct_builder.payload_msg_builder() – a Capnp_msg_builder_interface – must already have been root-initialized, and the root type must be Body; or must not have been root-initialized at all (in which case the ctor will perform initRoot<Body>()).
If it was already root-initialized, but not with <Body>, then behavior is undefined, and the trouble may only be detected on the opposing side upon receipt of *this message, in trying to deserialize it in Msg_in.
If you chose to not root-initialize before this ctor, and therefore it performs initRoot<Body>(), then naturally the message root tree shall be blank, similarly to the other/vanilla ctor.
This is typically accomplished via struct_builder.payload_msg_builder()->initRoot<Body>(), although there are other techniques available. See capnp docs for capnp::MessageBuilder (Capnp_msg_builder_interface).
That having been guaranteed, the message may be further mutated via body_root().
Naturally it may also have already been mutated (beyond initRoot()/etc.), possibly to its final intended form.
Conversely, in practice, if you chose to not root-initialize struct_builder, you'll want to in fact use body_root() mutations to actually load the message with something useful.
For exposition purposes: note that the other ctor form, which takes a Builder::Config, behaves as-if delegating to the present ctor: Msg_out(Builder(struct_builder_config)). When creating a straightforward message in ~one place in the user code, using that other ctor form is usually therefore more convenient, avoiding some boiler-plate.
Parameters
struct_builder See above. Note the requirements listed.
Definition at line 886 of file msg.hpp.
Msg_out() [3/4]
template<typename Message_body , typename Struct_builder_t > ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::Msg_out
Creates non-message; any operation except move-to or destruction results in undefined behavior subsequently.
Definition at line 867 of file msg.hpp.
Msg_out() [4/4]
template<typename Message_body , typename Struct_builder_t > ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::Msg_out (Msg_out< Message_body, Struct_builder_t > && src)
Move ctor: Make *this equal to src, while src becomes as-if default-cted (in that any operation except move-to or destruction results in undefined behavior subsequently).
Parameters
src Source object.
Definition at line 902 of file msg.hpp.
References ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::operator=().
~Msg_out()
template<typename Message_body , typename Struct_builder_t > ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::~Msg_out
Returns resources, including potentially significant RAM resources and native_handle_or_null(), taken throughout; in the case of SHM-based RAM resources their return may be delayed until counterpart Msg_ins are also destroyed.
See class doc header for discussion.
Definition at line 979 of file msg.hpp.
Member Function Documentation
body_root() [1/2]
template<typename Message_body , typename Struct_builder_t > Msg_out< Message_body, Struct_builder_t >::Body_builder * ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::body_root
The Body root capnp-generated mutator object.
E.g.: this->body_root()->initSomeStruct().setSomeField(123) will create the capnp-struct-typed root field someStruct and set the value someField – presumably an integer – within it. The pointer returned shall always be the same value until *this is destroyed.
Body_builder is light-weight, so you may make a copy and then mutate via that, if desired. However whether *(body_root()) or such a copy, such a Builder object may not be accessed after *this is destroyed.
Informally we recommend against copying *(body_root()): Light-weight or not, it's a copy, and copying a pointer is cheaper; and it may not live past *this anyway; and body_root() always returns the same pointer. So just store the pointer (or reference from it).
Quick capnp tips
You should really read all of capnp docs at its web site. They are very useful and well written and not overly formal despite being quite comprehensive. That said a couple of gotchas/tips:
On a Builder, .getX() and .setX() are lightning-fast, like accessing struct members directly – but only when X is of a scalar type. Compound types, where .getX() returns not a native type but another Builder, need to perform some pointer checking and are slower. Therefore, if you plan to .getX() and then .setA() and .setB() (and similar) on that X, you should save the result (auto x = ....getX();); then mutate via the saved result (x.setA(...); x.setB(...)).
Let X be a compound field, particularly List, Text (string/list-of-characters), Data (list-of-bytes). It is usually, to begin, null; you must perform .initX(size_t n) or equivalent to initialize it (fill it with n zeroes). However, suppose you are mutating a message, such as a previously-sent message, and wish to modify the X. If the new value might have the same length (which is common), the correct thing to do is: check .hasX(); if true, modify .getX(); but if false then .initX(n) (as X was null after all). Performing .initX() on an already-.initX()ed value works but has a nasty invisible effect: the existing datum continues taking space in the serialization; the new datum takes a new chunk of the serialization segments (and might even cause the allocation of a new segment if needed). As of this writing capnp does not reuse such orphaned space. If the new n equals the old n, this is a straight waste of RAM; and can lead to pathologically growing memory leaks if done many times.
However, if the new n is different from the preceding, then there is no choice but to re-.initX(). A list/blob/string's size cannot be modified in capnp.
It is best to avoid any situation where the n would change; try to design your protocol differently.
Returns
See above.
Definition at line 1018 of file msg.hpp.
Referenced by ipc::transport::struc::Msg_mdt_out< Struct_builder_config >::Msg_mdt_out(), and ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::send_core().
body_root() [2/2]
template<typename Message_body , typename Struct_builder_t > const Msg_out< Message_body, Struct_builder_t >::Body_builder * ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::body_root
Equivalent to the other body_root() overload but immutable version.
May be useful for, say, pretty-printing it to log (e.g.: capnp::prettyPrint(M.body_root()->asReader()).flatten().cStr()).
Returns
See above.
Definition at line 1024 of file msg.hpp.
emit_serialization()
template<typename Message_body , typename Struct_builder_t > void ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::emit_serialization (Segment_ptrs * target_blobs, const typename Builder::Session & session, Error_code * err_code) const protected
Returns the serialization in the form of a sequence of 1+ Blobs.
It is meant to be invoked at struc::Channel::send() time.
It can be invoked repeatedly: session can specify a different destination each time; or the same destination each time; or an arbitrary mix thereof. In particular struc::Channel::send() (and its derivatives struc::Channel::sync_request(), struc::Channel::async_request()) shall each time specify the channel's opposing process as the destination – regardless of which struc::Channel's struc::Channel::create_msg() originally generated *this (assuming that method was even used for construction of *this – in no way required, just often convenient).
See also
our class doc header and/or "Lifecycle of an out-message" section of struc::Channel class doc header. Recall that where it mentions struc::Channel::send(), you can understand there a 1-1 relationship with a synchronous call to this->emit_serialization().
Errors
See Struct_builder::emit_serialization(). This essentially forwards to that and emits its errors if any. Out-arg native_handle_or_null is untouched on error.
Parameters
target_blobs On success (no error emitted) this is cleared and replaced with the sequence of segments as Blobs.
session Specifies the opposing recipient for which the serialization is intended. If Builder::Session is Null_session, then Session() is the only value to supply here. Otherwise more information is necessary.
err_code See flow::Error_code docs for error reporting semantics. See above.
Definition at line 1059 of file msg.hpp.
n_serialization_segments()
template<typename Message_body , typename Struct_builder_t > size_t ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::n_serialization_segments protected
Returns what target_blobs.size() would return after calling emit_serialization(&target_blobs) (with an empty target_blobs going-in), right now.
Returns
See above.
Definition at line 1066 of file msg.hpp.
native_handle_or_null()
template<typename Message_body , typename Struct_builder_t > Native_handle ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::native_handle_or_null
Returns whatever was the last word according to store_native_handle_or_null().
Note it is a copy; *this retains ownership of the OS resource.
Returns
See ctor (which stores no handle), store_native_handle_or_null().
Definition at line 1053 of file msg.hpp.
Referenced by ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::check_unsendable(), and ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::send_core().
operator=()
template<typename Message_body , typename Struct_builder_t > Msg_out< Message_body, Struct_builder_t > & ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::operator= (Msg_out< Message_body, Struct_builder_t > && src)
Move assignment: Destroy *this contents; make *this equal to src, while src becomes as-if default-cted (in that any operation except move-to or destruction results in undefined behavior subsequently).
no-op if &src == this.
Parameters
src Source object.
Returns
*this.
Definition at line 988 of file msg.hpp.
Referenced by ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::Msg_out().
orphanage()
template<typename Message_body , typename Struct_builder_t > Msg_out< Message_body, Struct_builder_t >::Orphanage ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::orphanage
Convenience method that returns a capnp::Orphan factory in the same capnp::MessageBuilder as body_root().
Therefore Orphans generated via the returned Orphanage can be adopt...()ed by the Builder *(body_root()) and its various sub-fields' Builders (at any depth).
Suggested technique
In general, the orphan concept is discussed briefly but usefully in the "C++ serialization" section of capnp docs (the web site). We do not attempt to get into all these topics. However consider the following pattern.
In general the Flow-IPC system places almost no constraints on Body (the schema), but there is one: Generally there must be an anonymous capnp-union at the top of Body, and in practice any message will eventually load the root (body_root()) with one of the union choices. (This is to operate within the struc::Channel::expect_msg() and struc::Channel::expect_msgs() APIs.) The vanilla approach to building the message is top-down: body_root() is pre-initialized to be a Body; then, say, if your plan is to load it with the union choice someChoice, then you'd do body_root()->initSomeChoice(); then mutate stuff inside the Builder returned by that. There could be an arbitrarily complex sub-tree within that, built top-down in the same fashion.
Instead you may choose to build it bottom-up. For this discussion let's assume struct SomeChoice has a number of scalars. You would first obtain and save an Orphanage: auto orphan_factory = M.orphanage(). Next you would create an orphan, not yet connected to the root body_root(), like so: auto some_choice_orphan = orphan_factory.newOrphan<SomeChoice>(); some_choice_builder = some_choice_orphan.get(). Next you'd set the scalars within it: some_choice_builder.set...(...). Lastly, when it's ready, graft it into the actual root: body_root()->adoptSomeChoice(some_choice_orphan).
Due to the simplicity of this example one might wonder why not simply build it top-down in the first place. Indeed. However, if struct SomeChoice is a complex tree of structs within Lists within (...), it would be reasonable to build the lowest levels of that tree by generating intermediate orphans (via orphan_factory.newOrphan<LowerLevelStructOrListOrWhatever>()), adopting them into higher-level orphans, and so on, finishing it via the top-level body_root()->adoptSomeChoice() call.
Similar technique
See also the 2nd (advanced) ctor form. It allows one to do the above but takes it further by not even needing a Msg_out until the time comes to actually struc::Channel::send() the message. I.e., one would work with essentially a Capnp_msg_builder_interface directly, including invoking Capnp_msg_builder_interface.getOrphanage().
Returns
See above.
Definition at line 1030 of file msg.hpp.
store_native_handle_or_null()
template<typename Message_body , typename Struct_builder_t > void ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::store_native_handle_or_null (Native_handle && native_handle_or_null)
Store the Native_handle (potentially .null(), meaning none) in this out-message; no-ops if the same .m_native_handle already stored; otherwise returns the previously stored native handle to the OS (similarly to dtor).
Parameters
native_handle_or_null The Native_handle (.null() == true if none) to move into *this. Made .null() == true upon return.
Definition at line 1038 of file msg.hpp.
References ipc::transport::asio_local_stream_socket::release_native_peer_socket().
Referenced by ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::create_msg().
to_ostream()
template<typename Message_body , typename Struct_builder_t > void ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::to_ostream (std::ostream * os) const
Prints string representation to the given ostream.
This representation lacks newlines/indentation; includes a (potentially truncated) pretty-printed representation of body_root() contents; and includes native_handle_or_null().
Caution: This could be an operation expensive in processor cycles and, temporarily, RAM; and thus should be used judiciously. To help drive your decision-making: This method, internally,
uses capnp kj::str(*(this->body_root)) to generate a full pretty-print of body_root() contents;
truncates the result of the latter, as needed for a reasonably short output, and prints the result;
adds native_handle_or_null() and possibly a few other small information items.
Because there is no reasonably-available way to stop generating the pretty-print in step 1 upon reaching a certain number of characters, the operation may take a while, if many non-default bytes have been mutated-in; and before truncation the resulting string may take significant RAM accordingly.
Parameters
os Stream to which to write.
Definition at line 1072 of file msg.hpp.
Friends And Related Function Documentation
operator<<()
template<typename Message_body , typename Struct_builder_t > std::ostream & operator<< (std::ostream & os, const Msg_out< Message_body, Struct_builder_t > & val) related
Prints string representation of the given Msg_out to the given ostream.
Namely it prints via Msg_out::to_ostream()`; be sure to read perf notes on that!
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 1108 of file msg.hpp.
Member Data Documentation
m_body_root
template<typename Message_body , typename Struct_builder_t > Body_builder ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::m_body_root private
See body_root().
Rationale
We don't strictly need to save this; we could have body_root() return the Body_builder, not a pointer to it. This would not be out of line; it is a general capnp-documented tip to act on a given Builder repeatedly as opposed to accessing it via an accessor each time; so we could encourage the user to do that – not our problem. (Though I (ygoldfel) am not positive that perf tip applies to the root capnp-struct; maybe look into it sometime for education.) It would also reduce *this footprint a bit and simplify/speed-up the move-ctor and move-assignment somewhat (a capnp Builder is light-weight but not totally tiny, consisting of a few pointers and integers). So why do this?
Honestly keeping it this way is firstly a historic artifact from an earlier situation where keeping a pointer made sense in a no-longer-relevant sense (explaining how here would be uninteresting). That said it's a fairly cheap little optimization that allows the repeated use of body_root() with no perf penalty, and it is nice and expressive to have a non-const accessor returning a pointer to the thing that would mutate *this. Similarly it's nice to have a const accessor returning pointer-to-const suitable for pretty-printing. Throw in now having to change existing call sites, and voila, this decision.
Definition at line 480 of file msg.hpp.
m_builder
template<typename Message_body , typename Struct_builder_t > Builder ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::m_builder private
The guy serializing a Body. Underlying serialization potentially futher mutated by user via body_root().
Definition at line 459 of file msg.hpp.
m_hndl_or_null
template<typename Message_body , typename Struct_builder_t > Native_handle ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::m_hndl_or_null private
The Native_handle, if any, embedded inside this message.
Definition at line 483 of file msg.hpp.
The documentation for this class was generated from the following files:
transport/struc/msg.hpp
transport/struc/struc_fwd.hpp