Flow-IPC: ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle > Class Template Reference
ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle > Class Template Reference
Internal implementation of Blob_stream_mq_base class template; and common utilities used by Blob_stream_mq_sender_impl and Blob_stream_mq_receiver_impl (static items only as of this writing).
#include <blob_stream_mq_impl.hpp>
Public Types
using Mq = Persistent_mq_handle
Short-hand for template arg for underlying MQ handle type.
using Auto_closing_mq = boost::movelib::unique_ptr< Mq, Function< void(Mq *)> >
Persistent_mq_handle holder that takes a deleter lambda on construction, intended here to perform additional deinit steps in addition to closing the Mq by deleting it.
Static Public Member Functions
static void remove_persistent (flow::log::Logger *logger_ptr, const Shared_name &name, Error_code *err_code)
See Blob_stream_mq_base counterpart.
template<typename Handle_name_func >
static void for_each_persistent (const Handle_name_func &handle_name_func)
See Blob_stream_mq_base counterpart.
static Auto_closing_mq ensure_unique_peer (flow::log::Logger *logger_ptr, Mq &&mq, bool snd_else_rcv, Error_code *err_code)
Internal helper for Blob_stream_mq_sender and Blob_stream_mq_receiver that operates both the start and end of the anti-dupe-endpoint machinery used by those 2 classes to prevent more than 1 _sender and more than 1 _receiver for a given underlying MQ.
Protected Types
enum class Control_cmd : uint64_t { S_END_SENDING , S_PING , S_END_SENTINEL }
If Blob_stream_mq_sender_impl sends an empty message, in NORMAL state Blob_stream_mq_receiver enters CONTROL state and expects one of these values in the next message, to react as documented per enum value (upon re-entering NORMAL state).
Static Private Member Functions
static Shared_name mq_sentinel_name (const Shared_name &mq_name, bool snd_else_rcv)
Name of sentinel SHM pool created by ensure_unique_peer() and potentially cleaned up by remove_persistent().
Detailed Description
template<typename Persistent_mq_handle>
class ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle >
Internal implementation of Blob_stream_mq_base class template; and common utilities used by Blob_stream_mq_sender_impl and Blob_stream_mq_receiver_impl (static items only as of this writing).
Template Parameters
Persistent_mq_handle See Persistent_mq_handle concept doc header.
Definition at line 41 of file blob_stream_mq_impl.hpp.
Member Typedef Documentation
Auto_closing_mq
template<typename Persistent_mq_handle > using ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle >::Auto_closing_mq = boost::movelib::unique_ptr<Mq, Function<void (Mq*)> >
Persistent_mq_handle holder that takes a deleter lambda on construction, intended here to perform additional deinit steps in addition to closing the Mq by deleting it.
Used by ensure_unique_peer() machinery.
Definition at line 53 of file blob_stream_mq_impl.hpp.
Mq
template<typename Persistent_mq_handle > using ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle >::Mq = Persistent_mq_handle
Short-hand for template arg for underlying MQ handle type.
Definition at line 47 of file blob_stream_mq_impl.hpp.
Member Enumeration Documentation
Control_cmd
template<typename Persistent_mq_handle > enum class ipc::transport::Blob_stream_mq_base_impl::Control_cmd : uint64_t strong protected
If Blob_stream_mq_sender_impl sends an empty message, in NORMAL state Blob_stream_mq_receiver enters CONTROL state and expects one of these values in the next message, to react as documented per enum value (upon re-entering NORMAL state).
Enumerator
S_END_SENDING
Indicates sender user invoked Blob_sender::end_sending() (graceful close). Emit/queue graceful-close to user.
S_PING
Indicates sender user invoked auto_ping() earlier, and this is an incoming periodic ping.
If receiver user invoked idle_timer_run() earlier, reset countdown to death due to lacking in-pings.
S_END_SENTINEL
Sentinel: not a valid value. May be used to, e.g., ensure validity of incoming value of allegedly this type.
Definition at line 118 of file blob_stream_mq_impl.hpp.
Member Function Documentation
ensure_unique_peer()
template<typename Persistent_mq_handle > Blob_stream_mq_base_impl< Persistent_mq_handle >::Auto_closing_mq ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle >::ensure_unique_peer (flow::log::Logger * logger_ptr, Mq && mq, bool snd_else_rcv, Error_code * err_code) static
Internal helper for Blob_stream_mq_sender and Blob_stream_mq_receiver that operates both the start and end of the anti-dupe-endpoint machinery used by those 2 classes to prevent more than 1 _sender and more than 1 _receiver for a given underlying MQ.
The input is a handle to the MQ, as created by user as of this writing, either on the sender or receiver end (snd_else_rcv). The output is one of:
a null return, indicating that either there's already a sender (or receiver) already registered (typically), or some other (unlikely) system error. *err_code will indicate what happened; or
a non-null returned unique_ptr that has moved mq into itself/taken over ownership of it, with certain machinery such that when that unique_ptr (or moved version thereof) is .reset() or destroyed, the proper deinit will run, making it possible to create another MQ at the same Shared_name.
mq is untouched if null is returned.
Parameters
logger_ptr Logger to use subsequently. Errors are logged as WARNING; otherwise nothing of INFO or higher verbosity is logged.
mq See above.
snd_else_rcv true if this is the sender side; else the receiver side.
err_code Must not be null, or behavior undefined; will be set to success if non-null returned or reason for failure otherwise.
Returns
null or pointer to new Persistent_mq_handle moved-from mq, and with deinit deleter.
Definition at line 206 of file blob_stream_mq_impl.hpp.
References ipc::transport::Persistent_mq_handle::absolute_name(), ipc::util::CREATE_ONLY, ipc::util::remove_persistent_shm_pool(), ipc::transport::error::S_BLOB_STREAM_MQ_RECEIVER_EXISTS, and ipc::transport::error::S_BLOB_STREAM_MQ_SENDER_EXISTS.
Referenced by ipc::transport::sync_io::Blob_stream_mq_receiver_impl< Persistent_mq_handle >::Blob_stream_mq_receiver_impl(), and ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Blob_stream_mq_sender_impl().
for_each_persistent()
template<typename Persistent_mq_handle > template<typename Handle_name_func > void ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle >::for_each_persistent (const Handle_name_func & handle_name_func) static
See Blob_stream_mq_base counterpart.
Template Parameters
Handle_name_func See Blob_stream_mq_base counterpart.
Parameters
handle_name_func See Blob_stream_mq_base counterpart.
Definition at line 185 of file blob_stream_mq_impl.hpp.
Referenced by ipc::transport::Blob_stream_mq_base< Persistent_mq_handle >::for_each_persistent().
mq_sentinel_name()
template<typename Persistent_mq_handle > Shared_name ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle >::mq_sentinel_name (const Shared_name & mq_name, bool snd_else_rcv) static private
Name of sentinel SHM pool created by ensure_unique_peer() and potentially cleaned up by remove_persistent().
Parameters
mq_name mq.absolute_name(). See ensure_unique_peer().
snd_else_rcv See ensure_unique_peer().
Returns
Absolute name.
Definition at line 331 of file blob_stream_mq_impl.hpp.
References ipc::util::Shared_name::absolute(), ipc::util::build_conventional_non_session_based_shared_name(), and ipc::util::Shared_name::S_RESOURCE_TYPE_ID_SHM.
remove_persistent()
template<typename Persistent_mq_handle > void ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle >::remove_persistent (flow::log::Logger * logger_ptr, const Shared_name & name, Error_code * err_code) static
See Blob_stream_mq_base counterpart.
Parameters
logger_ptr See Blob_stream_mq_base counterpart.
name See Blob_stream_mq_base counterpart.
err_code See Blob_stream_mq_base counterpart.
Definition at line 151 of file blob_stream_mq_impl.hpp.
References ipc::util::remove_persistent_shm_pool().
Referenced by ipc::transport::Blob_stream_mq_base< Persistent_mq_handle >::remove_persistent().
The documentation for this class was generated from the following file:
transport/detail/blob_stream_mq_impl.hpp