Flow-IPC: ipc::shm::classic::Pool_arena Class Reference
ipc::shm::classic::Pool_arena Class Reference
A SHM-classic interface around a single SHM pool with allocation-algorithm services by boost.interprocess, as in bipc::managed_shared_memory, with symmetric read/write semantics, compatible with ipc::shm::stl STL-compliance and SHM-handle borrowing manually or via ipc::session.
#include <pool_arena.hpp>
Classes
struct Handle_in_shm
The data structure stored in SHM corresponding to an original construct()-returned Handle; exactly one of which exists per construct() call invoked from any Pool_arena connected to the underlying pool.
Public Types
template<typename T >
using Pointer = ::ipc::bipc::offset_ptr< T >
SHM-storable fancy-pointer.
template<typename T >
using Handle = boost::shared_ptr< T >
Outer handle to a SHM-stored object; really a regular-looking shared_ptr but with custom deleter that ensures deallocation via Pool_arena as well as cross-process ref-count semantics.
using Blob = flow::util::Blob_sans_log_context
Alias for a light-weight blob.
Public Member Functions
Pool_arena (flow::log::Logger *logger_ptr, const Shared_name &pool_name, util::Create_only mode_tag, size_t pool_sz, const util::Permissions &perms=util::Permissions(), Error_code *err_code=0)
Construct Pool_arena accessor object to non-existing named SHM pool, creating it first.
Pool_arena (flow::log::Logger *logger_ptr, const Shared_name &pool_name, util::Open_or_create mode_tag, size_t pool_sz, const util::Permissions &perms_on_create=util::Permissions(), Error_code *err_code=0)
Construct Pool_arena accessor object to non-existing named SHM pool, or else if it does not exist creates it first and opens it (atomically).
Pool_arena (flow::log::Logger *logger_ptr, const Shared_name &pool_name, util::Open_only mode_tag, bool read_only=false, Error_code *err_code=0)
Construct Pool_arena accessor object to existing named SHM pool.
~Pool_arena ()
Destroys Pool_arena accessor object.
void * allocate (size_t n)
Allocates buffer of specified size, in bytes, in the accessed pool; returns locally-derefernceable address to the first byte.
bool deallocate (void *buf_not_null) noexcept
Undoes effects of local allocate() that returned buf_not_null; or another-process's allocate() that returned pointer whose locally-dereferenceable equivalent is but_not_null.
template<typename T , typename... Ctor_args>
Handle< T > construct (Ctor_args &&... ctor_args)
Constructs an object of given type with given ctor args, having allocated space directly in attached SHM pool, and returns a ref-counted handle that (1) guarantees destruction and deallocation shall occur once no owners hold a reference; and (2) can be lent to other processes (and other processes still indefinitely), thus adding owners beyond this process, via lend_object()/borrow_object().
template<typename T >
Blob lend_object (const Handle< T > &handle)
Adds an owner process to the owner count of the given construct()-created handle, and returns an opaque blob, such that if one passes it to borrow_object() in the receiving process, that borrow_object() shall return an equivalent Handle in that process.
template<typename T >
Handle< T > borrow_object (const Blob &serialization)
Completes the cross-process operation begun by lend_object() that returned serialization; to be invoked in the intended new owner process.
template<typename T >
bool is_handle_in_arena (const Handle< T > &handle) const
Returns true if and only if handle came from either this->construct<T>() or this->borrow_object<T>().
Static Public Member Functions
static void remove_persistent (flow::log::Logger *logger_ptr, const Shared_name &name, Error_code *err_code=0)
Removes the named SHM pool object.
template<typename Handle_name_func >
static void for_each_persistent (const Handle_name_func &handle_name_func)
Lists all named SHM pool objects currently persisting, invoking the given handler synchronously on each one.
Public Attributes
const Shared_name m_pool_name
SHM pool name as set immutably at construction.
Private Types
using Pool = ::ipc::bipc::managed_shared_memory
The SHM pool type one instance of which is managed by *this.
Private Member Functions
template<typename Mode_tag >
Pool_arena (Mode_tag mode_tag, flow::log::Logger *logger_ptr, const Shared_name &pool_name, size_t pool_sz, const util::Permissions &perms, Error_code *err_code)
Helper ctor delegated by the 2 public ctors that take Open_or_create or Create_only mode.
template<typename T >
void handle_deleter_impl (Handle_in_shm< T > *handle_state)
Identical deleter for Handle returned by both construct() and borrow_object(); invoked when a given process's (borrow_object() caller's) shared_ptr group reaches ref-count 0.
Static Private Member Functions
template<typename T , typename... Ctor_args>
static void construct_at (T *obj, Ctor_args &&... ctor_args)
std::construct_at() equivalent; unavailable until C++20, so here it is.
Private Attributes
boost::movelib::unique_ptr< Pool > m_pool
Attached SHM pool. If ctor fails in non-throwing fashion then this remains null. Immutable after ctor.
Related Functions
(Note that these are not member functions.)
std::ostream & operator<< (std::ostream &os, const Pool_arena &val)
Prints string representation of the given Pool_arena to the given ostream.
Detailed Description
A SHM-classic interface around a single SHM pool with allocation-algorithm services by boost.interprocess, as in bipc::managed_shared_memory, with symmetric read/write semantics, compatible with ipc::shm::stl STL-compliance and SHM-handle borrowing manually or via ipc::session.
When to use
Generally, this is a simple way to work with SHM. It is very easy to set up and has very little infrastructure on top of what is provided by a typically-used subset of bipc's SHM API – which, itself, is essentially a thin wrapper around a classic OS-supplied SHM pool (segment) API, plus a Boost-supplied heap-like allocation algorithm. Nevertheless this wrapper, when combined with ipc::shm::stl, is eminently usable and flexible. Its main limitations may or may not be serious in production use, depending on the context. These limitations include the following.
When buffers are allocated and deallocated, bipc's default memory allocation algorithm – rbtree_best_fit – is what is used. (We could also allow for the other supplied algo, simple_seq_fit, or a custom user-supplied one.) While surely care was taken in writing this, in production one might demand something with thread caching and just general, like, industry relevance/experience; a jemalloc or tcmalloc maybe.
Possible contingency: Not really. In many cases this does not matter too much; but if one wants general performance equal to that of the general heap in a loaded production environment, then classic::Pool_arena is probably not for you. Consider jemalloc-based SHM provided elsewhere in ipc::shm.
It works within exactly one pool a/k/a mmap()ped segment, and that pool's max size must be specified at creation. Once it is exhausted via un-deallocated allocations, it'll throw exceptions likely to wreak havoc in your application.
Possible contingency: You may set the max pool size to a giant value. This will not take it from the OS like Linux: only when a page is actually touched, such as by allocating in it, does that actual RAM get assigned to your application(s). There is unfortunately, at least in Linux, some configurable kernel parameters as to the sum of max pool sizes active at a given time – ENOSPC (No space left on device) may be emitted when trying to open a pool beyond this. All in all it is a viable approach but may need a measure of finesse.
The ability to allocate in a given backing pool via any process's Pool_arena handle to that backing pool – not to mention deallocate in process B what was allocated in process A – requires guaranteed read-write capability in all Pool_arenas accessing a given pool. That read-write capability in and of itself (orthogonally to allocations) provides algorithmic possibilities which are not easily available in an asymmetric setup, where only one process can write or deallocate, while others can only borrow handles and read. How is this a limitation, you ask? While providing power and simplicity, it also hugely increases the number and difficulty of dealing with unexpected conditions. That is – any process can write and corrupt the pool's contents, thus "poisoning" other processes; any process crashing means the others cannot trust the integrity of the pool's contents; things of that nature.
Possible contingency: It would not be difficult to enable read-only access from all but one process; we provide such a constructor argument. However, one cannot use the SHM-handle borrowing method borrow_object() which severely stunts the usefulness of the class in that process and therefore across the system. That said one could imagine somewhat extending Pool_arena to enable lend-borrow and delegated deallocation (and maybe delegated allocation while at it) by adding some internal message-passing (maybe through a supplied transport::Channel or something). Doable but frankly goes against the spirit of simplicty and closeness-to-the-"source-material" cultivated by classic::Pool_arena. The jemalloc-based API available elsewhere in ipc::shm is the one that happily performs message-passing IPC internally for such reasons. It's a thought though.
Properties
Backing pool structure: One (1) SHM pool, explicitly named at construction. Can open handle with create-only, create-or-open (atomic), or open-only semantics. Pool size specified at construction/cannot be changed. Vaddr structure is not synchronized (so void* p pointing into SHM in process 1 cannot be used in process 2 without first adjusting it based on the different base vaddr of the mapped pool in process 2 versus 1).
Handle-to-arena structure: Pool_arena is the only type, used by any process involved, that accesses the underlying arena, and once open all capabilities are symmetrically available to all Pool_arena objects in all processes.
Any Pool_arena can allocate (and deallocate what it has allocated).
Any Pool_arena can deallocate what any other Pool_arena has allocated (as long as the correct locally-dereferenceable void* has been obtained in the deallocating process).
Allocation algorithm: As of this writing the bipc default, rbtree_best_fit. See its description in bipc docs. Note it does not perform any thread-caching like modern malloc()s.
Allocation/deallocation API: See section below for proper use techniques.
Cleanup: The underlying SHM pool is deleted if and only if one calls remove_persistent(), supplying it the pool name. This is not invoked internally at all, so it is the user's responsibility. ipc::session-managed Pool_arenas will be automatically cleaned up, as ipc::session strives to clean all persistent shared resources via a general algorithm. See remove_persistent() and for_each_persistent() doc headers.
Satisfies Arena requirements for shm::stl::Stateless_allocator: Yes. I.e., it is easy to store STL-compliant containers directly in SHM by using Stateless_allocator<Pool_arena> as the allocator at all levels.
SHM-stored pointer type provided: Yes, Pointer. This is, in reality, bipc::offset_ptr.
Non-STL-compliant data structures with pointers, such as linked lists, can be written in terms of allocate() and deallocate(), but only if one uses Pointer as opposed to raw T* pointers. We recommend against this, but if it cannot be avoided due to legacy code or what-not....
Handle borrowing support: Yes. Pool_arena directly provides an API for this. Internally it uses minimalistic atomic ref-counting directly in SHM without any IPC messaging used. Due to this internal simplicity this support is symmetric and supports unlimited proxying out of the box. That is, any process of N, each with a Pool_arena open to the same pool named P, can construct a borrowable object, then lend it to any other process which can also lend it to any other of the N processes. Internally the last Pool_arena's borrowed (or originally lent) handle to reach 0 intra-process ref-count shall invoke the object's dtor and deallocate the underlying buffer. (Algorithms like this = why symmetric read/write capability is fairly central to Pool_arena as written.)
However, as of this writing, this support is deliberately basic. In particular if a borrower process dies ungracefully (crash that does not execute all destructors, and so on), then the memory will leak until cleanup via remove_persistent().
Allocation API and how to properly use it
The most basic and lowest-level API consists of allocate() and deallocate(). We recommend against user code using these, as it is easy to leak and double-free (same as with new and delete in regular heap, except as usual with SHM anything that was not allocated will persist in RAM until remove_persistent()).
shm::stl allocator(s) will use these APIs safely.
As noted earlier, if one writes a non-STL-compliant data structure (such as a manually written linked list), it is appropriate to use allocate(), deallocate(), and Pointer. It is best to avoid such data structures in favor of shm::stl-aided STL-compliant structures.
The next level of API is construct(). construct<T>() returns a regular-looking shared_ptr. If it is never lent to another process, then the constructed T will be destroyed automatically as one would expect. If one does properly lend such a shared_ptr (which we call a handle) to another process (and which it can proxy-lend to another process still), then the T will be destroyed by the last process whose handle reaches ref-count 0. No explicit locking on the user's part is required to make this work.
If T is a POD (plain old data-type), then that's that.
If not, but T is a shm::stl-allocator-aided STL-compliant-structure, then you're good.
If not (e.g., the aforementioned manually implemented linked list) but the T destructor performs the necessary inner deallocation via deallocate(), then you're good. Again, we recommend against this, but sometimes it cannot be helped.
If not, then one must manually do the inner deallocation first, then let the handle (shared_ptr) group reach ref-count 0. The key is to do it in that order (which is why doing it via T::~T() is easiest).
T cannot be a native array; and there is no facility for constructing such. Use std::array or boost::array as T if desired.
Definition at line 148 of file pool_arena.hpp.
Member Typedef Documentation
Blob
using ipc::shm::classic::Pool_arena::Blob = flow::util::Blob_sans_log_context
Alias for a light-weight blob.
They're little; TRACE-logging of deallocs and copies is of low value; otherwise this can be switched to flow::util::Blob.
Definition at line 192 of file pool_arena.hpp.
Handle
template<typename T > using ipc::shm::classic::Pool_arena::Handle = boost::shared_ptr<T>
Outer handle to a SHM-stored object; really a regular-looking shared_ptr but with custom deleter that ensures deallocation via Pool_arena as well as cross-process ref-count semantics.
See class doc header and construct(). A handle can also be lent/borrowed between processes; see lend_object() and borrow_object().
Rationale
Why have an alias, where it's a mere shared_ptr? Two-fold reason:
(Mostly) While it is just shared_ptr<T>, and acts just as one would expect if borrow_object() and lend_object() are not involved, (1) it is an outer handle to a SHM-stored object, unlike the inner (subordinate) Pointer values as maintained by STL-compliant logic or other data structure-internals code; and (2) it has special (if hopefully quite intuitive) capabilities of invoking ref-counting "across" processes via lend_object() and borrow_object().
(Minor) It's nice not to visibly impose a particular shared_ptr impl but kinda hide it behind an alias. Ahem....
Template Parameters
T The pointed-to type. Its dtor, informally, should ensure any inner deallocations subordinate to the managed T are performed before the shared_ptr reaches ref-count 0 in all processes to get the handle. See class doc header.
Definition at line 186 of file pool_arena.hpp.
Pointer
template<typename T > using ipc::shm::classic::Pool_arena::Pointer = ::ipc::bipc::offset_ptr<T>
SHM-storable fancy-pointer.
See class doc header for discussion. Suitable for shm::stl allocator(s).
Template Parameters
T The pointed-to type. Pointer<T> acts like T*.
Definition at line 162 of file pool_arena.hpp.
Pool
using ipc::shm::classic::Pool_arena::Pool = ::ipc::bipc::managed_shared_memory private
The SHM pool type one instance of which is managed by *this.
It would be possible to parameterize this somewhat, such as specifying different allocation algorithms or speed up perf in single-thread situations. See class doc header for discussion. It is not a formal to-do yet.
Definition at line 500 of file pool_arena.hpp.
Constructor & Destructor Documentation
Pool_arena() [1/4]
ipc::shm::classic::Pool_arena::Pool_arena (flow::log::Logger * logger_ptr, const Shared_name & pool_name, util::Create_only mode_tag, size_t pool_sz, const util::Permissions & perms = util::Permissions(), Error_code * err_code = 0) explicit
Construct Pool_arena accessor object to non-existing named SHM pool, creating it first.
If it already exists, it is an error. If an error is emitted via *err_code, methods shall return sentinel/false values.
Parameters
logger_ptr Logger to use for subsequently logging.
pool_name Absolute name at which the persistent SHM pool lives.
mode_tag API-choosing tag util::CREATE_ONLY.
perms Permissions to use for creation. Suggest the use of util::shared_resource_permissions() to translate from one of a small handful of levels of access; these apply almost always in practice. The applied permissions shall ignore the process umask and shall thus exactly match perms, unless an error occurs.
pool_sz Pool size. Note: OS, namely Linux, shall not in fact take (necessarily) this full amount from general availability but rather a small amount. Chunks of RAM (pages) shall be later reserved as they begin to be used, namely via the allocation API. It may be viable to set this to a quite large value to avoid running out of pool space. However watch out for (typically configurable) kernel parameters as to the sum of sizes of active pools.
err_code See flow::Error_code docs for error reporting semantics. Error_code generated: various. Most likely creation failed due to permissions, or it already existed. An ENOSPC (No space left on device) error means the aforementioned kernel parameter has been hit (Linux at least); pool size rebalancing in your overall system may be required (or else one might tweak the relevant kernel parameter(s)).
Definition at line 62 of file pool_arena.cpp.
Pool_arena() [2/4]
ipc::shm::classic::Pool_arena::Pool_arena (flow::log::Logger * logger_ptr, const Shared_name & pool_name, util::Open_or_create mode_tag, size_t pool_sz, const util::Permissions & perms_on_create = util::Permissions(), Error_code * err_code = 0) explicit
Construct Pool_arena accessor object to non-existing named SHM pool, or else if it does not exist creates it first and opens it (atomically).
If an error is emitted via *err_code, methods shall return sentinel/false values.
Parameters
logger_ptr Logger to use for subsequently logging.
pool_name Absolute name at which the persistent SHM pool lives.
mode_tag API-choosing tag util::OPEN_OR_CREATE.
perms_on_create Permissions to use for creation. Suggest the use of util::shared_resource_permissions() to translate from one of a small handful of levels of access; these apply almost always in practice. The applied permissions shall ignore the process umask and shall thus exactly match perms_on_create, unless an error occurs.
pool_sz Pool size. See note in first ctor.
err_code See flow::Error_code docs for error reporting semantics. Error_code generated: various. Most likely creation failed due to permissions, or it already existed.
Definition at line 70 of file pool_arena.cpp.
Pool_arena() [3/4]
ipc::shm::classic::Pool_arena::Pool_arena (flow::log::Logger * logger_ptr, const Shared_name & pool_name, util::Open_only mode_tag, bool read_only = false, Error_code * err_code = 0) explicit
Construct Pool_arena accessor object to existing named SHM pool.
If it does not exist, it is an error. If an error is emitted via *err_code, methods shall return sentinel/false values.
Parameters
logger_ptr Logger to use for subsequently logging.
pool_name Absolute name at which the persistent SHM pool lives.
mode_tag API-choosing tag util::OPEN_ONLY.
read_only If and only if true the calling process will be prevented by the OS from writing into the pages mapped by *this subsequently. Such attempts will lead to undefined behavior. Note that this includes any attempt at allocating as well as writing into allocated (or otherwise) address space. Further note that, internally, deallocation – directly or otherwise – involves (in this implementation) writing and is thus also disallowed. Lastly, and quite significantly, borrow_object() can be called, but undefined behavior shall result when the resulting shared_ptr (Handle) group reaches ref-count 0, as internally that requires a decrement of a counter (which is a write). Therefore borrow_object() cannot be used either. Therefore it is up to you, in that case, to (1) never call deallocate() directly or otherwise (i.e., through an allocator); and (2) to design your algorithms in such a way as to never require lending to this Pool_arena. In practice this would be quite a low-level, stunted use of Pool_arena across 2+ processes; but it is not necessarily useless. (There might be, say, test/debug/reporting use cases.)
err_code See flow::Error_code docs for error reporting semantics. Error_code generated: various. Most likely creation failed due to permissions, or it already existed.
Definition at line 78 of file pool_arena.cpp.
References m_pool, m_pool_name, ipc::util::Shared_name::native_str(), ipc::util::op_with_possible_bipc_exception(), ipc::util::OPEN_ONLY, and ipc::shm::classic::error::S_SHM_BIPC_MISC_LIBRARY_ERROR.
~Pool_arena()
ipc::shm::classic::Pool_arena::~Pool_arena ()
Destroys Pool_arena accessor object.
In and of itself this does not destroy the underlying pool named m_pool_name; it continues to exist as long as (1) any other similar accessor objects (or other OS-created handles) do; and/or (2) its entry in the file system lives (hence until remove_persistent() is called for m_pool_name). This is analogous to closing a descriptor to a file.
Definition at line 96 of file pool_arena.cpp.
Pool_arena() [4/4]
template<typename Mode_tag > ipc::shm::classic::Pool_arena::Pool_arena (Mode_tag mode_tag, flow::log::Logger * logger_ptr, const Shared_name & pool_name, size_t pool_sz, const util::Permissions & perms, Error_code * err_code) explicit private
Helper ctor delegated by the 2 public ctors that take Open_or_create or Create_only mode.
Template Parameters
Mode_tag Either util::Open_or_create or util::Create_only.
Parameters
logger_ptr See public ctors.
pool_name See public ctors.
mode_tag See public ctors.
pool_sz See public ctors.
perms See public ctors.
err_code See public ctors.
Definition at line 29 of file pool_arena.cpp.
References m_pool, m_pool_name, ipc::util::Shared_name::native_str(), ipc::util::op_with_possible_bipc_exception(), and ipc::shm::classic::error::S_SHM_BIPC_MISC_LIBRARY_ERROR.
Member Function Documentation
allocate()
void * ipc::shm::classic::Pool_arena::allocate (size_t n)
Allocates buffer of specified size, in bytes, in the accessed pool; returns locally-derefernceable address to the first byte.
Returns null if no pool attached to *this. Throws exception if ran out of space.
Take care to only use this when and as appropriate; see class doc header notes on this.
Rationale for throwing exception instead of returning null
This does go against the precedent in most of ipc, which either returns sentinel values or uses Flow-style Error_code based emission (out-arg or exception). The original reason may appear somewhat arbitrary and is 2-fold:
It's what bipc does (throws bipc::bad_alloc_exception), and indeed we propagate what it throws.
It's what STL-compliant allocators (such as our own in shm::stl) must do; and they will invoke this (certainly not exclusively).
I (ygoldfel) claim it's a matter of... synergy, maybe, or tradition. It really is an exceptional situation to run out of pool space. Supposing some system is built on-top of N pools, of which *this is one, it can certainly catch it (and in that case it shouldn't be frequent enough to seriously affect perf by virtue of slowness of exception-throwing/catching) and use another pool. Granted, it could use Flow semantics, which would throw only if an Error_code* supplied were null, but that misses the point that allocate() failing to allocate due to lack of space is the only thing that can really go wrong and is exceptional. Adding an Error_code* err_code out-arg would hardly add much value.
Parameters
n Desired buffer size in bytes. Must not be 0 (behavior undefined/assertion may trip).
Returns
Non-null on success (see above); null if ctor failed to attach pool.
Definition at line 101 of file pool_arena.cpp.
References m_pool.
Referenced by construct().
borrow_object()
template<typename T > Pool_arena::Handle< T > ipc::shm::classic::Pool_arena::borrow_object (const Blob & serialization)
Completes the cross-process operation begun by lend_object() that returned serialization; to be invoked in the intended new owner process.
Returns null if no pool attached to *this.
Consider the only 2 ways a user may obtain a new Handle to a T from *this:
construct(): This is allocation by the original/first owner of the T.
borrow_object(), after lend_object() was called on a previous Handle in another process, acquired there however it was acquired:
Acquired via construct(): I.e., the original/first owner lent to us. I.e., it's the original loan.
Acquired via another borrow_object(): I.e., it was itself first borrowed from another. I.e., it's a loan by a lender a/k/a proxying.
Integration with shm::stl::Stateless_allocator
Crucially, the 2nd paragraph of similarly named section of construct() doc header – where it speaks of applying Stateless_allocator context around dtor call possibly invoked by returned handle's deleter – applies exactly equally here. Please read it.
Template Parameters
T See lend_object().
Parameters
serialization Value, not .empty(), returned by lend_object() and transmitted bit-for-bit to this process.
Returns
Non-null on success; null if ctor failed to attach a pool.
Definition at line 682 of file pool_arena.hpp.
References m_pool.
construct()
template<typename T , typename... Ctor_args> Pool_arena::Handle< T > ipc::shm::classic::Pool_arena::construct (Ctor_args &&... ctor_args)
Constructs an object of given type with given ctor args, having allocated space directly in attached SHM pool, and returns a ref-counted handle that (1) guarantees destruction and deallocation shall occur once no owners hold a reference; and (2) can be lent to other processes (and other processes still indefinitely), thus adding owners beyond this process, via lend_object()/borrow_object().
Returns null if no pool attached to *this. Throws exception if ran out of space.
Is better to use this than allocate() whenever possible; see class doc header notes on this.
Note that that there is no way to construct() a native array. If that is your aim please use T = std::array<> or similar.
Integration with shm::stl::Stateless_allocator
This method, bracketing the invocation of the T ctor, sets the thread-local shm::stl::Arena_activator<Pool_arena> context to this. Therefore the caller need not do so. If T does not store an STL-compliant structure that uses Stateless_allocator, then this is harmless albeit a small perf hit. If T does do so, then it is a convenience.
Arguably more importantly: The returned shared_ptr is such that when garbage-collection of the created data structure does occur – which may occur in this process, but via lend_object() and borrow_object() may well occur in another process – the T::~T() dtor call shall also be bracketed by the aforementioned context. Again: If T does not rely on Stateless_allocator, then it's harmless; but if it does then doing this is quite essential. That is because the user cannot, typically (or at least sufficiently easily), control the per-thread allocator context at the time of dtor call – simply because who knows who or what will be running when the cross-process ref-count reaches 0.
Template Parameters
T Object type. See class doc header for discussion on appropriate properties of T. Short version: PODs work; STL nested container+POD combos work, as long as a shm::stl allocator is used at all levels; manually-implemented non-STL-compliant data structures work if care is taken to use allocate() and Pointer.
Ctor_args T ctor arg types.
Parameters
ctor_args 0 or more args to T constructor.
Returns
Non-null on success; null if ctor failed to attach a pool.
Definition at line 619 of file pool_arena.hpp.
References allocate(), construct_at(), and m_pool.
construct_at()
template<typename T , typename... Ctor_args> void ipc::shm::classic::Pool_arena::construct_at (T * obj, Ctor_args &&... ctor_args) static private
std::construct_at() equivalent; unavailable until C++20, so here it is.
Template Parameters
T Object type.
Ctor_args T ctor arg types.
Parameters
obj Pointer to uninitialized T.
ctor_args Ctor args for T::T().
Definition at line 757 of file pool_arena.hpp.
Referenced by construct().
deallocate()
bool ipc::shm::classic::Pool_arena::deallocate (void * buf_not_null) noexcept
Undoes effects of local allocate() that returned buf_not_null; or another-process's allocate() that returned pointer whose locally-dereferenceable equivalent is but_not_null.
Returns false if and only if no pool attached to *this. Does not throw exception. Behavior is undefined if buf_not_null is not as described above; in particular if it is null.
Parameters
buf_not_null See above.
Returns
true on success; false if ctor failed to attach a pool.
Definition at line 131 of file pool_arena.cpp.
Referenced by handle_deleter_impl().
for_each_persistent()
template<typename Handle_name_func > void ipc::shm::classic::Pool_arena::for_each_persistent (const Handle_name_func & handle_name_func) static
Lists all named SHM pool objects currently persisting, invoking the given handler synchronously on each one.
Note that, in a sanely set-up OS install, all existing pools will be listed by this function; but permissions/ownership may forbid certain operations the user may typically want to invoke on a given listed name – for example remove_persistent(). This function does not filter-out any potentially inaccessible items.
Note
The listed pools need not have been created via Pool_arena objects; they will be all pools created by name ultimately via OS shm_open() or equivalent call. Therefore this is a utility that is not limited for use in the ipc::shm::classic context.
Template Parameters
Handle_name_func Function object matching signature void F(const Shared_name&).
Parameters
handle_name_func handle_name_func() shall be invoked for each item. See Handle_name_func.
Definition at line 769 of file pool_arena.hpp.
References ipc::util::for_each_persistent_shm_pool().
handle_deleter_impl()
template<typename T > void ipc::shm::classic::Pool_arena::handle_deleter_impl (Handle_in_shm< T > * handle_state) private
Identical deleter for Handle returned by both construct() and borrow_object(); invoked when a given process's (borrow_object() caller's) shared_ptr group reaches ref-count 0.
It decrements Handle_in_shm::m_atomic_owner_ct; and if and only if that made it reach zero performs the opposite of what construct() did including:
runs T::~T() dtor;
deallocate().
Otherwise (if m_atomic_owner_ct is not yet 0) does nothing further; other owners still remain.
Parameters
handle_state Handle<T>::~Handle() shall run, and if that made shared-ref-count reach 0, call handle_deleter_impl(...that_ptr...). Since the Handle returned by construct() and borrow_object() is really an alias-cted shared_ptr<T> to shared_ptr<Handle_in_shm<T>>, and Handle_in_shm::m_obj (of type T) is the first member in its type, those addresses are numerically equal.
Definition at line 723 of file pool_arena.hpp.
References deallocate(), ipc::shm::classic::Pool_arena::Handle_in_shm< T >::m_atomic_owner_ct, and ipc::shm::classic::Pool_arena::Handle_in_shm< T >::m_obj.
is_handle_in_arena()
template<typename T > bool ipc::shm::classic::Pool_arena::is_handle_in_arena (const Handle< T > & handle) const
Returns true if and only if handle came from either this->construct<T>() or this->borrow_object<T>().
Another way of saying that is: if and only if handle may be passed to this->lend_object<T>(). (The words "came from" mean "was returned by or is a copy/move of one that was," or equivalently "belongs to the `shared_ptr` group of one that was returned by.")
Parameters
handle An object, or copy/move of an object, returned by construct<T>() or borrow_object<T>() of a Pool_arena (not necessarily *this), while *this was already constructed.
Returns
See above.
Definition at line 611 of file pool_arena.hpp.
References m_pool.
lend_object()
template<typename T > Pool_arena::Blob ipc::shm::classic::Pool_arena::lend_object (const Handle< T > & handle)
Adds an owner process to the owner count of the given construct()-created handle, and returns an opaque blob, such that if one passes it to borrow_object() in the receiving process, that borrow_object() shall return an equivalent Handle in that process.
The returned Blob is guaranteed to have non-zero size that is small enough to be considered very cheap to copy; in particular internally as of this writing it is a ptrdiff_t. Returns .empty() object if no pool attached to *this.
It is the user's responsibility to transmit the returned blob, such as via a transport::Channel or any other copying IPC mechanism, to the owning process. Failing to do so will leak the object until remove_persistent(). That process dying without running Handle dtor(s) will similarly leak it.
Template Parameters
T See construct().
Parameters
handle Value returned by construct() (lending from original allocating process) or borrow_object() (proxying); or copied/moved therefrom. Note this is a mere shared_ptr<T> albeit with unspecified custom deleter logic attached. See Handle doc header.
Returns
See above. .empty() if and only if ctor failed to attach a pool.
Definition at line 650 of file pool_arena.hpp.
References m_pool.
remove_persistent()
void ipc::shm::classic::Pool_arena::remove_persistent (flow::log::Logger * logger_ptr, const Shared_name & name, Error_code * err_code = 0) static
Removes the named SHM pool object.
The name name is removed from the system immediately; and the function is non-blocking. However the underlying pool if any continues to exist until all handles (accessor objects Pool_arena or other OS-created handles) to it are closed; their presence in this or other process is not an error. See also dtor doc header for related notes.
Note
The specified pool need not have been created via a Pool_arena object; it can be any pool created by name ultimately via OS shm_open() or equivalent call. Therefore this is a utility that is not limited for use in the ipc::shm::classic context.
See also
util::remove_each_persistent_*() for a convenient way to remove more than one item. E.g., util::remove_each_persistent_with_name_prefix<Pool_arena>() combines remove_persistent() and for_each_persistent() in a common-sense way to remove only those names starting with a given prefix; or simply all of them.
Trying to remove a non-existent name is an error.
Logs INFO message.
Parameters
logger_ptr Logger to use for subsequently logging.
name Absolute name at which the persistent SHM pool lives.
err_code See flow::Error_code docs for error reporting semantics. Error_code generated: various. Most likely it'll be a not-found error or permissions error.
Definition at line 163 of file pool_arena.cpp.
References ipc::util::remove_persistent_shm_pool().
Friends And Related Function Documentation
operator<<()
std::ostream & operator<< (std::ostream & os, const Pool_arena & val) related
Prints string representation of the given Pool_arena to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 170 of file pool_arena.cpp.
References m_pool_name.
Member Data Documentation
m_pool
boost::movelib::unique_ptr<Pool> ipc::shm::classic::Pool_arena::m_pool private
Attached SHM pool. If ctor fails in non-throwing fashion then this remains null. Immutable after ctor.
Definition at line 603 of file pool_arena.hpp.
Referenced by allocate(), borrow_object(), construct(), is_handle_in_arena(), lend_object(), and Pool_arena().
m_pool_name
const Shared_name ipc::shm::classic::Pool_arena::m_pool_name
SHM pool name as set immutably at construction.
Definition at line 489 of file pool_arena.hpp.
Referenced by operator<<(), and Pool_arena().
The documentation for this class was generated from the following files:
shm/classic/pool_arena.hpp
shm/classic/classic_fwd.hpp
shm/classic/pool_arena.cpp