Flow-IPC: ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle > Class Template Reference
ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle > Class Template Reference
Internal, non-movable pImpl-lite implementation of sync_io::Blob_stream_mq_sender class template.
#include <blob_stream_mq_snd_impl.hpp>
Classes
struct Snd_low_lvl_payload
Data store representing a payload corresponding to exactly one attempted async write-op, albeit used if and only if we encounter would-block in send_blob() or on_ev_auto_ping_now_timer_fired() or *end_sending() and have to queue (and therefore one-time-copy) data in m_pending_payloads_q.
Public Types
using Base = Blob_stream_mq_base_impl< Persistent_mq_handle >
Short-hand for our base with static goodies at least.
using Mq = typename Base::Mq
Short-hand for template arg for underlying MQ handle type.
Public Types inherited from ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle >
using Mq = Persistent_mq_handle
Short-hand for template arg for underlying MQ handle type.
using Auto_closing_mq = boost::movelib::unique_ptr< Mq, Function< void(Mq *)> >
Persistent_mq_handle holder that takes a deleter lambda on construction, intended here to perform additional deinit steps in addition to closing the Mq by deleting it.
Public Member Functions
Blob_stream_mq_sender_impl (flow::log::Logger *logger_ptr, util::String_view nickname_str, Mq &&mq_moved, Error_code *err_code)
See Blob_stream_mq_sender counterpart.
~Blob_stream_mq_sender_impl ()
See Blob_stream_mq_sender counterpart.
template<typename Create_ev_wait_hndl_func >
bool replace_event_wait_handles (const Create_ev_wait_hndl_func &create_ev_wait_hndl_func)
See Blob_stream_mq_sender counterpart.
size_t send_blob_max_size () const
See Blob_stream_mq_sender counterpart, but assuming PEER state.
bool start_send_blob_ops (util::sync_io::Event_wait_func &&ev_wait_func)
See Blob_stream_mq_sender counterpart.
bool send_blob (const util::Blob_const &blob, Error_code *err_code)
See Blob_stream_mq_sender counterpart, but assuming PEER state.
template<typename Task_err >
bool async_end_sending (Error_code *sync_err_code, Task_err &&on_done_func)
See Blob_stream_mq_sender counterpart, but assuming PEER state.
bool end_sending ()
See Blob_stream_mq_sender counterpart, but assuming PEER state.
bool auto_ping (util::Fine_duration period)
See Blob_stream_mq_sender counterpart, but assuming PEER state.
const std::string & nickname () const
See Blob_stream_mq_sender counterpart, but assuming PEER state.
const Shared_name & absolute_name () const
See Blob_stream_mq_sender counterpart, but assuming PEER state.
Private Types
using Control_cmd = typename Base::Control_cmd
Short-hand for Blob_stream_mq_base_impl::Control_cmd.
Private Member Functions
bool op_started (util::String_view context) const
Helper that returns true silently if start_*_ops() has been called; else logs WARNING and returns false.
bool async_end_sending_impl (Error_code *sync_err_code_ptr_or_null, flow::async::Task_asio_err &&on_done_func_or_empty)
*end_sending() body.
void on_ev_auto_ping_now_timer_fired ()
Handler for the async-wait, via util::sync_io::Timer_event_emitter, of the auto-ping timer firing; if all is cool, sends auto-ping and schedules the next such async-wait.
bool sync_write_or_q_payload (const util::Blob_const &orig_blob, bool *avoided_qing_or_null)
Either synchronously sends orig_blob low-level blob over m_mq, or if an async-send is in progress queues it to be sent later; dropping-sans-queuing allowed under certain circumstances in avoided_qing mode.
bool sync_write_or_q_ctl_cmd (Control_cmd cmd)
Writes the 2 payloads corresponding to CONTROL command cmd to m_mq; if unable to do so synchronously – either because items are already queued in m_pending_payloads_q, or MQ is full – then enqueue 1-2 of the payloads onto that queue.
bool sync_write_or_q_ctl_cmd_impl (std::underlying_type_t< Control_cmd > raw_cmd)
Equivalent to sync_write_or_q_ctl_cmd() but takes the raw representation of the command to send; this allows both sending the enum Control_cmd value or the special protocol negotiation payload.
void async_write_q_head_payload ()
Initiates async-write over m_mq of the low-level payload at the head of out-queue m_pending_payloads_q, with completion handler also inside this method.
Private Attributes
const std::string m_nickname
See nickname().
Protocol_negotiator m_protocol_negotiator
Handles the protocol negotiation at the start of the pipe.
const Shared_name m_absolute_name
See absolute_name().
std::optional< flow::util::Task_engine > m_nb_task_engine
The Task_engine for m_mq_ready_*.
flow::util::Task_engine m_ev_hndl_task_engine_unused
The Task_engine for m_ev_wait_hndl_*, unless it is replaced via replace_event_wait_handles().
Base::Auto_closing_mq m_mq
The MQ handle adopted by the ctor, through which nb-sends and blocking-waits are executed.
const size_t m_mq_max_msg_sz
Equals m_mq.max_msg_size().
std::optional< util::Pipe_reader > m_mq_ready_reader
Read-end of IPC-pipe used by thread U to detect that a thread-W transmissibility-wait has completed, meaning would-block has cleared, and therefore thread U can attempt to nb-transmit again.
std::optional< util::Pipe_writer > m_mq_ready_writer
Write-end of IPC-pipe used by thread W to inform thread U that a thread-W transmissibility-wait has completed, meaning would-block has cleared, and therefore thread U can attempt to nb-transmit again.
util::sync_io::Asio_waitable_native_handle m_ev_wait_hndl_mq
Descriptor waitable by outside event loop async-waits – storing the same Native_handle as (and thus being used to wait on events from) m_mq_ready_reader; or if m_mq can be watched directly (known at compile-time) then as m_mq itself.
util::sync_io::Timer_event_emitter m_timer_worker
As typical in timer-needing sync_io-pattern-implementing objects, maintains a thread exclusively for Timer wait completion handlers which ferry timer-fired events to internal IPC-mechanisms waitable by the sync_io-pattern-using outside event loop.
std::queue< typename Snd_low_lvl_payload::Ptr > m_pending_payloads_q
Queue storing (at head) the currently in-progress async write-op of a Snd_low_lvl_payload; followed by the payloads that should be written after that completes, in order.
Error_code m_pending_err_code
The first and only connection-hosing error condition detected when attempting to low-level-write on m_mq; or falsy if no such error has yet been detected.
bool m_finished
false at start; set to true forever on the first *end_sending() invocation; true will prevent any subsequent send_blob() calls from proceeding.
flow::async::Task_asio_err m_pending_on_last_send_done_func_or_empty
Function passed to async_end_sending(), if it returned true and was unable to synchronously flush everything including the graceful-close itself (synchronously detecting new or previous pipe-hosing error does entail flushing everything); otherwise .empty().
util::Fine_duration m_auto_ping_period
Equals zero() before auto_ping(); immutably equals period (auto_ping() arg) subsequently to that first successful call (if any).
flow::util::Timer m_auto_ping_timer
Timer that fires on_ev_auto_ping_now_timer_fired() (which sends an auto-ping) and is always scheduled to fire m_auto_ping_period after the last send (send_blob(), auto_ping(), on_ev_auto_ping_now_timer_fired() itself).
util::sync_io::Timer_event_emitter::Timer_fired_read_end * m_auto_ping_timer_fired_peer
Read-end of IPC-mechanism used by m_timer_worker to ferry timer-fired events from m_auto_ping_timer to sync_io outside async-wait to our actual on-timer-fired handler logic.
util::sync_io::Asio_waitable_native_handle m_ev_wait_hndl_auto_ping_timer_fired_peer
Descriptor waitable by outside event loop async-waits – storing the same Native_handle as (and thus being used to wait on events from) m_auto_ping_timer_fired_peer.
util::sync_io::Event_wait_func m_ev_wait_func
Function (set forever in start_send_blob_ops()) through which we invoke the outside event loop's async-wait facility for descriptors/events to our ops.
std::optional< flow::async::Single_thread_task_loop > m_blocking_worker
Worker thread W always in one of 2 states: idle; or (when m_mq is in would-block condition) executing an indefinite, interrupting blocking wait for transmissibility of m_mq.
Related Functions
(Note that these are not member functions.)
template<typename Persistent_mq_handle >
std::ostream & operator<< (std::ostream &os, const Blob_stream_mq_sender_impl< Persistent_mq_handle > &val)
Prints string representation of the given Blob_stream_mq_sender to the given ostream.
Additional Inherited Members
Static Public Member Functions inherited from ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle >
static void remove_persistent (flow::log::Logger *logger_ptr, const Shared_name &name, Error_code *err_code)
See Blob_stream_mq_base counterpart.
template<typename Handle_name_func >
static void for_each_persistent (const Handle_name_func &handle_name_func)
See Blob_stream_mq_base counterpart.
static Auto_closing_mq ensure_unique_peer (flow::log::Logger *logger_ptr, Mq &&mq, bool snd_else_rcv, Error_code *err_code)
Internal helper for Blob_stream_mq_sender and Blob_stream_mq_receiver that operates both the start and end of the anti-dupe-endpoint machinery used by those 2 classes to prevent more than 1 _sender and more than 1 _receiver for a given underlying MQ.
Protected Types inherited from ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle >
enum class Control_cmd : int64_t { S_END_SENDING , S_PING , S_END_SENTINEL }
If Blob_stream_mq_sender_impl sends an empty message, in NORMAL state Blob_stream_mq_receiver enters CONTROL state and expects one of these values in the next message, to react as documented per enum value (upon re-entering NORMAL state).
Detailed Description
template<typename Persistent_mq_handle>
class ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >
Internal, non-movable pImpl-lite implementation of sync_io::Blob_stream_mq_sender class template.
In and of itself it would have been directly and publicly usable; however Blob_stream_mq_sender adds move semantics which are essential to cooperation with the rest of the API, Channel in particular.
See also
All discussion of the public API is in Blob_stream_mq_sender doc header; that class template forwards to this one. All discussion of pImpl-lite-related notions is also there. See that doc header first please. Then come back here.
Impl design
Here's the thing. All the _sender and _receiver stuff historically was written first in what is now sync_io::Native_socket_stream::Impl. Next, this MQ stuff was written to implement (basically) the same concepts. So everything is explained, first, in sync_io::Native_socket_stream::Impl. Next I (ygoldfel) wrote each of *this and Blob_stream_mq_receiver_impl. Therefore:
*this impl is similar to the outgoing-direction, PEER-state logic in that socket-stream Impl class.
And accordingly for incoming-direction and Blob_stream_mq_receiver_impl.
Therefore we will only explain here the differences between that socket-stream out-pipe algorithms and *this impl. Before going into it more consider these points:
Socket-stream has to worry about both directions and (some) interaction between the two (even though it is full-duplex). We do not. There are no mutual concurrency issues to speak of in particular.
Socket-stream has to worry about going from NULL state to PEER state via CONNECTING (optionally) – sync_connect() at least. We do not: the _impl is always in PEER state (unless ctor failed, but that's not interesting).
Socket-stream must be able to transmit Native_handles, and when applicable they correspond in a tricky way to byte 1 of the containing send/receive call. We do not transmit them – just blobs.
Socket-stream is operating over a medium that lacks message boundaries; so it must worry about transmitting only part of a payload, etc. We do not: a low-level message either goes through, or it does not (would-block). A user message is 1-1 with a low-level message; so we need not transmit length prefixes. There are 2 exceptions:
An auto-ping is a special message. We express it as an "escape" low-level message (0-length – as a user message must not be 0-length) followed by an encoded enumeration value in the following message.
A graceful-close is a special message. It is a similarly escaped enumeration value (2 low-level messages).
I (ygoldfel) could find no way to reuse code between the 2 counterparts despite similarities. Some comments and some code are repeated, but they are also different enough to where it couldn't really be avoided. That said: if you have a reason to understand Native_socket_stream::Impl specifically first, then coming back here afterward should be a piece of cake.
If not, due to the simplified/reduced purview of a *this, it should be quite doable to follow the logic. I won't pontificate with some overview beyond the above. Simply grok the following simple protocol, then the sync_io pattern (util::sync_io doc header) – and then jump into the code.
(For that last part, we recommend starting with the data member doc headers.)
So, the protocol:
Two states: steady state, CONTROL state. In steady state (default) each user message corresponds to a message over the MQ. By the concept, these cannot be empty. When it is necessary to send an auto-ping (auto_ping() and then periodically as needed), we enter CONTROL state, sending an empty message, then Control_cmd::S_PING in the next message, which enters steady state again. Lastly, *end_sending() means we enter CONTROL state similarly, then send Control_cmd::S_END_SENDING in the next message, which enters steady state again.
Protocol negotiation
This adds a bit of stuff onto the above protocol. It is very simple; please see Protocol_negotiator doc header; we use that convention. Moreover, since this is the init version (version 1) of the protocol, we need not worry about speaking more than one version. So all we do is send the version ahead of the first payload that would otherwise be sent for any reason (user message from send_blob(), end-sending token from *end_sending(), or ping from auto_ping(), as of this writing), as a special CONTROL message that encodes the value -1, meaning version 1 (as the true Control_cmd enum values would be 0, 1, etc.). Conversely Blob_stream_mq_receiver_impl expects the first message it does receive to be that CONTROL message encoding a version number; but that's not our concern here, as we are only the outgoing-direction class.
Note
It is very tempting to do that initial send in lazy fashion: meaning, about to send the first "real" payload? OK, then pre-pend the negotiation message. However this can create trouble in the future, if a future protocol wants to be backwards-compatible (support more than 2 protocol versions): we'll need to have received the opposing guy's preferred version, and thus determined which version to speak, before sending further (non-negotiation) messages. Bottom line... the initial send shall occur as soon as we are operational (start_send_native_handle_ops()).
After that, we just speak what we speak... which is the protocol's initial version – as there is no other version for us. (The opposing-side peer is responsible for closing the MQs, if it is unable to speak version 1.)
If we do add protocol version 2, etc., in the future, then things might become somewhat more complex (but even then not necessarily so). This is discussed in the Protocol_negotiator m_protocol_negotiator member doc header.
Note
We suggest that if version 2, etc., is/are added, then the above notes be kept more or less intact; then add updates to show changes. This will provide a good overview of how the protocol evolved; and our backwards-compatibility story (even if we decide to have no backwards-compatibility).
Template Parameters
Persistent_mq_handle See Persistent_mq_handle concept doc header.
Definition at line 121 of file blob_stream_mq_snd_impl.hpp.
Member Typedef Documentation
Base
template<typename Persistent_mq_handle > using ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Base = Blob_stream_mq_base_impl<Persistent_mq_handle>
Short-hand for our base with static goodies at least.
Definition at line 130 of file blob_stream_mq_snd_impl.hpp.
Control_cmd
template<typename Persistent_mq_handle > using ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Control_cmd = typename Base::Control_cmd private
Short-hand for Blob_stream_mq_base_impl::Control_cmd.
Definition at line 274 of file blob_stream_mq_snd_impl.hpp.
Mq
template<typename Persistent_mq_handle > using ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Mq = typename Base::Mq
Short-hand for template arg for underlying MQ handle type.
Definition at line 133 of file blob_stream_mq_snd_impl.hpp.
Constructor & Destructor Documentation
Blob_stream_mq_sender_impl()
template<typename Persistent_mq_handle > ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Blob_stream_mq_sender_impl (flow::log::Logger * logger_ptr, util::String_view nickname_str, Mq && mq_moved, Error_code * err_code) explicit
See Blob_stream_mq_sender counterpart.
Parameters
logger_ptr See Blob_stream_mq_sender counterpart.
mq_moved See Blob_stream_mq_sender counterpart.
nickname_str See Blob_stream_mq_sender counterpart.
err_code See Blob_stream_mq_sender counterpart.
Definition at line 640 of file blob_stream_mq_snd_impl.hpp.
References ipc::util::sync_io::Asio_waitable_native_handle::assign(), ipc::transport::Blob_stream_mq_base_impl< Persistent_mq_handle >::ensure_unique_peer(), ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_blocking_worker, ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_ev_wait_hndl_mq, ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_mq, ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_mq_ready_reader, ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_mq_ready_writer, ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_nb_task_engine, ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_pending_err_code, and ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::nickname().
~Blob_stream_mq_sender_impl()
template<typename Persistent_mq_handle > ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::~Blob_stream_mq_sender_impl
See Blob_stream_mq_sender counterpart.
Definition at line 753 of file blob_stream_mq_snd_impl.hpp.
Member Function Documentation
absolute_name()
template<typename Persistent_mq_handle > const Shared_name & ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::absolute_name
See Blob_stream_mq_sender counterpart, but assuming PEER state.
Returns
See Blob_stream_mq_sender counterpart.
Definition at line 1690 of file blob_stream_mq_snd_impl.hpp.
Referenced by ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::operator<<().
async_end_sending()
template<typename Persistent_mq_handle > template<typename Task_err > bool ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::async_end_sending (Error_code * sync_err_code, Task_err && on_done_func)
See Blob_stream_mq_sender counterpart, but assuming PEER state.
Parameters
sync_err_code See Blob_stream_mq_sender counterpart.
on_done_func See Blob_stream_mq_sender counterpart.
Returns
See Blob_stream_mq_sender counterpart.
Definition at line 1048 of file blob_stream_mq_snd_impl.hpp.
async_end_sending_impl()
template<typename Persistent_mq_handle > bool ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::async_end_sending_impl (Error_code * sync_err_code_ptr_or_null, flow::async::Task_asio_err && on_done_func_or_empty) private
*end_sending() body.
Parameters
sync_err_code_ptr_or_null See async_end_sending(). Null if and only if invoked from the no-arg end_sending(). Note well: even if async_end_sending(sync_err_code = nullptr) was used, this must not be null.
on_done_func_or_empty See async_end_sending(). .empty() == true if and only if invoked from the no-arg end_sending().
Returns
See async_end_sending() and end_sending().
Definition at line 1074 of file blob_stream_mq_snd_impl.hpp.
References ipc::transport::error::S_SYNC_IO_WOULD_BLOCK.
async_write_q_head_payload()
template<typename Persistent_mq_handle > void ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::async_write_q_head_payload private
Initiates async-write over m_mq of the low-level payload at the head of out-queue m_pending_payloads_q, with completion handler also inside this method.
The first step of this is an async-wait via sync_io pattern.
Definition at line 1507 of file blob_stream_mq_snd_impl.hpp.
References ipc::util::pipe_consume(), ipc::util::pipe_produce(), and ipc::transport::error::S_INTERRUPTED.
auto_ping()
template<typename Persistent_mq_handle > bool ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::auto_ping (util::Fine_duration period)
See Blob_stream_mq_sender counterpart, but assuming PEER state.
Parameters
period See Blob_stream_mq_sender counterpart.
Returns
See Blob_stream_mq_sender counterpart.
Definition at line 1171 of file blob_stream_mq_snd_impl.hpp.
end_sending()
template<typename Persistent_mq_handle > bool ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::end_sending
See Blob_stream_mq_sender counterpart, but assuming PEER state.
Returns
See Blob_stream_mq_sender counterpart.
Definition at line 1041 of file blob_stream_mq_snd_impl.hpp.
nickname()
template<typename Persistent_mq_handle > const std::string & ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::nickname
See Blob_stream_mq_sender counterpart, but assuming PEER state.
Returns
See Blob_stream_mq_sender counterpart.
Definition at line 1696 of file blob_stream_mq_snd_impl.hpp.
Referenced by ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Blob_stream_mq_sender_impl(), and ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::operator<<().
on_ev_auto_ping_now_timer_fired()
template<typename Persistent_mq_handle > void ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::on_ev_auto_ping_now_timer_fired private
Handler for the async-wait, via util::sync_io::Timer_event_emitter, of the auto-ping timer firing; if all is cool, sends auto-ping and schedules the next such async-wait.
That wait itself can be rescheduled when non-idleness (other send attempts) occurs. If all is not cool – sends finished via *end_sending(), out-pipe hosed – then neither sends auto-ping nor schedules another.
Definition at line 1274 of file blob_stream_mq_snd_impl.hpp.
op_started()
template<typename Persistent_mq_handle > bool ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::op_started (util::String_view context) const private
Helper that returns true silently if start_*_ops() has been called; else logs WARNING and returns false.
Parameters
context For logging: the algorithmic context (function name or whatever).
Returns
See above.
Definition at line 864 of file blob_stream_mq_snd_impl.hpp.
replace_event_wait_handles()
template<typename Persistent_mq_handle > template<typename Create_ev_wait_hndl_func > bool ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::replace_event_wait_handles (const Create_ev_wait_hndl_func & create_ev_wait_hndl_func)
See Blob_stream_mq_sender counterpart.
Template Parameters
Create_ev_wait_hndl_func See Blob_stream_mq_sender counterpart.
Parameters
create_ev_wait_hndl_func See Blob_stream_mq_sender counterpart.
Returns
See Blob_stream_mq_sender counterpart.
Definition at line 781 of file blob_stream_mq_snd_impl.hpp.
References ipc::util::Native_handle::m_native_handle.
send_blob()
template<typename Persistent_mq_handle > bool ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::send_blob (const util::Blob_const & blob, Error_code * err_code)
See Blob_stream_mq_sender counterpart, but assuming PEER state.
Parameters
blob See Blob_stream_mq_sender counterpart.
err_code See Blob_stream_mq_sender counterpart.
Returns
See Blob_stream_mq_sender counterpart.
Definition at line 878 of file blob_stream_mq_snd_impl.hpp.
References ipc::transport::error::S_INVALID_ARGUMENT, and ipc::transport::error::S_SENDS_FINISHED_CANNOT_SEND.
send_blob_max_size()
template<typename Persistent_mq_handle > size_t ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::send_blob_max_size
See Blob_stream_mq_sender counterpart, but assuming PEER state.
Returns
See Blob_stream_mq_sender counterpart.
Definition at line 1684 of file blob_stream_mq_snd_impl.hpp.
start_send_blob_ops()
template<typename Persistent_mq_handle > bool ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::start_send_blob_ops (util::sync_io::Event_wait_func && ev_wait_func)
See Blob_stream_mq_sender counterpart.
Parameters
ev_wait_func See Blob_stream_mq_sender counterpart.
Returns
See Blob_stream_mq_sender counterpart.
Definition at line 824 of file blob_stream_mq_snd_impl.hpp.
References ipc::transport::Protocol_negotiator::S_VER_UNKNOWN.
sync_write_or_q_ctl_cmd()
template<typename Persistent_mq_handle > bool ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::sync_write_or_q_ctl_cmd (Control_cmd cmd) private
Writes the 2 payloads corresponding to CONTROL command cmd to m_mq; if unable to do so synchronously – either because items are already queued in m_pending_payloads_q, or MQ is full – then enqueue 1-2 of the payloads onto that queue.
In the case of Control_cmd::S_PING it may drop both payloads silently (see sync_write_or_q_payload() notes regarding avoided_qing mode).
Essentially this combines 1-2 sync_write_or_q_payload() for the specific task of sending out a CONTROL command. If one desires to send a normal (user) message – use sync_write_or_q_payload() directly (it shall deal with a single payload).
If a sync-write uncovers m_mq is hosed, then m_pending_err_code is made truthy.
Parameters
cmd See above.
Returns
A-la sync_write_or_q_payload(): false if outgoing-direction pipe still has stuff in it; true otherwise.
Definition at line 1448 of file blob_stream_mq_snd_impl.hpp.
sync_write_or_q_ctl_cmd_impl()
template<typename Persistent_mq_handle > bool ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::sync_write_or_q_ctl_cmd_impl (std::underlying_type_t< Control_cmd > raw_cmd) private
Equivalent to sync_write_or_q_ctl_cmd() but takes the raw representation of the command to send; this allows both sending the enum Control_cmd value or the special protocol negotiation payload.
We always send the latter as the first message, and never again; and the receiver side expects this; after that only regular Control_cmd-bearing CONTROL messages are sent and expected.
Parameters
raw_cmd Either a non-negative value, which equals the cast of a Control_cmd to its underlying type; or a negative value, which equals the arithmetic negation of our highest (preferred) protocol version. So in the latter case -1 means version 1, -2 means version 2, etc.
Returns
See sync_write_or_q_ctl_cmd().
Definition at line 1454 of file blob_stream_mq_snd_impl.hpp.
sync_write_or_q_payload()
template<typename Persistent_mq_handle > bool ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::sync_write_or_q_payload (const util::Blob_const & orig_blob, bool * avoided_qing_or_null) private
Either synchronously sends orig_blob low-level blob over m_mq, or if an async-send is in progress queues it to be sent later; dropping-sans-queuing allowed under certain circumstances in avoided_qing mode.
For details on the latter see below.
m_pending_err_code (pre-condition: it is falsy) is set to the error to ultimately return; and if no such outgoing-pipe-hosing is synchronously encountered it is left untouched. In particular, if falsy upon return, you may call this again to send the next low-level payload. Otherwise m_mq cannot be subsequently used (it is hosed). Thus we maintain the invariant that m_mq is null if and only if that guy is truthy.
avoided_qing mode for auto-ping
If avoided_qing_or_null is null, then see above. If it points to a bool, though, then: the above behavior is slightly modified as follows. Suppose orig_blob encodes an auto-ping message (see auto_ping()). Its purpose is to inform the opposing side that we are alive/not idle. So suppose this method is unable to send orig_blob, either because there are already-queued data waiting to be sent pending writability (due to earlier would-block), or because the MQ has already-queued bytes waiting to be popped by receiver, and there is no space there to enqueue orig_blob. Then the receiver must not be keeping up with us, and the next pop of the MQ will get some message, even if it's not the auto-ping we wanted to send; hence they'll know we are not-idle without the auto-ping. So in that case this method shall:
disregard orig_blob (do not queue it – drop it, as it would be redundant anyway);
return true if and only if the size of the out-queue is 0 (though as of this writing the caller should not care: auto-ping is a fire-and-forget operation, as long as it does not detect a pipe-hosing error);
set *avoided_qing_or_null.
If avoided_qing_or_null is not null, but no error or would-block was encountered – meaning it was placed into MQ synchronously – then *avoided_qing_or_null is set to false.
Why do we even have this as an out-arg? Answer: It is to be used for payload 1 of a CONTROL PING message; so if this is set to true, then caller should not sync_write_or_q_payload() again for payload 2. Otherwise (assuming m_mq is still alive) it should.
Parameters
orig_blob Blob to send. Empty blob is allowed.
avoided_qing_or_null See above.
Returns
false if outgoing-direction pipe still has queued stuff in it that must be sent once transport becomes writable; true otherwise. If true is returned, but avoided_qing_or_null != nullptr, then possibly orig_blob was not sent (at all); was dropped (check *avoided_qing_or_null to see if so).
Definition at line 1335 of file blob_stream_mq_snd_impl.hpp.
Friends And Related Function Documentation
operator<<()
template<typename Persistent_mq_handle > std::ostream & operator<< (std::ostream & os, const Blob_stream_mq_sender_impl< Persistent_mq_handle > & val) related
Prints string representation of the given Blob_stream_mq_sender to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 1702 of file blob_stream_mq_snd_impl.hpp.
References ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::absolute_name(), and ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::nickname().
Member Data Documentation
m_absolute_name
template<typename Persistent_mq_handle > const Shared_name ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_absolute_name private
See absolute_name().
Definition at line 439 of file blob_stream_mq_snd_impl.hpp.
m_auto_ping_period
template<typename Persistent_mq_handle > util::Fine_duration ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_auto_ping_period private
Equals zero() before auto_ping(); immutably equals period (auto_ping() arg) subsequently to that first successful call (if any).
Definition at line 577 of file blob_stream_mq_snd_impl.hpp.
m_auto_ping_timer
template<typename Persistent_mq_handle > flow::util::Timer ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_auto_ping_timer private
Timer that fires on_ev_auto_ping_now_timer_fired() (which sends an auto-ping) and is always scheduled to fire m_auto_ping_period after the last send (send_blob(), auto_ping(), on_ev_auto_ping_now_timer_fired() itself).
Each of these calls indicates a send occurs, hence at worst the pipe will be idle (in need of auto-ping) in m_auto_ping_period. Note that *end_sending(), while also sending bytes, does not schedule m_auto_ping_timer, as *end_sending() closes the conceptual pipe, and there is no need for auto-pinging (see Blob_receiver::idle_timer_run()).
Since we implement sync_io pattern, the timer is obtained from, and used via, util::sync_io::Timer_event_emitter m_timer_worker. See that member's doc header for more info.
Definition at line 590 of file blob_stream_mq_snd_impl.hpp.
m_auto_ping_timer_fired_peer
template<typename Persistent_mq_handle > util::sync_io::Timer_event_emitter::Timer_fired_read_end* ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_auto_ping_timer_fired_peer private
Read-end of IPC-mechanism used by m_timer_worker to ferry timer-fired events from m_auto_ping_timer to sync_io outside async-wait to our actual on-timer-fired handler logic.
See also
m_timer_worker for more info.
Definition at line 598 of file blob_stream_mq_snd_impl.hpp.
m_blocking_worker
template<typename Persistent_mq_handle > std::optional<flow::async::Single_thread_task_loop> ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_blocking_worker private
Worker thread W always in one of 2 states: idle; or (when m_mq is in would-block condition) executing an indefinite, interrupting blocking wait for transmissibility of m_mq.
When thread U wants to send-out a payload but gets would-block, it issues the wait on this thread W and a sync_io-pattern async-wait for m_ev_wait_hndl_mq; once that wait completes in thread W, it writes a byte to an internal IPC-pipe. m_ev_wait_hndl_mq becomes readable, the outside event loop lets *this know, which completes the async-wait.
In dtor we stop thread W, including using Persistent_mq_handle::interrupt_sends() to abort the indefinite wait in thread W, as it will no longer be used once *this is destroyed.
Ordering: If we want to let things get auto-destroyed without explicit m_blocking_worker->stop() or nullifying wrappers in an explicit order, then this must be declared after m_mq. Otherwise code may still be finishing up in thread W when m_mq is destroyed already. Anyway – as long as this is destroyed or .stop()ed before m_mq is gone, you're cool.
Never touched if Persistent_mq_handle::S_HAS_NATIVE_HANDLE.
Definition at line 632 of file blob_stream_mq_snd_impl.hpp.
Referenced by ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Blob_stream_mq_sender_impl().
m_ev_hndl_task_engine_unused
template<typename Persistent_mq_handle > flow::util::Task_engine ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_ev_hndl_task_engine_unused private
The Task_engine for m_ev_wait_hndl_*, unless it is replaced via replace_event_wait_handles().
There are 2 possibilities:
They leave this guy associated with m_ev_wait_hndl_*. Then no one shall be doing .async_wait() on them, and instead the user aims to perhaps use raw [e]poll*() on their .native_handle()s. We still need some Task_engine to construct them though, so we use this.
They use replace_event_wait_handles(), and therefore this becomes dissociated with m_ev_wait_hndl_* and becomes completely unused in any fashion, period. Then they shall probably be doing their own .async_wait() – associated with their own Task_engine – on m_ev_wait_hndl_*.
This is all to fulfill the sync_io pattern.
Definition at line 470 of file blob_stream_mq_snd_impl.hpp.
m_ev_wait_func
template<typename Persistent_mq_handle > util::sync_io::Event_wait_func ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_ev_wait_func private
Function (set forever in start_send_blob_ops()) through which we invoke the outside event loop's async-wait facility for descriptors/events to our ops.
See util::sync_io::Event_wait_func doc header for a refresher on this mechanic.
Definition at line 613 of file blob_stream_mq_snd_impl.hpp.
m_ev_wait_hndl_auto_ping_timer_fired_peer
template<typename Persistent_mq_handle > util::sync_io::Asio_waitable_native_handle ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_ev_wait_hndl_auto_ping_timer_fired_peer private
Descriptor waitable by outside event loop async-waits – storing the same Native_handle as (and thus being used to wait on events from) m_auto_ping_timer_fired_peer.
See also
m_timer_worker for more info.
Definition at line 606 of file blob_stream_mq_snd_impl.hpp.
m_ev_wait_hndl_mq
template<typename Persistent_mq_handle > util::sync_io::Asio_waitable_native_handle ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_ev_wait_hndl_mq private
Descriptor waitable by outside event loop async-waits – storing the same Native_handle as (and thus being used to wait on events from) m_mq_ready_reader; or if m_mq can be watched directly (known at compile-time) then as m_mq itself.
Its name suggests it's watching m_mq (for transmissibility), and that's true: In the latter case one directly watches it for transmissibility in the proper direction; in the former case Persistent_mq_handle lacks a Native_handle to watch directly – but we use the m_mq_ready_* pipe and a background thread to simulate it having one. Thus in that case m_mq_ready_reader FD = this FD, and it being transmissible = MQ being transmissible.
Definition at line 533 of file blob_stream_mq_snd_impl.hpp.
Referenced by ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Blob_stream_mq_sender_impl().
m_finished
template<typename Persistent_mq_handle > bool ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_finished private
false at start; set to true forever on the first *end_sending() invocation; true will prevent any subsequent send_blob() calls from proceeding.
See class doc header impl section for design discussion.
Definition at line 564 of file blob_stream_mq_snd_impl.hpp.
m_mq
template<typename Persistent_mq_handle > Base::Auto_closing_mq ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_mq private
The MQ handle adopted by the ctor, through which nb-sends and blocking-waits are executed.
It is not directly protected by any mutex; however it is accessed exclusively as follows:
By thread W, when m_pending_payloads_q has elements (would-block state), thus thread U has tasked it with awaiting sendability – which it is doing and is not yet done doing.
By thread U, when m_pending_payloads_q is .empty() (no would-block at the moment); or it is not .empty(), but thread W has signaled it is done awaiting non-would-block, so thread U is trying to empty it via nb-writes.
Exception: m_mq->interrupt_sends() is done from thread U (dtor), potentially while thread W is inside m_mq->wait_sendable(). However that specific action is allowed by Persistent_mq_handle contract (in fact that is the main utility of Persistent_mq_handle::interrupt_sends()). It makes the Persistent_mq_handle::wait_sendable() immediately return.
When is it null?
See Blob_stream_mq_receiver_impl::m_mq doc header. The same comments apply here.
Explicit reminder though: Do not m_mq.reset() until dtor, if not null upon exiting ctor!
Definition at line 491 of file blob_stream_mq_snd_impl.hpp.
Referenced by ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Blob_stream_mq_sender_impl().
m_mq_max_msg_sz
template<typename Persistent_mq_handle > const size_t ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_mq_max_msg_sz private
Equals m_mq.max_msg_size().
Rationale
It is saved in ctor, instead of invoking m_mq->max_msg_size() when needed, to keep the rules for when m_mq is accessed simple and as described in its doc header. After all this value would never change anyway.
Definition at line 499 of file blob_stream_mq_snd_impl.hpp.
m_mq_ready_reader
template<typename Persistent_mq_handle > std::optional<util::Pipe_reader> ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_mq_ready_reader private
Read-end of IPC-pipe used by thread U to detect that a thread-W transmissibility-wait has completed, meaning would-block has cleared, and therefore thread U can attempt to nb-transmit again.
The signal byte is read out of m_mq_ready_reader, making it empty again (the steady-state before the next time would-block occurs, and a byte is written to it making it non-empty).
See also
m_mq_ready_writer.
Never touched if Persistent_mq_handle::S_HAS_NATIVE_HANDLE.
Definition at line 511 of file blob_stream_mq_snd_impl.hpp.
Referenced by ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Blob_stream_mq_sender_impl().
m_mq_ready_writer
template<typename Persistent_mq_handle > std::optional<util::Pipe_writer> ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_mq_ready_writer private
Write-end of IPC-pipe used by thread W to inform thread U that a thread-W transmissibility-wait has completed, meaning would-block has cleared, and therefore thread U can attempt to nb-transmit again.
A signal byte is written to m_mq_ready_writer, making it non-empty.
See also
m_mq_ready_reader.
Never touched if Persistent_mq_handle::S_HAS_NATIVE_HANDLE.
Definition at line 522 of file blob_stream_mq_snd_impl.hpp.
Referenced by ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Blob_stream_mq_sender_impl().
m_nb_task_engine
template<typename Persistent_mq_handle > std::optional<flow::util::Task_engine> ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_nb_task_engine private
The Task_engine for m_mq_ready_*.
It is necessary to construct those pipe-end objects, but we never use that guy's ->async_*() APIs – only non-blocking operations, essentially leveraging boost.asio's portable transmission APIs but not its actual, um, async-I/O abilities in this case. Accordingly we never load any tasks onto m_nb_task_engine and certainly never .run() (or .poll() or ...) it.
In the sync_io pattern the user's outside event loop is responsible for awaiting readability/writability of a guy like m_mq_ready_reader via our exporting of its .native_handle().
Never touched if Persistent_mq_handle::S_HAS_NATIVE_HANDLE.
Todo:
Consider using specialization instead of or in addition if constexpr() w/r/t Mq::S_HAS_NATIVE_HANDLE-based compile-time branching: it could save some RAM by eliminating optionals such as the one near this to-do; though code would likely become wordier.
Definition at line 456 of file blob_stream_mq_snd_impl.hpp.
Referenced by ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Blob_stream_mq_sender_impl().
m_nickname
template<typename Persistent_mq_handle > const std::string ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_nickname private
See nickname().
Definition at line 394 of file blob_stream_mq_snd_impl.hpp.
m_pending_err_code
template<typename Persistent_mq_handle > Error_code ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_pending_err_code private
The first and only connection-hosing error condition detected when attempting to low-level-write on m_mq; or falsy if no such error has yet been detected.
Among possible other uses, it is returned by send_blob() and the completion handler of async_end_sending().
Definition at line 557 of file blob_stream_mq_snd_impl.hpp.
Referenced by ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::Blob_stream_mq_sender_impl().
m_pending_on_last_send_done_func_or_empty
template<typename Persistent_mq_handle > flow::async::Task_asio_err ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_pending_on_last_send_done_func_or_empty private
Function passed to async_end_sending(), if it returned true and was unable to synchronously flush everything including the graceful-close itself (synchronously detecting new or previous pipe-hosing error does entail flushing everything); otherwise .empty().
It's the completion handler of that graceful-close-send API.
Definition at line 571 of file blob_stream_mq_snd_impl.hpp.
m_pending_payloads_q
template<typename Persistent_mq_handle > std::queue<typename Snd_low_lvl_payload::Ptr> ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_pending_payloads_q private
Queue storing (at head) the currently in-progress async write-op of a Snd_low_lvl_payload; followed by the payloads that should be written after that completes, in order.
Only touched if would-block is encountered in... well, see Snd_low_lvl_payload doc header (et al).
Definition at line 550 of file blob_stream_mq_snd_impl.hpp.
m_protocol_negotiator
template<typename Persistent_mq_handle > Protocol_negotiator ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_protocol_negotiator private
Handles the protocol negotiation at the start of the pipe.
See also
Protocol_negotiator doc header for key background on the topic. In particular check out the discussion "Key tip: Coding for version-1 versus one version versus multiple versions."
Maintenace/future
This version of the software talks only the initial version of the protocol: version 1 by Protocol_negotiator convention. (Deities willing, we won't need to create more, but possibly we will.) As expained in the above-mentioned doc header section, we have very little to worry about as the sender: Just send our version, 1, as the first message (in fact, a special CONTROL message; and we send it first-thing, ahead of the first payload that would be otherwise sent, whether it's a user payload, or the end-sending token, or an auto-ping). Only version 1 exists, so we simply speak it.
This might change in the future. If there is a version 2 or later, and at some point we decide to maintain backwards-compatibility (not a no-brainer decision in either direction), meaning we pass a range of 2 versions or more to Protocol_negotiator ctor, then:
We will need to know which version to speak when sending at least some of our messages.
Normally we'd get this via a separate incoming pipe – a paired Blob_stream_mq_receiver handling a separate associated MQ. So we'd need:
some kind of internal logic to enter a would-block state of sorts (if we need to know the version for a certain out-message, and we haven't been told it yet) during which stuff is queued-up and not yet sent until signaled with the negotiated protocol version;
some kind of API that would let the paired Blob_stream_mq_receiver signal us to tell us that version, when it knows;
possibly some kind of API that one could use in the absence of such a paired opposite-facing pipe, so that our user can simply tell us what protocol version to speak in lieu of the paired Blob_stream_mq_receiver.
(Just to point a fine point on it: We are one direction of a likely bidirectional comm pathway. Protocol_negotiator by definition applies to a bidirectional pathway. Yet we can exist in isolation, with no partner opposing MQ and therefore no partner local Blob_stream_mq_sender_impl. If that is indeed the case, then it is meaningless for us to somehow find out what protocol the either side speaks, as the other side has no way of sending us anything! Hence the dichotomy between those last 2 sub-bullets: If we exist in isolation and are unidirectional, then you'd best simply tell us what to speak... but if we're part of a bidirectional setup, then we can cooperate with the other direction more automagically.
These are decisions and work for another day, though; it is not relevant until version 2 of this protocol at the earliest. That might not even happen.
Definition at line 436 of file blob_stream_mq_snd_impl.hpp.
m_timer_worker
template<typename Persistent_mq_handle > util::sync_io::Timer_event_emitter ipc::transport::sync_io::Blob_stream_mq_sender_impl< Persistent_mq_handle >::m_timer_worker private
As typical in timer-needing sync_io-pattern-implementing objects, maintains a thread exclusively for Timer wait completion handlers which ferry timer-fired events to internal IPC-mechanisms waitable by the sync_io-pattern-using outside event loop.
In our case we (optionally) maintain the auto-ping timer.
See also
util::sync_io::Timer_event_emitter doc header for design/rationale discussion.
Definition at line 542 of file blob_stream_mq_snd_impl.hpp.
The documentation for this class was generated from the following files:
transport/detail/transport_fwd.hpp
transport/sync_io/detail/blob_stream_mq_snd_impl.hpp