Flow-IPC: ipc::session::sync_io::Session_server_adapter< Session_server > Class Template Reference
ipc::session::sync_io::Session_server_adapter< Session_server > Class Template Reference
sync_io-pattern counterpart to async-I/O-pattern session::Session_server types and all their SHM-aware variations (at least shm::classic::Session_server and shm::arena_lend::jemalloc::Session_server).
#include <session_server_adapter.hpp>
Public Types
using Session_server_obj = Session_server
Short-hand, for generic programming et al, for template parameter Session_server.
using Session_obj = Server_session_adapter< typename Session_server_obj::Server_session_obj >
Short-hand for object type targeted by async_accept().
using Async_io_obj = Session_server_obj
Useful for generic programming, the async-I/O-pattern counterpart to *this type.
using Sync_io_obj = transport::Null_peer
You may disregard.
Public Member Functions
template<typename... Ctor_args>
Session_server_adapter (Ctor_args &&... ctor_args)
Forwards to the Session_server_obj ctor.
template<typename Event_wait_func_t >
bool start_ops (Event_wait_func_t &&ev_wait_func)
All notes from Client_session_adapter::start_ops() apply equally.
template<typename Create_ev_wait_hndl_func >
bool replace_event_wait_handles (const Create_ev_wait_hndl_func &create_ev_wait_hndl_func)
All notes from Client_session_adapter::replace_event_wait_handles() apply equally.
template<typename Task_err >
bool async_accept (Session_obj *target_session, Task_err &&on_done_func)
Acts identically to 1-arg overload of Session_server::async_accept(), except that the completion handler is invoked in the sync_io-pattern fashion, synchronously inside an async-wait performed by you and reported via (*on_active_ev_func)().
template<typename Task_err , typename N_init_channels_by_srv_req_func , typename Mdt_load_func >
bool async_accept (Session_obj *target_session, typename Session_server_obj::Channels *init_channels_by_srv_req, typename Session_server_obj::Mdt_reader_ptr *mdt_from_cli_or_null, typename Session_server_obj::Channels *init_channels_by_cli_req, N_init_channels_by_srv_req_func &&n_init_channels_by_srv_req_func, Mdt_load_func &&mdt_load_func, Task_err &&on_done_func)
Acts identically to 7-arg overload of Session_server::async_accept(), except that the completion handler is invoked in the sync_io-pattern fashion, synchronously inside an async-wait performed by you and reported via (*on_active_ev_func)().
Session_server_obj * core ()
The adapted mutable Session_server_obj.
const Session_server_obj * core () const
The adapted immutable Session_server_obj.
flow::log::Logger * get_logger () const
See flow::log::Log_context.
const flow::log::Component & get_log_component () const
See flow::log::Log_context.
Private Member Functions
void accept_write (const Error_code &err_code)
The real handler given for on_done_func to Session_server_obj::async_accept(): it records the result of that async-accept to m_target_err_code, then signals accept_read() via the IPC-pipe.
void accept_read ()
Signaled by accept_write(), it returns the IPC-pipe to steady-state (empty, not readable), then invokes the original user on_done_func().
Private Attributes
flow::util::Task_engine m_nb_task_engine
Similar to the one in Session_adapter.
flow::util::Task_engine m_ev_hndl_task_engine_unused
Similar to the one in Session_adapter.
util::Pipe_reader m_ready_reader
Similar to the one in Session_adapter, applied to async_accept().
util::Pipe_writer m_ready_writer
Similar to the one in Session_adapter, applied to async_accept().
util::sync_io::Asio_waitable_native_handle m_ev_wait_hndl
Similar to the one in Session_adapter, applied to async_accept().
util::sync_io::Event_wait_func m_ev_wait_func
Similar to the one in Session_adapter.
flow::async::Task_asio_err m_on_done_func_or_empty
on_done_func from async_accept() if one is pending; otherwise .empty().
Error_code m_target_err_code
Result given to (or about to be given to) m_on_done_func_or_empty.
Async_io_obj m_async_io
This guy does all the work. In our dtor this will be destroyed (hence thread stopped) first-thing.
Related Functions
(Note that these are not member functions.)
template<typename Session_server >
std::ostream & operator<< (std::ostream &os, const Session_server_adapter< Session_server > &val)
Prints string representation of the given Session_server_adapter to the given ostream.
Detailed Description
template<typename Session_server>
class ipc::session::sync_io::Session_server_adapter< Session_server >
sync_io-pattern counterpart to async-I/O-pattern session::Session_server types and all their SHM-aware variations (at least shm::classic::Session_server and shm::arena_lend::jemalloc::Session_server).
In point of fact:
Use this if and only if you desire a sync_io-pattern style of being informed of async events from a Session_server and Server_session of any kind. For example, you may find this convenient if your event loop is an old-school reactor using poll() or epoll_wait(). This affects exactly the following APIs:
Session_server::async_accept(),
This Session_server_adapter adapts a Session_server constructed and stored within *this. All APIs excluding the above – that is to say all non-async APIs – are to be invoked via core() accessor.
Trying to use core()->async_accept() leads to undefined behavior.
See also
util::sync_io doc header – describes the general sync_io pattern we are following.
session::Session_server, shm::classic::Session_server, shm::arena_lend::jemalloc::Session_server.
As is generally the case when choosing sync_io::X versus X, we recommend using X due to it being easier. In this particular case (see below) there is no perf benefit to using sync_io::X, either, so the only reason to use sync_io::X in this case would be because you've got an old-school reactor event loop with a poll() or epoll_wait(), in which case the sync_io API may be easier to integrate.
To use it:
Construct it explicitly. The ctor signature is exactly identical to that of session::Session_server.
Set up sync_io pattern using start_ops() (and if needed precede it with replace_event_wait_handles()).
Use async_accept() in similar fashion to async-I/O Server_session supplying a completion handler (though it will be invoked synchronously per sync_io pattern).
As normal, construct a blank Server_session to pass as the target of async_accept(). The type of this object shall be Session_server_adapter::Session_obj; it shall be a concrete type of the class template Session_server_adapter.
On successful accept:
See doc header for Session_server_adapter on what to do next. Spoiler alert: Server_session_adapter::start_ops(), then Server_session_adapter::init_handlers() (mirroring a vanilla Server_session).
Use core()-> for all other API needs (e.g., shm::classic::Session_server::app_shm()).
Internal implementation
Normally this would not be in the public docs for this public-use class, but indulge us...
...by reading an equally applicable note in Client_session_adapter doc header.
Template Parameters
Session_server The async-I/O Session_server concrete type being adapted. As of this writing that would be one of at least: session::Session_server<knobs>, session::shm::classic::Session_server<knobs>, session::shm::jemalloc::Session_server<knobs>.
Definition at line 73 of file session_server_adapter.hpp.
Member Typedef Documentation
Async_io_obj
template<typename Session_server > using ipc::session::sync_io::Session_server_adapter< Session_server >::Async_io_obj = Session_server_obj
Useful for generic programming, the async-I/O-pattern counterpart to *this type.
Definition at line 85 of file session_server_adapter.hpp.
Session_obj
template<typename Session_server > using ipc::session::sync_io::Session_server_adapter< Session_server >::Session_obj = Server_session_adapter<typename Session_server_obj::Server_session_obj>
Short-hand for object type targeted by async_accept().
Definition at line 82 of file session_server_adapter.hpp.
Session_server_obj
template<typename Session_server > using ipc::session::sync_io::Session_server_adapter< Session_server >::Session_server_obj = Session_server
Short-hand, for generic programming et al, for template parameter Session_server.
Definition at line 79 of file session_server_adapter.hpp.
Sync_io_obj
template<typename Session_server > using ipc::session::sync_io::Session_server_adapter< Session_server >::Sync_io_obj = transport::Null_peer
You may disregard.
Definition at line 87 of file session_server_adapter.hpp.
Constructor & Destructor Documentation
Session_server_adapter()
template<typename Session_server > template<typename... Ctor_args> ipc::session::sync_io::Session_server_adapter< Session_server >::Session_server_adapter (Ctor_args &&... ctor_args)
Forwards to the Session_server_obj ctor.
See Session_server ctor doc headers.
Template Parameters
Ctor_args See above.
Parameters
ctor_args See above.
Definition at line 266 of file session_server_adapter.hpp.
References ipc::util::sync_io::Asio_waitable_native_handle::assign(), ipc::session::sync_io::Session_server_adapter< Session_server >::m_ev_wait_hndl, ipc::session::sync_io::Session_server_adapter< Session_server >::m_ready_reader, and ipc::session::sync_io::Session_server_adapter< Session_server >::m_ready_writer.
Member Function Documentation
accept_read()
template<typename Session_server > void ipc::session::sync_io::Session_server_adapter< Session_server >::accept_read private
Signaled by accept_write(), it returns the IPC-pipe to steady-state (empty, not readable), then invokes the original user on_done_func().
Definition at line 419 of file session_server_adapter.hpp.
References ipc::util::pipe_consume().
accept_write()
template<typename Session_server > void ipc::session::sync_io::Session_server_adapter< Session_server >::accept_write (const Error_code & err_code) private
The real handler given for on_done_func to Session_server_obj::async_accept(): it records the result of that async-accept to m_target_err_code, then signals accept_read() via the IPC-pipe.
Parameters
err_code Result from Session_server_obj::async_accept().
Definition at line 402 of file session_server_adapter.hpp.
References ipc::util::pipe_produce(), and ipc::session::error::S_OBJECT_SHUTDOWN_ABORTED_COMPLETION_HANDLER.
async_accept() [1/2]
template<typename Session_server > template<typename Task_err > bool ipc::session::sync_io::Session_server_adapter< Session_server >::async_accept (Session_obj * target_session, Task_err && on_done_func)
Acts identically to 1-arg overload of Session_server::async_accept(), except that the completion handler is invoked in the sync_io-pattern fashion, synchronously inside an async-wait performed by you and reported via (*on_active_ev_func)().
Returns false if invoked before start_ops().
Template Parameters
Task_err See above.
Parameters
target_session Pointer to Session_obj which shall be assigned an almost-PEER-state (open, requires Server_session_adapter::init_handlers() to enter PEER state) as on_done_func() is called. Not touched on error. Recommend default-constructing a Session_obj and passing pointer thereto here.
on_done_func See above.
Returns
true on successful start to async-accept; false if called before start_ops().
Definition at line 341 of file session_server_adapter.hpp.
References ipc::session::sync_io::Server_session_adapter< Session >::core().
async_accept() [2/2]
template<typename Session_server > template<typename Task_err , typename N_init_channels_by_srv_req_func , typename Mdt_load_func > bool ipc::session::sync_io::Session_server_adapter< Session_server >::async_accept (Session_obj * target_session, typename Session_server_obj::Channels * init_channels_by_srv_req, typename Session_server_obj::Mdt_reader_ptr * mdt_from_cli_or_null, typename Session_server_obj::Channels * init_channels_by_cli_req, N_init_channels_by_srv_req_func && n_init_channels_by_srv_req_func, Mdt_load_func && mdt_load_func, Task_err && on_done_func)
Acts identically to 7-arg overload of Session_server::async_accept(), except that the completion handler is invoked in the sync_io-pattern fashion, synchronously inside an async-wait performed by you and reported via (*on_active_ev_func)().
Returns false if invoked before start_ops().
Template Parameters
Task_err See above.
N_init_channels_by_srv_req_func See above.
Mdt_load_func See above.
Parameters
target_session See above.
init_channels_by_srv_req See above.
mdt_from_cli_or_null See above: null or pointer to Reader of metadata which shall be set for access on success.
init_channels_by_cli_req See above.
n_init_channels_by_srv_req_func See above.
mdt_load_func See above.
on_done_func See above.
Returns
true on successful start to async-accept; false if called before start_ops().
Definition at line 368 of file session_server_adapter.hpp.
References ipc::session::sync_io::Server_session_adapter< Session >::core().
core() [1/2]
template<typename Session_server > Session_server_adapter< Session_server >::Session_server_obj * ipc::session::sync_io::Session_server_adapter< Session_server >::core
The adapted mutable Session_server_obj.
It is safe to access any API except for core()->async_accept() (undefined behavior); use this->async_accept() instead. Remember that start_ops() is required first.
Returns
See above.
Definition at line 434 of file session_server_adapter.hpp.
Referenced by ipc::session::sync_io::Session_server_adapter< Session_server >::operator<<().
core() [2/2]
template<typename Session_server > const Session_server_adapter< Session_server >::Session_server_obj * ipc::session::sync_io::Session_server_adapter< Session_server >::core
The adapted immutable Session_server_obj.
Remember that start_ops() is required first.
Returns
See above.
Definition at line 441 of file session_server_adapter.hpp.
get_log_component()
template<typename Session_server > const flow::log::Component & ipc::session::sync_io::Session_server_adapter< Session_server >::get_log_component
See flow::log::Log_context.
Returns
See above.
Definition at line 453 of file session_server_adapter.hpp.
get_logger()
template<typename Session_server > flow::log::Logger * ipc::session::sync_io::Session_server_adapter< Session_server >::get_logger
See flow::log::Log_context.
Returns
See above.
Definition at line 447 of file session_server_adapter.hpp.
replace_event_wait_handles()
template<typename Session_server > template<typename Create_ev_wait_hndl_func > bool ipc::session::sync_io::Session_server_adapter< Session_server >::replace_event_wait_handles (const Create_ev_wait_hndl_func & create_ev_wait_hndl_func)
All notes from Client_session_adapter::replace_event_wait_handles() apply equally.
Template Parameters
Create_ev_wait_hndl_func See above.
Parameters
create_ev_wait_hndl_func See above.
Returns
See above.
Definition at line 313 of file session_server_adapter.hpp.
start_ops()
template<typename Session_server > template<typename Event_wait_func_t > bool ipc::session::sync_io::Session_server_adapter< Session_server >::start_ops (Event_wait_func_t && ev_wait_func)
All notes from Client_session_adapter::start_ops() apply equally.
Template Parameters
Event_wait_func_t See above.
Parameters
ev_wait_func See above.
Returns
See above.
Definition at line 291 of file session_server_adapter.hpp.
Friends And Related Function Documentation
operator<<()
template<typename Session_server > std::ostream & operator<< (std::ostream & os, const Session_server_adapter< Session_server > & val) related
Prints string representation of the given Session_server_adapter to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 459 of file session_server_adapter.hpp.
References ipc::session::sync_io::Session_server_adapter< Session_server >::core().
Member Data Documentation
m_async_io
template<typename Session_server > Async_io_obj ipc::session::sync_io::Session_server_adapter< Session_server >::m_async_io private
This guy does all the work. In our dtor this will be destroyed (hence thread stopped) first-thing.
Definition at line 257 of file session_server_adapter.hpp.
m_ev_hndl_task_engine_unused
template<typename Session_server > flow::util::Task_engine ipc::session::sync_io::Session_server_adapter< Session_server >::m_ev_hndl_task_engine_unused private
Similar to the one in Session_adapter.
Definition at line 236 of file session_server_adapter.hpp.
m_ev_wait_func
template<typename Session_server > util::sync_io::Event_wait_func ipc::session::sync_io::Session_server_adapter< Session_server >::m_ev_wait_func private
Similar to the one in Session_adapter.
Definition at line 248 of file session_server_adapter.hpp.
m_ev_wait_hndl
template<typename Session_server > util::sync_io::Asio_waitable_native_handle ipc::session::sync_io::Session_server_adapter< Session_server >::m_ev_wait_hndl private
Similar to the one in Session_adapter, applied to async_accept().
Definition at line 245 of file session_server_adapter.hpp.
Referenced by ipc::session::sync_io::Session_server_adapter< Session_server >::Session_server_adapter().
m_nb_task_engine
template<typename Session_server > flow::util::Task_engine ipc::session::sync_io::Session_server_adapter< Session_server >::m_nb_task_engine private
Similar to the one in Session_adapter.
Definition at line 233 of file session_server_adapter.hpp.
m_on_done_func_or_empty
template<typename Session_server > flow::async::Task_asio_err ipc::session::sync_io::Session_server_adapter< Session_server >::m_on_done_func_or_empty private
on_done_func from async_accept() if one is pending; otherwise .empty().
Definition at line 251 of file session_server_adapter.hpp.
m_ready_reader
template<typename Session_server > util::Pipe_reader ipc::session::sync_io::Session_server_adapter< Session_server >::m_ready_reader private
Similar to the one in Session_adapter, applied to async_accept().
Definition at line 239 of file session_server_adapter.hpp.
Referenced by ipc::session::sync_io::Session_server_adapter< Session_server >::Session_server_adapter().
m_ready_writer
template<typename Session_server > util::Pipe_writer ipc::session::sync_io::Session_server_adapter< Session_server >::m_ready_writer private
Similar to the one in Session_adapter, applied to async_accept().
Definition at line 242 of file session_server_adapter.hpp.
Referenced by ipc::session::sync_io::Session_server_adapter< Session_server >::Session_server_adapter().
m_target_err_code
template<typename Session_server > Error_code ipc::session::sync_io::Session_server_adapter< Session_server >::m_target_err_code private
Result given to (or about to be given to) m_on_done_func_or_empty.
Definition at line 254 of file session_server_adapter.hpp.
The documentation for this class was generated from the following files:
session/session_fwd.hpp
session/sync_io/session_server_adapter.hpp