Flow-IPC: ipc::transport::struc::Heap_fixed_builder Class Reference
ipc::transport::struc::Heap_fixed_builder Class Reference
Implements Struct_builder concept by straightforwardly allocating fixed-size segments on-demand in the regular heap and serializing directly inside those segments.
#include <heap_serializer.hpp>
Classes
struct Config
Implements Struct_builder::Config sub-concept.
Public Types
using Session = Null_session
Implements concept API.
Public Member Functions
Heap_fixed_builder ()
Implements concept API.
Heap_fixed_builder (const Config &config)
Implements concept API.
Heap_fixed_builder (const Heap_fixed_builder &)=delete
Disallow copy construction.
Heap_fixed_builder (Heap_fixed_builder &&src)
Implements concept API.
~Heap_fixed_builder ()
Implements concept API.
Heap_fixed_builder & operator= (const Heap_fixed_builder &)=delete
Disallow copy assignment.
Heap_fixed_builder & operator= (Heap_fixed_builder &&src)
Implements concept API.
Capnp_msg_builder_interface * payload_msg_builder ()
Implements concept API.
void emit_serialization (Segment_ptrs *target_blobs, const Session &session, Error_code *err_code=0) const
Implements concept API.
size_t n_serialization_segments () const
Implements concept API.
Private Types
using Capnp_heap_engine = Heap_fixed_builder_capnp_message_builder
Alias for the capnp MallocMessageBuilder-like serialization engine of ours.
Private Attributes
size_t m_segment_sz
See ctor. We only store it to be able to emit S_INTERNAL_ERROR_SERIALIZE_LEAF_TOO_BIG in emit_serialization().
boost::movelib::unique_ptr< Capnp_heap_engine > m_engine
The capnp builder engine which really does the work including owning the needed allocated segments so far.
Related Functions
(Note that these are not member functions.)
std::ostream & operator<< (std::ostream &os, const Heap_fixed_builder &val)
Prints string representation of the given Heap_fixed_builder to the given ostream.
Detailed Description
Implements Struct_builder concept by straightforwardly allocating fixed-size segments on-demand in the regular heap and serializing directly inside those segments.
That is, each mutation via payload_msg_builder() may, as needed, trigger a malloc() (or similar) of size N passed to the ctor of Heap_fixed_builder; and each buffer returned by emit_serialization() will be of size N or less.
Failure mode
As long as each leaf capnp object set via mutation of payload_msg_builder() can be serialized in N bytes or fewer, emit_serialization() shall succeed. For fixed-size leaves this is generally not a problem; for reasonable N in the KiB, things such as integers and enumerations won't be a problem. However for variable-size objects, particularly strings and blobs and lists and the like, it can be easy to exceed N. In this case, even though internally the problem could be detected at mutation time, it will be reported in the next emit_serialization() call (as mandated by the concept API). Specifically error::Code::S_INTERNAL_ERROR_SERIALIZE_LEAF_TOO_BIG shall be emitted. See "Reasonable uses" below for discussion on avoiding this fate.
Reasonable uses
This is suitable for transmission via a Blob_sender (or Native_handle_sender) wherein each blob (or meta-blob, respectively) sent has either a hard size limit (meaning a Blob_sender::send_blob() or Native_handle_sender::send_native_handle() call will fail if this limit is exceeded) or an effective limit (meaning transmission performance is poor in the same event). Indeed the use cases that informed this strategy were:
Blob_stream_mq_sender::send_blob() shall fail if blob.size() >= N, where N is the message size limit passed to its ctor.
Native_socket_stream::send_*() shall fail if blob.size() >= sync_io::Native_socket_stream::S_MAX_META_BLOB_LENGTH.
Moreover Native_socket_stream informally is documented to feature good performance compared to the MQ-based streams when not exceeding the "10s-of-KiB range" (quoting its doc header as of this writing).
In "Failure mode" above we pointed out an immediate danger if one uses Heap_fixed_builder to naively serialize arbitrary user-supplied schemas. Simply put, if one mutates payload_msg_builder() in such a way as to introduce a big leaf, such as a large image blob, then emit_serialization()) will emit error::Code::S_INTERNAL_ERROR_SERIALIZE_LEAF_TOO_BIG; and that's the end of that.
Even if one avoids this somehow – let's say by always fragmenting large things into smaller-size leaves (itself undesirable: the point of serialization of structured data is to not have to worry about data representation at the application level) – this can lead to, well, a fragmented representation, inefficiently using each N-sized segment with too much unused space. So what to do?
One could write a builder similar to Heap_fixed_builder minus the _fixed part; certainly capnp supplies the tools needed to simply allocate large-enough segments (internally, a capnp::MallocMessageBuilder-like MessageBuilder is used already; we'd just need to use different knob values on MallocMessageBuilder or similar and be less draconian in what segment sizes emit_serialization()) will allow). Of course then the transport mechanism used for the resulting segments would need to be able to handle larger blobs. Blob_stream_mq_sender already supports larger max message sizes, and Native_socket_stream with a larger or variable S_MAX_META_BLOB_LENGTH could be written. Or even without that one could split any too-large segments across multiple blobs. However that's hardly consolation in practice: too much RAM use could result; and/or the copying involved would eventually prove too expensive. So... probably the non-_fixed/multi-blob-segment approaches are not good enough, at least not in general. So what to do?
At least one approach is to use a 2-layer approach. The true serialization of the user's schema could be placed in SHared Memory (SHM). Then only a handle (or handles) to this SHM-stored serialization could be transmitted via Heap_fixed_builder; even a single segment of small size would be enough to transmit as much, as each handle is (more or less) a pointer. Although the SHM-based builder (documented elsewhere) would be the one used at the higher level, internally it would leverage Heap_fixed_builder to transmit the handle(s) to SHM.
Hence Heap_fixed_builder remains of use; but keep in mind the above limitations and (at least its original) intended use.
The above discussion is a more specific treatment of the outer-serialization/inner-serialization discussion in the Struct_builder concept doc header.
Implementation
If one is familiar with capnp, then one can probably quickly guess how this class template accomplishes what it promises in just the brief summary at the top of this doc header: Heap_fixed_builder_capnp_message_builder is what we use internally; it's like MallocMessageBuilder but (1) mandates the equivalent of AllocationStrategy::FIXED_SIZE always and (2) has support for a framing prefix and postfix coexisting within each allocated buffer per segment (per our ctor args). As it must, that builder (like MallocMessageBuilder) is documented to allocate a larger-than-N segment if necessary to encode a particular too-large leaf. We do not stop this in and of itself; but emit_serialization() simply refuses to return this resulting serialization, if it detects than indeed such a segment had to be allocated during preceding payload_msg_builder() mutations. So *this will allocate and eat the needed RAM; but it simply will refuse to return it publicly.
See also
Heap_reader Counterpart Struct_reader implementation that can deserialize data that this has serialized.
Struct_builder: implemented concept.
Definition at line 130 of file heap_serializer.hpp.
Member Typedef Documentation
Capnp_heap_engine
using ipc::transport::struc::Heap_fixed_builder::Capnp_heap_engine = Heap_fixed_builder_capnp_message_builder private
Alias for the capnp MallocMessageBuilder-like serialization engine of ours.
Definition at line 278 of file heap_serializer.hpp.
Session
using ipc::transport::struc::Heap_fixed_builder::Session = Null_session
Implements concept API.
This being a non-zero-copy Struct_builder, no information is needed for emit_serialization() beyond the payload itself.
Definition at line 177 of file heap_serializer.hpp.
Constructor & Destructor Documentation
Heap_fixed_builder() [1/3]
ipc::transport::struc::Heap_fixed_builder::Heap_fixed_builder () default
Implements concept API.
See also
Struct_builder::Struct_builder(): implemented concept.
Heap_fixed_builder() [2/3]
ipc::transport::struc::Heap_fixed_builder::Heap_fixed_builder (const Config & config) explicit
Implements concept API.
See Config doc header for information on how *this behavior is controlled by config.
Parameters
config See above.
See also
Struct_builder::Struct_builder(): implemented concept.
Definition at line 41 of file heap_serializer.cpp.
References m_segment_sz.
Heap_fixed_builder() [3/3]
ipc::transport::struc::Heap_fixed_builder::Heap_fixed_builder (Heap_fixed_builder && src) default
Implements concept API.
Parameters
src See above.
See also
Struct_builder::Struct_builder(): implemented concept.
~Heap_fixed_builder()
ipc::transport::struc::Heap_fixed_builder::~Heap_fixed_builder ()
Implements concept API.
In this impl: frees all segments allocated on-demand so far.
See also
Struct_builder::~Struct_builder(): implemented concept.
Definition at line 57 of file heap_serializer.cpp.
Member Function Documentation
emit_serialization()
void ipc::transport::struc::Heap_fixed_builder::emit_serialization (Segment_ptrs * target_blobs, const Session & session, Error_code * err_code = 0) const
Implements concept API.
Errors
As discussed in class doc header, you should be on guard for the particular error error::Code::S_INTERNAL_ERROR_SERIALIZE_LEAF_TOO_BIG. See class doc header for discussion on how to avoid it. As of this writing no other failure modes exist.
Parameters
target_blobs See above. Also recall (see ctor) that for each returned blob: individual segment sizes shall never exceed Config::m_segment_sz (for the [begin(), end()) area), with start() == m_frame_prefix_sz, and with capacity() - start() - size() >= m_frame_postfix_sz.
session See above. In this case the proper value is NULL_SESSION.
err_code See above. Error_code generated: error::Code::S_INTERNAL_ERROR_SERIALIZE_LEAF_TOO_BIG (a previous mutation introduced a leaf whose serialization would necessitate allocating a segment exceeding Config::m_segment_sz – see ctor – in size).
See also
Struct_builder::emit_serialization(): implemented concept.
Definition at line 72 of file heap_serializer.cpp.
References emit_serialization(), m_engine, m_segment_sz, and ipc::transport::struc::error::S_INTERNAL_ERROR_SERIALIZE_LEAF_TOO_BIG.
Referenced by ipc::transport::struc::shm::Builder< Shm_arena >::emit_serialization(), and emit_serialization().
n_serialization_segments()
size_t ipc::transport::struc::Heap_fixed_builder::n_serialization_segments () const
Implements concept API.
Returns
See above.
See also
Struct_builder::n_serialization_segments(): implemented concept.
Definition at line 125 of file heap_serializer.cpp.
References m_engine.
operator=()
Heap_fixed_builder & ipc::transport::struc::Heap_fixed_builder::operator= (Heap_fixed_builder && src) default
Implements concept API.
Parameters
src See above.
Returns
See above.
See also
Struct_builder::Struct_builder(): implemented concept.
payload_msg_builder()
Capnp_msg_builder_interface * ipc::transport::struc::Heap_fixed_builder::payload_msg_builder ()
Implements concept API.
Returns
See above.
See also
Struct_builder::payload_msg_builder(): implemented concept.
Definition at line 65 of file heap_serializer.cpp.
References m_engine.
Referenced by ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::send_proto_neg().
Friends And Related Function Documentation
operator<<()
std::ostream & operator<< (std::ostream & os, const Heap_fixed_builder & val) related
Prints string representation of the given Heap_fixed_builder to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 132 of file heap_serializer.cpp.
Member Data Documentation
m_engine
boost::movelib::unique_ptr<Capnp_heap_engine> ipc::transport::struc::Heap_fixed_builder::m_engine private
The capnp builder engine which really does the work including owning the needed allocated segments so far.
payload_msg_builder() simply returns (up-cast of) &m_engine.
Why the unique_ptr wrapper?
This is subtler than it appears: We need to be move-ctible and move-assignable; and m_engine therefore does too – and in fact Capnp_heap_engine is. So the unique_ptr wrapping appears superfluous and a waste of compute and space at least. However, see the note on move-ctibility/assignability in Heap_fixed_builder_capnp_message_builder doc header: It is those things, because super-class (interface) Capnp_msg_builder_interface is, but any Capnp_msg_builder_interface sub-class's move (if available) has to copy ~200 bytes at least. Whether the extra alloc/dealloc is better than a copy of that length is a bit questionable, but we suspect it is at least somewhat better.
As a side benefit: it's an easy way to detect a moved-from *this and assert() in some situations.
Definition at line 300 of file heap_serializer.hpp.
Referenced by emit_serialization(), n_serialization_segments(), and payload_msg_builder().
m_segment_sz
size_t ipc::transport::struc::Heap_fixed_builder::m_segment_sz private
See ctor. We only store it to be able to emit S_INTERNAL_ERROR_SERIALIZE_LEAF_TOO_BIG in emit_serialization().
Definition at line 283 of file heap_serializer.hpp.
Referenced by emit_serialization(), and Heap_fixed_builder().
The documentation for this class was generated from the following files:
transport/struc/heap_serializer.hpp
transport/struc/heap_serializer.cpp
transport/struc/struc_fwd.hpp