Flow-IPC: ipc::session::sync_io::Session_adapter< Session > Class Template Reference
ipc::session::sync_io::Session_adapter< Session > Class Template Reference
Internal-use workhorse containing common elements of Client_session_adapter and Server_session_adapter.
#include <session_adapter.hpp>
Classes
struct Channel_open_result
Set of result arg values from a successful passive-channel-open from a Session_obj invoking On_channel_func.
Public Types
using Session_obj = Session
See, e.g., Client_session_adapter.
using Base = Session_obj
Our main base.
using Sync_io_obj = transport::Null_peer
See, e.g., Client_session_adapter.
using Async_io_obj = Session_obj
See, e.g., Client_session_adapter.
using Channel_obj = typename Session_obj::Channel_obj
Short-hand for session-openable Channel type.
using Mdt_reader_ptr = typename Session_obj::Mdt_reader_ptr
Short-hand for session-open metadata reader.
using On_channel_func = Function< void(Channel_obj &&, Mdt_reader_ptr &&)>
Short-hand for passive-channel-open handler.
Public Types inherited from ipc::session::Session< Mdt_payload >
using Channel_obj = unspecified
Each successful open_channel() and on-passive-open handler firing shall yield a concrete transport::Channel instance of this type – in PEER state.
using Mdt_payload_obj = Mdt_payload
Short-hand for Mdt_payload template arg.
using Mdt_builder = typename transport::struc::schema::Metadata< Mdt_payload_obj >::Builder
Pointee of Mdt_builder_ptr.
using Mdt_builder_ptr = shared_ptr< Mdt_builder >
Ref-counted handle to a capnp-generated Builder (and the payload it accesses) through which the user shall mutate the open_channel() metadata before invoking open_channel().
using Mdt_reader_ptr = shared_ptr< typename transport::struc::schema::Metadata< Mdt_payload_obj >::Reader >
Ref-counted handle to a capnp-generated Reader (and the payload it accesses) through which the user shall access the metadata the other side prepared via Mdt_builder_ptr.
template<typename Message_body >
using Structured_channel = transport::struc::Channel< unspecified >
Convenience alias for the transport::struc::Channel concrete type to use if one desires (1) to upgrade a *this-generated channel to a struc::Channel and (2) to efficiently use the built-in capabilities of *this (notably, if applicable: SHM) for zero-copy performance when sending messages through that channel.
using Structured_msg_builder_config = unspecified
Convenience alias equal to Structured_channel<M>::Builder_config (regardless of M).
using Structured_msg_reader_config = unspecified
Convenience alias equal to Structured_channel<M>::Reader_config (regardless of M).
Public Member Functions
template<typename On_passive_open_channel_handler , typename Task_err >
Session_adapter (flow::log::Logger *logger_ptr, const Client_app &cli_app_ref, const Server_app &srv_app_ref, Task_err &&on_err_func, On_passive_open_channel_handler &&on_passive_open_channel_func)
Compilable only when Session_obj is a Client_session variant, forwards to its ctor of identical form, except that the handlers are replaced with sync_io-adapting ones.
template<typename Task_err >
Session_adapter (flow::log::Logger *logger_ptr, const Client_app &cli_app_ref, const Server_app &srv_app_ref, Task_err &&on_err_func)
Compilable only when Session_obj is a Client_session variant, forwards to its ctor of identical form, except that the handler is replaced with sync_io-adapting one.
Session_adapter ()
Forwards to the Session_obj default ctor.
template<typename Event_wait_func_t >
bool start_ops (Event_wait_func_t &&ev_wait_func)
See, e.g., Client_session_adapter.
template<typename Create_ev_wait_hndl_func >
bool replace_event_wait_handles (const Create_ev_wait_hndl_func &create_ev_wait_hndl_func)
See, e.g., Client_session_adapter.
template<typename Task_err , typename On_passive_open_channel_handler >
bool init_handlers (Task_err &&on_err_func_arg, On_passive_open_channel_handler &&on_passive_open_channel_func_arg)
Compilable only when Session_obj is a Server_session variant, forwards to its method of identical form, except that the handlers are replaced with sync_io-adapting ones.
template<typename Task_err >
bool init_handlers (Task_err &&on_err_func_arg)
Compilable only when Session_obj is a Server_session variant, forwards to its method of identical form, except that the handlers are replaced with sync_io-adapting ones.
Public Member Functions inherited from ipc::session::Session< Mdt_payload >
Session ()
Default ctor: creates Session in NULL state (not operational).
Session (Session &&src)
Move ctor: *this becomes identical to src; while src becomes as-if default-cted.
Session (const Session &)=delete
Copy construction is disallowed.
~Session ()
In NULL state, no-op; in PEER state: Ends the session while informing (if possible) the opposing peer Session that the present session has ended.
Session & operator= (Session &&src)
Move assignment: acts as-if *this dtor executed; then *this becomes identical to src; while src becomes as-if default-cted.
Session & operator= (const Session &)=delete
Copy assignment is disallowed.
Mdt_builder_ptr mdt_builder ()
Returns a new metadata holder to be subsequently mutated by the user and then passed to open_channel() to initiate active-open attempt.
bool open_channel (Channel_obj *target_channel, const Mdt_builder_ptr &mdt, Error_code *err_code=0)
Synchronously active-opens a new channel which, on success, is moved-to *target_channel.
bool open_channel (Channel_obj *target_channel, Error_code *err_code=0)
Identical to open_channel(target_channel, mdt_builder(), err_code); in other words attempts to open channel with an uninitialized channel-open metadata payload.
const Session_token & session_token () const
In PEER state: Returns the (non-nil) logged-in session token to be used for any struc::Channels one may wish to upgrade from Channel_obj channels yielded by open_channel() or passive-opens; or nil if in NULL state, or if *this session is hosed from a prior error.
Protected Member Functions
template<typename... Args>
void async_wait (Args &&... args)
Forwards to the util::sync_io::Event_wait_func saved in start_ops().
void init_pipe (util::Pipe_reader *reader, util::Pipe_writer *writer, util::sync_io::Asio_waitable_native_handle *ev_wait_hndl)
Utility that sets up an IPC-pipe in the given peer objects as well as loading a watcher-descriptor object for the read-end.
Private Types
using Channel_open_result_q = std::queue< typename Channel_open_result::Ptr >
Queue of Channel_open_result.
Private Member Functions
void on_ev_channel_open ()
Signaled by the function returned by on_channel_func_sio(), it returns the IPC-pipe to steady-state (empty, not readable), invokes the original user handler passed to on_channel_func_sio(), and lastly begins the next async-wait for the procedure.
flow::async::Task_asio_err on_err_func_sio ()
Returns the proper on-error handler to set up on the underlying Session_obj (Client_session: via ctor; Server_session: via init_handlers()).
On_channel_func on_channel_func_sio ()
Returns the proper on-passive-channel-open handler to set up on the underlying Session_obj (Client_session: via ctor; Server_session: via init_handlers() 2-arg form).
Private Attributes
flow::util::Task_engine m_nb_task_engine
The Task_engine for m_ready_*.
flow::util::Task_engine m_ev_hndl_task_engine_unused
The Task_engine for m_ev_wait_hndl_*, unless it is replaced via replace_event_wait_handles().
util::Pipe_reader m_ready_reader_err
Read-end of IPC-pipe used by *this used to detect that the error-wait has completed.
util::Pipe_writer m_ready_writer_err
Write-end of IPC-pipe together with m_ready_reader_err.
util::sync_io::Asio_waitable_native_handle m_ev_wait_hndl_err
Descriptor waitable by outside event loop async-waits – storing the same Native_handle as (and thus being used to wait on events from) m_ready_reader_err.
util::Pipe_reader m_ready_reader_chan
Read-end of IPC-pipe used by *this used to detect that a channel-open-wait has completed.
util::Pipe_writer m_ready_writer_chan
Write-end of IPC-pipe together with m_ready_reader_chan.
util::sync_io::Asio_waitable_native_handle m_ev_wait_hndl_chan
Descriptor waitable by outside event loop async-waits – storing the same Native_handle as (and thus being used to wait on events from) m_ready_reader_chan.
util::sync_io::Event_wait_func m_ev_wait_func
Function (set forever in start_ops()) through which we invoke the outside event loop's async-wait facility for descriptors/events relevant to our ops.
flow::async::Task_asio_err m_on_err_func
on_err_func from init_handlers(); .empty() until then.
On_channel_func m_on_channel_func_or_empty
on_passive_open_channel_func_or_empty from init_handlers() (possibly .empty() if not supplied); until then .empty().
Error_code m_target_err_code_err
Result given to (or about to be given to) m_on_err_func.
Channel_open_result_q m_target_channel_open_q
Queue of On_channel_func handler arg sets received from async-I/O Session_obj – meaning the Session, in unspecified background thread, informing us (which we signal via m_ready_writer_chan) a channel has been passively open – and not yet fed to m_on_channel_func_or_empty.
flow::util::Mutex_non_recursive m_target_channel_open_q_mutex
Protects m_target_channel_open_q, accessed from user async-wait-reporter thread; and Session_obj worker thread.
Additional Inherited Members
Static Public Attributes inherited from ipc::session::Session< Mdt_payload >
static constexpr schema::ShmType S_SHM_TYPE = unspecified
Specifies the SHM-provider for which this Session concept implementation provides support; or NONE if this is a vanilla Session that does not provide SHM-based zero-copy support.
static constexpr bool S_SHM_ENABLED = unspecified
Specifies whether this Session concept implementation provides support for zero-copy via SHM plus direct access to SHM arenas and lending/borrowing within them.
Detailed Description
template<typename Session>
class ipc::session::sync_io::Session_adapter< Session >
Internal-use workhorse containing common elements of Client_session_adapter and Server_session_adapter.
As such it contains the machinery for:
storing (deriving from) the adapted Session as accessible via Session_adapter::core();
adapting async-I/O on-error and on-passive-channel-open (if enabled) events to sync_io pattern;
storing and invoking the central util::sync_io::Event_wait_func supplied by the user;
type aliases common to all sessions.
Template Parameters
Session See, e.g., Client_session_adapter.
Definition at line 50 of file session_adapter.hpp.
Member Typedef Documentation
Async_io_obj
template<typename Session > using ipc::session::sync_io::Session_adapter< Session >::Async_io_obj = Session_obj
See, e.g., Client_session_adapter.
Definition at line 64 of file session_adapter.hpp.
Base
template<typename Session > using ipc::session::sync_io::Session_adapter< Session >::Base = Session_obj
Our main base.
Definition at line 59 of file session_adapter.hpp.
Channel_obj
template<typename Session > using ipc::session::sync_io::Session_adapter< Session >::Channel_obj = typename Session_obj::Channel_obj
Short-hand for session-openable Channel type.
Definition at line 67 of file session_adapter.hpp.
Channel_open_result_q
template<typename Session > using ipc::session::sync_io::Session_adapter< Session >::Channel_open_result_q = std::queue<typename Channel_open_result::Ptr> private
Queue of Channel_open_result.
Definition at line 245 of file session_adapter.hpp.
Mdt_reader_ptr
template<typename Session > using ipc::session::sync_io::Session_adapter< Session >::Mdt_reader_ptr = typename Session_obj::Mdt_reader_ptr
Short-hand for session-open metadata reader.
Definition at line 70 of file session_adapter.hpp.
On_channel_func
template<typename Session > using ipc::session::sync_io::Session_adapter< Session >::On_channel_func = Function<void (Channel_obj&&, Mdt_reader_ptr&&)>
Short-hand for passive-channel-open handler.
Definition at line 73 of file session_adapter.hpp.
Session_obj
template<typename Session > using ipc::session::sync_io::Session_adapter< Session >::Session_obj = Session
See, e.g., Client_session_adapter.
Definition at line 57 of file session_adapter.hpp.
Sync_io_obj
template<typename Session > using ipc::session::sync_io::Session_adapter< Session >::Sync_io_obj = transport::Null_peer
See, e.g., Client_session_adapter.
Definition at line 62 of file session_adapter.hpp.
Constructor & Destructor Documentation
Session_adapter() [1/3]
template<typename Session > template<typename On_passive_open_channel_handler , typename Task_err > ipc::session::sync_io::Session_adapter< Session >::Session_adapter (flow::log::Logger * logger_ptr, const Client_app & cli_app_ref, const Server_app & srv_app_ref, Task_err && on_err_func, On_passive_open_channel_handler && on_passive_open_channel_func) explicit
Compilable only when Session_obj is a Client_session variant, forwards to its ctor of identical form, except that the handlers are replaced with sync_io-adapting ones.
Do not use init_handlers() after this ctor, as that is for Server_session.
Parameters
logger_ptr See Client_session_mv.
cli_app_ref See Client_session_mv.
srv_app_ref See Client_session_mv.
on_err_func See Client_session_mv. However in *this case this shall be invoked – though still only following successful async_connect() as usual – according to sync_io pattern, synchronously inside an async-wait performed by you and reported via (*on_active_ev_func)().
on_passive_open_channel_func See Client_session_mv. However in *this case this shall be invoked – though still only following successful async_connect() as usual – according to sync_io pattern, synchronously inside an async-wait performed by you and reported via (*on_active_ev_func)().
Template Parameters
On_passive_open_channel_handler See Client_session_mv.
Task_err See Client_session_mv.
Definition at line 412 of file session_adapter.hpp.
References ipc::session::sync_io::Session_adapter< Session >::init_pipe(), ipc::session::sync_io::Session_adapter< Session >::m_ev_wait_hndl_chan, ipc::session::sync_io::Session_adapter< Session >::m_ev_wait_hndl_err, ipc::session::sync_io::Session_adapter< Session >::m_ready_reader_chan, ipc::session::sync_io::Session_adapter< Session >::m_ready_reader_err, ipc::session::sync_io::Session_adapter< Session >::m_ready_writer_chan, and ipc::session::sync_io::Session_adapter< Session >::m_ready_writer_err.
Session_adapter() [2/3]
template<typename Session > template<typename Task_err > ipc::session::sync_io::Session_adapter< Session >::Session_adapter (flow::log::Logger * logger_ptr, const Client_app & cli_app_ref, const Server_app & srv_app_ref, Task_err && on_err_func) explicit
Compilable only when Session_obj is a Client_session variant, forwards to its ctor of identical form, except that the handler is replaced with sync_io-adapting one.
Do not use init_handlers() after this ctor, as that is for Server_session.
Parameters
logger_ptr Logger to use for logging subsequently.
cli_app_ref See Client_session_mv.
srv_app_ref See Client_session_mv.
on_err_func See Client_session_mv. However in *this case this shall be invoked – though still only following successful async_connect() as usual – according to sync_io pattern, synchronously inside an async-wait performed by you and reported via (*on_active_ev_func)().
Template Parameters
Task_err See Client_session_mv.
Definition at line 434 of file session_adapter.hpp.
References ipc::session::sync_io::Session_adapter< Session >::init_pipe(), ipc::session::sync_io::Session_adapter< Session >::m_ev_wait_hndl_chan, ipc::session::sync_io::Session_adapter< Session >::m_ev_wait_hndl_err, ipc::session::sync_io::Session_adapter< Session >::m_ready_reader_chan, ipc::session::sync_io::Session_adapter< Session >::m_ready_reader_err, ipc::session::sync_io::Session_adapter< Session >::m_ready_writer_chan, and ipc::session::sync_io::Session_adapter< Session >::m_ready_writer_err.
Session_adapter() [3/3]
template<typename Session > ipc::session::sync_io::Session_adapter< Session >::Session_adapter
Forwards to the Session_obj default ctor.
Definition at line 398 of file session_adapter.hpp.
References ipc::session::sync_io::Session_adapter< Session >::init_pipe(), ipc::session::sync_io::Session_adapter< Session >::m_ev_wait_hndl_chan, ipc::session::sync_io::Session_adapter< Session >::m_ev_wait_hndl_err, ipc::session::sync_io::Session_adapter< Session >::m_ready_reader_chan, ipc::session::sync_io::Session_adapter< Session >::m_ready_reader_err, ipc::session::sync_io::Session_adapter< Session >::m_ready_writer_chan, and ipc::session::sync_io::Session_adapter< Session >::m_ready_writer_err.
Member Function Documentation
async_wait()
template<typename Session > template<typename... Args> void ipc::session::sync_io::Session_adapter< Session >::async_wait (Args &&... args) protected
Forwards to the util::sync_io::Event_wait_func saved in start_ops().
Template Parameters
Args See above.
Parameters
args See above.
Definition at line 688 of file session_adapter.hpp.
init_handlers() [1/2]
template<typename Session > template<typename Task_err > bool ipc::session::sync_io::Session_adapter< Session >::init_handlers (Task_err && on_err_func_arg)
Compilable only when Session_obj is a Server_session variant, forwards to its method of identical form, except that the handlers are replaced with sync_io-adapting ones.
Do not use non-default ctor before this, as that is for Client_session.
Template Parameters
Task_err See Session_server.
Parameters
on_err_func_arg See Session_server.
Returns
See Session_server; in addition returns false/no-ops if invoked before start_ops().
Definition at line 478 of file session_adapter.hpp.
init_handlers() [2/2]
template<typename Session > template<typename Task_err , typename On_passive_open_channel_handler > bool ipc::session::sync_io::Session_adapter< Session >::init_handlers (Task_err && on_err_func_arg, On_passive_open_channel_handler && on_passive_open_channel_func_arg)
Compilable only when Session_obj is a Server_session variant, forwards to its method of identical form, except that the handlers are replaced with sync_io-adapting ones.
Do not use non-default ctor before this, as that is for Client_session.
Template Parameters
Task_err See Session_server.
On_passive_open_channel_handler See Session_server.
Parameters
on_err_func_arg See Session_server.
on_passive_open_channel_func_arg See Session_server.
Returns
See Session_server; in addition returns false/no-ops if invoked before start_ops().
Definition at line 453 of file session_adapter.hpp.
init_pipe()
template<typename Session > void ipc::session::sync_io::Session_adapter< Session >::init_pipe (util::Pipe_reader * reader, util::Pipe_writer * writer, util::sync_io::Asio_waitable_native_handle * ev_wait_hndl) protected
Utility that sets up an IPC-pipe in the given peer objects as well as loading a watcher-descriptor object for the read-end.
This should be called before start_ops() or replace_event_wait_handles().
Parameters
reader Pipe read end to load. It should be constructed with its intended execution context/executor but not .is_open().
writer Pipe write end to load. It should be constructed with its intended execution context/executor but not .is_open().
ev_wait_hndl Watcher for reader. It should be constructed with its intended execution context/executor but not .is_open().
Definition at line 499 of file session_adapter.hpp.
References ipc::util::sync_io::Asio_waitable_native_handle::assign().
Referenced by ipc::session::sync_io::Client_session_adapter< Session >::Client_session_adapter(), and ipc::session::sync_io::Session_adapter< Session >::Session_adapter().
on_channel_func_sio()
template<typename Session > Session_adapter< Session >::On_channel_func ipc::session::sync_io::Session_adapter< Session >::on_channel_func_sio private
Returns the proper on-passive-channel-open handler to set up on the underlying Session_obj (Client_session: via ctor; Server_session: via init_handlers() 2-arg form).
The resulting handler must not be invoked before start_ops() and m_on_channel_func_or_empty being set; else behavior undefined.
Returns
See above.
Definition at line 655 of file session_adapter.hpp.
References ipc::util::pipe_produce().
on_err_func_sio()
template<typename Session > flow::async::Task_asio_err ipc::session::sync_io::Session_adapter< Session >::on_err_func_sio private
Returns the proper on-error handler to set up on the underlying Session_obj (Client_session: via ctor; Server_session: via init_handlers()).
The resulting handler must not be invoked before start_ops() and m_on_err_func being set; else behavior undefined.
Returns
See above.
Definition at line 632 of file session_adapter.hpp.
References ipc::util::pipe_produce().
on_ev_channel_open()
template<typename Session > void ipc::session::sync_io::Session_adapter< Session >::on_ev_channel_open private
Signaled by the function returned by on_channel_func_sio(), it returns the IPC-pipe to steady-state (empty, not readable), invokes the original user handler passed to on_channel_func_sio(), and lastly begins the next async-wait for the procedure.
Definition at line 567 of file session_adapter.hpp.
References ipc::util::pipe_consume().
replace_event_wait_handles()
template<typename Session > template<typename Create_ev_wait_hndl_func > bool ipc::session::sync_io::Session_adapter< Session >::replace_event_wait_handles (const Create_ev_wait_hndl_func & create_ev_wait_hndl_func)
See, e.g., Client_session_adapter.
Template Parameters
Create_ev_wait_hndl_func See above.
Parameters
create_ev_wait_hndl_func See above.
Returns
See above.
Definition at line 602 of file session_adapter.hpp.
start_ops()
template<typename Session > template<typename Event_wait_func_t > bool ipc::session::sync_io::Session_adapter< Session >::start_ops (Event_wait_func_t && ev_wait_func)
See, e.g., Client_session_adapter.
Template Parameters
Event_wait_func_t See above.
Parameters
ev_wait_func See above.
Returns
See above.
Definition at line 521 of file session_adapter.hpp.
References ipc::util::pipe_consume().
Member Data Documentation
m_ev_hndl_task_engine_unused
template<typename Session > flow::util::Task_engine ipc::session::sync_io::Session_adapter< Session >::m_ev_hndl_task_engine_unused private
The Task_engine for m_ev_wait_hndl_*, unless it is replaced via replace_event_wait_handles().
This is to fulfill the sync_io pattern.
Definition at line 296 of file session_adapter.hpp.
m_ev_wait_func
template<typename Session > util::sync_io::Event_wait_func ipc::session::sync_io::Session_adapter< Session >::m_ev_wait_func private
Function (set forever in start_ops()) through which we invoke the outside event loop's async-wait facility for descriptors/events relevant to our ops.
See util::sync_io::Event_wait_func doc header for a refresher on this mechanic.
Definition at line 345 of file session_adapter.hpp.
m_ev_wait_hndl_chan
template<typename Session > util::sync_io::Asio_waitable_native_handle ipc::session::sync_io::Session_adapter< Session >::m_ev_wait_hndl_chan private
Descriptor waitable by outside event loop async-waits – storing the same Native_handle as (and thus being used to wait on events from) m_ready_reader_chan.
Definition at line 338 of file session_adapter.hpp.
Referenced by ipc::session::sync_io::Session_adapter< Session >::Session_adapter().
m_ev_wait_hndl_err
template<typename Session > util::sync_io::Asio_waitable_native_handle ipc::session::sync_io::Session_adapter< Session >::m_ev_wait_hndl_err private
Descriptor waitable by outside event loop async-waits – storing the same Native_handle as (and thus being used to wait on events from) m_ready_reader_err.
Definition at line 313 of file session_adapter.hpp.
Referenced by ipc::session::sync_io::Session_adapter< Session >::Session_adapter().
m_nb_task_engine
template<typename Session > flow::util::Task_engine ipc::session::sync_io::Session_adapter< Session >::m_nb_task_engine private
The Task_engine for m_ready_*.
It is necessary to construct those pipe-end objects, but we never use that guy's ->async_*() APIs – only non-blocking operations, essentially leveraging boost.asio's portable transmission APIs but not its actual, um, async-I/O abilities in this case. Accordingly we never load any tasks onto m_nb_task_engine and certainly never .run() (or .poll() or ...) it.
In the sync_io pattern the user's outside event loop is responsible for awaiting readability/writability of a guy like m_ready_reader_chan via our exporting of its .native_handle().
Definition at line 289 of file session_adapter.hpp.
m_on_channel_func_or_empty
template<typename Session > On_channel_func ipc::session::sync_io::Session_adapter< Session >::m_on_channel_func_or_empty private
on_passive_open_channel_func_or_empty from init_handlers() (possibly .empty() if not supplied); until then .empty().
Definition at line 354 of file session_adapter.hpp.
m_on_err_func
template<typename Session > flow::async::Task_asio_err ipc::session::sync_io::Session_adapter< Session >::m_on_err_func private
on_err_func from init_handlers(); .empty() until then.
Definition at line 348 of file session_adapter.hpp.
m_ready_reader_chan
template<typename Session > util::Pipe_reader ipc::session::sync_io::Session_adapter< Session >::m_ready_reader_chan private
Read-end of IPC-pipe used by *this used to detect that a channel-open-wait has completed.
The signal byte is read out of m_ready_reader_chan, after it was written there via m_ready_writer_chan. As explained in m_target_channel_open_q doc header, channel-opens can occur at any time from another thread, even while *this is synchronously dealing with an existing one; therefore this is a rare case where more than 1 byte could be readable at a given time. Nevertheless we issue one async-wait on m_ready_reader_chan per channel-open, in series; eventually all of them get popped, meaning all the channel-opens have been served.
This is not a rare occurrence necessarily: an opposing Session user can perform 2+ open_channel() right in a row, and since creating a Channel with all its 2-4 fat peer objects can be relatively lengthy on this side, the 2nd/3rd/... on-channel-open firing can "step on" a preceding one.
See also
m_ready_writer_chan.
Definition at line 329 of file session_adapter.hpp.
Referenced by ipc::session::sync_io::Session_adapter< Session >::Session_adapter().
m_ready_reader_err
template<typename Session > util::Pipe_reader ipc::session::sync_io::Session_adapter< Session >::m_ready_reader_err private
Read-end of IPC-pipe used by *this used to detect that the error-wait has completed.
The signal byte is detected in m_ready_reader_err. There is no need to read it, as an error can occur at most once.
See also
m_ready_writer_err.
Definition at line 304 of file session_adapter.hpp.
Referenced by ipc::session::sync_io::Session_adapter< Session >::Session_adapter().
m_ready_writer_chan
template<typename Session > util::Pipe_writer ipc::session::sync_io::Session_adapter< Session >::m_ready_writer_chan private
Write-end of IPC-pipe together with m_ready_reader_chan.
Definition at line 332 of file session_adapter.hpp.
Referenced by ipc::session::sync_io::Session_adapter< Session >::Session_adapter().
m_ready_writer_err
template<typename Session > util::Pipe_writer ipc::session::sync_io::Session_adapter< Session >::m_ready_writer_err private
Write-end of IPC-pipe together with m_ready_reader_err.
Definition at line 307 of file session_adapter.hpp.
Referenced by ipc::session::sync_io::Session_adapter< Session >::Session_adapter().
m_target_channel_open_q
template<typename Session > Channel_open_result_q ipc::session::sync_io::Session_adapter< Session >::m_target_channel_open_q private
Queue of On_channel_func handler arg sets received from async-I/O Session_obj – meaning the Session, in unspecified background thread, informing us (which we signal via m_ready_writer_chan) a channel has been passively open – and not yet fed to m_on_channel_func_or_empty.
Protected by m_target_channel_open_q_mutex.
Rationale
There's a queue here, which stands in contrast to (as of this writing) all other sync_io pattern impls in the project, including the on-error stuff in *this: those always deal with a single async-op at a time, and therefore no queue is necessary (just a single arg-set; usually just an Error_code, sometimes with a size_t sz though).
The reason this one is different is as follows.
It's unlike, e.g., Client_session_adapter::async_connect(), because an async-connect is triggered by the user explicitly, which triggers a single async-wait, and we disallow in our API to trigger more, until that one completes.
It's unlike, e.g., m_on_err_func stuff in *this, because while that one can indeed happen at any time from another thread – without the user explicitly beginning the async-op (it sort of begins by itself) – it can also only happen at most once per *this (modulo move-assignment).
At any rate: the handler we register with (Session_obj*)this – on_channel_func_sio() – can be invoked from a background thread at any time. This triggers signaling m_ready_reader_chan (via m_ready_writer_chan), on which there is always a sync_io-pattern async-wait outstanding. We are informed of a completed async-wait (byte is available on m_ready_reader_chan); we consume the byte and pop and pass the result from top of m_target_channel_open_q. Then we start another async-wait. If there are more items in the queue that were added in the meantime, the same number of bytes have been pushed into m_ready_writer_chan; so those async-waits are satisfied (in series) quickly, leading to the progressive emptying of this queue and passing along those results to m_on_channel_func_or_empty().
Definition at line 389 of file session_adapter.hpp.
m_target_channel_open_q_mutex
template<typename Session > flow::util::Mutex_non_recursive ipc::session::sync_io::Session_adapter< Session >::m_target_channel_open_q_mutex mutable private
Protects m_target_channel_open_q, accessed from user async-wait-reporter thread; and Session_obj worker thread.
Definition at line 392 of file session_adapter.hpp.
m_target_err_code_err
template<typename Session > Error_code ipc::session::sync_io::Session_adapter< Session >::m_target_err_code_err private
Result given to (or about to be given to) m_on_err_func.
Definition at line 357 of file session_adapter.hpp.
The documentation for this class was generated from the following file:
session/sync_io/detail/session_adapter.hpp