Flow-IPC: ipc::session::sync_io::Client_session_adapter< Session > Class Template Reference
ipc::session::sync_io::Client_session_adapter< Session > Class Template Reference
sync_io-pattern counterpart to async-I/O-pattern session::Client_session types and all their SHM-aware variations (at least shm::classic::Client_session et al and shm::arena_lend::jemalloc::Client_session et al).
#include <client_session_adapter.hpp>
Public Types
using Session_obj = typename Base::Session_obj
Short-hand, for generic programming et al, for template parameter Session.
using Async_io_obj = typename Base::Async_io_obj
Useful for generic programming, the async-I/O-pattern counterpart to *this type.
using Sync_io_obj = typename Base::Sync_io_obj
You may disregard.
Public Member Functions
template<typename... Ctor_args>
Client_session_adapter (Ctor_args &&... ctor_args)
Forwards to the Session_obj ctor.
template<typename Event_wait_func_t >
bool start_ops (Event_wait_func_t &&ev_wait_func)
Sets up the sync_io-pattern interaction between *this and the user's event loop; required before *this will do any work.
template<typename Create_ev_wait_hndl_func >
bool replace_event_wait_handles (const Create_ev_wait_hndl_func &create_ev_wait_hndl_func)
Analogous to transport::sync_io::Native_handle_sender::replace_event_wait_handles().
template<typename Task_err >
bool async_connect (Task_err &&on_done_func)
Acts identically to 1-arg overload of Client_session_mv::async_connect(), except that the completion handler is invoked in the sync_io-pattern fashion, synchronously inside an async-wait performed by you and reported via (*on_active_ev_func)().
template<typename Task_err >
bool async_connect (const typename Session_obj::Mdt_builder_ptr &mdt, typename Session_obj::Channels *init_channels_by_cli_req_pre_sized, typename Session_obj::Mdt_reader_ptr *mdt_from_srv_or_null, typename Session_obj::Channels *init_channels_by_srv_req, Task_err &&on_done_func)
Acts identically to 5-arg overload of Client_session_mv::async_connect(), except that the completion handler is invoked in the sync_io-pattern fashion, synchronously inside an async-wait performed by you and reported via (*on_active_ev_func)().
Session_obj * core ()
The adapted mutable Session_obj.
const Session_obj * core () const
The adapted immutable Session_obj.
Private Types
using Base = Session_adapter< Session >
Our main base.
Private Types inherited from ipc::session::sync_io::Session_adapter< Session >
using Session_obj = Session
See, e.g., Client_session_adapter.
using Base = Session_obj
Our main base.
using Sync_io_obj = transport::Null_peer
See, e.g., Client_session_adapter.
using Async_io_obj = Session_obj
See, e.g., Client_session_adapter.
using Channel_obj = typename Session_obj::Channel_obj
Short-hand for session-openable Channel type.
using Mdt_reader_ptr = typename Session_obj::Mdt_reader_ptr
Short-hand for session-open metadata reader.
using On_channel_func = Function< void(Channel_obj &&, Mdt_reader_ptr &&)>
Short-hand for passive-channel-open handler.
Private Types inherited from ipc::session::Session< Mdt_payload >
using Channel_obj = unspecified
Each successful open_channel() and on-passive-open handler firing shall yield a concrete transport::Channel instance of this type – in PEER state.
using Mdt_payload_obj = Mdt_payload
Short-hand for Mdt_payload template arg.
using Mdt_builder = typename transport::struc::schema::Metadata< Mdt_payload_obj >::Builder
Pointee of Mdt_builder_ptr.
using Mdt_builder_ptr = shared_ptr< Mdt_builder >
Ref-counted handle to a capnp-generated Builder (and the payload it accesses) through which the user shall mutate the open_channel() metadata before invoking open_channel().
using Mdt_reader_ptr = shared_ptr< typename transport::struc::schema::Metadata< Mdt_payload_obj >::Reader >
Ref-counted handle to a capnp-generated Reader (and the payload it accesses) through which the user shall access the metadata the other side prepared via Mdt_builder_ptr.
template<typename Message_body >
using Structured_channel = transport::struc::Channel< unspecified >
Convenience alias for the transport::struc::Channel concrete type to use if one desires (1) to upgrade a *this-generated channel to a struc::Channel and (2) to efficiently use the built-in capabilities of *this (notably, if applicable: SHM) for zero-copy performance when sending messages through that channel.
using Structured_msg_builder_config = unspecified
Convenience alias equal to Structured_channel<M>::Builder_config (regardless of M).
using Structured_msg_reader_config = unspecified
Convenience alias equal to Structured_channel<M>::Reader_config (regardless of M).
Private Member Functions
void conn_write (const Error_code &err_code)
The real handler given for on_done_func to Session_obj::async_connect(): it records the result of that async-connect to m_target_err_code_conn, then signals conn_read() via the IPC-pipe.
void conn_read ()
Signaled by conn_write(), it returns the IPC-pipe to steady-state (empty, not readable), then invokes the original user on_done_func().
Private Member Functions inherited from ipc::session::sync_io::Session_adapter< Session >
template<typename On_passive_open_channel_handler , typename Task_err >
Session_adapter (flow::log::Logger *logger_ptr, const Client_app &cli_app_ref, const Server_app &srv_app_ref, Task_err &&on_err_func, On_passive_open_channel_handler &&on_passive_open_channel_func)
Compilable only when Session_obj is a Client_session variant, forwards to its ctor of identical form, except that the handlers are replaced with sync_io-adapting ones.
template<typename Task_err >
Session_adapter (flow::log::Logger *logger_ptr, const Client_app &cli_app_ref, const Server_app &srv_app_ref, Task_err &&on_err_func)
Compilable only when Session_obj is a Client_session variant, forwards to its ctor of identical form, except that the handler is replaced with sync_io-adapting one.
Session_adapter ()
Forwards to the Session_obj default ctor.
template<typename Event_wait_func_t >
bool start_ops (Event_wait_func_t &&ev_wait_func)
See, e.g., Client_session_adapter.
template<typename Create_ev_wait_hndl_func >
bool replace_event_wait_handles (const Create_ev_wait_hndl_func &create_ev_wait_hndl_func)
See, e.g., Client_session_adapter.
template<typename Task_err , typename On_passive_open_channel_handler >
bool init_handlers (Task_err &&on_err_func_arg, On_passive_open_channel_handler &&on_passive_open_channel_func_arg)
Compilable only when Session_obj is a Server_session variant, forwards to its method of identical form, except that the handlers are replaced with sync_io-adapting ones.
template<typename Task_err >
bool init_handlers (Task_err &&on_err_func_arg)
Compilable only when Session_obj is a Server_session variant, forwards to its method of identical form, except that the handlers are replaced with sync_io-adapting ones.
template<typename... Args>
void async_wait (Args &&... args)
Forwards to the util::sync_io::Event_wait_func saved in start_ops().
void init_pipe (util::Pipe_reader *reader, util::Pipe_writer *writer, util::sync_io::Asio_waitable_native_handle *ev_wait_hndl)
Utility that sets up an IPC-pipe in the given peer objects as well as loading a watcher-descriptor object for the read-end.
Private Member Functions inherited from ipc::session::Session< Mdt_payload >
Session ()
Default ctor: creates Session in NULL state (not operational).
Session (Session &&src)
Move ctor: *this becomes identical to src; while src becomes as-if default-cted.
Session (const Session &)=delete
Copy construction is disallowed.
~Session ()
In NULL state, no-op; in PEER state: Ends the session while informing (if possible) the opposing peer Session that the present session has ended.
Session & operator= (Session &&src)
Move assignment: acts as-if *this dtor executed; then *this becomes identical to src; while src becomes as-if default-cted.
Session & operator= (const Session &)=delete
Copy assignment is disallowed.
Mdt_builder_ptr mdt_builder ()
Returns a new metadata holder to be subsequently mutated by the user and then passed to open_channel() to initiate active-open attempt.
bool open_channel (Channel_obj *target_channel, const Mdt_builder_ptr &mdt, Error_code *err_code=0)
Synchronously active-opens a new channel which, on success, is moved-to *target_channel.
bool open_channel (Channel_obj *target_channel, Error_code *err_code=0)
Identical to open_channel(target_channel, mdt_builder(), err_code); in other words attempts to open channel with an uninitialized channel-open metadata payload.
const Session_token & session_token () const
In PEER state: Returns the (non-nil) logged-in session token to be used for any struc::Channels one may wish to upgrade from Channel_obj channels yielded by open_channel() or passive-opens; or nil if in NULL state, or if *this session is hosed from a prior error.
Private Attributes
flow::util::Task_engine m_nb_task_engine
Similar to the one in Base.
flow::util::Task_engine m_ev_hndl_task_engine_unused
Similar to the one in Base.
util::Pipe_reader m_ready_reader_conn
Similar to the ones in Base, applied to async_connect().
util::Pipe_writer m_ready_writer_conn
Similar to the ones in Base, applied to async_connect().
util::sync_io::Asio_waitable_native_handle m_ev_wait_hndl_conn
Similar to the ones in Base, applied to async_connect().
flow::async::Task_asio_err m_on_conn_func_or_empty
on_done_func from async_connect() if one is pending; otherwise .empty().
Error_code m_target_err_code_conn
Result given to (or about to be given to) m_on_conn_func_or_empty.
Related Functions
(Note that these are not member functions.)
template<typename Session >
std::ostream & operator<< (std::ostream &os, const Client_session_adapter< Session > &val)
Prints string representation of the given Client_session_adapter to the given ostream.
Additional Inherited Members
Static Private Attributes inherited from ipc::session::Session< Mdt_payload >
static constexpr schema::ShmType S_SHM_TYPE = unspecified
Specifies the SHM-provider for which this Session concept implementation provides support; or NONE if this is a vanilla Session that does not provide SHM-based zero-copy support.
static constexpr bool S_SHM_ENABLED = unspecified
Specifies whether this Session concept implementation provides support for zero-copy via SHM plus direct access to SHM arenas and lending/borrowing within them.
Detailed Description
template<typename Session>
class ipc::session::sync_io::Client_session_adapter< Session >
sync_io-pattern counterpart to async-I/O-pattern session::Client_session types and all their SHM-aware variations (at least shm::classic::Client_session et al and shm::arena_lend::jemalloc::Client_session et al).
In point of fact:
Use this if and only if you desire a sync_io-pattern style of being informed of async events from a Client_session of any kind. For example, you may find this convenient if your event loop is an old-school reactor using poll() or epoll_wait(). This affects exactly the following APIs:
Client_session::async_connect() reporting that a session-open attempt has completed.
Client_session reporting a session-hosing error via on-error handler.
Set up via ctor.
Client_session reporting a channel having been passively-opened via that handler.
Set up via ctor.
This Client_session_adapter adapts a Client_session constructed and stored within *this. All APIs excluding the above – that is to say all non-async APIs – are to be invoked via core() accessor.
Trying to use core()->async_connect() leads to undefined behavior.
See also
util::sync_io doc header – describes the general sync_io pattern we are following.
session::Client_session_mv, session::Client_session, et al.
As is generally the case when choosing sync_io::X versus X, we recommend using X due to it being easier. In this particular case (see below) there is no perf benefit to using sync_io::X, either, so the only reason to use sync_io::X in this case would be because you've got an old-school reactor event loop with a poll() or epoll_wait(), in which case the sync_io API may be easier to integrate.
To use it:
Construct it explicitly. As with an async-I/O Client_session you will need to provide:
Error handler (though it will be invoked synchronously per sync_io pattern).
(Optional – if you want to enable channel passive-open): Channel passive-open handler (though it will be invoked via... ditto).
Set up sync_io pattern using start_ops() (and if needed precede it with replace_event_wait_handles()).
Use async_connect() in similar fashion to async-I/O Client_session (though it will be invoked via... ditto).
On successful connect:
Be ready for error handler to fire (in sync_io style).
Be ready for passive-channel-open handler to fire (in sync_io style).
Use core()-> for all other API needs (e.g., open_channel(), session_shm() – if SHM-aware).
Internal implementation
Normally this would not be in the public docs for this public-use class, but indulge us.
In perf-critical situations, such as the various transport::Blob_sender / transport::Blob_receiver / etc. impls, typically sync_io::X contains the core implementation, then X adapts a sync_io::X core to provide background-thread-driven work and signaling of completion. We do not consider the present X = Client_session to be perf-critical; as such the present sync_io::X adapts the X. Internally this is accomplished using an unnamed IPC-pipe, where an internal background thread W tickles said IPC-pipe which is waited-on by the user of sync_io::Client_session_adapter.
Todo:
Make all of Server_session_adapter, Client_session_adapter move-ctible/assignable like their adapted counterparts. It is not of utmost importance practically, unlike for the adapter guys, but at least for consistency it would be good; and of course it never hurts usability even if not critical. (Internally: This is not difficult to implement; the async-I/O guys being movable was really the hard part.)
Template Parameters
Session The async-I/O Client_session concrete type being adapted. As of this writing that would be one of at least: session::Client_session<knobs>, session::shm::classic::Client_session<knobs>, session::shm::jemalloc::Client_session<knobs>.
Definition at line 85 of file client_session_adapter.hpp.
Member Typedef Documentation
Async_io_obj
template<typename Session > using ipc::session::sync_io::Client_session_adapter< Session >::Async_io_obj = typename Base::Async_io_obj
Useful for generic programming, the async-I/O-pattern counterpart to *this type.
Definition at line 102 of file client_session_adapter.hpp.
Base
template<typename Session > using ipc::session::sync_io::Client_session_adapter< Session >::Base = Session_adapter<Session> private
Our main base.
Definition at line 93 of file client_session_adapter.hpp.
Session_obj
template<typename Session > using ipc::session::sync_io::Client_session_adapter< Session >::Session_obj = typename Base::Session_obj
Short-hand, for generic programming et al, for template parameter Session.
Definition at line 99 of file client_session_adapter.hpp.
Sync_io_obj
template<typename Session > using ipc::session::sync_io::Client_session_adapter< Session >::Sync_io_obj = typename Base::Sync_io_obj
You may disregard.
Definition at line 104 of file client_session_adapter.hpp.
Constructor & Destructor Documentation
Client_session_adapter()
template<typename Session > template<typename... Ctor_args> ipc::session::sync_io::Client_session_adapter< Session >::Client_session_adapter (Ctor_args &&... ctor_args)
Forwards to the Session_obj ctor.
See Client_session_mv ctor doc headers.
Template Parameters
Ctor_args See above.
Parameters
ctor_args See above.
Definition at line 265 of file client_session_adapter.hpp.
References ipc::session::sync_io::Session_adapter< Session >::init_pipe(), ipc::session::sync_io::Client_session_adapter< Session >::m_ev_wait_hndl_conn, ipc::session::sync_io::Client_session_adapter< Session >::m_ready_reader_conn, and ipc::session::sync_io::Client_session_adapter< Session >::m_ready_writer_conn.
Member Function Documentation
async_connect() [1/2]
template<typename Session > template<typename Task_err > bool ipc::session::sync_io::Client_session_adapter< Session >::async_connect (const typename Session_obj::Mdt_builder_ptr & mdt, typename Session_obj::Channels * init_channels_by_cli_req_pre_sized, typename Session_obj::Mdt_reader_ptr * mdt_from_srv_or_null, typename Session_obj::Channels * init_channels_by_srv_req, Task_err && on_done_func)
Acts identically to 5-arg overload of Client_session_mv::async_connect(), except that the completion handler is invoked in the sync_io-pattern fashion, synchronously inside an async-wait performed by you and reported via (*on_active_ev_func)().
Returns false if invoked before start_ops() in addition to the possible reasons per Client_session_mv::async_connect().
Template Parameters
Task_err See above.
Parameters
mdt See above.
init_channels_by_cli_req_pre_sized See above.
mdt_from_srv_or_null See above.
init_channels_by_srv_req See above.
on_done_func See above.
Returns
See above.
Definition at line 337 of file client_session_adapter.hpp.
async_connect() [2/2]
template<typename Session > template<typename Task_err > bool ipc::session::sync_io::Client_session_adapter< Session >::async_connect (Task_err && on_done_func)
Acts identically to 1-arg overload of Client_session_mv::async_connect(), except that the completion handler is invoked in the sync_io-pattern fashion, synchronously inside an async-wait performed by you and reported via (*on_active_ev_func)().
Returns false if invoked before start_ops() in addition to the possible reasons per Client_session_mv::async_connect().
Template Parameters
Task_err See above.
Parameters
on_done_func See above.
Returns
See above.
Definition at line 308 of file client_session_adapter.hpp.
conn_read()
template<typename Session > void ipc::session::sync_io::Client_session_adapter< Session >::conn_read private
Signaled by conn_write(), it returns the IPC-pipe to steady-state (empty, not readable), then invokes the original user on_done_func().
Definition at line 391 of file client_session_adapter.hpp.
References ipc::util::pipe_consume().
conn_write()
template<typename Session > void ipc::session::sync_io::Client_session_adapter< Session >::conn_write (const Error_code & err_code) private
The real handler given for on_done_func to Session_obj::async_connect(): it records the result of that async-connect to m_target_err_code_conn, then signals conn_read() via the IPC-pipe.
Parameters
err_code Result from Session_obj::async_connect().
Definition at line 374 of file client_session_adapter.hpp.
References ipc::util::pipe_produce(), and ipc::session::error::S_OBJECT_SHUTDOWN_ABORTED_COMPLETION_HANDLER.
core() [1/2]
template<typename Session > Client_session_adapter< Session >::Session_obj * ipc::session::sync_io::Client_session_adapter< Session >::core
The adapted mutable Session_obj.
It is safe to access any API except for core()->async_connect() (undefined behavior); use this->async_connect() instead. Remember that start_ops() is required first.
Returns
See above.
Definition at line 406 of file client_session_adapter.hpp.
Referenced by ipc::session::sync_io::Client_session_adapter< Session >::operator<<().
core() [2/2]
template<typename Session > const Client_session_adapter< Session >::Session_obj * ipc::session::sync_io::Client_session_adapter< Session >::core
The adapted immutable Session_obj.
Remember that start_ops() is required first.
Returns
See above.
Definition at line 413 of file client_session_adapter.hpp.
replace_event_wait_handles()
template<typename Session > template<typename Create_ev_wait_hndl_func > bool ipc::session::sync_io::Client_session_adapter< Session >::replace_event_wait_handles (const Create_ev_wait_hndl_func & create_ev_wait_hndl_func)
Analogous to transport::sync_io::Native_handle_sender::replace_event_wait_handles().
Template Parameters
Create_ev_wait_hndl_func See above.
Parameters
create_ev_wait_hndl_func See above.
Returns
See above.
Definition at line 287 of file client_session_adapter.hpp.
start_ops()
template<typename Session > template<typename Event_wait_func_t > bool ipc::session::sync_io::Client_session_adapter< Session >::start_ops (Event_wait_func_t && ev_wait_func)
Sets up the sync_io-pattern interaction between *this and the user's event loop; required before *this will do any work.
ev_wait_func() – with signature matching util::sync_io::Event_wait_func – is a key function memorized by *this. It shall be invoked by *this operations when some op cannot complete synchronously and requires a certain event (readable/writable) to be active on a certain native-handle.
See also
util::sync_io::Event_wait_func doc header for useful and complete instructions on how to write an ev_wait_func() properly. Doing so correctly is the crux of using the sync_io pattern.
This is a standard sync_io-pattern API per util::sync_io doc header.
Template Parameters
Event_wait_func_t Function type matching util::sync_io::Event_wait_func.
Parameters
ev_wait_func See above.
Returns
false if this has already been invoked; no-op logging aside. true otherwise.
Definition at line 277 of file client_session_adapter.hpp.
Friends And Related Function Documentation
operator<<()
template<typename Session > std::ostream & operator<< (std::ostream & os, const Client_session_adapter< Session > & val) related
Prints string representation of the given Client_session_adapter to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 419 of file client_session_adapter.hpp.
References ipc::session::sync_io::Client_session_adapter< Session >::core().
Member Data Documentation
m_ev_hndl_task_engine_unused
template<typename Session > flow::util::Task_engine ipc::session::sync_io::Client_session_adapter< Session >::m_ev_hndl_task_engine_unused private
Similar to the one in Base.
Definition at line 241 of file client_session_adapter.hpp.
m_ev_wait_hndl_conn
template<typename Session > util::sync_io::Asio_waitable_native_handle ipc::session::sync_io::Client_session_adapter< Session >::m_ev_wait_hndl_conn private
Similar to the ones in Base, applied to async_connect().
Definition at line 250 of file client_session_adapter.hpp.
Referenced by ipc::session::sync_io::Client_session_adapter< Session >::Client_session_adapter().
m_nb_task_engine
template<typename Session > flow::util::Task_engine ipc::session::sync_io::Client_session_adapter< Session >::m_nb_task_engine private
Similar to the one in Base.
Definition at line 238 of file client_session_adapter.hpp.
m_on_conn_func_or_empty
template<typename Session > flow::async::Task_asio_err ipc::session::sync_io::Client_session_adapter< Session >::m_on_conn_func_or_empty private
on_done_func from async_connect() if one is pending; otherwise .empty().
Definition at line 253 of file client_session_adapter.hpp.
m_ready_reader_conn
template<typename Session > util::Pipe_reader ipc::session::sync_io::Client_session_adapter< Session >::m_ready_reader_conn private
Similar to the ones in Base, applied to async_connect().
Definition at line 244 of file client_session_adapter.hpp.
Referenced by ipc::session::sync_io::Client_session_adapter< Session >::Client_session_adapter().
m_ready_writer_conn
template<typename Session > util::Pipe_writer ipc::session::sync_io::Client_session_adapter< Session >::m_ready_writer_conn private
Similar to the ones in Base, applied to async_connect().
Definition at line 247 of file client_session_adapter.hpp.
Referenced by ipc::session::sync_io::Client_session_adapter< Session >::Client_session_adapter().
m_target_err_code_conn
template<typename Session > Error_code ipc::session::sync_io::Client_session_adapter< Session >::m_target_err_code_conn private
Result given to (or about to be given to) m_on_conn_func_or_empty.
Definition at line 256 of file client_session_adapter.hpp.
The documentation for this class was generated from the following files:
session/session_fwd.hpp
session/sync_io/client_session_adapter.hpp