Flow-IPC: ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config > Class Template Reference
ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config > Class Template Reference
sync_io-pattern counterpart to async-I/O-pattern transport::struc::Channel.
#include <channel.hpp>
Classes
struct Expecting_response
Policy for how to act upon receiving a response in-message that indicates its originating out-message is the message associated with this object in Expecting_response_map.
struct Msg_in_pipe
Data and policy with respect to receipt of the next/currently-incomplete in-message.
Public Types
using Async_io_obj = transport::struc::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >
Useful for generic programming, the async-I/O-pattern counterpart to *this type.
using Sync_io_obj = Null_peer
You may disregard.
using Owned_channel = Channel_obj
See Async_io_obj counterpart.
using Builder_config = Struct_builder_config
See Async_io_obj counterpart.
using Reader_config = Struct_reader_config
See Async_io_obj counterpart.
using Msg_body = Message_body
See Async_io_obj counterpart.
using Msg_which = typename Message_body::Which
See Async_io_obj counterpart.
using Msg_which_in = Msg_which
See Async_io_obj counterpart.
using Msg_which_out = Msg_which
See Async_io_obj counterpart.
using Msg_out = struc::Msg_out< Msg_body, typename Builder_config::Builder >
See Async_io_obj counterpart.
using Msg_in = struc::Msg_in< Msg_body, Reader_config >
See Async_io_obj counterpart.
using Msg_in_ptr = boost::shared_ptr< Msg_in >
See Async_io_obj counterpart.
using Msgs_in = std::vector< Msg_in_ptr >
List of in-messages used in certain APIs like expect_msgs() to synchronously emit cached in-messages.
using msg_id_out_t = Channel_base::msg_id_out_t
See Async_io_obj counterpart.
Public Types inherited from ipc::transport::struc::Channel_base
using msg_id_out_t = msg_id_t
Clarifying short-hand for outgoing-message IDs.
Public Member Functions
Channel (flow::log::Logger *logger_ptr, Owned_channel &&channel, const Builder_config &struct_builder_config, const typename Builder_config::Builder::Session &struct_lender_session, const Reader_config &struct_reader_config, const Session_token &session_token_non_nil)
Non-tag, no-log-in ctor form: Creates structured channel peer with no log-in phase (log-in phase must have occurred in a preceding struc::Channel called session master channel), the session token already known and passed-in to this ctor.
Channel (flow::log::Logger *logger_ptr, Owned_channel &&channel, const Builder_config &struct_builder_config, const typename Builder_config::Builder::Session &struct_lender_session, const Reader_config &struct_reader_config, bool is_server)
Non-tag, with-log-in ctor form: Creates structured channel peer (endpoint of the session master channel) with a log-in phase, this peer being the server or client depending on the arg is_server.
Channel (flow::log::Logger *logger_ptr, Owned_channel &&channel, Serialize_via_heap tag, const Session_token &session_token_non_nil)
Tag version of non-tag, no-log-in ctor: Serialize_via_heap (bidirectional heap-based, non-zero-copy message serialization).
Channel (flow::log::Logger *logger_ptr, Owned_channel &&channel, Serialize_via_heap tag, bool is_server)
Tag version of non-tag, with-log-in ctor: Serialize_via_heap (bidirectional heap-based, non-zero-copy message serialization).
template<typename Session >
Channel (flow::log::Logger *logger_ptr, Owned_channel &&channel, Serialize_via_session_shm tag, Session *session, const Session_token &session_token_explicit=NULL_SESSION_TOKEN)
Tag version of non-tag, no-log-in ctor: Serialize_via_session_shm (bidirectional SHM-based provider, zero-copy message serialization, per-session-scope arena).
template<typename Session >
Channel (flow::log::Logger *logger_ptr, Owned_channel &&channel, Serialize_via_session_shm tag, Session *session, bool is_server)
Tag version of non-tag, with-log-in ctor: Serialize_via_session_shm (bidirectional SHM-based provider, zero-copy message serialization, per-session-scope arena).
template<typename Session >
Channel (flow::log::Logger *logger_ptr, Owned_channel &&channel, Serialize_via_app_shm tag, Session *session, const Session_token &session_token_explicit=NULL_SESSION_TOKEN)
Tag version of non-tag, no-log-in ctor: Serialize_via_app_shm (bidirectional SHM-based provider, zero-copy message serialization, per-app-scope arena).
template<typename Session >
Channel (flow::log::Logger *logger_ptr, Owned_channel &&channel, Serialize_via_app_shm tag, Session *session, bool is_server)
Tag version of non-tag, no-log-in ctor: Serialize_via_app_shm (bidirectional SHM-based provider, zero-copy message serialization, per-app-scope arena).
~Channel ()
Invokes the destructor on the Owned_channel.
template<typename Create_ev_wait_hndl_func >
bool replace_event_wait_handles (const Create_ev_wait_hndl_func &create_ev_wait_hndl_func)
Analogous to transport::sync_io::Native_handle_sender::replace_event_wait_handles().
template<typename Event_wait_func_t >
bool start_ops (Event_wait_func_t &&ev_wait_func)
Sets up the sync_io-pattern interaction between *this and the user's event loop; required before async_accept() will work (as opposed to no-op/return false).
template<typename Task_err >
bool start_and_poll (Task_err &&on_err_func)
Permanently memorizes the incoming-direction on-error handler, thus authorizing the emission of any in-messages (and/or an error) to handlers registered via this call, expect_*(), async_request(), set_*unexpected_response_handler(); and synchronously executes any immediately relevant such handlers due to pending in-traffic.
const Builder_config & struct_builder_config () const
See Async_io_obj counterpart.
const Builder_config::Builder::Session & struct_lender_session () const
See Async_io_obj counterpart.
const Reader_config & struct_reader_config () const
See Async_io_obj counterpart.
const Owned_channel & owned_channel () const
See Async_io_obj counterpart.
Owned_channel * owned_channel_mutable ()
See Async_io_obj counterpart.
const Session_token & session_token () const
See Async_io_obj counterpart.
Msg_out create_msg (Native_handle &&hndl_or_null=Native_handle()) const
See Async_io_obj counterpart.
template<typename On_msg_handler >
bool expect_msg (Msg_which_in which, Msg_in_ptr *qd_msg, On_msg_handler &&on_msg_func)
Registers the expectation (which may be immediately met) of up to 1 notification in-message whose Msg_which equals which.
template<typename On_msg_handler >
bool expect_log_in_request (Msg_which_in which, Msg_in_ptr *qd_msg, On_msg_handler &&on_log_in_req_func)
In log-in phase as server only: Registers the expectation (which may be immediately met) of up to 1 log-in request in-message whose Msg_which equals which.
template<typename On_msg_handler >
bool expect_msgs (Msg_which_in which, Msgs_in *qd_msgs, On_msg_handler &&on_msg_func)
Registers the expectation (some of which may be immediately met) of 0+ notification in-messages whose Msg_which equals which.
bool undo_expect_msgs (Msg_which_in which)
See Async_io_obj counterpart.
bool send (const Msg_out &msg, const Msg_in *originating_msg_or_null=0, Error_code *err_code=0)
See Async_io_obj counterpart.
template<typename On_msg_handler >
bool async_request (const Msg_out &msg, const Msg_in *originating_msg_or_null, msg_id_out_t *id_unless_one_off, On_msg_handler &&on_rsp_func, Error_code *err_code=0)
See Async_io_obj counterpart; though naturally on_rsp_func() is invoked in the sync_io-pattern fashion.
bool undo_expect_responses (msg_id_out_t originating_msg_id)
See Async_io_obj counterpart.
template<typename On_unexpected_response_handler >
bool set_unexpected_response_handler (On_unexpected_response_handler &&on_func)
See Async_io_obj counterpart; though naturally on_func() is invoked in the sync_io-pattern fashion.
bool unset_unexpected_response_handler ()
See Async_io_obj counterpart.
template<typename On_remote_unexpected_response_handler >
bool set_remote_unexpected_response_handler (On_remote_unexpected_response_handler &&on_func)
See Async_io_obj counterpart; though naturally on_func() is invoked in the sync_io-pattern fashion.
bool unset_remote_unexpected_response_handler ()
See Async_io_obj counterpart.
template<typename Task_err >
bool async_end_sending (Error_code *sync_err_code, Task_err &&on_done_func)
See Async_io_obj counterpart; except (1) naturally on_done_func() is invoked in the sync_io-pattern fashion, and (2) the operation may (and is very likely to) complete synchronously and thus ignore on_done_func.
Private Types
enum class Phase { S_LOGGED_IN , S_SRV_LOG_IN , S_CLI_LOG_IN }
The state of *this (given start_ops() success); see m_phase.
enum class Rcv_next_step { S_READ_LEAD_MSG , S_READ_CONT_MSG , S_STOP }
Upon receiving an unstructured message along 1 given pipe of Owned_channel this indicates the next such message expected if any.
using Msg_out_impl = struc::Msg_out_impl< Msg_body, typename Builder_config::Builder >
Exact equivalent of Msg_out but with the internal-use (intended for us!) interface exposed.
using Msg_in_impl = struc::Msg_in_impl< Msg_body, Reader_config >
Exact equivalent of Msg_in but with the internal-use (intended for us!) interface exposed.
using Msg_mdt_out = struc::Msg_mdt_out< Builder_config >
Metadata message: internal-use out-message describing the associated Msg_out; or describing/containing internal message body (then not associated with a user-message).
using msg_id_in_t = msg_id_t
Clarifying short-hand for incoming-message IDs.
using On_msg_func = Function< void(Msg_in_ptr &&msg)>
Concrete type corresponding to On_msg_handler template param: in-message handler.
using On_msg_func_ptr = boost::shared_ptr< On_msg_func >
Ref-counted wrapper of On_msg_func.
using On_unexpected_response_func = Function< void(Msg_in_ptr &&msg)>
Concrete type corresponding to On_unexpected_response_handler template param (see set_unexpected_response_handler()).
using On_remote_unexpected_response_func = Function< void(msg_id_out_t msg_id_out, std::string &&msg_metadata_text)>
Concrete type corresponding to On_remote_unexpected_response_handler template param (see set_remote_unexpected_response_handler()).
using Expecting_msg = Expecting_response
Policy for how to act upon receiving an in-message whose top-level-union Msg_which_in enum equals the Msg_which_in associated with this object in Expecting_msg_map.
using Expecting_response_map = boost::unordered_map< msg_id_out_t, typename Expecting_response::Ptr >
Table mapping originating out-message to the policy for handling an in-message that indicates that out-message as the originating message (via message ID – after the out-message is sent via send()).
using Expecting_msg_map = boost::unordered_map< Msg_which_in, typename Expecting_msg::Ptr >
Table mapping in-message Msg_which_in enum value to the policy for handling an in-message with that which() value.
using Msg_in_ptr_uniq = boost::movelib::unique_ptr< Msg_in_impl >
Like Msg_in_ptr but unique_ptr instead of shared_ptr. Note the latter can upgrade-from a move()d former.
using Msg_in_q = std::queue< Msg_in_ptr_uniq >
Short-hand for queue (FIFO) of in-messages.
using Reassembly_q = std::map< msg_id_in_t, Msg_in_ptr_uniq >
Reassembly queue type: "queue" of all in-messages with msg_id_in_t exceeding m_rcv_msg_next_id, sorted in increasing order by that msg_id_in_t (sequence #).
Private Member Functions
template<typename Task >
void handlers_post (util::String_view context, Task &&handler)
Record handler to invoke in handlers_poll() soon.
void handlers_poll (util::String_view context)
Executes what was recorded recently in handlers_post().
size_t rcv_blob_max_size (decltype(Msg_in_pipe::m_lead_msg_mode) mode) const
Helper that returns the max receive-buffer size for any async-read into a given Msg_in_pipe.
void rcv_async_read_lead_or_continuation_msg (Msg_in_pipe *pipe, bool lead_else_cont)
This key method acts on the pre-condition that the given in-pipe is not known to be in would-block state; and therefore we should read (and process) as many unstructured in-messages as synchronously possible until reaching would-block state, at which point we should return with a pending async-wait/read on that in-pipe.
Rcv_next_step rcv_on_async_read_lead_msg (Msg_in_pipe *pipe, const Error_code &err_code, size_t sz)
To execute upon completing an m_channel.async_receive_*() of an expected lead message along the given in-pipe, this processes the result (message or error) and returns what should be done next; does not invoke handlers_poll().
Rcv_next_step rcv_on_async_read_continuation_msg (Msg_in_pipe *pipe, const Error_code &err_code, size_t sz)
Same as rcv_on_async_read_lead_msg() but for an expected continuation message instead of lead.
bool rcv_struct_new_msg_in (Msg_in_ptr_uniq &&msg_in)
Helper from rcv_on_async_read_*(), processes a newly completed structured in-message, as it exits the Channel-layer and enters into the structured-layer of processing.
bool rcv_struct_new_internal_msg_in (const Msg_in_impl &msg_in)
Helper from rcv_struct_new_msg_in(): the case where the in-message has a sentinel message ID value, indicating an internal message rather that one from a user send() (et al).
bool rcv_struct_new_msg_in_during_log_in_as_cli (Msg_in_ptr_uniq &&msg_in)
Helper from rcv_struct_new_msg_in(): the case where m_phase is Phase::S_CLI_LOG_IN, and the in-message has the log-in-response value 1 + session-token=nil as required: Processes the in-message according to the rigid log-in phase algorithm.
bool rcv_struct_new_msg_in_during_log_in_as_srv (Msg_in_ptr_uniq &&msg_in)
Like rcv_struct_new_msg_in_during_log_in_as_cli() but for Phase::S_SRV_LOG_IN instead of CLI_LOG_IN.
bool rcv_struct_new_msg_in_is_next_expected (Msg_in_ptr_uniq &&msg_in)
Helper from rcv_struct_new_msg_in() (possibly indirectly): the case where the in-message's session-token and message ID have been validated (and the latter indicates a user, not internal, message), and the message ID (seq #) indicates this is the next expected in-order message (hence m_rcv_msg_next_id was just ++ed).
void rcv_struct_inform_of_unexpected_response (Msg_in_ptr_uniq &&msg_in)
Helper from rcv_struct_new_msg_in_is_next_expected() that reacts to receiving an otherwise valid reponse in-message when no such response is expected.
bool handle_async_err_code (const Error_code &err_code, util::String_view context)
Helper for async handlers: returns true if and only if err_code indicates a new error or m_channel_err_code_or_ok indicates a previously-occurred one or both; updates m_channel_err_code_or_ok to err_code in the former case.
void handle_new_error (const Error_code &err_code_not_ok, util::String_view context)
Helper that handles the situation where m_channel_err_code_or_ok is falsy, and processing has found a new error condition.
bool check_not_started_ops (util::String_view context) const
Helper that returns true if and only if start_ops() has not yet been called.
bool check_prior_error (util::String_view context) const
Helper for some public APIs to use at the top: ensures that no prior error has been detected (by incoming-direction processing or send()); returns true if not; false if so.
bool check_phase_and_prior_error (Phase required_phase, util::String_view context) const
Helper for most public APIs to use at the top: ensures check_prior_error() passes, and that m_phase equals required_phase; returns true if not; false if so.
bool expect_msgs_impl (Msgs_in *qd_msgs, bool one_off, Msg_which_in which, On_msg_func_ptr &&on_msg_func)
Core of expect_msg(), expect_msgs(), and expect_log_in_request().
bool send_impl (const Msg_out &msg, const Msg_in *originating_msg_or_null, Error_code *err_code, const On_msg_func_ptr &on_rsp_func_or_null, msg_id_out_t *id_unless_one_off)
send() and async_request() implementation.
bool send_core (const Msg_mdt_out &mdt, const Msg_out_impl *msg, Error_code *err_code_or_ignore)
Core of send() or internal-message-send: Serializes the given structured out-messages (metadata out-message; user out-message optionally) and Owned_channel::send*()s the result (synchronously).
bool check_unsendable (const Msg_out &msg) const
send() and async_request() helper that returns true if and only if msg contains a native handle, but Owned_channel is compile-time-incapable of transporting them.
Private Attributes
const Builder_config m_struct_builder_config
The builder engine config for out-messages: Small data store, such that the Struct_builder Builder_config::Builder (really the containing class of Builder_config) main-ctor takes an object of this type, its contents being knobs controlling the behavior of the resulting Struct_builder.
const Builder_config::Builder::Session m_struct_lender_session
Value (possibly of size 0 depending on this type) to pass to Msg_out::emit_serialization() to indicate the opposing side of the Owned_channel.
const Reader_config m_struct_reader_config
Analogous to m_struct_builder_config but for deserialization.
bool m_started_ops
Whether start_ops() has been called yet or not.
flow::async::Task_asio_err m_on_err_func
The channel-hosed error reporting handler.
boost::array< std::optional< Msg_in_pipe >, 2 > m_rcv_pipes
1 or 2 active (via optional) structs containing policy and state w/r/t receipt of low-level (unstructured) messages with the aim to complete the next structured in-message(s).
On_unexpected_response_func m_on_unexpected_response_func_or_empty
See set_unexpected_response_handler().
On_remote_unexpected_response_func m_on_remote_unexpected_response_func_or_empty
See set_remote_unexpected_response_handler().
Session_token m_session_token
Session token: in Phase::S_LOGGED_IN to send in every out-message and check-against every in-message; in log-in phase as client equals nil; in log-in phase as server it is auto-generated at construction.
msg_id_out_t m_snd_msg_next_id
Next out-message ID (for the next send() or async_request()).
Phase m_phase
Phase (w/r/t log-in or lack thereof) of *this peer.
bool m_phase_log_in_started
Used when m_phase is Phase::S_SRV_LOG_IN, this starts false and is changed to true at thread-U call of expect_log_in_request(); if already true then a 2nd (illegal) expect_log_in_request() call has been made and shall be ignored (no-op, return sentinel).
Error_code m_channel_err_code_or_ok
Starts falsy; becomes forever truthy (with a specific Error_code that will not change thereafter) when one of the following detects the first channel-hosing condition: send() or async_request(), on-receive handler rcv_on_async_read_lead_msg() or rcv_on_async_read_continuation_msg().
Expecting_response_map m_rcv_expecting_response_map
Map storing current policy for expecting responses. See Expecting_response_map doc header for details.
Expecting_msg_map m_rcv_expecting_msg_map
Map storing current policy for expecting non-response messages.
msg_id_in_t m_rcv_msg_next_id
Next expected in-message ID (sequence #), incremented from initial value 1 to 2, 3, ... on in-order message receipt.
std::optional< Reassembly_q > m_rcv_reassembly_q
When Owned_channel::S_HAS_2_PIPES, stores the reassembly queue of in-messages to feed into m_rcv_pending_msgs once in-messages filling the msg_id_in_t (sequence #) gap between m_rcv_msg_next_id and m_rcv_reassembly_q.front() is filled.
boost::unordered_map< Msg_which_in, Msg_in_q > m_rcv_pending_msgs
Queues of in-messages, keyed by Msg_which_in, each in msg_id_in_t (sequence #) order, for which no Msg_which_in handler has yet been registered by the user (expect_msg(), expect_msgs(), expect_log_in_request()).
Owned_channel m_channel
The Channel taken-over in ctor, lifetime until dtor.
std::vector< boost::movelib::unique_ptr< util::Task > > m_sync_io_handlers
The handlers as pushed by handlers_post() to be flushed via handlers_poll() (internally by *this).
Related Functions
(Note that these are not member functions.)
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config >
std::ostream & operator<< (std::ostream &os, const Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config > &val)
Prints string representation of the given struc::sync_io::Channel to the given ostream.
Additional Inherited Members
Static Public Attributes inherited from ipc::transport::struc::Channel_base
static constexpr Serialize_via_heap S_SERIALIZE_VIA_HEAP = {}
The sole value of the tag type Serialize_via_heap.
static constexpr Serialize_via_session_shm S_SERIALIZE_VIA_SESSION_SHM = {}
The sole value of the tag type Serialize_via_session_shm.
static constexpr Serialize_via_app_shm S_SERIALIZE_VIA_APP_SHM = {}
The sole value of the tag type Serialize_via_app_shm.
Detailed Description
template<typename Channel_obj, typename Message_body, typename Struct_builder_config, typename Struct_reader_config>
class ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >
sync_io-pattern counterpart to async-I/O-pattern transport::struc::Channel.
See also
transport::struc::Channel and util::sync_io doc headers. The latter describes the general pattern which we implement here; it also contrasts it with the async-I/O pattern, which the former implements. In general we recommend you use a transport::struc::Channel rather than a *this – but you may have particular needs (summarized in util::sync_io doc header) that would make you decide otherwise.
All notes on functionality in transport::struc::Channel (a/k/a alias Channel::Async_io_obj) doc header apply to us. The difference, as usual given sync_io and async-I/O mutual counterparts, is in how results are reported. Because struc::Channel in general stands apart from the many concept impls of Blob_sender, Blob_receiver, etc. – e.g., Native_socket_stream – it may be helpful to summarize how this sync_io-pattern type reports results. The APIs look somewhat different from those core-layer guys owing to the more complex mission statement here versus there.
expect_*(..., F): This says you want messages of a certain type, and when one arrives to invoke F(I), I being the in-message. However, depending on the API 1+ message(s) may already have been cached and are immediately available. These are synchronously emitted via an out-arg; for example expect_msgs() takes a list-of-in-messages out-arg. Depending on the API future messages may be relevant and will be emitted via F().
async_request(M, ..., F): This says you want M sent and expect 1 or 0+ (depending on args) response(s), and when one arrives to invoke F(I), I being a response. Since it is not possible to have received a response to a not-yet-sent out-message, that is just how it works. There are no synchronous out-args.
set_*unexpected_response_handler(): If it's set, and an unexpected-response event occurs, this fires. If not, it doesn't. There are no synchronous out-args.
start_and_poll(F): This begins incoming-direction operation. F() is the on-error handler. It fires up to once per *this to indicate underlying Owned_channel or other channel-hosing error (including receiving graceful-close). An error may synchronously occur right then, plus any expect_*()- and async_request()-triggered in-messages may be synchronously detected. Therefore – and this is quite rare (singular as of this writing in Flow-IPC):
start_and_poll(F) may synchronously (!) call a number of queued-up (in a sense) handlers including:
expect_*() handlers;
async_request() handlers;
set_*unexpected_response_handler() handlers;
on-error handler F() itself.
Tip: If you'd rather not worry about start_and_poll()-executed handlers – except on-error handler which might occur regardless – then avoid calling expect_*(), async_request(), set_*() before start_and_poll(). (No in-messages are ever dropped, so you won't "miss" something by registering an expectation too late.) That said there's nothing wrong per se with setting those things up before start_and_poll() either. Just be ready for the _and_poll part.
Implementation overview
Like all sync_io-core object types, this one is essentially a linear state machine with no actual asynchronicity or concurrency. (Some sync_ios do need to start threads in order to perform unavoidable blocking operations – namely the Blob_stream_mq_* guys with at least the bipc MQ type which lacks an FD-tickling API – but this can be thought of similarly to a background kernel service. Anyway sync_io::Channel doesn't even feature that caveat.)
So as with other sync_io cores, it's a linear sequence of API calls into *this that may not be mutually concurrent (when non-const). As with those others in this context an API call is either a method call (duh) or an async-wait Event_wait_func calling into *this via (*on_active_ev_func)(). Hence we don't care what thread a given thing runs in, as long as our user (e.g., transport::struc::Channel) doesn't invoke things concurrently.
So it's "just" a matter of implementing each direction – outgoing (send() et al), incoming (expect_*(), async_request()), and their (reasonably limited) interplay (e.g., async_request() conceptually = a send() + registering expectation of particular future response in-message(s)).
Implementation: layers
In the outgoing direction, the layers involved are fairly straightforward: send() is synchronous. When it is called, the zero-copy serialization of the structured out-message Msg_out has been completed: the raw blobs comprised by it are easily accessible from the Msg_out (Msg_out::emit_serialization()) passed to send() (as is the optional Native_handle). The 1+ blobs + the Native_handle are synchronously Channel::send_*()ed, and then send() returns. In addition, but still synchronously within send(), each such user message is internally accompanied by another similarly-serialized message: the metadata message. This message, with a schema in structured_msg.capnp (a detail/ file), represents a description of the associated Msg_out. Its schema is controlled by us and is sufficiently small to require just one segment (blob) and no Native_handle. This contains information about the message (a/k/a metadata), notably: its message ID (discussed below), the ID of the message to which it responds (or 0 if unsolicited), and the session token. To summarize, then, send() of a user message in fact sends exactly 1 metadata message (Msg_mdt_out, a special-purpose sub-class of Msg_out, adding no data members but a convenient internally-used APIs to set its fields), across exactly 1 blob (segment), plus 1+ blobs (segments) serializing the user message. (async_request() = internally such a send() more or less, plus registering that future in-message(s) with certain metadata content are expected.)
Lastly, for some special purposes, we sometimes send internal messages. An internal message consists of only the metadata (Msg_mdt_out, alias Msg_mdt_out), with the optional internal-message-body field filled-out, and no user message. Hence in this case exactly 1 Blob (segment) is sent. In the few cases where an internal message is required, internal code calls send_core() directly (with the Msg_out arg set to null); whereas a user message goes through send() or async_request() which invokes send_core() (with Msg_out arg non-null but rather the user-supplied Msg_out).
In the incoming direction, it is much more complex. Receiving a blob, or blob+handle pair, is by definition a (potentially) asynchronous operation; and a given structured in-message may consist of more than 1 blob/blob+handle pair. The zero-copy deserialization invoked by the user can only occur once all of them are received, so we must build up 1 given structured in-message over 1+ async-read ops and only emit the result (a newly allocated/cted Msg_in a/k/a Msg_in_ptr) to the user once the last of the 1+ async-read ops finishes. So that's 2 layers: async-read op at the Owned_channel level; then the structured level once a Msg_in is ready. Msg_in represents, conceptually, a pointer to 1-2 serialized in-messages: the metadata in-message (always present) and, except for internal messages, the user-supplied in-message (supplied originally via Msg_out). However, to the user, only the latter is accessible, and an internal message is by definition never emitted to the user (if it were, there would be nothing for them to access).
The preceding paragraph talks only of one Channel pipe. It is possible Owned_channel contains 2 pipes (Channel::S_HAS_2_PIPES), operating potentially in parallel. (This may be useful for perf; discussion omitted here.) Naturally this creates the possibility of reordering of in-messages. Hence, optionally, there is another layer between completing a Msg_in (Msg_in_ptr) and emitting it: a simple reassembly queue. To make this work: each in-message (hence each out-message instance) is supplied with a unique message ID (required anyway for, at least, request-response correlation); and that message ID doubles as a sequence # (1, 2, ...). Reassembly_q is a reassembly queue that is (probably infrequently) used to temporarily store out-of-order structured in-messages, flushing them once the gap between last-emitted-to-next-layer in-message-sequence-# and lowest-in-message-sequence-#-in-reassembly-queue is filled.
Okay; let's assume an in-message has gone through the above 2-3 layers (Channel layer, (optional) reassembly queue layer, Msg_in completion layer). Can we finally emit it to the user? Often yes... but generally no:
In the incoming-direction, we add notification and response expectation APIs (these are mandatory before the *this user receives an emitted in-message via handler). This adds a further layer of processing. Once a Msg_in (Msg_in_ptr) is assembled and ready to deserialize, one of 2 things happens: either an expect_msg() or async_request() has registered a handler for this in-message – then it is immediately emitted to that handler (done!); or not – then it is stored inside *this. (Once a handler is subsequently registered, the appropriate stored in-messages shall be emitted via synchronous out-args such as qd_msgs for expect_msgs().)
That's the overview. Various doc headers on private types and/or data members should fill in the details.
Template Parameters
Channel_obj See Async_io_obj doc header.
Message_body See Async_io_obj doc header.
Struct_builder_config See Async_io_obj doc header.
Struct_reader_config See Async_io_obj doc header.
Definition at line 178 of file channel.hpp.
Member Typedef Documentation
Async_io_obj
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Async_io_obj = transport::struc::Channel<Channel_obj, Message_body, Struct_builder_config, Struct_reader_config>
Useful for generic programming, the async-I/O-pattern counterpart to *this type.
Definition at line 187 of file channel.hpp.
Builder_config
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Builder_config = Struct_builder_config
See Async_io_obj counterpart.
Definition at line 200 of file channel.hpp.
Expecting_msg
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Expecting_msg = Expecting_response private
Policy for how to act upon receiving an in-message whose top-level-union Msg_which_in enum equals the Msg_which_in associated with this object in Expecting_msg_map.
It is aliased to Expecting_response for brevity, since that struct's fields are easily reworked to the present application.
m_one_expected is repurposed to apply to undo_expect_msgs().
m_on_msg_func is repurposed as the handler for a Msg_which_in value (see expect_msg(), expect_msgs()).
Definition at line 982 of file channel.hpp.
Expecting_msg_map
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Expecting_msg_map = boost::unordered_map<Msg_which_in, typename Expecting_msg::Ptr> private
Table mapping in-message Msg_which_in enum value to the policy for handling an in-message with that which() value.
Definition at line 994 of file channel.hpp.
Expecting_response_map
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Expecting_response_map = boost::unordered_map<msg_id_out_t, typename Expecting_response::Ptr> private
Table mapping originating out-message to the policy for handling an in-message that indicates that out-message as the originating message (via message ID – after the out-message is sent via send()).
Definition at line 988 of file channel.hpp.
Msg_body
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_body = Message_body
See Async_io_obj counterpart.
Definition at line 205 of file channel.hpp.
msg_id_in_t
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::msg_id_in_t = msg_id_t private
Clarifying short-hand for incoming-message IDs.
Definition at line 897 of file channel.hpp.
msg_id_out_t
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::msg_id_out_t = Channel_base::msg_id_out_t
See Async_io_obj counterpart.
Definition at line 229 of file channel.hpp.
Msg_in
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_in = struc::Msg_in<Msg_body, Reader_config>
See Async_io_obj counterpart.
Definition at line 220 of file channel.hpp.
Msg_in_impl
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_in_impl = struc::Msg_in_impl<Msg_body, Reader_config> private
Exact equivalent of Msg_in but with the internal-use (intended for us!) interface exposed.
Definition at line 888 of file channel.hpp.
Msg_in_ptr
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_in_ptr = boost::shared_ptr<Msg_in>
See Async_io_obj counterpart.
Definition at line 223 of file channel.hpp.
Msg_in_ptr_uniq
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_in_ptr_uniq = boost::movelib::unique_ptr<Msg_in_impl> private
Like Msg_in_ptr but unique_ptr instead of shared_ptr. Note the latter can upgrade-from a move()d former.
Definition at line 997 of file channel.hpp.
Msg_in_q
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_in_q = std::queue<Msg_in_ptr_uniq> private
Short-hand for queue (FIFO) of in-messages.
Definition at line 1000 of file channel.hpp.
Msg_mdt_out
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_mdt_out = struc::Msg_mdt_out<Builder_config> private
Metadata message: internal-use out-message describing the associated Msg_out; or describing/containing internal message body (then not associated with a user-message).
Definition at line 894 of file channel.hpp.
Msg_out
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_out = struc::Msg_out<Msg_body, typename Builder_config::Builder>
See Async_io_obj counterpart.
Definition at line 217 of file channel.hpp.
Msg_out_impl
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_out_impl = struc::Msg_out_impl<Msg_body, typename Builder_config::Builder> private
Exact equivalent of Msg_out but with the internal-use (intended for us!) interface exposed.
Definition at line 885 of file channel.hpp.
Msg_which
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_which = typename Message_body::Which
See Async_io_obj counterpart.
Definition at line 208 of file channel.hpp.
Msg_which_in
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_which_in = Msg_which
See Async_io_obj counterpart.
Definition at line 211 of file channel.hpp.
Msg_which_out
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_which_out = Msg_which
See Async_io_obj counterpart.
Definition at line 214 of file channel.hpp.
Msgs_in
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msgs_in = std::vector<Msg_in_ptr>
List of in-messages used in certain APIs like expect_msgs() to synchronously emit cached in-messages.
Definition at line 226 of file channel.hpp.
On_msg_func
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::On_msg_func = Function<void (Msg_in_ptr&& msg)> private
Concrete type corresponding to On_msg_handler template param: in-message handler.
Definition at line 900 of file channel.hpp.
On_msg_func_ptr
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::On_msg_func_ptr = boost::shared_ptr<On_msg_func> private
Ref-counted wrapper of On_msg_func.
Definition at line 903 of file channel.hpp.
On_remote_unexpected_response_func
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::On_remote_unexpected_response_func = Function<void (msg_id_out_t msg_id_out, std::string&& msg_metadata_text)> private
Concrete type corresponding to On_remote_unexpected_response_handler template param (see set_remote_unexpected_response_handler()).
Definition at line 915 of file channel.hpp.
On_unexpected_response_func
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::On_unexpected_response_func = Function<void (Msg_in_ptr&& msg)> private
Concrete type corresponding to On_unexpected_response_handler template param (see set_unexpected_response_handler()).
Definition at line 909 of file channel.hpp.
Owned_channel
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Owned_channel = Channel_obj
See Async_io_obj counterpart.
Definition at line 193 of file channel.hpp.
Reader_config
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Reader_config = Struct_reader_config
See Async_io_obj counterpart.
Definition at line 202 of file channel.hpp.
Reassembly_q
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Reassembly_q = std::map<msg_id_in_t, Msg_in_ptr_uniq> private
Reassembly queue type: "queue" of all in-messages with msg_id_in_t exceeding m_rcv_msg_next_id, sorted in increasing order by that msg_id_in_t (sequence #).
Relevant only if Owned_channel::S_HAS_2_PIPES == true.
Definition at line 1006 of file channel.hpp.
Sync_io_obj
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > using ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Sync_io_obj = Null_peer
You may disregard.
Definition at line 190 of file channel.hpp.
Member Enumeration Documentation
Phase
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > enum class ipc::transport::struc::sync_io::Channel::Phase strong private
The state of *this (given start_ops() success); see m_phase.
Enumerator
S_LOGGED_IN
Regular-operation phase: the general API (expect_msg(), etc.) is available.
Most struc::Channels begin in this phase, via ctor that takes session_token_non_nil. This is the terminal phase. Phases that lead to it are S_SRV_LOG_IN and S_CLI_LOG_IN.
S_SRV_LOG_IN
Logging-in phase, as server process: The general API (expect_msg(), etc.) is unavailable; only expect_log_in_request() and send() are available.
This is an initial phase for a session master channel, via ctor that does not take session_token_non_nil and has is_server == true. Leads to S_LOGGED_IN.
S_CLI_LOG_IN
Logging-in phase, as client process: The general API (expect_msg(), etc.) is unavailable; only create_msg() and send() (response-expecting form) are available.
This is an initial phase for a session master channel, via ctor that does not take session_token_non_nil and has is_server == false. Leads to S_LOGGED_IN.
Definition at line 919 of file channel.hpp.
Rcv_next_step
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > enum class ipc::transport::struc::sync_io::Channel::Rcv_next_step strong private
Upon receiving an unstructured message along 1 given pipe of Owned_channel this indicates the next such message expected if any.
Enumerator
S_READ_LEAD_MSG
Next message is lead message.
The case in these situations:
Initial state (start_and_poll()).
The last message was lead unstructured message comprised by a structured internal message. (An internal structured message = always 1 unstructured lead message.)
The last message was continuation unstructured message N of N comprised by a structured user message's serialization; where N is the segment count for the serialization of the user message. N itself is communicated in the lead unstructured message (the metadata). Ideally, and typically, N=1.
S_READ_CONT_MSG
Next message is continuation message.
The case in these situations:
The last message was lead unstructured message comprised by a structured user message message. (An user structured message = always 1 unstructured lead message containing metadata + 1+ continuation messages comprised by structured user message's serialization.)
The last message was continuation unstructured message less-than-N of N comprised by a structured user message's serialization; where N is the segment count for the serialization of the user message. N itself is communicated in the lead unstructured message. Ideally, and typically, N=1.
S_STOP
The pipe should no longer be read-from ever (the case on error).
Definition at line 1244 of file channel.hpp.
Constructor & Destructor Documentation
Channel() [1/8]
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Channel (flow::log::Logger * logger_ptr, Owned_channel && channel, const Builder_config & struct_builder_config, const typename Builder_config::Builder::Session & struct_lender_session, const Reader_config & struct_reader_config, const Session_token & session_token_non_nil) explicit
Non-tag, no-log-in ctor form: Creates structured channel peer with no log-in phase (log-in phase must have occurred in a preceding struc::Channel called session master channel), the session token already known and passed-in to this ctor.
Consider also:
A tag-form ctor (usually simpler than manually cting struct_builder_config and struct_reader_config).
With-log-in ctor (usually needed for session master channel only).
Note
This ctor form is forwarded-to from Async_io_obj ctor. Documentation below applies to both ctors except where noted.
If *this ctor is for sync_io::Channel: You'll need to start_ops() (possibly preceded by replace_event_wait_handles()) per sync_io pattern. (If *this ctor is for Async_io_obj: not applicable.) Then:
You may send() (et al) immediately after this. However no in-messages shall be emitted, regardless of registered expectations such as via expect_msg(), until you invoke start_and_poll(). (For Async_io_obj: transport::struc::Channel::start().)
Consider, also, owned_channel_mutable()->auto_ping() and/or owned_channel_mutable()->idle_timer_run(), if you desire these features to be ambiently enabled. See Channel::auto_ping(), Channel::idle_timer_run() for background.
How/whether to obtain a Builder_config struct_builder_config (and related)
It is easiest, usually, to use a different ctor form instead; namely use a tagged-ctor version that will set everything up. See Channel_base::Serialize_via_*. Only use the present ctor form:
IF: your serialization strategy of choice is simply not covered by the tagged-ctor versions available (you have a custom builder/reader you want to use for advanced purposes). OR:
IF: you want to use a different serialization strategy in the outgoing direction versus incoming direction: e.g., this side sends only short things – and you want to use Heap_fixed_builder here and Heap_reader there; but the other side sends huge things, so you want SHM-based serialization there and deserialization here. The tag ctors assume symmetry and don't support this.
If you've chosen to use this ctor form:
Formally speaking it's simply up to you to construct these args before calling this ctor; see the docs for the particular Builder_config class of choice. Informally: if you're constructing the Builder_config and/or specifying struct_lender_session (less so Reader_config, but for consistency it too) directly, you're probably not doing the right thing. The following places are available to obtain tese for safety and efficiency (and code maintainability):
From another, compatible, Channel via struct_builder_config(), struct_lender_session(), struct_reader_config().
Heap-backed:
struct_lender_session is always NULL_SESSION. As for the other 2:
If you have the target Owned_channel: via static heap_fixed_builder_config() and heap_reader_config().
Otherwise: session::Session_mv::heap_fixed_builder_config() (static or non-static), session::Session_mv::heap_reader_config() (ditto).
SHM-backed (using SHM-classic as example):
session::shm::classic::Session_mv::session_shm_builder_config() (ditto reader), session::shm::classic::Session_mv::session_shm_lender_session(), session::shm::classic::Session_mv::app_shm_builder_config() (ditto reader), session::shm::classic::Session_mv::app_shm_lender_session(). Requires a Session object.
session::shm::classic::Session_server::app_shm_builder_config() (requires session::Client_app). Server-only; if a Session is not available or applicable.
Parameters
logger_ptr Logger to use for logging subsequently.
channel Channel in PEER state with no prior traffic. All configurations (1 pipe, 2 pipes) are supported. If channel.initialized() is false, behavior is undefined (assertion may trip): suggest sanity-checking this prior to this ctor. Behavior is undefined if it is not in PEER state or has had prior traffic. (Reminder: PEER state does not mean it isn't hosed from error/whatever: This is handled gracefully.) The channel is moved-into *this.
struct_builder_config The serialization engine config to use for serializing out-messages. This small object is copied.
struct_lender_session See Struct_builder::Session (and/or Struct_builder::emit_serialization()) concept doc header. This small value (typically a pointer) is copied; or the type may be Null_session which is empty; then there is nothing to even copy.
struct_reader_config The deserialization engine config to use for deserializing in-messages. This small object is copied.
session_token_non_nil The session token to place into all out-messages and for which value to check against all in-messages. If a check fails, the channel is hosed immediately. Behavior undefined if it equals nil (assertion may trip). See class doc header regarding how to obtain the value to pass-in here.
Definition at line 1972 of file channel.hpp.
References ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_rcv_reassembly_q, and ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_session_token.
Channel() [2/8]
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Channel (flow::log::Logger * logger_ptr, Owned_channel && channel, const Builder_config & struct_builder_config, const typename Builder_config::Builder::Session & struct_lender_session, const Reader_config & struct_reader_config, bool is_server) explicit
Non-tag, with-log-in ctor form: Creates structured channel peer (endpoint of the session master channel) with a log-in phase, this peer being the server or client depending on the arg is_server.
Consider also:
A tag-form ctor (usually simpler than manually cting struct_builder_config and struct_reader_config).
No-log-in ctor (since present ctor is usually needed for session master channel only).
No general user communication can occur until the log-in phase is completed. As such *this would be the session master channel with, presumably, exactly 1 such *this in the entire process at a given time. See Async_io_obj class doc header for background.
Note
This ctor form is forwarded-to from Async_io_obj ctor. Documentation below applies to both ctors except where noted.
If *this ctor is for sync_io::Channel: You'll need to start_ops() (possibly preceded by replace_event_wait_handles()) per sync_io pattern. (If *this ctor is for Async_io_obj: not applicable.) Then:
You may send() (et al) immediately after this. However no in-messages shall be emitted, regardless of registered expectations such as via expect_msg(), until you invoke start_and_poll(). (For Async_io_obj: transport::struc::Channel::start().)
Consider, also, owned_channel_mutable()->auto_ping() and/or owned_channel_mutable()->idle_timer_run(), if you desire these features to be ambiently enabled. See Channel::auto_ping(), Channel::idle_timer_run() for background.
As server
To begin the log-in phase – and thus start to move to the logged-in phase, in which general traffic can occur – you must use expect_log_in_request(). *this will proceed to logged-in phase automatically once the log-in request message M arrives, and you then invoke send(X, M), where X is the log-in response out-message you create/fill-out. To be clear the phase change occurs as the last step in that successful send().
As client
To begin the log-in phase – and thus start to move to the logged-in phase, in which general traffic can occur – you must send(X, nullptr, nullptr, F), where X is the log-in request out-message you create/fill-out, while F() is the handler for the log-in response. *this will proceed to logged-in phase automatically once the response to X arrives; and will then invoke F() for any further validation the user may desire.
How/whether to obtain a Builder_config struct_builder_config (and Reader_config similarly)
See notes for the other (no-log-in) non-tag ctor overload.
Parameters
logger_ptr See other ctor overload.
channel See other ctor overload.
struct_builder_config See other ctor overload.
struct_lender_session See other ctor overload.
struct_reader_config See other ctor overload.
is_server See above.
Definition at line 2012 of file channel.hpp.
References ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_rcv_reassembly_q.
Channel() [3/8]
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Channel (flow::log::Logger * logger_ptr, Owned_channel && channel, Serialize_via_heap tag, const Session_token & session_token_non_nil) explicit
Tag version of non-tag, no-log-in ctor: Serialize_via_heap (bidirectional heap-based, non-zero-copy message serialization).
See also
Serialize_via_heap doc header for serialization-related background.
non-tag, no-log-in ctor. As directed there, use the present form whenever sufficient, and indeed you want this type of serialization setup. Consider also the other tag forms for other serialization methods which may match your requirements better.
Parameters
logger_ptr See non-tag ctor form.
channel See non-tag ctor form.
tag Ctor-selecting tag.
session_token_non_nil See non-tag ctor form.
Definition at line 2055 of file channel.hpp.
Channel() [4/8]
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Channel (flow::log::Logger * logger_ptr, Owned_channel && channel, Serialize_via_heap tag, bool is_server) explicit
Tag version of non-tag, with-log-in ctor: Serialize_via_heap (bidirectional heap-based, non-zero-copy message serialization).
See also
Serialize_via_heap doc header for serialization-related background.
non-tag, with-log-in ctor. As directed there, use the present form whenever sufficient, and indeed you want this type of serialization setup. Consider also the other tag forms for other serialization methods which may match your requirements better.
Parameters
logger_ptr See non-tag ctor form.
channel See non-tag ctor form.
tag Ctor-selecting tag.
is_server See non-tag ctor form.
Definition at line 2067 of file channel.hpp.
Channel() [5/8]
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > template<typename Session > ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Channel (flow::log::Logger * logger_ptr, Owned_channel && channel, Serialize_via_session_shm tag, Session * session, const Session_token & session_token_explicit = NULL_SESSION_TOKEN) explicit
Tag version of non-tag, no-log-in ctor: Serialize_via_session_shm (bidirectional SHM-based provider, zero-copy message serialization, per-session-scope arena).
See also
Serialize_via_session_shm doc header for serialization-related background.
non-tag, no-log-in ctor. As directed there, use the present form whenever sufficient, and indeed you want this type of serialization setup. Consider also the other tag forms for other serialization methods which may match your requirements better.
Template Parameters
Session One of, at least: session::shm::classic::Client_session, session::shm::classic::Server_session, session::shm::arena_lend::jemalloc::Client_session, session::shm::arena_lend::jemalloc::Server_session.
Parameters
logger_ptr See non-tag ctor form.
channel See non-tag ctor form.
tag Ctor-selecting tag.
session session->session_shm() shall be used as the backing SHM space. *session must be in PEER state, or behavior is undefined.
session_token_explicit See non-tag ctor form. However, for convenience, if you instead supply value equal to NULL_SESSION_TOKEN (i.e., nil) (which is default), then session->session_token() shall be used. After all... why not? That's probably what you want.
Definition at line 2080 of file channel.hpp.
Channel() [6/8]
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > template<typename Session > ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Channel (flow::log::Logger * logger_ptr, Owned_channel && channel, Serialize_via_session_shm tag, Session * session, bool is_server) explicit
Tag version of non-tag, with-log-in ctor: Serialize_via_session_shm (bidirectional SHM-based provider, zero-copy message serialization, per-session-scope arena).
See also
Serialize_via_session_shm doc header for serialization-related background.
non-tag, no-log-in ctor. As directed there, use the present form whenever sufficient, and indeed you want this type of serialization setup. Consider also the other tag forms for other serialization methods which may match your requirements better.
Template Parameters
Session One of, at least: session::shm::classic::Client_session, session::shm::classic::Server_session, session::shm::arena_lend::jemalloc::Client_session, session::shm::arena_lend::jemalloc::Server_session.
Parameters
logger_ptr See non-tag ctor form.
channel See non-tag ctor form.
tag Ctor-selecting tag.
session session->session_shm() shall be used as the backing SHM space. *session must be in PEER state, or behavior is undefined.
is_server See non-tag ctor form.
Definition at line 2095 of file channel.hpp.
Channel() [7/8]
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > template<typename Session > ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Channel (flow::log::Logger * logger_ptr, Owned_channel && channel, Serialize_via_app_shm tag, Session * session, const Session_token & session_token_explicit = NULL_SESSION_TOKEN) explicit
Tag version of non-tag, no-log-in ctor: Serialize_via_app_shm (bidirectional SHM-based provider, zero-copy message serialization, per-app-scope arena).
See also
Serialize_via_app_shm doc header for serialization-related background.
non-tag, no-log-in ctor. As directed there, use the present form whenever sufficient, and indeed you want this type of serialization setup. Consider also the other tag forms for other serialization methods which may match your requirements better.
Template Parameters
Session One of, at least: session::shm::classic::Client_session, session::shm::classic::Server_session, session::shm::arena_lend::jemalloc::Server_session (not session::shm::arena_lend::jemalloc::Client_session – will not compile).
Parameters
logger_ptr See non-tag ctor form.
channel See non-tag ctor form.
tag Ctor-selecting tag.
session session->app_shm() shall be used as the backing SHM space. *session must be in PEER state, or behavior is undefined.
session_token_explicit See session_token_explicit in the Serialize_via_session_shm counterpart to this ctor form. Spoiler alert: probably you'll want to leave this at default.
Definition at line 2108 of file channel.hpp.
Channel() [8/8]
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > template<typename Session > ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Channel (flow::log::Logger * logger_ptr, Owned_channel && channel, Serialize_via_app_shm tag, Session * session, bool is_server) explicit
Tag version of non-tag, no-log-in ctor: Serialize_via_app_shm (bidirectional SHM-based provider, zero-copy message serialization, per-app-scope arena).
See also
Serialize_via_app_shm doc header for serialization-related background.
non-tag, no-log-in ctor. As directed there, use the present form whenever sufficient, and indeed you want this type of serialization setup. Consider also the other tag forms for other serialization methods which may match your requirements better.
Template Parameters
Session One of, at least: session::shm::classic::Client_session, session::shm::classic::Server_session, session::shm::arena_lend::jemalloc::Server_session (not ession::shm::arena_lend::jemalloc::Client_session – will not compile).
Parameters
logger_ptr See non-tag ctor form.
channel See non-tag ctor form.
tag Ctor-selecting tag.
session session->app_shm() shall be used as the backing SHM space. *session must be in PEER state, or behavior is undefined.
is_server See non-tag ctor form.
Definition at line 2123 of file channel.hpp.
~Channel()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::~Channel
Invokes the destructor on the Owned_channel.
Reminder: It is recommended, before invoking this destructor, to:
Call async_end_sending(F).
Invoke this destructor once F() fires.
See discussion in async_end_sending() doc header or shorter version in class doc header.
Definition at line 2135 of file channel.hpp.
Member Function Documentation
async_end_sending()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > template<typename Task_err > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::async_end_sending (Error_code * sync_err_code, Task_err && on_done_func)
See Async_io_obj counterpart; except (1) naturally on_done_func() is invoked in the sync_io-pattern fashion, and (2) the operation may (and is very likely to) complete synchronously and thus ignore on_done_func.
Note
It is highly recommended to read the Async_io_obj transport::struc::Channel::async_end_sending() doc header's recommendations on how/when/why to use the method.
The sync-versus-async-completion dichotomy is exactly forwarded from Owned_channel, and you can read the details in sync_io::Native_handle_sender::async_end_sending() doc header.
Template Parameters
Task_err See above.
Parameters
sync_err_code See above.
on_done_func See above.
Returns
See above. In addition false returned if called before start_ops().
Definition at line 4122 of file channel.hpp.
async_request()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > template<typename On_msg_handler > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::async_request (const Msg_out & msg, const Msg_in * originating_msg_or_null, msg_id_out_t * id_unless_one_off, On_msg_handler && on_rsp_func, Error_code * err_code = 0)
See Async_io_obj counterpart; though naturally on_rsp_func() is invoked in the sync_io-pattern fashion.
There is no possibility of the response expectation being immediately (synchronously) met.
Template Parameters
On_msg_handler See expect_msg().
Parameters
msg See above.
originating_msg_or_null See above.
id_unless_one_off See above.
on_rsp_func See above.
err_code See above.
Returns
See above. In addition false returned if called before start_ops().
Definition at line 3762 of file channel.hpp.
check_not_started_ops()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::check_not_started_ops (util::String_view context) const private
Helper that returns true if and only if start_ops() has not yet been called.
This guard is required for APIs that trigger m_channel transmission API calls. Outgoing-direction such calls would be, e.g., send() and async_end_sending(). Incoming-direction transmission is all triggered by start_and_poll() (which begins the async-read chain(s) indefinitely.)
Parameters
context Brief context string for logging.
Returns
true if not started (do not proceed); else false.
Definition at line 2262 of file channel.hpp.
check_phase_and_prior_error()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::check_phase_and_prior_error (Phase required_phase, util::String_view context) const private
Helper for most public APIs to use at the top: ensures check_prior_error() passes, and that m_phase equals required_phase; returns true if not; false if so.
I.e., please no-op if returns true.
Parameters
required_phase m_phase must equal this to return false.
context Brief context string for logging.
Returns
See above. true bad. false good.
Definition at line 4148 of file channel.hpp.
check_prior_error()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::check_prior_error (util::String_view context) const private
Helper for some public APIs to use at the top: ensures that no prior error has been detected (by incoming-direction processing or send()); returns true if not; false if so.
I.e., please no-op if returns true.
Parameters
context Brief context string for logging.
Returns
See above. true bad. false good.
Definition at line 4134 of file channel.hpp.
check_unsendable()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::check_unsendable (const Msg_out & msg) const private
send() and async_request() helper that returns true if and only if msg contains a native handle, but Owned_channel is compile-time-incapable of transporting them.
No *this state other than logging context is accessed.
Parameters
msg See, e.g., send().
Returns
true if unsendable; else false.
Definition at line 3719 of file channel.hpp.
References ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::native_handle_or_null().
create_msg()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_out ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::create_msg (Native_handle && hndl_or_null = Native_handle()) const
See Async_io_obj counterpart.
Parameters
hndl_or_null See above.
Returns
See above.
Definition at line 4168 of file channel.hpp.
References ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::store_native_handle_or_null().
expect_log_in_request()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > template<typename On_msg_handler > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::expect_log_in_request (Msg_which_in which, Msg_in_ptr * qd_msg, On_msg_handler && on_log_in_req_func)
In log-in phase as server only: Registers the expectation (which may be immediately met) of up to 1 log-in request in-message whose Msg_which equals which.
No-op and return false if expect_log_in_request() has already been invoked, if log-in phase is not active or active in the client role, or if a prior error has hosed the owned Channel.
The expectation is unregistered upon receipt of the applicable in-message (and firing it with that in-message Msg_in_ptr as arg). In addition:
The 1 expected in-message may already be available synchronously. In that case:
*qd_msg shall be loaded with that message; and it is purged from *this. You must handle it as you see fit upon return from this method.
The expectation is immediately unregistered.
on_log_in_req_func is ignored (it is not memorized).
Therefore on_log_in_req_func() can only execute upon a future sync_io-pattern async-wait firing its (*on_active_ev_func)().
Tips
Informally the proper behavior is:
Construct in log-in-as-server phase.
Invoke expect_log_in_request().
Await on_log_in_req_func(X&&) firing, or immediate delivery of X via *qd_msg, where X is the log-in request.
After on_log_in_req_func(X&&) handler, or immediate delivery pf X via *qd_msg: check X for correctness (such as process identity checks). If it fails checks, destroy *this; else:
Fill out X = this->create_msg() (the log-in response) as needed via X->body_root().
send(X). The latter automatically moves *this to logged-in phase locally: the bulk of the API becomes available.
Template Parameters
On_msg_handler See expect_msg().
Parameters
which See expect_msg().
qd_msg See expect_msg().
on_log_in_req_func See above.
Returns
true on success; false due to one of the above conditions.
Definition at line 4233 of file channel.hpp.
expect_msg()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > template<typename On_msg_handler > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::expect_msg (Msg_which_in which, Msg_in_ptr * qd_msg, On_msg_handler && on_msg_func)
Registers the expectation (which may be immediately met) of up to 1 notification in-message whose Msg_which equals which.
No-op and return false if which is already being expected, if log-in phase is not yet completed, or if a prior error has hosed the owned Channel.
The expectation is unregistered upon receipt of the applicable in-message (and firing it with that in-message Msg_in_ptr as arg). In addition:
The 1 expected in-message may already be available synchronously. In that case:
*qd_msg shall be loaded with that message; and it is purged from *this. You must handle it as you see fit upon return from this method.
The expectation is immediately unregistered.
on_msg_func is ignored (it is not memorized).
Therefore on_msg_func() can only execute upon a future sync_io-pattern async-wait firing its (*on_active_ev_func)().
Template Parameters
On_msg_handler Handler type for in-messages; see class doc header for in-message handling signature.
Parameters
which Top-level Msg_body union which() value to expect.
qd_msg *qd_msg is set to null if no message is immediately available; else set to that message (see above).
on_msg_func on_msg_func(M) shall be invoked in the manner explained in class doc header, on receipt of message with which() == which; unless it is immediately available and therefore loaded into *qd_msg.
Returns
true on success; false due to one of the above conditions.
Definition at line 4182 of file channel.hpp.
expect_msgs()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > template<typename On_msg_handler > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::expect_msgs (Msg_which_in which, Msgs_in * qd_msgs, On_msg_handler && on_msg_func)
Registers the expectation (some of which may be immediately met) of 0+ notification in-messages whose Msg_which equals which.
No-op and return false if which is already being expected, if log-in phase is not yet completed, or if a prior error has hosed the owned Channel.
The expectation is unregistered upon subsequent undo_expect_msgs(which).
1+ expected in-messages may already be available synchronously. In that case:
*qd_msgs is loaded with those messages; and they are purged from *this. You must handle them as you see fit upon return from this method.
The expectation continues to be registered; on_msg_func() may be invoked in the future.
Therefore on_msg_func() can only execute upon a future sync_io-pattern async-wait firing its (*on_active_ev_func)().
Template Parameters
On_msg_handler See expect_msg().
Parameters
which See expect_msg().
qd_msgs *qd_msgs is cleared; then filled with any messages (possibly none) immediately available.
on_msg_func See above and expect_msg().
Returns
See expect_msg().
Definition at line 4214 of file channel.hpp.
expect_msgs_impl()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::expect_msgs_impl (Msgs_in * qd_msgs, bool one_off, Msg_which_in which, On_msg_func_ptr && on_msg_func) private
Core of expect_msg(), expect_msgs(), and expect_log_in_request().
Records the expectation of the given message type (which) in m_rcv_pending_msgs; then scans messages queued-up in m_rcv_pending_msgs with matching Msg_which_in, in order. It async-emits one (if one_off) or all (otherwise) such messages into *qd_msgs out-arg.
Note that, if one_off, and a matching in-message is queued, m_rcv_pending_msgs will not have changed when comparing pre- and post-state.
Parameters
qd_msgs See expect_msgs() and similar.
one_off true for expect_msg() and expect_log_in_request() (which are almost identical); false for expect_msgs(). In the latter case undo_expect_msgs() is a thing.
which Message type to expect.
on_msg_func See expect_msg() among others.
Returns
true usually; false if which expectation is already in m_rcv_pending_msgs; or if m_phase is LOGGED_IN, and m_rcv_pending_msgs does contain a queued-up in-message already, and its Msg_which_in does not equal which. The latter indicates that the logging-in opposing peer disagrees with the expected protocol and issued a log-in request of unexpected type; the on-error handler shall fire asynchronously+immediately, similarly to having received the erroneous in-message after expect_msgs_impl() returns.
Definition at line 4273 of file channel.hpp.
References ipc::transport::struc::error::S_STRUCT_CHANNEL_GOT_UNEXPECTED_LOG_IN_REQUEST.
handle_async_err_code()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::handle_async_err_code (const Error_code & err_code, util::String_view context) private
Helper for async handlers: returns true if and only if err_code indicates a new error or m_channel_err_code_or_ok indicates a previously-occurred one or both; updates m_channel_err_code_or_ok to err_code in the former case.
Logs appropriately.
Parameters
err_code Code from the async op.
context Brief context string for logging.
Returns
true if err_code or a prior condition indicate the channel is hosed; false otherwise.
Definition at line 3641 of file channel.hpp.
handle_new_error()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > void ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::handle_new_error (const Error_code & err_code_not_ok, util::String_view context) private
Helper that handles the situation where m_channel_err_code_or_ok is falsy, and processing has found a new error condition.
Sets m_channel_err_code_or_ok accordingly and emits to on-error handler.
Do not use when synchronously emitting an error (send_core() only as of this writing).
Parameters
err_code_not_ok Truthy code (or assertion may trip).
context Brief context string for logging.
Definition at line 3676 of file channel.hpp.
handlers_poll()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > void ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::handlers_poll (util::String_view context) private
Executes what was recorded recently in handlers_post().
As of this writing this is done after scanning each unstructured (low-level) in-message. If Channel::S_HAS_2_PIPES is true, then 1+ handlers may execute here; otherwise at most 1 can execute here.
See also
Doc header for m_sync_io_handlers which discusses the design+trade-offs here.
Parameters
context Brief context string for logging.
Definition at line 3194 of file channel.hpp.
handlers_post()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > template<typename Task > void ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::handlers_post (util::String_view context, Task && handler) private
Record handler to invoke in handlers_poll() soon.
The context for this is: we're scanning an unstructured (low-level) message received along a pipe of Owned_channel; and it completed something such that the user shall be informed of this via a completion handler they had registered. As of this writing the relevant completion handlers are:
those from expect_*();
those from async_request();
those from set_*unexpected_response_handler().
(async_end_sending() completion handler is a separate, lower-level thing.)
See also
Doc header for m_sync_io_handlers which discusses the design+trade-offs here.
Template Parameters
Task Function type matching void F().
Parameters
context Brief context string for logging.
handler Code to run in handlers_poll().
Definition at line 3171 of file channel.hpp.
owned_channel()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > const Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Owned_channel & ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::owned_channel
See Async_io_obj counterpart.
Returns
See above.
Definition at line 4496 of file channel.hpp.
owned_channel_mutable()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Owned_channel * ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::owned_channel_mutable
See Async_io_obj counterpart.
Reminder: can be useful for ->auto_ping() and ->idle_timer_run().
Returns
See above.
Definition at line 4502 of file channel.hpp.
rcv_async_read_lead_or_continuation_msg()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > void ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::rcv_async_read_lead_or_continuation_msg (Msg_in_pipe * pipe, bool lead_else_cont) private
This key method acts on the pre-condition that the given in-pipe is not known to be in would-block state; and therefore we should read (and process) as many unstructured in-messages as synchronously possible until reaching would-block state, at which point we should return with a pending async-wait/read on that in-pipe.
This shall be called in exactly the following situations:
initially (start_and_poll());
upon this sequence occurring:
An async-read (from this very method) yielded would-block.
The would-block ended – a message was received asynchronously.
rcv_on_async_read_lead_msg() or rcv_on_async_read_continuation_msg() processed that in-message and would like to now read as many in-messages as possible that follow it (synchronously).
To avoid growing the stack proportionally to the # of pending in-messages on the low-level transport, this method does not call itself – it reads all available messages in a loop until would-block or pipe-hosing error. Therefore the following is not a trigger for calling this method:
we've executed an async-read, and it yielded an in-message synchronously, which we then processed; and would like to now read as many in-messages as possible that follow it (synchronously).
Parameters
lead_else_cont true if seeking lead unstructured in-message; false if continuation. It may be helpful to look at Rcv_next_step docs for brief overview of when it would be one versus the other. Or if you love reading and being confused by ygoldfel's verbiage then Msg_in_pipe doc header. (The preceding sentence was written by ygoldfel. Self-shade only.)
pipe Pointer into m_rcv_pipes array.
Definition at line 2457 of file channel.hpp.
References ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_in_pipe::m_lead_msg_mode, ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_in_pipe::m_n_segs_left_after_this_read, ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_in_pipe::m_target_blob, ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_in_pipe::m_target_hndl, ipc::util::Native_handle::null(), and ipc::transport::error::S_SYNC_IO_WOULD_BLOCK.
rcv_blob_max_size()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > size_t ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::rcv_blob_max_size (decltype(Msg_in_pipe::m_lead_msg_mode) mode) const private
Helper that returns the max receive-buffer size for any async-read into a given Msg_in_pipe.
Parameters
mode Msg_in_pipe::m_lead_msg_mode. The reason we don't take a const Msg_in_pipe& here is that there is a use case where this value is necessary just before the Msg_in_pipe is actually constructed.
Returns
See above.
Definition at line 2427 of file channel.hpp.
rcv_on_async_read_continuation_msg()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Rcv_next_step ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::rcv_on_async_read_continuation_msg (Msg_in_pipe * pipe, const Error_code & err_code, size_t sz) private
Same as rcv_on_async_read_lead_msg() but for an expected continuation message instead of lead.
Parameters
pipe See rcv_on_async_read_lead_msg().
err_code See rcv_on_async_read_lead_msg().
sz See rcv_on_async_read_lead_msg().
Returns
What to do next: read another continuation message; read lead message; or stop (pipe-hosing error).
Definition at line 2784 of file channel.hpp.
References ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_in_pipe::m_incomplete_msg, ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_in_pipe::m_lead_msg_mode, ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_in_pipe::m_n_segs_left_after_this_read, ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_in_pipe::m_target_blob, ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_in_pipe::m_target_hndl, ipc::util::Native_handle::null(), ipc::transport::struc::error::S_INTERNAL_ERROR_DESERIALIZE_TARGET_ALLOC_FAILED, ipc::transport::error::S_OBJECT_SHUTDOWN_ABORTED_COMPLETION_HANDLER, ipc::transport::struc::error::S_STRUCT_CHANNEL_INTERNAL_PROTOCOL_MISMATCH_GOT_HNDL, and ipc::transport::struc::error::S_STRUCT_CHANNEL_INTERNAL_PROTOCOL_MISMATCH_GOT_NO_BLOB.
rcv_on_async_read_lead_msg()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Rcv_next_step ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::rcv_on_async_read_lead_msg (Msg_in_pipe * pipe, const Error_code & err_code, size_t sz) private
To execute upon completing an m_channel.async_receive_*() of an expected lead message along the given in-pipe, this processes the result (message or error) and returns what should be done next; does not invoke handlers_poll().
Parameters
pipe See rcv_async_read_lead_or_continuation_msg(). *pipe->m_target_blob and *pipe->m_target_hndl may have been received-into.
err_code From Channel::async_receive_*().
sz From Channel::async_receive_*().
Returns
What to do next: read another lead message; read continuation message; or stop (pipe-hosing error).
Definition at line 2640 of file channel.hpp.
References ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_in_pipe::m_incomplete_msg, ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_in_pipe::m_lead_msg_mode, ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_in_pipe::m_n_segs_left_after_this_read, ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_in_pipe::m_target_blob, ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Msg_in_pipe::m_target_hndl, ipc::util::Native_handle::null(), ipc::transport::struc::error::S_INTERNAL_ERROR_DESERIALIZE_TARGET_ALLOC_FAILED, ipc::transport::error::S_OBJECT_SHUTDOWN_ABORTED_COMPLETION_HANDLER, ipc::transport::struc::error::S_STRUCT_CHANNEL_INTERNAL_PROTOCOL_MISMATCH_GOT_NO_BLOB, and ipc::transport::struc::error::S_STRUCT_CHANNEL_INTERNAL_PROTOCOL_MISMATCH_GOT_NO_HNDL.
rcv_struct_inform_of_unexpected_response()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > void ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::rcv_struct_inform_of_unexpected_response (Msg_in_ptr_uniq && msg_in) private
Helper from rcv_struct_new_msg_in_is_next_expected() that reacts to receiving an otherwise valid reponse in-message when no such response is expected.
Hence it deals with set_unexpected_response_handler() (if set) handler invocation and informing the opposing side, so that it might invoke its set_remote_unexpected_response_handler() (if set) handler.
Parameters
msg_in See rcv_struct_new_msg_in_is_next_expected().
Definition at line 3585 of file channel.hpp.
References ipc::transport::struc::Msg_mdt_out< Struct_builder_config >::internal_msg_body_root().
rcv_struct_new_internal_msg_in()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::rcv_struct_new_internal_msg_in (const Msg_in_impl & msg_in) private
Helper from rcv_struct_new_msg_in(): the case where the in-message has a sentinel message ID value, indicating an internal message rather that one from a user send() (et al).
m_channel_err_code_or_ok must be falsy.
Parameters
msg_in Deserialized in-message with sentinel message ID value.
Returns
See rcv_struct_new_msg_in().
Definition at line 3226 of file channel.hpp.
References ipc::transport::struc::Msg_in_impl< Message_body, Struct_reader_config >::internal_msg_body_root(), ipc::transport::struc::Msg_in_impl< Message_body, Struct_reader_config >::originating_msg_id_or_none(), ipc::transport::struc::error::S_STRUCT_CHANNEL_INTERNAL_PROTOCOL_INTERNAL_MSG_TYPE_UNKNOWN, and ipc::transport::struc::error::S_STRUCT_CHANNEL_INTERNAL_PROTOCOL_MISUSED_SCHEMA.
rcv_struct_new_msg_in()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::rcv_struct_new_msg_in (Msg_in_ptr_uniq && msg_in) private
Helper from rcv_on_async_read_*(), processes a newly completed structured in-message, as it exits the Channel-layer and enters into the structured-layer of processing.
m_channel_err_code_or_ok must be falsy.
Parameters
msg_in The completed structured in-message: after Msg_in::deserialize_mdt() but before Msg_in::deserialize_body().
Returns
false if something in msg_in triggers truthy m_channel_err_code_or_ok; hence the async-read chain must end now. Otherwise true.
Definition at line 2891 of file channel.hpp.
References ipc::transport::struc::error::S_STRUCT_CHANNEL_INTERNAL_PROTOCOL_BAD_AUTH, ipc::transport::struc::error::S_STRUCT_CHANNEL_INTERNAL_PROTOCOL_LOG_IN_MISUSED_SCHEMA, and ipc::transport::struc::error::S_STRUCT_CHANNEL_INTERNAL_PROTOCOL_MISUSED_SCHEMA.
rcv_struct_new_msg_in_during_log_in_as_cli()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::rcv_struct_new_msg_in_during_log_in_as_cli (Msg_in_ptr_uniq && msg_in) private
Helper from rcv_struct_new_msg_in(): the case where m_phase is Phase::S_CLI_LOG_IN, and the in-message has the log-in-response value 1 + session-token=nil as required: Processes the in-message according to the rigid log-in phase algorithm.
rcv_struct_new_msg_in() returns what this returns, immediately.
m_channel_err_code_or_ok must be falsy.
Parameters
msg_in Deserialized in-message with message ID 1 and session-token=nil.
Returns
See rcv_struct_new_msg_in().
Definition at line 3286 of file channel.hpp.
References ipc::transport::struc::error::S_STRUCT_CHANNEL_INTERNAL_PROTOCOL_LOG_IN_MISUSED_SCHEMA.
rcv_struct_new_msg_in_during_log_in_as_srv()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::rcv_struct_new_msg_in_during_log_in_as_srv (Msg_in_ptr_uniq && msg_in) private
Like rcv_struct_new_msg_in_during_log_in_as_cli() but for Phase::S_SRV_LOG_IN instead of CLI_LOG_IN.
Parameters
msg_in See rcv_struct_new_msg_in_during_log_in_as_cli().
Returns
See rcv_struct_new_msg_in_during_log_in_as_cli().
Definition at line 3366 of file channel.hpp.
References ipc::transport::struc::error::S_STRUCT_CHANNEL_GOT_UNEXPECTED_LOG_IN_REQUEST, and ipc::transport::struc::error::S_STRUCT_CHANNEL_INTERNAL_PROTOCOL_LOG_IN_MISUSED_SCHEMA.
rcv_struct_new_msg_in_is_next_expected()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::rcv_struct_new_msg_in_is_next_expected (Msg_in_ptr_uniq && msg_in) private
Helper from rcv_struct_new_msg_in() (possibly indirectly): the case where the in-message's session-token and message ID have been validated (and the latter indicates a user, not internal, message), and the message ID (seq #) indicates this is the next expected in-order message (hence m_rcv_msg_next_id was just ++ed).
m_phase may be any of the 3 values; but the special processing in rcv_struct_new_msg_in_during_log_in_as_cli() or rcv_struct_new_msg_in_during_log_in_as_srv() must have already completed if not LOGGED_IN.
Assuming no detected error therein, this method processes taking msg_in from the lower 2-3 layers (Channel-layer, structured message layer, possibly reassembly queue layer) into the next 1-2 (possibly caching in m_rcv_pending_msgs, emission to user).
Handles just msg_in itself: Does not check whether the gap to any messages in m_rcv_reassembly_q has been filled by this. That is, it's not self-perpetuating: caller must call us again for any messages dequeued from m_rcv_reassembly_q.
m_channel_err_code_or_ok must be falsy.
Parameters
msg_in Deserialized in-message with sentinel message ID value.
Returns
See rcv_struct_new_msg_in().
Definition at line 3471 of file channel.hpp.
References ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Expecting_response::m_on_msg_func, and ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Expecting_response::m_one_expected.
replace_event_wait_handles()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > template<typename Create_ev_wait_hndl_func > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::replace_event_wait_handles (const Create_ev_wait_hndl_func & create_ev_wait_hndl_func)
Analogous to transport::sync_io::Native_handle_sender::replace_event_wait_handles().
Template Parameters
Create_ev_wait_hndl_func See above.
Parameters
create_ev_wait_hndl_func See above.
Returns
See above.
Definition at line 2143 of file channel.hpp.
Referenced by ipc::transport::struc::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Channel().
send()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::send (const Msg_out & msg, const Msg_in * originating_msg_or_null = 0, Error_code * err_code = 0)
See Async_io_obj counterpart.
Parameters
msg See above.
originating_msg_or_null See above.
err_code See above.
Returns
See above. In addition false returned if called before start_ops().
Definition at line 3737 of file channel.hpp.
send_core()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::send_core (const Msg_mdt_out & mdt, const Msg_out_impl * msg, Error_code * err_code_or_ignore) private
Core of send() or internal-message-send: Serializes the given structured out-messages (metadata out-message; user out-message optionally) and Owned_channel::send*()s the result (synchronously).
This is the last step of send() and async_request() (for user out-messages) or an internal attempt to send internal out-message. As such (being the last step): If user message (msg not null), and send_core() succeeds in Phase::S_SRV_LOG_IN, m_phase moves to Phase::S_LOGGED_IN within this method.
As of this writing msg being null (internal message) means we are logged-in; behavior is undefined (assertion may trip) otherwise. Rationale: We aim to keep log-in phase very rigid. This detail could change in the future.
Parameters
mdt Finalized metadata out-message (message about user message; or the internal message itself if it's not "about" anything) to serialize and send over Owned_channel. If internal message: msg shall be null, mdt-held ID shall be 0 and a filled-out Msg_mdt_out::internal_msg_body_root(). Otherwise the opposite of all 3 shall hold.
msg Pointer to user out-message (as from create_msg() or direct Msg_out ction); or null is this is an internal message send.
err_code_or_ignore See send_impl() (analogous meaning, even if send_impl() is not calling send_core() in this case). Or, additionally, leave it null to ignore errors as follows: m_channel_err_code_or_ok is not touched even on error; the idea being this is a best-effort internal message; and if it exposes error on an m_channel out-pipe, then the next user send will just see the same error and emit it that time. Otherwise an internal error could detect the problem – and our caller would not emit it. Thus it would get lost.
Returns
See send_impl() (analogous meaning, even if send_impl() is not calling send_core() in this case). As of this writing, at this stage, there is only one remaining reason this might return false: Owned_channel::send*() yielded transport::error::Code::S_SENDS_FINISHED_CANNOT_SEND.
Definition at line 3920 of file channel.hpp.
References ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::body_root(), ipc::transport::struc::Msg_mdt_out< Struct_builder_config >::body_root(), ipc::transport::struc::Msg_mdt_out< Struct_builder_config >::emit_serialization(), ipc::transport::struc::Msg_out_impl< Message_body, Struct_builder >::emit_serialization(), ipc::transport::struc::Msg_out_impl< Message_body, Struct_builder >::n_serialization_segments(), ipc::transport::struc::Msg_out< Message_body, Struct_builder_t >::native_handle_or_null(), and ipc::transport::error::S_SENDS_FINISHED_CANNOT_SEND.
send_impl()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::send_impl (const Msg_out & msg, const Msg_in * originating_msg_or_null, Error_code * err_code, const On_msg_func_ptr & on_rsp_func_or_null, msg_id_out_t * id_unless_one_off) private
send() and async_request() implementation.
Note this is still the higher-level, public send() or async_request() really; it handles user messages; and once it has decided to indeed attempt the actual sending over Owned_channel, it synchronously invokes send_core(). To send an internal message use send_core() directly.
check_unsendable(msg) and check_prior_error() must have returned false.
Parameters
msg See send() and sync_request().
originating_msg_or_null See send() and sync_request().
err_code Non-null target Error_code.
on_rsp_func_or_null For async_request() non-null pointer to on_rsp_func; else null.
id_unless_one_off Ignored if on_rsp_func_or_null is null: See async_request().
Returns
See send() and async_request().
Definition at line 3791 of file channel.hpp.
session_token()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > const Session_token & ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::session_token
See Async_io_obj counterpart.
Returns
See above.
Definition at line 4508 of file channel.hpp.
References ipc::transport::struc::NULL_SESSION_TOKEN.
set_remote_unexpected_response_handler()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > template<typename On_remote_unexpected_response_handler > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::set_remote_unexpected_response_handler (On_remote_unexpected_response_handler && on_func)
See Async_io_obj counterpart; though naturally on_func() is invoked in the sync_io-pattern fashion.
Template Parameters
On_remote_unexpected_response_handler See above.
Parameters
on_func See above.
Returns
See above.
Definition at line 4466 of file channel.hpp.
set_unexpected_response_handler()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > template<typename On_unexpected_response_handler > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::set_unexpected_response_handler (On_unexpected_response_handler && on_func)
See Async_io_obj counterpart; though naturally on_func() is invoked in the sync_io-pattern fashion.
Template Parameters
On_unexpected_response_handler See above.
Parameters
on_func See above.
Returns
See above.
Definition at line 4435 of file channel.hpp.
start_and_poll()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > template<typename Task_err > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::start_and_poll (Task_err && on_err_func)
Permanently memorizes the incoming-direction on-error handler, thus authorizing the emission of any in-messages (and/or an error) to handlers registered via this call, expect_*(), async_request(), set_*unexpected_response_handler(); and synchronously executes any immediately relevant such handlers due to pending in-traffic.
To be clear: the caller must be ready for 0+ (potentially many) handlers to be synchronously invoked by this call. Even on_err_func() itself may be executed. That said, recursive-mayhem is unlikely to be a concern, since start_and_poll() itself is a one-time operation for a given *this.
Until this is invoked, any incoming lower-level traffic is nevertheless saved in this process's or opposing process's user RAM to be emitted as required by, and after, start_and_poll(). Therefore there is no need to worry about in-traffic disappearing without a trace due to start_and_poll() being invoked too late.
Template Parameters
Task_err Handler type matching signature of flow::async::Task_asio_err.
Parameters
on_err_func The permanent on-channel-hosed error handler. See class doc header for discussion of error semantics.
Returns
true on success; false if start_ops() not yet called, or if already start_and_poll()ed, or if a prior error outgoing-direction error has hosed the owned Channel (then no-op).
Definition at line 2275 of file channel.hpp.
References ipc::transport::struc::error::S_INTERNAL_ERROR_DESERIALIZE_TARGET_ALLOC_FAILED.
start_ops()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > template<typename Event_wait_func_t > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::start_ops (Event_wait_func_t && ev_wait_func)
Sets up the sync_io-pattern interaction between *this and the user's event loop; required before async_accept() will work (as opposed to no-op/return false).
ev_wait_func() – with signature matching util::sync_io::Event_wait_func – is a key function memorized by *this. It shall be invoked by *this operations when some op cannot complete synchronously and requires a certain event (readable/writable) to be active on a certain native-handle.
See also
util::sync_io::Event_wait_func doc header for useful and complete instructions on how to write an ev_wait_func() properly. Doing so correctly is the crux of using the sync_io pattern.
This is a standard sync_io-pattern API per util::sync_io doc header.
Template Parameters
Event_wait_func_t Function type matching util::sync_io::Event_wait_func.
Parameters
ev_wait_func See above.
Returns
false if this has already been invoked; no-op logging aside. true otherwise.
Definition at line 2150 of file channel.hpp.
Referenced by ipc::transport::struc::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Channel().
struct_builder_config()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > const Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Builder_config & ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::struct_builder_config
See Async_io_obj counterpart.
Returns
See above.
Definition at line 3699 of file channel.hpp.
struct_lender_session()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > const Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Builder_config::Builder::Session & ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::struct_lender_session
See Async_io_obj counterpart.
Returns
See above.
Definition at line 3706 of file channel.hpp.
struct_reader_config()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > const Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Reader_config & ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::struct_reader_config
See Async_io_obj counterpart.
Returns
See above.
Definition at line 3713 of file channel.hpp.
undo_expect_msgs()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::undo_expect_msgs (Msg_which_in which)
See Async_io_obj counterpart.
Parameters
which See above.
Returns
See above.
Definition at line 4381 of file channel.hpp.
undo_expect_responses()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::undo_expect_responses (msg_id_out_t originating_msg_id)
See Async_io_obj counterpart.
Parameters
originating_msg_id See above.
Returns
See above.
Definition at line 4406 of file channel.hpp.
unset_remote_unexpected_response_handler()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::unset_remote_unexpected_response_handler
See Async_io_obj counterpart.
Returns
See above.
Definition at line 4481 of file channel.hpp.
unset_unexpected_response_handler()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::unset_unexpected_response_handler
See Async_io_obj counterpart.
Returns
See above.
Definition at line 4450 of file channel.hpp.
Friends And Related Function Documentation
operator<<()
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > std::ostream & operator<< (std::ostream & os, const Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config > & val) related
Prints string representation of the given struc::sync_io::Channel to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Member Data Documentation
m_channel
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > Owned_channel ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_channel private
The Channel taken-over in ctor, lifetime until dtor.
See also
also m_channel_err_code_or_ok.
Definition at line 1868 of file channel.hpp.
m_channel_err_code_or_ok
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > Error_code ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_channel_err_code_or_ok private
Starts falsy; becomes forever truthy (with a specific Error_code that will not change thereafter) when one of the following detects the first channel-hosing condition: send() or async_request(), on-receive handler rcv_on_async_read_lead_msg() or rcv_on_async_read_continuation_msg().
Once that becomes the case:
Any subsequent on-receive handler (possibly none but at most one per ongoing async-read chain, of which there are 1-2) will immediately no-op and end async chain.
Any subsequent send() or async_request() will immediately no-op and return false.
Any subsequent other mutable-state-touching API – e.g., session_token(), expect_msg() – will immediately no-op and return false/null/sentinel value. Exception: async_end_sending() (see below). create_msg() is a convenience thing that does not touch mutable state, so it won't care either.
Note
async_end_sending() is orthogonal to this. It is a Channel-level call that (per its doc header) simply forwards to Channel::async_end_sending(), no questions asked. The F() passed to async_end_sending() may well trigger synchronous emission of E, with E == m_channel_err_code_or_ok; or not; but nothing should or does count on this.
Definition at line 1768 of file channel.hpp.
m_on_err_func
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > flow::async::Task_asio_err ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_on_err_func private
The channel-hosed error reporting handler.
See start_and_poll() + class doc header for discussion of error semantics.
Definition at line 1684 of file channel.hpp.
m_on_remote_unexpected_response_func_or_empty
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > On_remote_unexpected_response_func ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_on_remote_unexpected_response_func_or_empty private
See set_remote_unexpected_response_handler().
Definition at line 1698 of file channel.hpp.
m_on_unexpected_response_func_or_empty
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > On_unexpected_response_func ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_on_unexpected_response_func_or_empty private
See set_unexpected_response_handler().
Definition at line 1695 of file channel.hpp.
m_phase
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > Phase ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_phase private
Phase (w/r/t log-in or lack thereof) of *this peer.
It is either Phase::S_LOGGED_IN throughout; or starts as one of the other 2 values, then is assigned LOGGED_IN and unmodified further.
If not LOGGED_IN from the start (see ctors) then it is written exactly once:
Phase::S_SRV_LOG_IN => Phase::S_LOGGED_IN (see ctors): When send() of the log-in response is invoked.
Phase::S_CLI_LOG_IN => Phase::S_LOGGED_IN (see ctors): When response to the async_request() of the log-in request is received.
It is generally checked at the start of all or most APIs (check_phase_and_prior_error()). In particular many APIs, such as expect_msg(), no-op and return sentinel unless LOGGED_IN; ~one (expect_log_in_request()) does the same unless in a proper *_LOG_IN phase. If the user is acting sanely, they would invoke the log-in APIs before entry to LOGGED_IN and vice versa for the logged-in APIs; namely:
SRV_LOG_IN -> LOGGED_IN: After send() of the log-in response, which itself would be only after the handler passed to expect_log_in_request() fires.
CLI_LOG_IN -> LOGGED_IN: After the handler, passed to async_request() along with log-in request out-message, fires indicating receiving the expected log-in response.
If the user disregards these best practices and invokes a logged-in API before those points, then they're engaging in a race. Worst-case, they'll get an unexpected sentinel return of something like expect_msg() – their own fault.
Definition at line 1743 of file channel.hpp.
m_phase_log_in_started
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_phase_log_in_started private
Used when m_phase is Phase::S_SRV_LOG_IN, this starts false and is changed to true at thread-U call of expect_log_in_request(); if already true then a 2nd (illegal) expect_log_in_request() call has been made and shall be ignored (no-op, return sentinel).
Definition at line 1750 of file channel.hpp.
m_rcv_expecting_msg_map
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > Expecting_msg_map ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_rcv_expecting_msg_map private
Map storing current policy for expecting non-response messages.
See Expecting_msg_map and Expecting_msg doc headers for details.
Definition at line 1777 of file channel.hpp.
m_rcv_expecting_response_map
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > Expecting_response_map ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_rcv_expecting_response_map private
Map storing current policy for expecting responses. See Expecting_response_map doc header for details.
Definition at line 1771 of file channel.hpp.
m_rcv_msg_next_id
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > msg_id_in_t ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_rcv_msg_next_id private
Next expected in-message ID (sequence #), incremented from initial value 1 to 2, 3, ... on in-order message receipt.
It is used purely for sanity checking of the opposing sender's payloads, when Owned_channel stores only 1 pipe (Channel::S_HAS_2_PIPES is false). Or: it is used with m_rcv_reassembly_q if Owned_channel stores 2 pipes (Channel::S_HAS_2_PIPES is true).
Algorithm summary: 2 in-pipes
In that latter case a handle-less in-message may arrive along the blobs in-pipe; while a handle-paired message may arrive along the handles in-pipe; and since the two might race, the one sent 1st might arrive 2nd, and vice versa. Then the out-of-order one would be stored temporarily in m_rcv_reassembly_q. (In theory this could occur for several in-messages.) This is detected by noting that an in-message's message ID (sequence number) exceeds m_rcv_msg_next_id. If it equals it, then it is in-order and skips m_rcv_reassembly_q. If it is lower, then that is misbehavior by the opposing peer and hoses the pipe.
Technically we could be more stringent in our sanity checking: while races may occur between the 2 in-pipes, for a given 1 of 2 pipes (the blobs pipe; the handles pipe), the message IDs must always be increasing, as these are reliable, in-order pipes. However we choose to not worry about this enforcement; in-order behavior of our various transports shall (possibly) be checked elsewhere and is a hard assumption. On the other hand it is cheap to check for non-repeating (always increasing) message IDs along the totality of the pipes, so we do.
Algorithm summary: 1 in-pipe
Each message received must contain ID, in fact, equal m_rcv_msg_next_id which is then incremented. There is no reassembly, as there is only 1 in-pipe, and it must be in-order. This is (as noted just above) easy to sanity-check.
Definition at line 1806 of file channel.hpp.
m_rcv_pending_msgs
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > boost::unordered_map<Msg_which_in, Msg_in_q> ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_rcv_pending_msgs private
Queues of in-messages, keyed by Msg_which_in, each in msg_id_in_t (sequence #) order, for which no Msg_which_in handler has yet been registered by the user (expect_msg(), expect_msgs(), expect_log_in_request()).
They'll stay there until such a thing is indeed registered; once it is, that queue's elements are fed, in order, to that handler, and the element is removed from m_rcv_pending_msgs.
Corner case: a response arrives to an originating out-message for which no response is expected
It is relatively normal, if ideally avoided (informally speaking), that there is no Msg_which_in listener yet registered for a given in-message. (One can be registered later: then such messages will be flushed to that handler.) By contrast: It is a user protocol error that a response arrives unexpectedly. Let's break down the realistic possibilities for how that might happen:
A response arrives to message M, but the local user never issued a request for that message as triggered by async_request(). The opposing user must have erroneously issued a response to a non-request.
A response arrives to message M, and the local user did issue an async_request() for that message; but either it was a one-off request – and this is the 2nd/3rd/... response – or it was an open-ended request, but the local user called undo_expect_responses() for it since. Typically this is a miscommunication at the user level: e.g., opposing user indicated a previous response was the last one but then erroneously sent another response anyway. Or, more simply, it sent 2+ responses to a one-off request (again erroneously).
Both situations involve non-trivial user-level protocol mistakes. What to do?
We could hose the whole channel: fire all handlers with some fatal Error_code and disallow further work. This feels too draconian and inflexible at such a high layer.
Or we could inform the user of the problem.
We choose the latter. In particular:
We fire the user-protocol-error handler (see start_and_poll()) locally. We feed them the problem in-message and then forget that message: they can do with it as they wish.
We send an internal message to the opposing peer indicating the issue including the triggering in-message ID (to them, out-message ID). The opposing peer Channel shall fire their own user-protocol-error handler similarly.
Other than that the channel continues operating. The user can choose to close it, or ignore the problem, or alert, or whatever.
To wit:
See also
set_unexpected_response_handler().
set_remote_unexpected_response_handler().
Definition at line 1859 of file channel.hpp.
m_rcv_pipes
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > boost::array<std::optional<Msg_in_pipe>, 2> ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_rcv_pipes private
1 or 2 active (via optional) structs containing policy and state w/r/t receipt of low-level (unstructured) messages with the aim to complete the next structured in-message(s).
See also
Msg_in_pipe doc header for detailed algorithm overview.
Definition at line 1692 of file channel.hpp.
m_rcv_reassembly_q
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > std::optional<Reassembly_q> ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_rcv_reassembly_q private
When Owned_channel::S_HAS_2_PIPES, stores the reassembly queue of in-messages to feed into m_rcv_pending_msgs once in-messages filling the msg_id_in_t (sequence #) gap between m_rcv_msg_next_id and m_rcv_reassembly_q.front() is filled.
Once that occurs, the maximally long sequence of in-messages at the front of this queue are moved into m_rcv_pending_msgs (or fed to waiting handlers immediately if possible). Left uninitialized if !S_HAS_2_PIPES.
See also
m_rcv_msg_next_id for algorithm summary; Reassembly_q doc header for data structure details.
Definition at line 1817 of file channel.hpp.
Referenced by ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Channel().
m_session_token
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > Session_token ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_session_token private
Session token: in Phase::S_LOGGED_IN to send in every out-message and check-against every in-message; in log-in phase as client equals nil; in log-in phase as server it is auto-generated at construction.
In non-log-in phase, it's either provided by user in ctor (if log-in phase skipped), or:
inherited from log-in phase (if as server);
deserialized from the log-in response (if as client).
It's used in 2 ways:
It is sent in every (structured) message – namely in the lead unstructured message. SO whenever an mdt message is created, we load m_session_token into it at that time.
Every message is checked against it (if not correct, channel is hosed immediately).
There is exactly one exception to this: The log-in request (received in log-in phase as server) must have nil session token: we have not yet sent m_session_token (which we generated at ction) to it in the response message, so the client could not have known it.
Definition at line 1715 of file channel.hpp.
Referenced by ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::Channel().
m_snd_msg_next_id
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > msg_id_out_t ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_snd_msg_next_id private
Next out-message ID (for the next send() or async_request()).
Definition at line 1718 of file channel.hpp.
m_started_ops
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > bool ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_started_ops private
Whether start_ops() has been called yet or not.
We could've used m_channel built-in guards against that, but then as of this writing there's no way to check that at the top of our own various APIs (check_not_started_ops()).
Definition at line 1678 of file channel.hpp.
m_struct_builder_config
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > const Builder_config ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_struct_builder_config private
The builder engine config for out-messages: Small data store, such that the Struct_builder Builder_config::Builder (really the containing class of Builder_config) main-ctor takes an object of this type, its contents being knobs controlling the behavior of the resulting Struct_builder.
The type Builder_config (a template parameter) determines the logic part of the serialization policy: what is the source of RAM for segments (heap? SHM?), as the user mutates an out-message? How big is each segment?
The members inside m_struct_builder_config further tweak the application of that logic by being knobs: Should prefix/postfix space be left in the serialization? How quickly should the segments grow? Where to log?
This Config is passed to Builder ctor to configure it.
Rationale
By storing this value, copied from the one passed to ctor, we delegate the policy decision (as to what kind of capnp-structured-to-binary serialization engine to use) to the *this config (user). The knobs controlling the configuration of that engine, each time it's created for a given out-message, depend on the builder concrete type, so we don't know what they are or even their nature or number. They are stored opaquely (to us) inside this item.
This member is used in two ways.
Every out-message (whether user-created or an internal one) is accompanied by/is an internal-use metadata message, which is just another Msg_out albeit with an internal friendly API, Msg_mdt_out, tailored to the stuff we need to put into these. The builder config used to create this is m_struct_builder_config.
So the schema template param is the internal-use metadata stuff from structured_msg.capnp.
Every user out-message created via create_msg() is supplied by the latter with m_struct_builder_config as the builder config.
So the schema template param is <Message_body>, the Channel template param from the user.
The user is allowed to simply direct-construct the Msg_out without any create_msg(). They have to supply the builder config themselves again, though. It has to be the same type as m_struct_builder_config, or it won't compile; but in theory it could have different knob values. E.g., it could have a null Logger, while *this one logs-galore. Usually one would want to keep it equal (but certainly need not be the same actual Builder_config object).
So it's an important member, but arguably its type is more important than its contents (knobs).
Definition at line 1658 of file channel.hpp.
m_struct_lender_session
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > const Builder_config::Builder::Session ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_struct_lender_session private
Value (possibly of size 0 depending on this type) to pass to Msg_out::emit_serialization() to indicate the opposing side of the Owned_channel.
If the type is Null_session (zero-sized), then no information is necessary to indicate this.
Definition at line 1665 of file channel.hpp.
m_struct_reader_config
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > const Reader_config ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_struct_reader_config private
Analogous to m_struct_builder_config but for deserialization.
See also
m_struct_builder_config
Definition at line 1671 of file channel.hpp.
m_sync_io_handlers
template<typename Channel_obj , typename Message_body , typename Struct_builder_config , typename Struct_reader_config > std::vector<boost::movelib::unique_ptr<util::Task> > ipc::transport::struc::sync_io::Channel< Channel_obj, Message_body, Struct_builder_config, Struct_reader_config >::m_sync_io_handlers private
The handlers as pushed by handlers_post() to be flushed via handlers_poll() (internally by *this).
handlers_poll() is only called internally as opposed to from a user API: there is no method the user can invoke that is immediately servable; except:
expect_*() (all going through expect_msg_impl()): But they emit immediate results avoiding the handler function.
async_sync_end_sending(): Same.
Unlike the core-layer guys, which always deal with at most 1 in-message at a given time, we have a situation where there can be more than 1 handler pending at a time; so this is a list as opposed to just 1 item. That said, there is indeed only 1 at a time if Channel::S_HAS_2_PIPES is false; but 1+ may be saved, and fired in handlers_poll() soon, if HAS_2_PIPES is true. At the risk of verbosity to try to help understanding let's examine each case.
HAS_2_PIPES = false: How do we keep it to 1 handler (or 0) at a time?
Well, why do handlers fire? Answer:
If a user is expecting an in-message (a notification via expect_*() or a response via async_request()), and that message arrives, then a saved handler shall fire.
If a user is not expecting a response, but one arrives, then a special handler shall fire if set.
If the opposing user is not expecting a response, but one arrives, then they send an internal message which arrives to us, and then a special handler here shall fire if set.
If something bad is reported to an async_receive_*() handler via Error_code, then the channel is hosed, and m_on_err_func shall fire.
Now, as noted, any cached in-messages to expect_*() are not a part of this equation (they are reported differently); nor is the special case of the m_channel async_end_sending() stuff which is at a lower level and handled separately. So the above 4 bullet points are the only relevant things.
Naturally, then, a handler can fire only as a reaction to an m_channel.async_receive_*() receiving an unstructured msg which then completes a structured message (either by itself or by combining with a preceding one). So we choose to fire (synchronously call) any such handler immediately upon processing an unstructured message's contents. You can see this in rcv_async_read_lead_or_continuation_msg(). So we handlers_post() while processing it... then handlers_poll() right after finishing doing so.
That leaves the possibility of said processing handlers_post()ing 2+ handlers. However, no, that is not possible as of this writing:
If an in-message is a response (it either is or isn't: it is a metadata header), then either
it is a response to a message earlier marked as awaiting response; or
it is not – and it is invalid and is reported (if so configured) via unexpected-response handler.
If it is not a response, then either
it is expected via earlier expect_msg_impl() (fire handler); or
it is not expected (cache it for later non-handler-emission, possibly, via expect_msg_impl()).
Otherwise it is malformed somehow (internal protocol error a/k/a bug here or in opposing guy).
Therefore you can see the fate of a given message is to go down one of these paths, each of which ends either with no handler being posted; or one being posted.
Then we handlers_poll() it before trying to read the next unstructured message (or stopping forever).
HAS_2_PIPES = true: Why there can be 1+ handlers at a time
The key difference is just after the structured message has been fully deserialized but before it is then given to the layer where its structured contents are either cached or emitted to the user. Namely, we check its ID against the next expected ID (sequence number). If there is only 1 pipe, it must always have the next expected ID. However if there are 2, as is the case here, then the seq # may exceed the expected ID causing message to be stored in m_rcv_reassembly_q. No problem so far....
Now say an in-message arrives that closes the gap between the next expected seq # and the lowest seq # in m_rcv_reassembly_q. Now potentially the entire m_rcv_reassembly_q must be emitted to the user! E.g., if we receive 1, 2, 4, 5, 6, 7, 3, then after 3 we must emit 4-5-6-7 as well. So in total upon receiving 1 unstructured message (the last continuation message comprised by structured message 3, we then emit five messages in one go).
So that's why there can be multiple handlers.
Rationale: Expressing this as a function object
I (ygoldfel) suspect the semantics of this guy and handlers_post() and handlers_poll() might be confusing. It may look like some sort of generalized boost.asio-post()-lite scheme, but in reality it is much simpler than that. In actual reality: we read an in-message; as a result we either need to do nothing user-handler-wise, or we need to invoke 1 relevant handler. (As of this writing no one in-message can mean 2+ user handlers are applicable. See above. Conceivably that could change but....) This calling-of-user-handler just needs to occur a few stack frames up (synchronously at that) and can be triggered by all manner of situations a few stack frames down. So, really, this could be communicated in some kind of union-enumeration combo. Expressing it as an actual function to run just seemed like the most code-economical way to express it. It's easier to code "execute this" rather than "decode this union-enumeration thing to tell you what you should execute." Perf-wise it might be worse... maybe... as Function<> is a polymorphic data structure. (Premature optimization is the root of all ev... and so on.)
Rationale: Communicating this via handlers_post() to handlers_poll()
Orthogonally, saving it (whether a union-enumeration thing or a callback) in this data structure (m_sync_io_handlers) felt more economical (in terms of lines of code) than returning it up a function-call chain. On the other hand, though, the algorithm would be more rigid-looking and robust that other way; generally speaking I (ygoldfel) always prefer to keep less state and be more functional in style – this here going against that. Indeed Native_socket_stream::Impl does it that more-functional way albeit in a totally different setting. Well, we'll see. Anyway it works at least.
Definition at line 1956 of file channel.hpp.
The documentation for this class was generated from the following files:
transport/struc/struc_fwd.hpp
transport/struc/sync_io/channel.hpp