Flow-IPC: ipc::session::shm::arena_lend::jemalloc Namespace Reference
ipc::session::shm::arena_lend::jemalloc Namespace Reference
Support for SHM-backed ipc::session sessions and session-servers with the SHM-jemalloc (ipc::shm::arena_lend::jemalloc) provider.
Namespaces
namespace error
Analogous to ipc::session::error but for errors pertaining to SHM-jemalloc-enabled sessions specifically.
Classes
class Client_session_impl
Core internally-used implementation of shm::arena_lend::jemalloc::Client_session: it is to the latter what its public super-class Client_session_impl is to Client_session.
class Client_session_mv
class Server_session
Identical to session::Server_session in every way, except that it makes available two SHM arenas, from the SHM-jemalloc provider (ipc::shm::arena_lend::jemalloc).
class Server_session_impl
Core internally-used implementation of shm::arena_lend::jemalloc::Server_session: it is to the latter what its public super-class Server_session_impl is to Server_session.
class Server_session_mv
class Session_impl
Common data and logic for shm::arena_lend::jemalloc::Server_session_impl and shm::arena_lend::jemalloc::Client_session_impl.
class Session_mv
Implements the SHM-related API common to shm::arena_lend::jemalloc::Server_session and shm::arena_lend::jemalloc::Client_session.
class Session_server
This is to vanilla Session_server what shm::arena_lend::jemalloc::Server_session is to vanilla Server_session: it is the session-server type that starts SHM-enabled sessions with SHM-jemalloc provider (ipc::shm::arena_lend::jemalloc).
Typedefs
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload = ::capnp::Void>
using Client_session = Session_mv< session::Client_session_mv< Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > > >
This is to session::Client_session what shm::arena_lend::jemalloc::Server_session is to session::Server_session.
Functions
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload >
std::ostream & operator<< (std::ostream &os, const Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > &val)
Prints string representation of the given Client_session_impl to the given ostream.
template<typename Session_impl_t >
std::ostream & operator<< (std::ostream &os, const Session_impl< Session_impl_t > &val)
Prints string representation of the given Session_impl to the given ostream.
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload >
std::ostream & operator<< (std::ostream &os, const Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > &val)
Prints string representation of the given Server_session_impl to the given ostream.
template<typename Session_t >
std::ostream & operator<< (std::ostream &os, const Session_mv< Session_t > &val)
Prints string representation of the given Session_mv to the given ostream.
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload >
std::ostream & operator<< (std::ostream &os, const Server_session< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > &val)
Prints string representation of the given Server_session to the given ostream.
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload >
std::ostream & operator<< (std::ostream &os, const Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > &val)
Prints string representation of the given Session_server to the given ostream.
Variables
const Shared_name SHM_SUBTYPE_PREFIX = Shared_name::ct("jem")
Internally used in pool names generated in this namespace to differentiate from those of other SHM-supporting session providers' pools (for example session::shm::classic versus session::shm::arena_lend::jemalloc).
Detailed Description
Support for SHM-backed ipc::session sessions and session-servers with the SHM-jemalloc (ipc::shm::arena_lend::jemalloc) provider.
See the doc header for the general ipc::session::shm namespace.
Typedef Documentation
Client_session
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload = ::capnp::Void> using ipc::session::shm::arena_lend::jemalloc::Client_session = typedef Session_mv <session::Client_session_mv <Client_session_impl<S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload> >>
This is to session::Client_session what shm::arena_lend::jemalloc::Server_session is to session::Server_session.
In terms of additional (to that of Client_session) public behavior, from the public API user's point of view, this class template alias is almost identical to shm::arena_lend::jemalloc::Server_session (see its doc header). (That is during PEER state.) There is however one difference:
Client_session lacks an app_shm() method (as well as the related APIs app_shm_builder_config() and app_shm_lender_session()). This is due to the nature of arena-lending SHM-providers. Namely each side maintains its own Arenas in which only it can allocate (Arena::construct()); and by definition of session-client, there is no longer-than-lifetime object to maintain any app-scope Arenas. In a session-server process, by contrast, there is Session_server which does just that and maintains app_shm(); hence Server_session can return one of those.
Implementation
First see the Implementation section of shm::arena_lend::jemalloc::Server_session. It gives a detailed description of the overall design – both its own side and this (client) side too. So read it; then come back here.
That said, shm::arena_lend::jemalloc::Client_session is a much simpler situation. It is not inter-operating with any server object; and (as explained in the referenced doc header) all it needs to do is create 1 each of Shm_session and Arena objects and register the latter with the former to enable lending objects
So all we have to do is provide a modified async_connect() which does the above. How? Answer:
execute vanilla session::Client_session_impl::async_connect(); once that triggers the on-done handler:
set up Shm_session and Arena (though for the former there's a prerequisite async step to establish an interal-use IPC channel);
invoke the user's original on-done handler.
In *this, mechanically: the true implementation of the needed setup and accessors (explained above) is split between shm::classic::Session_mv (common with Server_session_impl) and shm::arena_lend::jemalloc::Client_session_impl, with the vanilla core in super-class session::Client_session_impl.
That's the key; then session::Client_session_mv adds movability around session::Server_session_impl; and lastly this type aliases to that (by way of Session_mv). Session_mv completes the puzzle by pImpl-forwarding to the added (SHM-focused) API. (session::Client_session_mv only pImpl-forwards to the vanilla API.)
The last and most boring piece of the puzzle are the pImpl-lite wrappers around the SHM-specific API that shm::arena_lend::jemalloc::Client_session adds to super-class Client_session_mv: session_shm() and so on. Just see same spot in shm::arena_lend::jemalloc::Server_session doc header; it explains both client and server sides.
Template Parameters
S_MQ_TYPE_OR_NONE Identical to session::Client_session.
S_TRANSMIT_NATIVE_HANDLES Identical to session::Client_session.
Mdt_payload Identical to session::Client_session.
Definition at line 119 of file jemalloc_fwd.hpp.
Function Documentation
operator<<() [1/6]
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > std::ostream & operator<< (std::ostream & os, const Client_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > & val)
Prints string representation of the given Client_session_impl to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 585 of file client_session_impl.hpp.
operator<<() [2/6]
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > std::ostream & ipc::session::shm::arena_lend::jemalloc::operator<< (std::ostream & os, const Server_session< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > & val)
Prints string representation of the given Server_session to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 359 of file server_session.hpp.
operator<<() [3/6]
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > std::ostream & ipc::session::shm::arena_lend::jemalloc::operator<< (std::ostream & os, const Server_session_impl< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > & val)
Prints string representation of the given Server_session_impl to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 383 of file server_session_impl.hpp.
operator<<() [4/6]
template<typename Session_impl_t > std::ostream & ipc::session::shm::arena_lend::jemalloc::operator<< (std::ostream & os, const Session_impl< Session_impl_t > & val)
Prints string representation of the given Session_impl to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 619 of file session_impl.hpp.
operator<<() [5/6]
template<typename Session_t > std::ostream & ipc::session::shm::arena_lend::jemalloc::operator<< (std::ostream & os, const Session_mv< Session_t > & val)
Prints string representation of the given Session_mv to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 423 of file session.hpp.
operator<<() [6/6]
template<session::schema::MqType S_MQ_TYPE_OR_NONE, bool S_TRANSMIT_NATIVE_HANDLES, typename Mdt_payload > std::ostream & ipc::session::shm::arena_lend::jemalloc::operator<< (std::ostream & os, const Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload > & val)
Prints string representation of the given Session_server to the given ostream.
Parameters
os Stream to which to write.
val Object to serialize.
Returns
os.
Definition at line 715 of file session_server.hpp.
Variable Documentation
SHM_SUBTYPE_PREFIX
const Shared_name ipc::session::shm::arena_lend::jemalloc::SHM_SUBTYPE_PREFIX = Shared_name::ct("jem")
Internally used in pool names generated in this namespace to differentiate from those of other SHM-supporting session providers' pools (for example session::shm::classic versus session::shm::arena_lend::jemalloc).
Definition at line 34 of file session_shared_name.cpp.
Referenced by ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::cleanup(), ipc::session::shm::arena_lend::jemalloc::Session_server< S_MQ_TYPE_OR_NONE, S_TRANSMIT_NATIVE_HANDLES, Mdt_payload >::init_app_shm_as_needed(), and ipc::session::shm::arena_lend::jemalloc::Session_impl< Session_impl_t >::init_shm().